//! Cross-language parity tests against the CPython reference runtime.
//!
//! Certificate hashes are taken over canonical bytes, so Rust and Python must agree byte for
//! byte or a certificate produced by one cannot be replayed by the other. The float table is
//! generated by `tools/gen_python_ground_truth.py`; regenerate it if CPython changes.

use bioprism_ids::{python_repr_f64, to_canonical_string, ContentHash};
use serde_json::{json, Value};
use std::path::PathBuf;

const PYTHON_FLOAT_REPR: &[(u64, &str)] = &[
    (0x0000000000000000, "0.0"),
    (0x8000000000000000, "-0.0"),
    (0x3ff0000000000000, "1.0"),
    (0xbff0000000000000, "-1.0"),
    (0x3fe0000000000000, "0.5"),
    (0x4059000000000000, "100.0"),
    (0x430c6bf526340000, "1000000000000000.0"),
    (0x4341c37937e08000, "1e+16"),
    (0x4376345785d8a000, "1e+17"),
    (0x3f1a36e2eb1c432d, "0.0001"),
    (0x3ee4f8b588e368f1, "1e-05"),
    (0x3eb0c6f7a0b5ed8d, "1e-06"),
    (0x3fb999999999999a, "0.1"),
    (0x3fc999999999999a, "0.2"),
    (0x3fd5555555555555, "0.3333333333333333"),
    (0x3ff8000000000000, "1.5"),
    (0xc006000000000000, "-2.75"),
    (0x42dc12218377de40, "123456789012345.0"),
    (0x43118b54f22aeb00, "1234567890123456.0"),
    (0x4345ee2a2eb5a5c4, "1.2345678901234568e+16"),
    (0x54b249ad2594c37d, "1e+100"),
    (0x2b2bff2ee48e0530, "1e-100"),
    (0x3cb0000000000000, "2.220446049250313e-16"),
    (0x0000000000000001, "5e-324"),
    (0x7fefffffffffffff, "1.7976931348623157e+308"),
    (0x400921fb54442d11, "3.14159265358979"),
    (0x444b1ae4d6e2ef50, "1e+21"),
    (0x4341c37937e07ffb, "9999999999999990.0"),
    (0xc341c37937e08000, "-1e+16"),
    (0xbee4f8b588e368f1, "-1e-05"),
    (0x44dfe185ca57c517, "6.02214076e+23"),
];

#[test]
fn float_repr_matches_cpython() {
    for (bits, expected) in PYTHON_FLOAT_REPR {
        let value = f64::from_bits(*bits);
        let actual = python_repr_f64(value);
        assert_eq!(
            &actual, expected,
            "float repr diverged for bits 0x{bits:016x}"
        );
    }
}

#[test]
fn string_escaping_matches_cpython() {
    let cases: &[(&str, &str)] = &[
        ("a", r#"{"k":"a"}"#),
        ("\"", r#"{"k":"\""}"#),
        ("\\", r#"{"k":"\\"}"#),
        ("\n", r#"{"k":"\n"}"#),
        ("\t", r#"{"k":"\t"}"#),
        ("\r", r#"{"k":"\r"}"#),
        ("\u{08}", r#"{"k":"\b"}"#),
        ("\u{0c}", r#"{"k":"\f"}"#),
        ("\0", r##"{"k":"\u0000"}"##),
        ("\u{1f}", r##"{"k":"\u001f"}"##),
        ("\u{1b}", r##"{"k":"\u001b"}"##),
        ("\u{7f}", "{\"k\":\"\u{7f}\"}"),
        ("é", "{\"k\":\"é\"}"),
        ("日本", "{\"k\":\"日本\"}"),
        ("a/b", r#"{"k":"a/b"}"#),
        ("\u{2028}", "{\"k\":\"\u{2028}\"}"),
        ("😀", "{\"k\":\"😀\"}"),
    ];
    for (input, expected) in cases {
        let actual = to_canonical_string(&json!({ "k": input })).unwrap();
        assert_eq!(&actual, expected, "escaping diverged for {input:?}");
    }
}

#[test]
fn object_keys_are_sorted_by_code_point() {
    let value = json!({ "b": 1, "a": 2, "A": 3, "é": 4, "_": 5, "10": 6, "2": 7 });
    let actual = to_canonical_string(&value).unwrap();
    assert_eq!(actual, r#"{"10":6,"2":7,"A":3,"_":5,"a":2,"b":1,"é":4}"#);
}

#[test]
fn integers_never_gain_a_decimal_point() {
    let value = json!({ "i": 1, "neg": -3, "big": 9007199254740993i64, "f": 1.0 });
    let actual = to_canonical_string(&value).unwrap();
    assert_eq!(actual, r#"{"big":9007199254740993,"f":1.0,"i":1,"neg":-3}"#);
}

#[test]
fn separators_are_compact() {
    let value = json!({ "a": [1, 2, {"b": null}], "c": true });
    let actual = to_canonical_string(&value).unwrap();
    assert_eq!(actual, r#"{"a":[1,2,{"b":null}],"c":true}"#);
    assert!(!actual.contains(", "));
    assert!(!actual.contains(": "));
}

fn fixture(name: &str) -> Value {
    let path: PathBuf = [env!("CARGO_MANIFEST_DIR"), "..", "..", "fixtures", "fiber-v0.1", name]
        .iter()
        .collect();
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("missing fixture {}: {e}", path.display()));
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

#[test]
fn golden_world_hash_matches_cpython() {
    let world = fixture("radiogenomic_world.json");
    let canonical = to_canonical_string(&world).unwrap();
    assert_eq!(
        canonical.len(),
        332_026,
        "canonical byte length diverged from CPython"
    );
    assert_eq!(
        ContentHash::of_value(&world).unwrap().as_str(),
        "b3809731cf93040fcd8aef43deb2a552492064b49154e07ea58caa724c10cbb5"
    );
}

#[test]
fn golden_query_hash_matches_cpython() {
    let query = fixture("leakage_query.json");
    let canonical = to_canonical_string(&query).unwrap();
    assert_eq!(canonical.len(), 405);
    assert_eq!(
        ContentHash::of_value(&query).unwrap().as_str(),
        "d06368c62dd878f483d30ebfd56f38426b1234d37e46ca77d4536db81f59c684"
    );
}

#[test]
fn non_finite_numbers_are_rejected_rather_than_emitted() {
    assert!(
        serde_json::Number::from_f64(f64::NAN).is_none(),
        "NaN must never reach canonical bytes; CPython would emit a bare NaN token here"
    );
    assert!(
        serde_json::Number::from_f64(f64::INFINITY).is_none(),
        "Infinity must never reach canonical bytes"
    );
}

/// serde_json's default float parser is not correctly rounded, and disagrees with both native
/// Rust and CPython on values near the subnormal boundary and at the 2^53 integer limit. Since
/// canonical bytes are hashed, a mis-parsed float would silently produce a different digest than
/// the reference implementation for the same document.
///
/// The workspace enables serde_json's `float_roundtrip` feature to fix this. Without it,
/// `2.2250738585072011e-308` parses one ULP high and `9007199254740993.0` rounds the wrong way.
#[test]
fn float_parsing_agrees_with_native_rust_and_cpython() {
    let cases: &[(&str, &str)] = &[
        ("2.2250738585072011e-308", "2.225073858507201e-308"),
        ("9007199254740993.0", "9007199254740992.0"),
        ("0.30000000000000004", "0.30000000000000004"),
        ("1e-320", "1e-320"),
        ("1.7976931348623157e308", "1.7976931348623157e+308"),
    ];

    for (literal, cpython_repr) in cases {
        let parsed: Value = serde_json::from_str(literal).expect("valid JSON number");
        let via_serde = parsed.as_f64().expect("a float");
        let via_native: f64 = literal.parse().expect("valid Rust float literal");

        assert_eq!(
            via_serde.to_bits(),
            via_native.to_bits(),
            "serde_json parsed {literal} to different bits than Rust's own parser; \
             the float_roundtrip feature is missing from the workspace manifest"
        );
        assert_eq!(
            &python_repr_f64(via_serde),
            cpython_repr,
            "canonical form of {literal} diverged from CPython"
        );
    }
}
