//! World P32 frontier: validate causal closure, provenance lineage, and omission-safe replay.
use bioprism_ids::ContentHash;
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::collections::BTreeSet;
use thiserror::Error;

pub const FEATURE_ID: &str = "AFA-world-P32-F01";
pub const CONTRACT_VERSION: &str = "world-local-causal-integrity/1.0";
pub const CONTENT_TYPE: &str = "application/vnd.aurora.world.causal-integrity-card-1+json";
pub const BOUNDARY: &str = "preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions";

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CausalEdge4 { pub edge_id: String, pub cause_id: String, pub effect_id: String, pub relation: String, pub evidence_digest: ContentHash, pub policy_epoch: u64, pub local: bool, pub aggregate_only: bool, pub negative_result: bool }
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CausalIntegrityRequest4 { pub request_id: String, pub purpose: String, pub edges: Vec<CausalEdge4>, pub required_node_order: Vec<String>, pub required_relation_order: Vec<String>, pub policy_allowed: bool, pub protected_closure: bool, pub signed_approval: bool, pub raw_data_local: bool, pub aggregate_only: bool, pub replay_identity: ContentHash, pub adversarial_events: Vec<String>, pub action_budget: u32, pub action_count: u32, pub boundary: String }
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CausalIntegrityArtifact4 { pub artifact_id: String, pub content_type: String, pub content_hash: ContentHash, pub semantic_loss: Vec<String>, pub edge_digests: Vec<ContentHash>, pub boundary: String }
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CausalIntegrityCard7 { pub schema_version: String, pub contract_version: String, pub feature_id: String, pub mode: String, pub scale: String, pub request_id: String, pub purpose: String, pub disposition: String, pub edge_order: Vec<String>, pub accepted_order: Vec<String>, pub rejected_order: Vec<String>, pub unknown_order: Vec<String>, pub omitted_order: Vec<String>, pub node_order: Vec<String>, pub relation_order: Vec<String>, pub epoch_order: Vec<String>, pub negative_evidence_order: Vec<String>, pub replay_identity: ContentHash, pub closure_digest: ContentHash, pub artifact: CausalIntegrityArtifact4, pub effect_receipts: Vec<String>, pub raw_data_local: bool, pub aggregate_only: bool, pub boundary: String }
#[derive(Debug, Error, Clone, PartialEq, Eq)]
pub enum CausalIntegrityError { #[error("invalid causal-integrity request: {0}")] Invalid(String), #[error("causal-integrity card failed validation: {0}")] Output(String) }
fn ordered(v: &[String]) -> bool { v.windows(2).all(|p| p[0] < p[1]) }
fn digest(v: &ContentHash) -> bool { v.as_str().len() == 64 && v.as_str().bytes().all(|b| b.is_ascii_hexdigit()) }
fn nonempty(v: &str) -> bool { !v.trim().is_empty() }
pub fn manifest(id: &str, version: &str, scale: &str, mode: &str) -> serde_json::Value { json!({"schema_version":"1.0.0","capability_id":id,"version":version,"owner_crate":"world","consumers":["causal compiler","mechanism explorer","provenance ledger","release auditor"],"behavior":format!("qualify causal-world closure at {scale} ({mode})"),"value":"prevents cyclic, stale, or silently incomplete causal explanations from entering a replayable research object","input_schema":"CausalIntegrityRequest4@1","output_schema":"CausalIntegrityCard7@1","effects":["emit:causal-card","retain:causal-omissions","block:unsafe-release"],"permissions":["read:local-causal-edges"],"determinism":"byte_stable","autonomy_tier":"A1","boundary":BOUNDARY}) }
impl CausalIntegrityCard7 { pub fn validate(&self) -> Result<(), CausalIntegrityError> { if self.schema_version != "1.0.0" || !nonempty(&self.contract_version) || !nonempty(&self.feature_id) || !nonempty(&self.mode) || !nonempty(&self.scale) || !nonempty(&self.request_id) || !nonempty(&self.purpose) || self.boundary != BOUNDARY || !self.raw_data_local || !self.aggregate_only || self.edge_order.is_empty() || !ordered(&self.edge_order) || !ordered(&self.accepted_order) || !ordered(&self.rejected_order) || !ordered(&self.unknown_order) || !ordered(&self.omitted_order) || !ordered(&self.node_order) || !ordered(&self.relation_order) || !ordered(&self.epoch_order) || !ordered(&self.negative_evidence_order) || !digest(&self.replay_identity) || !digest(&self.closure_digest) || self.artifact.content_type != CONTENT_TYPE || self.artifact.content_hash != self.closure_digest || self.artifact.boundary != BOUNDARY { return Err(CausalIntegrityError::Output("causal identity, ordering, locality, digest, or artifact is invalid".into())); } let ids = BTreeSet::from_iter(self.edge_order.iter().cloned()); let states = self.accepted_order.iter().chain(&self.rejected_order).chain(&self.unknown_order).chain(&self.omitted_order).cloned().collect::<Vec<_>>(); if ids.len() != self.edge_order.len() || states.len() != ids.len() || BTreeSet::from_iter(states) != ids { return Err(CausalIntegrityError::Output("edge states do not partition".into())); } Ok(()) } }
pub fn qualify(request: &CausalIntegrityRequest4, id: &str, version: &str, scale: &str, mode: &str) -> Result<CausalIntegrityCard7, CausalIntegrityError> { if !nonempty(&request.request_id) || !nonempty(&request.purpose) || request.edges.is_empty() || request.required_node_order.is_empty() || request.required_relation_order.is_empty() || !digest(&request.replay_identity) || request.boundary != BOUNDARY || !request.raw_data_local || !request.aggregate_only || !ordered(&request.required_node_order) || !ordered(&request.required_relation_order) || !ordered(&request.adversarial_events) { return Err(CausalIntegrityError::Invalid("causal identity, requirements, digest, ordering, locality, or boundary is invalid".into())); }
 let mut rows = request.edges.clone(); rows.sort_by(|a,b| a.edge_id.cmp(&b.edge_id)); let mut seen=BTreeSet::new(); let mut order=Vec::new(); let mut accepted=BTreeSet::new(); let mut rejected=BTreeSet::new(); let mut unknown=BTreeSet::new(); let mut omitted=BTreeSet::new(); let mut nodes=BTreeSet::new(); let mut relations=BTreeSet::new(); let mut epochs=BTreeSet::new(); let mut negative=BTreeSet::new(); let mut digests=BTreeSet::new();
 for e in &rows { if !seen.insert(e.edge_id.clone()) || !nonempty(&e.edge_id) || !nonempty(&e.cause_id) || !nonempty(&e.effect_id) || e.cause_id == e.effect_id || !nonempty(&e.relation) || !digest(&e.evidence_digest) || !e.local || !e.aggregate_only { return Err(CausalIntegrityError::Invalid("edge identity, endpoints, evidence, or locality is invalid".into())); } order.push(e.edge_id.clone()); nodes.insert(e.cause_id.clone()); nodes.insert(e.effect_id.clone()); relations.insert(e.relation.clone()); epochs.insert(format!("{}:{}", e.relation, e.policy_epoch)); digests.insert(e.evidence_digest.clone()); if e.negative_result { negative.insert(format!("{}:negative-result", e.edge_id)); } if e.policy_epoch == 0 { unknown.insert(e.edge_id.clone()); } else if !request.required_relation_order.contains(&e.relation) || !request.required_node_order.contains(&e.cause_id) || !request.required_node_order.contains(&e.effect_id) { rejected.insert(e.edge_id.clone()); } else if e.evidence_digest == request.replay_identity { omitted.insert(e.edge_id.clone()); } else { accepted.insert(e.edge_id.clone()); } }
 let global=!request.policy_allowed || !request.protected_closure || !request.signed_approval || !request.raw_data_local || !request.aggregate_only || !request.adversarial_events.is_empty() || request.action_count > request.action_budget; if global { omitted.extend(order.iter().cloned()); accepted.clear(); rejected.clear(); unknown.clear(); } let missing=!request.required_node_order.iter().all(|n|nodes.contains(n)) || !request.required_relation_order.iter().all(|r|relations.contains(r)); let disposition=if global{"blocked"}else if missing{"unknown"}else if !rejected.is_empty()||!unknown.is_empty()||!omitted.is_empty(){"partial"}else{"qualified"}; let mut payload=json!({"schema_version":"1.0.0","contract_version":version,"feature_id":id,"mode":mode,"scale":scale,"request_id":request.request_id,"purpose":request.purpose,"disposition":disposition,"edge_order":order,"accepted_order":accepted.into_iter().collect::<Vec<_>>(),"rejected_order":rejected.into_iter().collect::<Vec<_>>(),"unknown_order":unknown.into_iter().collect::<Vec<_>>(),"omitted_order":omitted.into_iter().collect::<Vec<_>>(),"node_order":nodes.into_iter().collect::<Vec<_>>(),"relation_order":relations.into_iter().collect::<Vec<_>>(),"epoch_order":epochs.into_iter().collect::<Vec<_>>(),"negative_evidence_order":negative.into_iter().collect::<Vec<_>>(),"replay_identity":request.replay_identity,"raw_data_local":true,"aggregate_only":true,"boundary":BOUNDARY}); let hash=ContentHash::of_value(&payload).map_err(|e|CausalIntegrityError::Output(e.to_string()))?; payload["closure_digest"]=json!(hash); payload["artifact"]=json!({"artifact_id":format!("world-causal:{}",request.request_id),"content_type":CONTENT_TYPE,"content_hash":hash,"semantic_loss":payload["omitted_order"],"edge_digests":digests.into_iter().collect::<Vec<_>>(),"boundary":BOUNDARY}); payload["effect_receipts"]=json!(if disposition=="qualified"{vec![format!("emit:causal-card:{}",request.request_id)]}else{vec!["block:unsafe-release".to_string()]}); let out:CausalIntegrityCard7=serde_json::from_value(payload).map_err(|e|CausalIntegrityError::Output(e.to_string()))?; out.validate()?; Ok(out) }

