/** Public TypeScript contracts for Worldgen P30 adversarial recovery. */
import {digestJsonSync} from "./tooling.js";import {PRECLINICAL_BOUNDARY,RESEARCH_CONTRACT_SCHEMA_VERSION} from "./research-contracts.js";
export const WORLDGEN_ADVERSARIAL_RECOVERY_CONTENT_TYPE="application/vnd.aurora.worldgen.adversarial-recovery-receipt-1+json" as const;
export const WORLDGEN_LOCAL_ADVERSARIAL_RECOVERY_FEATURE_ID="AFA-worldgen-P30-F01" as const;export const WORLDGEN_MULTIMODAL_ADVERSARIAL_RECOVERY_FEATURE_ID="AFA-worldgen-P30-F02" as const;export const WORLDGEN_THROUGHPUT_ADVERSARIAL_RECOVERY_FEATURE_ID="AFA-worldgen-P30-F03" as const;export const WORLDGEN_FEDERATED_ADVERSARIAL_RECOVERY_FEATURE_ID="AFA-worldgen-P30-F04" as const;
export const WORLDGEN_LOCAL_ADVERSARIAL_RECOVERY_CONTRACT_FEATURE_ID="AFA-worldgen-P30-F05" as const;export const WORLDGEN_MULTIMODAL_ADVERSARIAL_RECOVERY_CONTRACT_FEATURE_ID="AFA-worldgen-P30-F06" as const;export const WORLDGEN_THROUGHPUT_ADVERSARIAL_RECOVERY_CONTRACT_FEATURE_ID="AFA-worldgen-P30-F07" as const;export const WORLDGEN_FEDERATED_ADVERSARIAL_RECOVERY_CONTRACT_FEATURE_ID="AFA-worldgen-P30-F08" as const;
export const WORLDGEN_LOCAL_ADVERSARIAL_RECOVERY_COPILOT_FEATURE_ID="AFA-worldgen-P30-F09" as const;export const WORLDGEN_MULTIMODAL_ADVERSARIAL_RECOVERY_COPILOT_FEATURE_ID="AFA-worldgen-P30-F10" as const;export const WORLDGEN_THROUGHPUT_ADVERSARIAL_RECOVERY_COPILOT_FEATURE_ID="AFA-worldgen-P30-F11" as const;export const WORLDGEN_FEDERATED_ADVERSARIAL_RECOVERY_COPILOT_FEATURE_ID="AFA-worldgen-P30-F12" as const;
export const WORLDGEN_LOCAL_ADVERSARIAL_RECOVERY_WORKFLOW_FEATURE_ID="AFA-worldgen-P30-F13" as const;export const WORLDGEN_MULTIMODAL_ADVERSARIAL_RECOVERY_WORKFLOW_FEATURE_ID="AFA-worldgen-P30-F14" as const;export const WORLDGEN_THROUGHPUT_ADVERSARIAL_RECOVERY_WORKFLOW_FEATURE_ID="AFA-worldgen-P30-F15" as const;export const WORLDGEN_FEDERATED_ADVERSARIAL_RECOVERY_WORKFLOW_FEATURE_ID="AFA-worldgen-P30-F16" as const;
export interface WorldgenAdversarialRecoveryCard{schema_version:string;contract_version:string;feature_id:string;mode:string;scale:string;request_id:string;disposition:"recovered"|"partial"|"unknown"|"blocked";event_order:string[];recovered_order:string[];quarantined_order:string[];blocked_order:string[];unknown_order:string[];omitted_order:string[];checkpoint_order:string[];compensation_order:string[];security_order:string[];negative_evidence_order:string[];replay_identity:string;recovery_digest:string;artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];event_digests:string[];boundary:string};effect_receipts:string[];raw_data_local:true;aggregate_only:true;boundary:string}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown)=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
function validate(r:WorldgenAdversarialRecoveryCard,id:string){if(r.schema_version!==RESEARCH_CONTRACT_SCHEMA_VERSION||r.feature_id!==id||r.boundary!==PRECLINICAL_BOUNDARY||r.raw_data_local!==true||r.aggregate_only!==true||!r.event_order.length||!digest(r.replay_identity)||!digest(r.recovery_digest)||r.artifact.content_type!==WORLDGEN_ADVERSARIAL_RECOVERY_CONTENT_TYPE||r.artifact.content_hash!==r.recovery_digest||r.artifact.boundary!==PRECLINICAL_BOUNDARY)throw new Error("adversarial recovery identity, locality, or digest is invalid");for(const v of [r.event_order,r.recovered_order,r.quarantined_order,r.blocked_order,r.unknown_order,r.omitted_order,r.checkpoint_order,r.compensation_order,r.security_order,r.negative_evidence_order,r.effect_receipts])if(!ordered(v))throw new Error("recovery vectors are not canonical");const ids=new Set(r.event_order),parts=new Set([...r.recovered_order,...r.quarantined_order,...r.blocked_order,...r.unknown_order,...r.omitted_order]);if(ids.size!==parts.size||[...ids].some(x=>!parts.has(x)))throw new Error("recovery states do not partition")}
export const validateWorldgenLocalAdversarialRecovery=(r:WorldgenAdversarialRecoveryCard)=>validate(r,WORLDGEN_LOCAL_ADVERSARIAL_RECOVERY_FEATURE_ID);export const validateWorldgenMultimodalAdversarialRecovery=(r:WorldgenAdversarialRecoveryCard)=>validate(r,WORLDGEN_MULTIMODAL_ADVERSARIAL_RECOVERY_FEATURE_ID);export const validateWorldgenThroughputAdversarialRecovery=(r:WorldgenAdversarialRecoveryCard)=>validate(r,WORLDGEN_THROUGHPUT_ADVERSARIAL_RECOVERY_FEATURE_ID);export const validateWorldgenFederatedAdversarialRecovery=(r:WorldgenAdversarialRecoveryCard)=>validate(r,WORLDGEN_FEDERATED_ADVERSARIAL_RECOVERY_FEATURE_ID);
export const worldgenAdversarialRecoveryDigest=(r:WorldgenAdversarialRecoveryCard)=>{validateWorldgenLocalAdversarialRecovery(r);return digestJsonSync(r)};export const worldgenAdversarialRecoveryContractDigest=(r:WorldgenAdversarialRecoveryCard)=>{validate(r,WORLDGEN_LOCAL_ADVERSARIAL_RECOVERY_CONTRACT_FEATURE_ID);return digestJsonSync(r)};export const worldgenAdversarialRecoveryCopilotDigest=(r:WorldgenAdversarialRecoveryCard)=>{validate(r,WORLDGEN_LOCAL_ADVERSARIAL_RECOVERY_COPILOT_FEATURE_ID);return digestJsonSync(r)};export const worldgenAdversarialRecoveryWorkflowDigest=(r:WorldgenAdversarialRecoveryCard)=>{validate(r,WORLDGEN_LOCAL_ADVERSARIAL_RECOVERY_WORKFLOW_FEATURE_ID);return digestJsonSync(r)};
