/** Public TypeScript contracts for Backends P32 capability-negotiation integrity cards. */
import {digestJsonSync} from "./tooling.js";
export const BACKENDS_CAPABILITY_NEGOTIATION_INTEGRITY_CONTENT_TYPE="application/vnd.aurora.backends.capability-negotiation-integrity-card-1+json" as const;
export const BACKENDS_CAPABILITY_NEGOTIATION_INTEGRITY_BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions" as const;
export const BACKENDS_LOCAL_CAPABILITY_NEGOTIATION_INTEGRITY_FEATURE_ID="AFA-backends-P32-F01" as const;export const BACKENDS_MULTIMODAL_CAPABILITY_NEGOTIATION_INTEGRITY_FEATURE_ID="AFA-backends-P32-F02" as const;export const BACKENDS_THROUGHPUT_CAPABILITY_NEGOTIATION_INTEGRITY_FEATURE_ID="AFA-backends-P32-F03" as const;export const BACKENDS_FEDERATED_CONTINUAL_CAPABILITY_NEGOTIATION_INTEGRITY_FEATURE_ID="AFA-backends-P32-F04" as const;
export const BACKENDS_LOCAL_CAPABILITY_NEGOTIATION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-backends-P32-F05" as const;export const BACKENDS_MULTIMODAL_CAPABILITY_NEGOTIATION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-backends-P32-F06" as const;export const BACKENDS_THROUGHPUT_CAPABILITY_NEGOTIATION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-backends-P32-F07" as const;export const BACKENDS_FEDERATED_CONTINUAL_CAPABILITY_NEGOTIATION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-backends-P32-F08" as const;
export const BACKENDS_LOCAL_CAPABILITY_NEGOTIATION_INTEGRITY_COPILOT_FEATURE_ID="AFA-backends-P32-F09" as const;export const BACKENDS_MULTIMODAL_CAPABILITY_NEGOTIATION_INTEGRITY_COPILOT_FEATURE_ID="AFA-backends-P32-F10" as const;export const BACKENDS_THROUGHPUT_CAPABILITY_NEGOTIATION_INTEGRITY_COPILOT_FEATURE_ID="AFA-backends-P32-F11" as const;export const BACKENDS_FEDERATED_CONTINUAL_CAPABILITY_NEGOTIATION_INTEGRITY_COPILOT_FEATURE_ID="AFA-backends-P32-F12" as const;
export const BACKENDS_LOCAL_CAPABILITY_NEGOTIATION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-backends-P32-F13" as const;export const BACKENDS_MULTIMODAL_CAPABILITY_NEGOTIATION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-backends-P32-F14" as const;export const BACKENDS_THROUGHPUT_CAPABILITY_NEGOTIATION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-backends-P32-F15" as const;export const BACKENDS_FEDERATED_CONTINUAL_CAPABILITY_NEGOTIATION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-backends-P32-F16" as const;
export interface BackendsCapabilityNegotiationIntegrityCard{schema_version:string;contract_version:string;feature_id:string;request_id:string;purpose:string;disposition:"selected"|"partial"|"unknown"|"blocked";backend_order:string[];selected_order:string[];rejected_order:string[];unknown_order:string[];omitted_order:string[];runtime_order:string[];version_order:string[];capability_order:string[];determinism_order:string[];replay_identity:string;closure_digest:string;selected_backend:string|null;raw_data_local:true;aggregate_only:true;boundary:string;effect_receipts:string[];artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];evidence_digests:string[];boundary:string}}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);function validate(c:BackendsCapabilityNegotiationIntegrityCard,id:string){if(c.schema_version!=="aurora-research-contract/1.0"||c.feature_id!==id||!c.request_id||!c.purpose||c.boundary!==BACKENDS_CAPABILITY_NEGOTIATION_INTEGRITY_BOUNDARY||c.raw_data_local!==true||c.aggregate_only!==true||!digest(c.replay_identity)||!digest(c.closure_digest)||c.artifact.content_type!==BACKENDS_CAPABILITY_NEGOTIATION_INTEGRITY_CONTENT_TYPE||c.artifact.content_hash!==c.closure_digest||c.artifact.boundary!==BACKENDS_CAPABILITY_NEGOTIATION_INTEGRITY_BOUNDARY)throw new Error("backend identity, locality, digest, artifact, or boundary is incomplete");for(const v of [c.backend_order,c.selected_order,c.rejected_order,c.unknown_order,c.omitted_order,c.runtime_order,c.version_order,c.capability_order,c.determinism_order,c.effect_receipts])if(!ordered(v))throw new Error("backend vectors are not canonical");const ids=new Set(c.backend_order),states=new Set([...c.selected_order,...c.rejected_order,...c.unknown_order,...c.omitted_order]);if(ids.size!==states.size||[...ids].some(x=>!states.has(x)))throw new Error("backend states do not partition candidates");if(c.selected_backend!==null&&!c.selected_order.includes(c.selected_backend))throw new Error("selected backend is not selected")}
export const validateBackendsLocalCapabilityNegotiationIntegrity=(c:BackendsCapabilityNegotiationIntegrityCard)=>validate(c,BACKENDS_LOCAL_CAPABILITY_NEGOTIATION_INTEGRITY_FEATURE_ID);export const validateBackendsMultimodalCapabilityNegotiationIntegrity=(c:BackendsCapabilityNegotiationIntegrityCard)=>validate(c,BACKENDS_MULTIMODAL_CAPABILITY_NEGOTIATION_INTEGRITY_FEATURE_ID);export const validateBackendsThroughputCapabilityNegotiationIntegrity=(c:BackendsCapabilityNegotiationIntegrityCard)=>validate(c,BACKENDS_THROUGHPUT_CAPABILITY_NEGOTIATION_INTEGRITY_FEATURE_ID);export const validateBackendsFederatedContinualCapabilityNegotiationIntegrity=(c:BackendsCapabilityNegotiationIntegrityCard)=>validate(c,BACKENDS_FEDERATED_CONTINUAL_CAPABILITY_NEGOTIATION_INTEGRITY_FEATURE_ID);
export const backendsCapabilityNegotiationIntegrityDigest=(c:BackendsCapabilityNegotiationIntegrityCard)=>{validateBackendsLocalCapabilityNegotiationIntegrity(c);return digestJsonSync(c)};export const backendsCapabilityNegotiationIntegrityContractDigest=(c:BackendsCapabilityNegotiationIntegrityCard)=>{validate(c,BACKENDS_LOCAL_CAPABILITY_NEGOTIATION_INTEGRITY_CONTRACT_FEATURE_ID);return digestJsonSync(c)};export const backendsCapabilityNegotiationIntegrityCopilotDigest=(c:BackendsCapabilityNegotiationIntegrityCard)=>{validate(c,BACKENDS_LOCAL_CAPABILITY_NEGOTIATION_INTEGRITY_COPILOT_FEATURE_ID);return digestJsonSync(c)};export const backendsCapabilityNegotiationIntegrityWorkflowDigest=(c:BackendsCapabilityNegotiationIntegrityCard)=>{validate(c,BACKENDS_LOCAL_CAPABILITY_NEGOTIATION_INTEGRITY_WORKFLOW_FEATURE_ID);return digestJsonSync(c)};
