/** Public TypeScript contracts for Worldgen P32 bounded evolution. */
import {digestJsonSync} from "./tooling.js";import {PRECLINICAL_BOUNDARY,RESEARCH_CONTRACT_SCHEMA_VERSION} from "./research-contracts.js";
export const WORLDGEN_BOUNDED_EVOLUTION_CONTENT_TYPE="application/vnd.aurora.worldgen.bounded-evolution-card-1+json" as const;
export const WORLDGEN_LOCAL_BOUNDED_EVOLUTION_FEATURE_ID="AFA-worldgen-P32-F01" as const;export const WORLDGEN_MULTIMODAL_BOUNDED_EVOLUTION_FEATURE_ID="AFA-worldgen-P32-F02" as const;export const WORLDGEN_THROUGHPUT_BOUNDED_EVOLUTION_FEATURE_ID="AFA-worldgen-P32-F03" as const;export const WORLDGEN_FEDERATED_BOUNDED_EVOLUTION_FEATURE_ID="AFA-worldgen-P32-F04" as const;
export const WORLDGEN_LOCAL_BOUNDED_EVOLUTION_CONTRACT_FEATURE_ID="AFA-worldgen-P32-F05" as const;export const WORLDGEN_MULTIMODAL_BOUNDED_EVOLUTION_CONTRACT_FEATURE_ID="AFA-worldgen-P32-F06" as const;export const WORLDGEN_THROUGHPUT_BOUNDED_EVOLUTION_CONTRACT_FEATURE_ID="AFA-worldgen-P32-F07" as const;export const WORLDGEN_FEDERATED_BOUNDED_EVOLUTION_CONTRACT_FEATURE_ID="AFA-worldgen-P32-F08" as const;
export const WORLDGEN_LOCAL_BOUNDED_EVOLUTION_COPILOT_FEATURE_ID="AFA-worldgen-P32-F09" as const;export const WORLDGEN_MULTIMODAL_BOUNDED_EVOLUTION_COPILOT_FEATURE_ID="AFA-worldgen-P32-F10" as const;export const WORLDGEN_THROUGHPUT_BOUNDED_EVOLUTION_COPILOT_FEATURE_ID="AFA-worldgen-P32-F11" as const;export const WORLDGEN_FEDERATED_BOUNDED_EVOLUTION_COPILOT_FEATURE_ID="AFA-worldgen-P32-F12" as const;
export const WORLDGEN_LOCAL_BOUNDED_EVOLUTION_WORKFLOW_FEATURE_ID="AFA-worldgen-P32-F13" as const;export const WORLDGEN_MULTIMODAL_BOUNDED_EVOLUTION_WORKFLOW_FEATURE_ID="AFA-worldgen-P32-F14" as const;export const WORLDGEN_THROUGHPUT_BOUNDED_EVOLUTION_WORKFLOW_FEATURE_ID="AFA-worldgen-P32-F15" as const;export const WORLDGEN_FEDERATED_BOUNDED_EVOLUTION_WORKFLOW_FEATURE_ID="AFA-worldgen-P32-F16" as const;
export interface WorldgenBoundedEvolutionCard{schema_version:string;contract_version:string;feature_id:string;mode:string;scale:string;request_id:string;disposition:"promoted"|"partial"|"unknown"|"blocked";candidate_order:string[];promoted_order:string[];rejected_order:string[];unknown_order:string[];omitted_order:string[];benchmark_order:string[];review_order:string[];uncertainty_order:string[];negative_evidence_order:string[];migration_order:string[];replay_identity:string;evolution_digest:string;artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];candidate_digests:string[];boundary:string};effect_receipts:string[];raw_data_local:true;aggregate_only:true;boundary:string}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown)=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
function validate(r:WorldgenBoundedEvolutionCard,id:string){if(r.schema_version!==RESEARCH_CONTRACT_SCHEMA_VERSION||r.feature_id!==id||r.boundary!==PRECLINICAL_BOUNDARY||r.raw_data_local!==true||r.aggregate_only!==true||!r.candidate_order.length||!digest(r.replay_identity)||!digest(r.evolution_digest)||r.artifact.content_type!==WORLDGEN_BOUNDED_EVOLUTION_CONTENT_TYPE||r.artifact.content_hash!==r.evolution_digest||r.artifact.boundary!==PRECLINICAL_BOUNDARY)throw new Error("bounded evolution identity, locality, or digest is invalid");for(const v of [r.candidate_order,r.promoted_order,r.rejected_order,r.unknown_order,r.omitted_order,r.benchmark_order,r.review_order,r.uncertainty_order,r.negative_evidence_order,r.migration_order,r.effect_receipts])if(!ordered(v))throw new Error("evolution vectors are not canonical");const ids=new Set(r.candidate_order),parts=new Set([...r.promoted_order,...r.rejected_order,...r.unknown_order,...r.omitted_order]);if(ids.size!==parts.size||[...ids].some(x=>!parts.has(x)))throw new Error("candidate states do not partition")}
export const validateWorldgenLocalBoundedEvolution=(r:WorldgenBoundedEvolutionCard)=>validate(r,WORLDGEN_LOCAL_BOUNDED_EVOLUTION_FEATURE_ID);export const validateWorldgenMultimodalBoundedEvolution=(r:WorldgenBoundedEvolutionCard)=>validate(r,WORLDGEN_MULTIMODAL_BOUNDED_EVOLUTION_FEATURE_ID);export const validateWorldgenThroughputBoundedEvolution=(r:WorldgenBoundedEvolutionCard)=>validate(r,WORLDGEN_THROUGHPUT_BOUNDED_EVOLUTION_FEATURE_ID);export const validateWorldgenFederatedBoundedEvolution=(r:WorldgenBoundedEvolutionCard)=>validate(r,WORLDGEN_FEDERATED_BOUNDED_EVOLUTION_FEATURE_ID);
export const worldgenBoundedEvolutionDigest=(r:WorldgenBoundedEvolutionCard)=>{validateWorldgenLocalBoundedEvolution(r);return digestJsonSync(r)};export const worldgenBoundedEvolutionContractDigest=(r:WorldgenBoundedEvolutionCard)=>{validate(r,WORLDGEN_LOCAL_BOUNDED_EVOLUTION_CONTRACT_FEATURE_ID);return digestJsonSync(r)};export const worldgenBoundedEvolutionCopilotDigest=(r:WorldgenBoundedEvolutionCard)=>{validate(r,WORLDGEN_LOCAL_BOUNDED_EVOLUTION_COPILOT_FEATURE_ID);return digestJsonSync(r)};export const worldgenBoundedEvolutionWorkflowDigest=(r:WorldgenBoundedEvolutionCard)=>{validate(r,WORLDGEN_LOCAL_BOUNDED_EVOLUTION_WORKFLOW_FEATURE_ID);return digestJsonSync(r)};
