/** Public TypeScript contracts for Bundle P32 signed research-object integrity cards. */
import {digestJsonSync} from "./tooling.js";
export const BUNDLE_RESEARCH_BUNDLE_INTEGRITY_CONTENT_TYPE="application/vnd.aurora.bundle.research-object-integrity-card-1+json" as const;
export const BUNDLE_RESEARCH_BUNDLE_INTEGRITY_BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions" as const;
export const BUNDLE_LOCAL_RESEARCH_BUNDLE_INTEGRITY_FEATURE_ID="AFA-bundle-P32-F01" as const;export const BUNDLE_MULTIMODAL_RESEARCH_BUNDLE_INTEGRITY_FEATURE_ID="AFA-bundle-P32-F02" as const;export const BUNDLE_THROUGHPUT_RESEARCH_BUNDLE_INTEGRITY_FEATURE_ID="AFA-bundle-P32-F03" as const;export const BUNDLE_FEDERATED_CONTINUAL_RESEARCH_BUNDLE_INTEGRITY_FEATURE_ID="AFA-bundle-P32-F04" as const;
export const BUNDLE_LOCAL_RESEARCH_BUNDLE_INTEGRITY_CONTRACT_FEATURE_ID="AFA-bundle-P32-F05" as const;export const BUNDLE_MULTIMODAL_RESEARCH_BUNDLE_INTEGRITY_CONTRACT_FEATURE_ID="AFA-bundle-P32-F06" as const;export const BUNDLE_THROUGHPUT_RESEARCH_BUNDLE_INTEGRITY_CONTRACT_FEATURE_ID="AFA-bundle-P32-F07" as const;export const BUNDLE_FEDERATED_CONTINUAL_RESEARCH_BUNDLE_INTEGRITY_CONTRACT_FEATURE_ID="AFA-bundle-P32-F08" as const;
export const BUNDLE_LOCAL_RESEARCH_BUNDLE_INTEGRITY_COPILOT_FEATURE_ID="AFA-bundle-P32-F09" as const;export const BUNDLE_MULTIMODAL_RESEARCH_BUNDLE_INTEGRITY_COPILOT_FEATURE_ID="AFA-bundle-P32-F10" as const;export const BUNDLE_THROUGHPUT_RESEARCH_BUNDLE_INTEGRITY_COPILOT_FEATURE_ID="AFA-bundle-P32-F11" as const;export const BUNDLE_FEDERATED_CONTINUAL_RESEARCH_BUNDLE_INTEGRITY_COPILOT_FEATURE_ID="AFA-bundle-P32-F12" as const;
export const BUNDLE_LOCAL_RESEARCH_BUNDLE_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-bundle-P32-F13" as const;export const BUNDLE_MULTIMODAL_RESEARCH_BUNDLE_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-bundle-P32-F14" as const;export const BUNDLE_THROUGHPUT_RESEARCH_BUNDLE_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-bundle-P32-F15" as const;export const BUNDLE_FEDERATED_CONTINUAL_RESEARCH_BUNDLE_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-bundle-P32-F16" as const;
export interface BundleResearchBundleIntegrityCard{schema_version:string;contract_version:string;feature_id:string;request_id:string;purpose:string;disposition:"released"|"partial"|"unknown"|"blocked";entry_order:string[];released_order:string[];rejected_order:string[];unknown_order:string[];omitted_order:string[];role_order:string[];content_order:string[];provenance_order:string[];replay_identity:string;closure_digest:string;release_digest:string;released_entry_count:number;total_entry_count:number;raw_data_local:true;aggregate_only:true;boundary:string;effect_receipts:string[];artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];evidence_digests:string[];boundary:string}}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);function validate(c:BundleResearchBundleIntegrityCard,id:string){if(c.schema_version!=="aurora-research-contract/1.0"||c.feature_id!==id||!c.request_id||!c.purpose||c.boundary!==BUNDLE_RESEARCH_BUNDLE_INTEGRITY_BOUNDARY||c.raw_data_local!==true||c.aggregate_only!==true||!digest(c.replay_identity)||!digest(c.closure_digest)||!digest(c.release_digest)||c.artifact.content_type!==BUNDLE_RESEARCH_BUNDLE_INTEGRITY_CONTENT_TYPE||c.artifact.content_hash!==c.closure_digest||c.artifact.boundary!==BUNDLE_RESEARCH_BUNDLE_INTEGRITY_BOUNDARY||c.released_entry_count>c.total_entry_count)throw new Error("bundle identity, locality, digest, artifact, boundary, or count is incomplete");for(const v of [c.entry_order,c.released_order,c.rejected_order,c.unknown_order,c.omitted_order,c.role_order,c.content_order,c.provenance_order,c.effect_receipts])if(!ordered(v))throw new Error("bundle vectors are not canonical");const ids=new Set(c.entry_order),states=new Set([...c.released_order,...c.rejected_order,...c.unknown_order,...c.omitted_order]);if(ids.size!==states.size||[...ids].some(x=>!states.has(x)))throw new Error("bundle states do not partition entries")}
export const validateBundleLocalResearchBundleIntegrity=(c:BundleResearchBundleIntegrityCard)=>validate(c,BUNDLE_LOCAL_RESEARCH_BUNDLE_INTEGRITY_FEATURE_ID);export const validateBundleMultimodalResearchBundleIntegrity=(c:BundleResearchBundleIntegrityCard)=>validate(c,BUNDLE_MULTIMODAL_RESEARCH_BUNDLE_INTEGRITY_FEATURE_ID);export const validateBundleThroughputResearchBundleIntegrity=(c:BundleResearchBundleIntegrityCard)=>validate(c,BUNDLE_THROUGHPUT_RESEARCH_BUNDLE_INTEGRITY_FEATURE_ID);export const validateBundleFederatedContinualResearchBundleIntegrity=(c:BundleResearchBundleIntegrityCard)=>validate(c,BUNDLE_FEDERATED_CONTINUAL_RESEARCH_BUNDLE_INTEGRITY_FEATURE_ID);
export const bundleResearchBundleIntegrityDigest=(c:BundleResearchBundleIntegrityCard)=>{validateBundleLocalResearchBundleIntegrity(c);return digestJsonSync(c)};export const bundleResearchBundleIntegrityContractDigest=(c:BundleResearchBundleIntegrityCard)=>{validate(c,BUNDLE_LOCAL_RESEARCH_BUNDLE_INTEGRITY_CONTRACT_FEATURE_ID);return digestJsonSync(c)};export const bundleResearchBundleIntegrityCopilotDigest=(c:BundleResearchBundleIntegrityCard)=>{validate(c,BUNDLE_LOCAL_RESEARCH_BUNDLE_INTEGRITY_COPILOT_FEATURE_ID);return digestJsonSync(c)};export const bundleResearchBundleIntegrityWorkflowDigest=(c:BundleResearchBundleIntegrityCard)=>{validate(c,BUNDLE_LOCAL_RESEARCH_BUNDLE_INTEGRITY_WORKFLOW_FEATURE_ID);return digestJsonSync(c)};
