/** Public TypeScript contracts for Choreography P32 protocol-execution integrity cards. */
import {digestJsonSync} from "./tooling.js";

export const CHOREOGRAPHY_PROTOCOL_EXECUTION_INTEGRITY_CONTENT_TYPE="application/vnd.aurora.choreography.protocol-execution-integrity-card-1+json" as const;
export const CHOREOGRAPHY_PROTOCOL_EXECUTION_INTEGRITY_BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions" as const;
export const CHOREOGRAPHY_LOCAL_PROTOCOL_EXECUTION_INTEGRITY_FEATURE_ID="AFA-choreography-P32-F01" as const;export const CHOREOGRAPHY_MULTIMODAL_PROTOCOL_EXECUTION_INTEGRITY_FEATURE_ID="AFA-choreography-P32-F02" as const;export const CHOREOGRAPHY_THROUGHPUT_PROTOCOL_EXECUTION_INTEGRITY_FEATURE_ID="AFA-choreography-P32-F03" as const;export const CHOREOGRAPHY_FEDERATED_CONTINUAL_PROTOCOL_EXECUTION_INTEGRITY_FEATURE_ID="AFA-choreography-P32-F04" as const;
export const CHOREOGRAPHY_LOCAL_PROTOCOL_EXECUTION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-choreography-P32-F05" as const;export const CHOREOGRAPHY_MULTIMODAL_PROTOCOL_EXECUTION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-choreography-P32-F06" as const;export const CHOREOGRAPHY_THROUGHPUT_PROTOCOL_EXECUTION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-choreography-P32-F07" as const;export const CHOREOGRAPHY_FEDERATED_CONTINUAL_PROTOCOL_EXECUTION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-choreography-P32-F08" as const;
export const CHOREOGRAPHY_LOCAL_PROTOCOL_EXECUTION_INTEGRITY_COPILOT_FEATURE_ID="AFA-choreography-P32-F09" as const;export const CHOREOGRAPHY_MULTIMODAL_PROTOCOL_EXECUTION_INTEGRITY_COPILOT_FEATURE_ID="AFA-choreography-P32-F10" as const;export const CHOREOGRAPHY_THROUGHPUT_PROTOCOL_EXECUTION_INTEGRITY_COPILOT_FEATURE_ID="AFA-choreography-P32-F11" as const;export const CHOREOGRAPHY_FEDERATED_CONTINUAL_PROTOCOL_EXECUTION_INTEGRITY_COPILOT_FEATURE_ID="AFA-choreography-P32-F12" as const;
export const CHOREOGRAPHY_LOCAL_PROTOCOL_EXECUTION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-choreography-P32-F13" as const;export const CHOREOGRAPHY_MULTIMODAL_PROTOCOL_EXECUTION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-choreography-P32-F14" as const;export const CHOREOGRAPHY_THROUGHPUT_PROTOCOL_EXECUTION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-choreography-P32-F15" as const;export const CHOREOGRAPHY_FEDERATED_CONTINUAL_PROTOCOL_EXECUTION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-choreography-P32-F16" as const;

export interface ChoreographyProtocolExecutionIntegrityCard{schema_version:string;contract_version:string;feature_id:string;request_id:string;purpose:string;disposition:"completed"|"partial"|"unknown"|"blocked";step_order:string[];completed_order:string[];blocked_order:string[];unknown_order:string[];omitted_order:string[];role_order:string[];operation_order:string[];state_order:string[];replay_identity:string;closure_digest:string;completed_step_count:number;total_step_count:number;raw_data_local:true;aggregate_only:true;boundary:string;effect_receipts:string[];artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];evidence_digests:string[];boundary:string}}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
function validate(c:ChoreographyProtocolExecutionIntegrityCard,id:string){if(c.schema_version!=="aurora-research-contract/1.0"||c.feature_id!==id||!c.request_id||!c.purpose||c.boundary!==CHOREOGRAPHY_PROTOCOL_EXECUTION_INTEGRITY_BOUNDARY||c.raw_data_local!==true||c.aggregate_only!==true||!digest(c.replay_identity)||!digest(c.closure_digest)||c.artifact.content_type!==CHOREOGRAPHY_PROTOCOL_EXECUTION_INTEGRITY_CONTENT_TYPE||c.artifact.content_hash!==c.closure_digest||c.artifact.boundary!==CHOREOGRAPHY_PROTOCOL_EXECUTION_INTEGRITY_BOUNDARY||c.completed_step_count>c.total_step_count)throw new Error("protocol identity, locality, artifact, digest, boundary, or count is incomplete");for(const v of [c.step_order,c.completed_order,c.blocked_order,c.unknown_order,c.omitted_order,c.role_order,c.operation_order,c.state_order,c.effect_receipts])if(!ordered(v))throw new Error("protocol vectors are not canonical");const ids=new Set(c.step_order),states=new Set([...c.completed_order,...c.blocked_order,...c.unknown_order,...c.omitted_order]);if(ids.size!==states.size||[...ids].some(x=>!states.has(x)))throw new Error("protocol states do not partition steps");if(c.completed_step_count!==c.completed_order.length)throw new Error("completed step count does not match completed order")}
export const validateChoreographyLocalProtocolExecutionIntegrity=(c:ChoreographyProtocolExecutionIntegrityCard)=>validate(c,CHOREOGRAPHY_LOCAL_PROTOCOL_EXECUTION_INTEGRITY_FEATURE_ID);export const validateChoreographyMultimodalProtocolExecutionIntegrity=(c:ChoreographyProtocolExecutionIntegrityCard)=>validate(c,CHOREOGRAPHY_MULTIMODAL_PROTOCOL_EXECUTION_INTEGRITY_FEATURE_ID);export const validateChoreographyThroughputProtocolExecutionIntegrity=(c:ChoreographyProtocolExecutionIntegrityCard)=>validate(c,CHOREOGRAPHY_THROUGHPUT_PROTOCOL_EXECUTION_INTEGRITY_FEATURE_ID);export const validateChoreographyFederatedContinualProtocolExecutionIntegrity=(c:ChoreographyProtocolExecutionIntegrityCard)=>validate(c,CHOREOGRAPHY_FEDERATED_CONTINUAL_PROTOCOL_EXECUTION_INTEGRITY_FEATURE_ID);
export const choreographyProtocolExecutionIntegrityDigest=(c:ChoreographyProtocolExecutionIntegrityCard)=>{validateChoreographyLocalProtocolExecutionIntegrity(c);return digestJsonSync(c)};export const choreographyProtocolExecutionIntegrityContractDigest=(c:ChoreographyProtocolExecutionIntegrityCard)=>{validate(c,CHOREOGRAPHY_LOCAL_PROTOCOL_EXECUTION_INTEGRITY_CONTRACT_FEATURE_ID);return digestJsonSync(c)};export const choreographyProtocolExecutionIntegrityCopilotDigest=(c:ChoreographyProtocolExecutionIntegrityCard)=>{validate(c,CHOREOGRAPHY_LOCAL_PROTOCOL_EXECUTION_INTEGRITY_COPILOT_FEATURE_ID);return digestJsonSync(c)};export const choreographyProtocolExecutionIntegrityWorkflowDigest=(c:ChoreographyProtocolExecutionIntegrityCard)=>{validate(c,CHOREOGRAPHY_LOCAL_PROTOCOL_EXECUTION_INTEGRITY_WORKFLOW_FEATURE_ID);return digestJsonSync(c)};
