/** Public TypeScript contracts for Worldgen P25 contract frontier. */
import { digestJsonSync } from "./tooling.js";
import { PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION } from "./research-contracts.js";
export const WORLDGEN_CONTRACT_FRONTIER_CONTENT_TYPE="application/vnd.aurora.worldgen.contract-frontier-receipt-1+json" as const;
export const WORLDGEN_LOCAL_CONTRACT_FRONTIER_FEATURE_ID="AFA-worldgen-P25-F01" as const;export const WORLDGEN_MULTIMODAL_CONTRACT_FRONTIER_FEATURE_ID="AFA-worldgen-P25-F02" as const;export const WORLDGEN_THROUGHPUT_CONTRACT_FRONTIER_FEATURE_ID="AFA-worldgen-P25-F03" as const;export const WORLDGEN_FEDERATED_CONTRACT_FRONTIER_FEATURE_ID="AFA-worldgen-P25-F04" as const;
export const WORLDGEN_LOCAL_CONTRACT_FRONTIER_CONTRACT_FEATURE_ID="AFA-worldgen-P25-F05" as const;export const WORLDGEN_MULTIMODAL_CONTRACT_FRONTIER_CONTRACT_FEATURE_ID="AFA-worldgen-P25-F06" as const;export const WORLDGEN_THROUGHPUT_CONTRACT_FRONTIER_CONTRACT_FEATURE_ID="AFA-worldgen-P25-F07" as const;export const WORLDGEN_FEDERATED_CONTRACT_FRONTIER_CONTRACT_FEATURE_ID="AFA-worldgen-P25-F08" as const;
export const WORLDGEN_LOCAL_CONTRACT_FRONTIER_COPILOT_FEATURE_ID="AFA-worldgen-P25-F09" as const;export const WORLDGEN_MULTIMODAL_CONTRACT_FRONTIER_COPILOT_FEATURE_ID="AFA-worldgen-P25-F10" as const;export const WORLDGEN_THROUGHPUT_CONTRACT_FRONTIER_COPILOT_FEATURE_ID="AFA-worldgen-P25-F11" as const;export const WORLDGEN_FEDERATED_CONTRACT_FRONTIER_COPILOT_FEATURE_ID="AFA-worldgen-P25-F12" as const;
export const WORLDGEN_LOCAL_CONTRACT_FRONTIER_WORKFLOW_FEATURE_ID="AFA-worldgen-P25-F13" as const;export const WORLDGEN_MULTIMODAL_CONTRACT_FRONTIER_WORKFLOW_FEATURE_ID="AFA-worldgen-P25-F14" as const;export const WORLDGEN_THROUGHPUT_CONTRACT_FRONTIER_WORKFLOW_FEATURE_ID="AFA-worldgen-P25-F15" as const;export const WORLDGEN_FEDERATED_CONTRACT_FRONTIER_WORKFLOW_FEATURE_ID="AFA-worldgen-P25-F16" as const;
export interface WorldgenContractFrontierCard{schema_version:string;contract_version:string;feature_id:string;mode:string;scale:string;request_id:string;benchmark_id:string;disposition:string;candidate_order:string[];selected_order:string[];rejected_order:string[];unknown_order:string[];omitted_order:string[];uncertainty_order:string[];negative_evidence_order:string[];capability_order:string[];schema_digest_order:string[];provenance_digest_order:string[];replay_identity:string;frontier_digest:string;artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];candidate_digests:string[];boundary:string};effect_receipts:string[];raw_data_local:true;aggregate_only:true;boundary:string}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown)=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
function validate(r:WorldgenContractFrontierCard,id:string){if(r.schema_version!==RESEARCH_CONTRACT_SCHEMA_VERSION||r.feature_id!==id||r.boundary!==PRECLINICAL_BOUNDARY||r.raw_data_local!==true||r.aggregate_only!==true||!r.candidate_order.length||!digest(r.replay_identity)||!digest(r.frontier_digest)||r.artifact.content_type!==WORLDGEN_CONTRACT_FRONTIER_CONTENT_TYPE||r.artifact.content_hash!==r.frontier_digest||r.artifact.boundary!==PRECLINICAL_BOUNDARY||JSON.stringify(r.artifact.semantic_loss)!==JSON.stringify(r.omitted_order))throw new Error("contract frontier identity, locality, or digest is invalid");for(const v of [r.candidate_order,r.selected_order,r.rejected_order,r.unknown_order,r.omitted_order,r.uncertainty_order,r.negative_evidence_order,r.capability_order,r.effect_receipts])if(!ordered(v))throw new Error("frontier vectors are not canonical");const ids=new Set(r.candidate_order),parts=new Set([...r.selected_order,...r.rejected_order,...r.unknown_order,...r.omitted_order]);if(ids.size!==parts.size||[...ids].some(x=>!parts.has(x)))throw new Error("candidate states do not partition")}
export const validateWorldgenLocalContractFrontier=(r:WorldgenContractFrontierCard)=>validate(r,WORLDGEN_LOCAL_CONTRACT_FRONTIER_FEATURE_ID);export const validateWorldgenMultimodalContractFrontier=(r:WorldgenContractFrontierCard)=>validate(r,WORLDGEN_MULTIMODAL_CONTRACT_FRONTIER_FEATURE_ID);export const validateWorldgenThroughputContractFrontier=(r:WorldgenContractFrontierCard)=>validate(r,WORLDGEN_THROUGHPUT_CONTRACT_FRONTIER_FEATURE_ID);export const validateWorldgenFederatedContractFrontier=(r:WorldgenContractFrontierCard)=>validate(r,WORLDGEN_FEDERATED_CONTRACT_FRONTIER_FEATURE_ID);
export const worldgenContractFrontierDigest=(r:WorldgenContractFrontierCard)=>{validateWorldgenLocalContractFrontier(r);return digestJsonSync(r)};export const worldgenContractFrontierContractDigest=(r:WorldgenContractFrontierCard)=>{validate(r,WORLDGEN_LOCAL_CONTRACT_FRONTIER_CONTRACT_FEATURE_ID);return digestJsonSync(r)};export const worldgenContractFrontierCopilotDigest=(r:WorldgenContractFrontierCard)=>{validate(r,WORLDGEN_LOCAL_CONTRACT_FRONTIER_COPILOT_FEATURE_ID);return digestJsonSync(r)};export const worldgenContractFrontierWorkflowDigest=(r:WorldgenContractFrontierCard)=>{validate(r,WORLDGEN_LOCAL_CONTRACT_FRONTIER_WORKFLOW_FEATURE_ID);return digestJsonSync(r)};
