/** Public TypeScript contracts for Worldgen P27 dependency composition. */
import {digestJsonSync} from "./tooling.js";import {PRECLINICAL_BOUNDARY,RESEARCH_CONTRACT_SCHEMA_VERSION} from "./research-contracts.js";
export const WORLDGEN_DEPENDENCY_COMPOSITION_CONTENT_TYPE="application/vnd.aurora.worldgen.dependency-composition-receipt-1+json" as const;
export const WORLDGEN_LOCAL_DEPENDENCY_COMPOSITION_FEATURE_ID="AFA-worldgen-P27-F01" as const;export const WORLDGEN_MULTIMODAL_DEPENDENCY_COMPOSITION_FEATURE_ID="AFA-worldgen-P27-F02" as const;export const WORLDGEN_THROUGHPUT_DEPENDENCY_COMPOSITION_FEATURE_ID="AFA-worldgen-P27-F03" as const;export const WORLDGEN_FEDERATED_DEPENDENCY_COMPOSITION_FEATURE_ID="AFA-worldgen-P27-F04" as const;
export const WORLDGEN_LOCAL_DEPENDENCY_COMPOSITION_CONTRACT_FEATURE_ID="AFA-worldgen-P27-F05" as const;export const WORLDGEN_MULTIMODAL_DEPENDENCY_COMPOSITION_CONTRACT_FEATURE_ID="AFA-worldgen-P27-F06" as const;export const WORLDGEN_THROUGHPUT_DEPENDENCY_COMPOSITION_CONTRACT_FEATURE_ID="AFA-worldgen-P27-F07" as const;export const WORLDGEN_FEDERATED_DEPENDENCY_COMPOSITION_CONTRACT_FEATURE_ID="AFA-worldgen-P27-F08" as const;
export const WORLDGEN_LOCAL_DEPENDENCY_COMPOSITION_COPILOT_FEATURE_ID="AFA-worldgen-P27-F09" as const;export const WORLDGEN_MULTIMODAL_DEPENDENCY_COMPOSITION_COPILOT_FEATURE_ID="AFA-worldgen-P27-F10" as const;export const WORLDGEN_THROUGHPUT_DEPENDENCY_COMPOSITION_COPILOT_FEATURE_ID="AFA-worldgen-P27-F11" as const;export const WORLDGEN_FEDERATED_DEPENDENCY_COMPOSITION_COPILOT_FEATURE_ID="AFA-worldgen-P27-F12" as const;
export const WORLDGEN_LOCAL_DEPENDENCY_COMPOSITION_WORKFLOW_FEATURE_ID="AFA-worldgen-P27-F13" as const;export const WORLDGEN_MULTIMODAL_DEPENDENCY_COMPOSITION_WORKFLOW_FEATURE_ID="AFA-worldgen-P27-F14" as const;export const WORLDGEN_THROUGHPUT_DEPENDENCY_COMPOSITION_WORKFLOW_FEATURE_ID="AFA-worldgen-P27-F15" as const;export const WORLDGEN_FEDERATED_DEPENDENCY_COMPOSITION_WORKFLOW_FEATURE_ID="AFA-worldgen-P27-F16" as const;
export interface WorldgenDependencyCompositionCard{schema_version:string;contract_version:string;feature_id:string;mode:string;scale:string;request_id:string;disposition:string;node_order:string[];edge_order:string[];root_order:string[];resolved_order:string[];blocked_order:string[];omitted_order:string[];cycle_order:string[];uncertainty_order:string[];semantic_loss_order:string[];replay_identity:string;composition_digest:string;artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];node_digests:string[];boundary:string};effect_receipts:string[];raw_data_local:true;aggregate_only:true;boundary:string}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown)=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
function validate(r:WorldgenDependencyCompositionCard,id:string){if(r.schema_version!==RESEARCH_CONTRACT_SCHEMA_VERSION||r.feature_id!==id||r.boundary!==PRECLINICAL_BOUNDARY||r.raw_data_local!==true||r.aggregate_only!==true||!r.node_order.length||!digest(r.replay_identity)||!digest(r.composition_digest)||r.artifact.content_type!==WORLDGEN_DEPENDENCY_COMPOSITION_CONTENT_TYPE||r.artifact.content_hash!==r.composition_digest||r.artifact.boundary!==PRECLINICAL_BOUNDARY)throw new Error("dependency composition identity, locality, or digest is invalid");for(const v of [r.node_order,r.edge_order,r.root_order,r.resolved_order,r.blocked_order,r.omitted_order,r.cycle_order,r.uncertainty_order,r.semantic_loss_order,r.effect_receipts])if(!ordered(v))throw new Error("composition vectors are not canonical");const ids=new Set(r.node_order),parts=new Set([...r.resolved_order,...r.blocked_order,...r.omitted_order]);if(ids.size!==parts.size||[...ids].some(x=>!parts.has(x)))throw new Error("dependency states do not partition")}
export const validateWorldgenLocalDependencyComposition=(r:WorldgenDependencyCompositionCard)=>validate(r,WORLDGEN_LOCAL_DEPENDENCY_COMPOSITION_FEATURE_ID);export const validateWorldgenMultimodalDependencyComposition=(r:WorldgenDependencyCompositionCard)=>validate(r,WORLDGEN_MULTIMODAL_DEPENDENCY_COMPOSITION_FEATURE_ID);export const validateWorldgenThroughputDependencyComposition=(r:WorldgenDependencyCompositionCard)=>validate(r,WORLDGEN_THROUGHPUT_DEPENDENCY_COMPOSITION_FEATURE_ID);export const validateWorldgenFederatedDependencyComposition=(r:WorldgenDependencyCompositionCard)=>validate(r,WORLDGEN_FEDERATED_DEPENDENCY_COMPOSITION_FEATURE_ID);
export const worldgenDependencyCompositionDigest=(r:WorldgenDependencyCompositionCard)=>{validateWorldgenLocalDependencyComposition(r);return digestJsonSync(r)};export const worldgenDependencyCompositionContractDigest=(r:WorldgenDependencyCompositionCard)=>{validate(r,WORLDGEN_LOCAL_DEPENDENCY_COMPOSITION_CONTRACT_FEATURE_ID);return digestJsonSync(r)};export const worldgenDependencyCompositionCopilotDigest=(r:WorldgenDependencyCompositionCard)=>{validate(r,WORLDGEN_LOCAL_DEPENDENCY_COMPOSITION_COPILOT_FEATURE_ID);return digestJsonSync(r)};export const worldgenDependencyCompositionWorkflowDigest=(r:WorldgenDependencyCompositionCard)=>{validate(r,WORLDGEN_LOCAL_DEPENDENCY_COMPOSITION_WORKFLOW_FEATURE_ID);return digestJsonSync(r)};
