/** Public TypeScript contracts for Docgraph P32 document-module lineage integrity cards. */
import {digestJsonSync} from "./tooling.js";
export const DOCGRAPH_DOCUMENT_GRAPH_INTEGRITY_CONTENT_TYPE="application/vnd.aurora.docgraph.document-module-integrity-card-1+json" as const;
export const DOCGRAPH_DOCUMENT_GRAPH_INTEGRITY_BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions" as const;
export const DOCGRAPH_LOCAL_DOCUMENT_GRAPH_INTEGRITY_FEATURE_ID="AFA-docgraph-P32-F01" as const;export const DOCGRAPH_MULTIMODAL_DOCUMENT_GRAPH_INTEGRITY_FEATURE_ID="AFA-docgraph-P32-F02" as const;export const DOCGRAPH_THROUGHPUT_DOCUMENT_GRAPH_INTEGRITY_FEATURE_ID="AFA-docgraph-P32-F03" as const;export const DOCGRAPH_FEDERATED_CONTINUAL_DOCUMENT_GRAPH_INTEGRITY_FEATURE_ID="AFA-docgraph-P32-F04" as const;
export const DOCGRAPH_LOCAL_DOCUMENT_GRAPH_INTEGRITY_CONTRACT_FEATURE_ID="AFA-docgraph-P32-F05" as const;export const DOCGRAPH_MULTIMODAL_DOCUMENT_GRAPH_INTEGRITY_CONTRACT_FEATURE_ID="AFA-docgraph-P32-F06" as const;export const DOCGRAPH_THROUGHPUT_DOCUMENT_GRAPH_INTEGRITY_CONTRACT_FEATURE_ID="AFA-docgraph-P32-F07" as const;export const DOCGRAPH_FEDERATED_CONTINUAL_DOCUMENT_GRAPH_INTEGRITY_CONTRACT_FEATURE_ID="AFA-docgraph-P32-F08" as const;
export const DOCGRAPH_LOCAL_DOCUMENT_GRAPH_INTEGRITY_COPILOT_FEATURE_ID="AFA-docgraph-P32-F09" as const;export const DOCGRAPH_MULTIMODAL_DOCUMENT_GRAPH_INTEGRITY_COPILOT_FEATURE_ID="AFA-docgraph-P32-F10" as const;export const DOCGRAPH_THROUGHPUT_DOCUMENT_GRAPH_INTEGRITY_COPILOT_FEATURE_ID="AFA-docgraph-P32-F11" as const;export const DOCGRAPH_FEDERATED_CONTINUAL_DOCUMENT_GRAPH_INTEGRITY_COPILOT_FEATURE_ID="AFA-docgraph-P32-F12" as const;
export const DOCGRAPH_LOCAL_DOCUMENT_GRAPH_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-docgraph-P32-F13" as const;export const DOCGRAPH_MULTIMODAL_DOCUMENT_GRAPH_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-docgraph-P32-F14" as const;export const DOCGRAPH_THROUGHPUT_DOCUMENT_GRAPH_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-docgraph-P32-F15" as const;export const DOCGRAPH_FEDERATED_CONTINUAL_DOCUMENT_GRAPH_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-docgraph-P32-F16" as const;
export interface DocgraphDocumentGraphIntegrityCard{schema_version:string;contract_version:string;feature_id:string;request_id:string;purpose:string;disposition:"qualified"|"partial"|"unknown"|"blocked";module_order:string[];admitted_order:string[];rejected_order:string[];unknown_order:string[];omitted_order:string[];lineage_order:string[];consumer_order:string[];contract_order:string[];replay_identity:string;closure_digest:string;admitted_module_count:number;total_module_count:number;raw_data_local:true;aggregate_only:true;boundary:string;effect_receipts:string[];artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];source_digests:string[];boundary:string}}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
function validate(c:DocgraphDocumentGraphIntegrityCard,id:string){if(c.schema_version!=="aurora-research-contract/1.0"||c.feature_id!==id||!c.request_id||!c.purpose||c.boundary!==DOCGRAPH_DOCUMENT_GRAPH_INTEGRITY_BOUNDARY||c.raw_data_local!==true||c.aggregate_only!==true||!digest(c.replay_identity)||!digest(c.closure_digest)||c.artifact.content_type!==DOCGRAPH_DOCUMENT_GRAPH_INTEGRITY_CONTENT_TYPE||c.artifact.content_hash!==c.closure_digest||c.artifact.boundary!==DOCGRAPH_DOCUMENT_GRAPH_INTEGRITY_BOUNDARY||c.admitted_module_count>c.total_module_count)throw new Error("document identity, locality, artifact, digest, boundary, or count is incomplete");for(const v of [c.module_order,c.admitted_order,c.rejected_order,c.unknown_order,c.omitted_order,c.lineage_order,c.consumer_order,c.contract_order,c.effect_receipts])if(!ordered(v))throw new Error("document graph vectors are not canonical");const ids=new Set(c.module_order),states=new Set([...c.admitted_order,...c.rejected_order,...c.unknown_order,...c.omitted_order]);if(ids.size!==states.size||[...ids].some(x=>!states.has(x)))throw new Error("document module states do not partition modules");if(c.admitted_module_count!==c.admitted_order.length)throw new Error("admitted module count does not match admitted order")}
export const validateDocgraphLocalDocumentGraphIntegrity=(c:DocgraphDocumentGraphIntegrityCard)=>validate(c,DOCGRAPH_LOCAL_DOCUMENT_GRAPH_INTEGRITY_FEATURE_ID);export const validateDocgraphMultimodalDocumentGraphIntegrity=(c:DocgraphDocumentGraphIntegrityCard)=>validate(c,DOCGRAPH_MULTIMODAL_DOCUMENT_GRAPH_INTEGRITY_FEATURE_ID);export const validateDocgraphThroughputDocumentGraphIntegrity=(c:DocgraphDocumentGraphIntegrityCard)=>validate(c,DOCGRAPH_THROUGHPUT_DOCUMENT_GRAPH_INTEGRITY_FEATURE_ID);export const validateDocgraphFederatedContinualDocumentGraphIntegrity=(c:DocgraphDocumentGraphIntegrityCard)=>validate(c,DOCGRAPH_FEDERATED_CONTINUAL_DOCUMENT_GRAPH_INTEGRITY_FEATURE_ID);
export const docgraphDocumentGraphIntegrityDigest=(c:DocgraphDocumentGraphIntegrityCard)=>{validateDocgraphLocalDocumentGraphIntegrity(c);return digestJsonSync(c)};export const docgraphDocumentGraphIntegrityContractDigest=(c:DocgraphDocumentGraphIntegrityCard)=>{validate(c,DOCGRAPH_LOCAL_DOCUMENT_GRAPH_INTEGRITY_CONTRACT_FEATURE_ID);return digestJsonSync(c)};export const docgraphDocumentGraphIntegrityCopilotDigest=(c:DocgraphDocumentGraphIntegrityCard)=>{validate(c,DOCGRAPH_LOCAL_DOCUMENT_GRAPH_INTEGRITY_COPILOT_FEATURE_ID);return digestJsonSync(c)};export const docgraphDocumentGraphIntegrityWorkflowDigest=(c:DocgraphDocumentGraphIntegrityCard)=>{validate(c,DOCGRAPH_LOCAL_DOCUMENT_GRAPH_INTEGRITY_WORKFLOW_FEATURE_ID);return digestJsonSync(c)};
