/** Public TypeScript contracts for Worldgen P31 federated commons. */
import {digestJsonSync} from "./tooling.js";import {PRECLINICAL_BOUNDARY,RESEARCH_CONTRACT_SCHEMA_VERSION} from "./research-contracts.js";
export const WORLDGEN_FEDERATED_COMMONS_CONTENT_TYPE="application/vnd.aurora.worldgen.federated-commons-envelope-1+json" as const;
export const WORLDGEN_LOCAL_FEDERATED_COMMONS_FEATURE_ID="AFA-worldgen-P31-F01" as const;export const WORLDGEN_MULTIMODAL_FEDERATED_COMMONS_FEATURE_ID="AFA-worldgen-P31-F02" as const;export const WORLDGEN_THROUGHPUT_FEDERATED_COMMONS_FEATURE_ID="AFA-worldgen-P31-F03" as const;export const WORLDGEN_FEDERATED_CONTINUAL_COMMONS_FEATURE_ID="AFA-worldgen-P31-F04" as const;
export const WORLDGEN_LOCAL_FEDERATED_COMMONS_CONTRACT_FEATURE_ID="AFA-worldgen-P31-F05" as const;export const WORLDGEN_MULTIMODAL_FEDERATED_COMMONS_CONTRACT_FEATURE_ID="AFA-worldgen-P31-F06" as const;export const WORLDGEN_THROUGHPUT_FEDERATED_COMMONS_CONTRACT_FEATURE_ID="AFA-worldgen-P31-F07" as const;export const WORLDGEN_FEDERATED_CONTINUAL_COMMONS_CONTRACT_FEATURE_ID="AFA-worldgen-P31-F08" as const;
export const WORLDGEN_LOCAL_FEDERATED_COMMONS_COPILOT_FEATURE_ID="AFA-worldgen-P31-F09" as const;export const WORLDGEN_MULTIMODAL_FEDERATED_COMMONS_COPILOT_FEATURE_ID="AFA-worldgen-P31-F10" as const;export const WORLDGEN_THROUGHPUT_FEDERATED_COMMONS_COPILOT_FEATURE_ID="AFA-worldgen-P31-F11" as const;export const WORLDGEN_FEDERATED_CONTINUAL_COMMONS_COPILOT_FEATURE_ID="AFA-worldgen-P31-F12" as const;
export const WORLDGEN_LOCAL_FEDERATED_COMMONS_WORKFLOW_FEATURE_ID="AFA-worldgen-P31-F13" as const;export const WORLDGEN_MULTIMODAL_FEDERATED_COMMONS_WORKFLOW_FEATURE_ID="AFA-worldgen-P31-F14" as const;export const WORLDGEN_THROUGHPUT_FEDERATED_COMMONS_WORKFLOW_FEATURE_ID="AFA-worldgen-P31-F15" as const;export const WORLDGEN_FEDERATED_CONTINUAL_COMMONS_WORKFLOW_FEATURE_ID="AFA-worldgen-P31-F16" as const;
export interface WorldgenFederatedCommonsCard{schema_version:string;contract_version:string;feature_id:string;mode:string;scale:string;request_id:string;purpose:string;disposition:"admitted"|"partial"|"unknown"|"blocked";peer_order:string[];admitted_order:string[];denied_order:string[];unknown_order:string[];omitted_order:string[];revoked_order:string[];negative_evidence_order:string[];capability_order:string[];localization:"origin-local-aggregate-only";replay_identity:string;federation_digest:string;artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];peer_digests:string[];purpose:string;localization:"origin-local-aggregate-only";boundary:string};effect_receipts:string[];raw_data_local:true;aggregate_only:true;boundary:string}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown)=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
function validate(r:WorldgenFederatedCommonsCard,id:string){if(r.schema_version!==RESEARCH_CONTRACT_SCHEMA_VERSION||r.feature_id!==id||r.boundary!==PRECLINICAL_BOUNDARY||r.raw_data_local!==true||r.aggregate_only!==true||r.localization!=="origin-local-aggregate-only"||!r.peer_order.length||!digest(r.replay_identity)||!digest(r.federation_digest)||r.artifact.content_type!==WORLDGEN_FEDERATED_COMMONS_CONTENT_TYPE||r.artifact.content_hash!==r.federation_digest||r.artifact.localization!=="origin-local-aggregate-only"||r.artifact.boundary!==PRECLINICAL_BOUNDARY)throw new Error("federated commons identity, locality, or digest is invalid");for(const v of [r.peer_order,r.admitted_order,r.denied_order,r.unknown_order,r.omitted_order,r.revoked_order,r.negative_evidence_order,r.capability_order,r.effect_receipts])if(!ordered(v))throw new Error("federation vectors are not canonical");const ids=new Set(r.peer_order),parts=new Set([...r.admitted_order,...r.denied_order,...r.unknown_order,...r.omitted_order]);if(ids.size!==parts.size||[...ids].some(x=>!parts.has(x)))throw new Error("peer states do not partition")}
export const validateWorldgenLocalFederatedCommons=(r:WorldgenFederatedCommonsCard)=>validate(r,WORLDGEN_LOCAL_FEDERATED_COMMONS_FEATURE_ID);export const validateWorldgenMultimodalFederatedCommons=(r:WorldgenFederatedCommonsCard)=>validate(r,WORLDGEN_MULTIMODAL_FEDERATED_COMMONS_FEATURE_ID);export const validateWorldgenThroughputFederatedCommons=(r:WorldgenFederatedCommonsCard)=>validate(r,WORLDGEN_THROUGHPUT_FEDERATED_COMMONS_FEATURE_ID);export const validateWorldgenFederatedContinualCommons=(r:WorldgenFederatedCommonsCard)=>validate(r,WORLDGEN_FEDERATED_CONTINUAL_COMMONS_FEATURE_ID);
export const worldgenFederatedCommonsDigest=(r:WorldgenFederatedCommonsCard)=>{validateWorldgenLocalFederatedCommons(r);return digestJsonSync(r)};export const worldgenFederatedCommonsContractDigest=(r:WorldgenFederatedCommonsCard)=>{validate(r,WORLDGEN_LOCAL_FEDERATED_COMMONS_CONTRACT_FEATURE_ID);return digestJsonSync(r)};export const worldgenFederatedCommonsCopilotDigest=(r:WorldgenFederatedCommonsCard)=>{validate(r,WORLDGEN_LOCAL_FEDERATED_COMMONS_COPILOT_FEATURE_ID);return digestJsonSync(r)};export const worldgenFederatedCommonsWorkflowDigest=(r:WorldgenFederatedCommonsCard)=>{validate(r,WORLDGEN_LOCAL_FEDERATED_COMMONS_WORKFLOW_FEATURE_ID);return digestJsonSync(r)};
