/** Public TypeScript contracts for Graph P32 projection-integrity cards. */
import {digestJsonSync} from "./tooling.js";
export const GRAPH_PROJECTION_INTEGRITY_CONTENT_TYPE="application/vnd.aurora.graph.projection-integrity-card-1+json" as const;
export const GRAPH_PROJECTION_INTEGRITY_BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions" as const;
export const GRAPH_LOCAL_PROJECTION_INTEGRITY_FEATURE_ID="AFA-graph-P32-F01" as const;export const GRAPH_MULTIMODAL_PROJECTION_INTEGRITY_FEATURE_ID="AFA-graph-P32-F02" as const;export const GRAPH_THROUGHPUT_PROJECTION_INTEGRITY_FEATURE_ID="AFA-graph-P32-F03" as const;export const GRAPH_FEDERATED_CONTINUAL_PROJECTION_INTEGRITY_FEATURE_ID="AFA-graph-P32-F04" as const;
export const GRAPH_LOCAL_PROJECTION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-graph-P32-F05" as const;export const GRAPH_MULTIMODAL_PROJECTION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-graph-P32-F06" as const;export const GRAPH_THROUGHPUT_PROJECTION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-graph-P32-F07" as const;export const GRAPH_FEDERATED_CONTINUAL_PROJECTION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-graph-P32-F08" as const;
export const GRAPH_LOCAL_PROJECTION_INTEGRITY_COPILOT_FEATURE_ID="AFA-graph-P32-F09" as const;export const GRAPH_MULTIMODAL_PROJECTION_INTEGRITY_COPILOT_FEATURE_ID="AFA-graph-P32-F10" as const;export const GRAPH_THROUGHPUT_PROJECTION_INTEGRITY_COPILOT_FEATURE_ID="AFA-graph-P32-F11" as const;export const GRAPH_FEDERATED_CONTINUAL_PROJECTION_INTEGRITY_COPILOT_FEATURE_ID="AFA-graph-P32-F12" as const;
export const GRAPH_LOCAL_PROJECTION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-graph-P32-F13" as const;export const GRAPH_MULTIMODAL_PROJECTION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-graph-P32-F14" as const;export const GRAPH_THROUGHPUT_PROJECTION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-graph-P32-F15" as const;export const GRAPH_FEDERATED_CONTINUAL_PROJECTION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-graph-P32-F16" as const;
export interface GraphProjectionIntegrityCard{schema_version:string;contract_version:string;feature_id:string;request_id:string;purpose:string;disposition:"qualified"|"partial"|"unknown"|"blocked";node_order:string[];edge_order:string[];selected_order:string[];rejected_order:string[];unknown_order:string[];omitted_order:string[];relation_order:string[];kind_order:string[];orphan_order:string[];replay_identity:string;closure_digest:string;raw_data_local:true;aggregate_only:true;boundary:string;effect_receipts:string[];artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];evidence_digests:string[];boundary:string}}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);function validate(c:GraphProjectionIntegrityCard,id:string){if(c.schema_version!=="aurora-research-contract/1.0"||c.feature_id!==id||!c.request_id||!c.purpose||c.boundary!==GRAPH_PROJECTION_INTEGRITY_BOUNDARY||c.raw_data_local!==true||c.aggregate_only!==true||!digest(c.replay_identity)||!digest(c.closure_digest)||c.artifact.content_type!==GRAPH_PROJECTION_INTEGRITY_CONTENT_TYPE||c.artifact.content_hash!==c.closure_digest||c.artifact.boundary!==GRAPH_PROJECTION_INTEGRITY_BOUNDARY)throw new Error("projection identity, locality, digest, artifact, or boundary is incomplete");for(const v of [c.node_order,c.edge_order,c.selected_order,c.rejected_order,c.unknown_order,c.omitted_order,c.relation_order,c.kind_order,c.orphan_order,c.effect_receipts])if(!ordered(v))throw new Error("projection vectors are not canonical");const ids=new Set(c.node_order),states=new Set([...c.selected_order,...c.rejected_order,...c.unknown_order,...c.omitted_order]);if(ids.size!==states.size||[...ids].some(x=>!states.has(x)))throw new Error("node states do not partition")}
export const validateGraphLocalProjectionIntegrity=(c:GraphProjectionIntegrityCard)=>validate(c,GRAPH_LOCAL_PROJECTION_INTEGRITY_FEATURE_ID);export const validateGraphMultimodalProjectionIntegrity=(c:GraphProjectionIntegrityCard)=>validate(c,GRAPH_MULTIMODAL_PROJECTION_INTEGRITY_FEATURE_ID);export const validateGraphThroughputProjectionIntegrity=(c:GraphProjectionIntegrityCard)=>validate(c,GRAPH_THROUGHPUT_PROJECTION_INTEGRITY_FEATURE_ID);export const validateGraphFederatedContinualProjectionIntegrity=(c:GraphProjectionIntegrityCard)=>validate(c,GRAPH_FEDERATED_CONTINUAL_PROJECTION_INTEGRITY_FEATURE_ID);
export const graphProjectionIntegrityDigest=(c:GraphProjectionIntegrityCard)=>{validateGraphLocalProjectionIntegrity(c);return digestJsonSync(c)};export const graphProjectionIntegrityContractDigest=(c:GraphProjectionIntegrityCard)=>{validate(c,GRAPH_LOCAL_PROJECTION_INTEGRITY_CONTRACT_FEATURE_ID);return digestJsonSync(c)};export const graphProjectionIntegrityCopilotDigest=(c:GraphProjectionIntegrityCard)=>{validate(c,GRAPH_LOCAL_PROJECTION_INTEGRITY_COPILOT_FEATURE_ID);return digestJsonSync(c)};export const graphProjectionIntegrityWorkflowDigest=(c:GraphProjectionIntegrityCard)=>{validate(c,GRAPH_LOCAL_PROJECTION_INTEGRITY_WORKFLOW_FEATURE_ID);return digestJsonSync(c)};
