/** Public TypeScript contracts for Hub P32 submission-release integrity cards. */
import {digestJsonSync} from "./tooling.js";

export const HUB_SUBMISSION_RELEASE_INTEGRITY_CONTENT_TYPE="application/vnd.aurora.hub.submission-release-integrity-card-1+json" as const;
export const HUB_SUBMISSION_RELEASE_INTEGRITY_BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions" as const;
export const HUB_LOCAL_SUBMISSION_RELEASE_INTEGRITY_FEATURE_ID="AFA-hub-P32-F01" as const;export const HUB_MULTIMODAL_SUBMISSION_RELEASE_INTEGRITY_FEATURE_ID="AFA-hub-P32-F02" as const;export const HUB_THROUGHPUT_SUBMISSION_RELEASE_INTEGRITY_FEATURE_ID="AFA-hub-P32-F03" as const;export const HUB_FEDERATED_CONTINUAL_SUBMISSION_RELEASE_INTEGRITY_FEATURE_ID="AFA-hub-P32-F04" as const;
export const HUB_LOCAL_SUBMISSION_RELEASE_INTEGRITY_CONTRACT_FEATURE_ID="AFA-hub-P32-F05" as const;export const HUB_MULTIMODAL_SUBMISSION_RELEASE_INTEGRITY_CONTRACT_FEATURE_ID="AFA-hub-P32-F06" as const;export const HUB_THROUGHPUT_SUBMISSION_RELEASE_INTEGRITY_CONTRACT_FEATURE_ID="AFA-hub-P32-F07" as const;export const HUB_FEDERATED_CONTINUAL_SUBMISSION_RELEASE_INTEGRITY_CONTRACT_FEATURE_ID="AFA-hub-P32-F08" as const;
export const HUB_LOCAL_SUBMISSION_RELEASE_INTEGRITY_COPILOT_FEATURE_ID="AFA-hub-P32-F09" as const;export const HUB_MULTIMODAL_SUBMISSION_RELEASE_INTEGRITY_COPILOT_FEATURE_ID="AFA-hub-P32-F10" as const;export const HUB_THROUGHPUT_SUBMISSION_RELEASE_INTEGRITY_COPILOT_FEATURE_ID="AFA-hub-P32-F11" as const;export const HUB_FEDERATED_CONTINUAL_SUBMISSION_RELEASE_INTEGRITY_COPILOT_FEATURE_ID="AFA-hub-P32-F12" as const;
export const HUB_LOCAL_SUBMISSION_RELEASE_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-hub-P32-F13" as const;export const HUB_MULTIMODAL_SUBMISSION_RELEASE_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-hub-P32-F14" as const;export const HUB_THROUGHPUT_SUBMISSION_RELEASE_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-hub-P32-F15" as const;export const HUB_FEDERATED_CONTINUAL_SUBMISSION_RELEASE_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-hub-P32-F16" as const;

export interface HubSubmissionReleaseIntegrityCard{schema_version:string;contract_version:string;feature_id:string;request_id:string;purpose:string;disposition:"released"|"partial"|"unknown"|"blocked";candidate_order:string[];released_order:string[];rejected_order:string[];unknown_order:string[];omitted_order:string[];scope_order:string[];provenance_order:string[];licence_order:string[];verification_order:string[];replay_identity:string;closure_digest:string;released_candidate_count:number;total_candidate_count:number;raw_data_local:true;aggregate_only:true;boundary:string;effect_receipts:string[];artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];evidence_digests:string[];boundary:string}}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
function validate(c:HubSubmissionReleaseIntegrityCard,id:string){if(c.schema_version!=="aurora-research-contract/1.0"||c.feature_id!==id||!c.request_id||!c.purpose||c.boundary!==HUB_SUBMISSION_RELEASE_INTEGRITY_BOUNDARY||c.raw_data_local!==true||c.aggregate_only!==true||!digest(c.replay_identity)||!digest(c.closure_digest)||c.artifact.content_type!==HUB_SUBMISSION_RELEASE_INTEGRITY_CONTENT_TYPE||c.artifact.content_hash!==c.closure_digest||c.artifact.boundary!==HUB_SUBMISSION_RELEASE_INTEGRITY_BOUNDARY||c.released_candidate_count>c.total_candidate_count)throw new Error("submission identity, locality, artifact, digest, boundary, or count is incomplete");for(const v of [c.candidate_order,c.released_order,c.rejected_order,c.unknown_order,c.omitted_order,c.scope_order,c.provenance_order,c.licence_order,c.verification_order,c.effect_receipts])if(!ordered(v))throw new Error("submission vectors are not canonical");const ids=new Set(c.candidate_order),states=new Set([...c.released_order,...c.rejected_order,...c.unknown_order,...c.omitted_order]);if(ids.size!==states.size||[...ids].some(x=>!states.has(x)))throw new Error("submission states do not partition candidates");if(c.released_candidate_count!==c.released_order.length)throw new Error("released candidate count does not match released order")}
export const validateHubLocalSubmissionReleaseIntegrity=(c:HubSubmissionReleaseIntegrityCard)=>validate(c,HUB_LOCAL_SUBMISSION_RELEASE_INTEGRITY_FEATURE_ID);export const validateHubMultimodalSubmissionReleaseIntegrity=(c:HubSubmissionReleaseIntegrityCard)=>validate(c,HUB_MULTIMODAL_SUBMISSION_RELEASE_INTEGRITY_FEATURE_ID);export const validateHubThroughputSubmissionReleaseIntegrity=(c:HubSubmissionReleaseIntegrityCard)=>validate(c,HUB_THROUGHPUT_SUBMISSION_RELEASE_INTEGRITY_FEATURE_ID);export const validateHubFederatedContinualSubmissionReleaseIntegrity=(c:HubSubmissionReleaseIntegrityCard)=>validate(c,HUB_FEDERATED_CONTINUAL_SUBMISSION_RELEASE_INTEGRITY_FEATURE_ID);
export const hubSubmissionReleaseIntegrityDigest=(c:HubSubmissionReleaseIntegrityCard)=>{validateHubLocalSubmissionReleaseIntegrity(c);return digestJsonSync(c)};export const hubSubmissionReleaseIntegrityContractDigest=(c:HubSubmissionReleaseIntegrityCard)=>{validate(c,HUB_LOCAL_SUBMISSION_RELEASE_INTEGRITY_CONTRACT_FEATURE_ID);return digestJsonSync(c)};export const hubSubmissionReleaseIntegrityCopilotDigest=(c:HubSubmissionReleaseIntegrityCard)=>{validate(c,HUB_LOCAL_SUBMISSION_RELEASE_INTEGRITY_COPILOT_FEATURE_ID);return digestJsonSync(c)};export const hubSubmissionReleaseIntegrityWorkflowDigest=(c:HubSubmissionReleaseIntegrityCard)=>{validate(c,HUB_LOCAL_SUBMISSION_RELEASE_INTEGRITY_WORKFLOW_FEATURE_ID);return digestJsonSync(c)};
