/** Public TypeScript contracts for Lab P32 instrument-execution integrity cards. */
import {digestJsonSync} from "./tooling.js";
export const LAB_INSTRUMENT_EXECUTION_INTEGRITY_CONTENT_TYPE="application/vnd.aurora.lab.instrument-execution-integrity-card-1+json" as const;
export const LAB_INSTRUMENT_EXECUTION_INTEGRITY_BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions" as const;
export const LAB_LOCAL_INSTRUMENT_EXECUTION_INTEGRITY_FEATURE_ID="AFA-lab-P32-F01" as const;export const LAB_MULTIMODAL_INSTRUMENT_EXECUTION_INTEGRITY_FEATURE_ID="AFA-lab-P32-F02" as const;export const LAB_THROUGHPUT_INSTRUMENT_EXECUTION_INTEGRITY_FEATURE_ID="AFA-lab-P32-F03" as const;export const LAB_FEDERATED_CONTINUAL_INSTRUMENT_EXECUTION_INTEGRITY_FEATURE_ID="AFA-lab-P32-F04" as const;
export const LAB_LOCAL_INSTRUMENT_EXECUTION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-lab-P32-F05" as const;export const LAB_MULTIMODAL_INSTRUMENT_EXECUTION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-lab-P32-F06" as const;export const LAB_THROUGHPUT_INSTRUMENT_EXECUTION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-lab-P32-F07" as const;export const LAB_FEDERATED_CONTINUAL_INSTRUMENT_EXECUTION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-lab-P32-F08" as const;
export const LAB_LOCAL_INSTRUMENT_EXECUTION_INTEGRITY_COPILOT_FEATURE_ID="AFA-lab-P32-F09" as const;export const LAB_MULTIMODAL_INSTRUMENT_EXECUTION_INTEGRITY_COPILOT_FEATURE_ID="AFA-lab-P32-F10" as const;export const LAB_THROUGHPUT_INSTRUMENT_EXECUTION_INTEGRITY_COPILOT_FEATURE_ID="AFA-lab-P32-F11" as const;export const LAB_FEDERATED_CONTINUAL_INSTRUMENT_EXECUTION_INTEGRITY_COPILOT_FEATURE_ID="AFA-lab-P32-F12" as const;
export const LAB_LOCAL_INSTRUMENT_EXECUTION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-lab-P32-F13" as const;export const LAB_MULTIMODAL_INSTRUMENT_EXECUTION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-lab-P32-F14" as const;export const LAB_THROUGHPUT_INSTRUMENT_EXECUTION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-lab-P32-F15" as const;export const LAB_FEDERATED_CONTINUAL_INSTRUMENT_EXECUTION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-lab-P32-F16" as const;
export interface LabInstrumentExecutionIntegrityCard{schema_version:string;contract_version:string;feature_id:string;request_id:string;purpose:string;disposition:"qualified"|"partial"|"unknown"|"blocked";action_order:string[];approved_order:string[];rejected_order:string[];unknown_order:string[];omitted_order:string[];interlock_order:string[];instrument_order:string[];effect_order:string[];replay_identity:string;closure_digest:string;raw_data_local:true;aggregate_only:true;boundary:string;effect_receipts:string[];artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];evidence_digests:string[];boundary:string}}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);function validate(c:LabInstrumentExecutionIntegrityCard,id:string){if(c.schema_version!=="aurora-research-contract/1.0"||c.feature_id!==id||!c.request_id||!c.purpose||c.boundary!==LAB_INSTRUMENT_EXECUTION_INTEGRITY_BOUNDARY||c.raw_data_local!==true||c.aggregate_only!==true||!digest(c.replay_identity)||!digest(c.closure_digest)||c.artifact.content_type!==LAB_INSTRUMENT_EXECUTION_INTEGRITY_CONTENT_TYPE||c.artifact.content_hash!==c.closure_digest||c.artifact.boundary!==LAB_INSTRUMENT_EXECUTION_INTEGRITY_BOUNDARY)throw new Error("execution identity, locality, digest, artifact, or boundary is incomplete");for(const v of [c.action_order,c.approved_order,c.rejected_order,c.unknown_order,c.omitted_order,c.interlock_order,c.instrument_order,c.effect_order,c.effect_receipts])if(!ordered(v))throw new Error("execution vectors are not canonical");const ids=new Set(c.action_order),states=new Set([...c.approved_order,...c.rejected_order,...c.unknown_order,...c.omitted_order]);if(ids.size!==states.size||[...ids].some(x=>!states.has(x)))throw new Error("action states do not partition")}
export const validateLabLocalInstrumentExecutionIntegrity=(c:LabInstrumentExecutionIntegrityCard)=>validate(c,LAB_LOCAL_INSTRUMENT_EXECUTION_INTEGRITY_FEATURE_ID);export const validateLabMultimodalInstrumentExecutionIntegrity=(c:LabInstrumentExecutionIntegrityCard)=>validate(c,LAB_MULTIMODAL_INSTRUMENT_EXECUTION_INTEGRITY_FEATURE_ID);export const validateLabThroughputInstrumentExecutionIntegrity=(c:LabInstrumentExecutionIntegrityCard)=>validate(c,LAB_THROUGHPUT_INSTRUMENT_EXECUTION_INTEGRITY_FEATURE_ID);export const validateLabFederatedContinualInstrumentExecutionIntegrity=(c:LabInstrumentExecutionIntegrityCard)=>validate(c,LAB_FEDERATED_CONTINUAL_INSTRUMENT_EXECUTION_INTEGRITY_FEATURE_ID);
export const labInstrumentExecutionIntegrityDigest=(c:LabInstrumentExecutionIntegrityCard)=>{validateLabLocalInstrumentExecutionIntegrity(c);return digestJsonSync(c)};export const labInstrumentExecutionIntegrityContractDigest=(c:LabInstrumentExecutionIntegrityCard)=>{validate(c,LAB_LOCAL_INSTRUMENT_EXECUTION_INTEGRITY_CONTRACT_FEATURE_ID);return digestJsonSync(c)};export const labInstrumentExecutionIntegrityCopilotDigest=(c:LabInstrumentExecutionIntegrityCard)=>{validate(c,LAB_LOCAL_INSTRUMENT_EXECUTION_INTEGRITY_COPILOT_FEATURE_ID);return digestJsonSync(c)};export const labInstrumentExecutionIntegrityWorkflowDigest=(c:LabInstrumentExecutionIntegrityCard)=>{validate(c,LAB_LOCAL_INSTRUMENT_EXECUTION_INTEGRITY_WORKFLOW_FEATURE_ID);return digestJsonSync(c)};
