/** Public TypeScript contracts for Worldgen P26 limitation closure. */
import {digestJsonSync} from "./tooling.js";import {PRECLINICAL_BOUNDARY,RESEARCH_CONTRACT_SCHEMA_VERSION} from "./research-contracts.js";
export const WORLDGEN_LIMITATION_CLOSURE_CONTENT_TYPE="application/vnd.aurora.worldgen.limitation-closure-receipt-1+json" as const;
export const WORLDGEN_LOCAL_LIMITATION_CLOSURE_FEATURE_ID="AFA-worldgen-P26-F01" as const;export const WORLDGEN_MULTIMODAL_LIMITATION_CLOSURE_FEATURE_ID="AFA-worldgen-P26-F02" as const;export const WORLDGEN_THROUGHPUT_LIMITATION_CLOSURE_FEATURE_ID="AFA-worldgen-P26-F03" as const;export const WORLDGEN_FEDERATED_LIMITATION_CLOSURE_FEATURE_ID="AFA-worldgen-P26-F04" as const;
export const WORLDGEN_LOCAL_LIMITATION_CLOSURE_CONTRACT_FEATURE_ID="AFA-worldgen-P26-F05" as const;export const WORLDGEN_MULTIMODAL_LIMITATION_CLOSURE_CONTRACT_FEATURE_ID="AFA-worldgen-P26-F06" as const;export const WORLDGEN_THROUGHPUT_LIMITATION_CLOSURE_CONTRACT_FEATURE_ID="AFA-worldgen-P26-F07" as const;export const WORLDGEN_FEDERATED_LIMITATION_CLOSURE_CONTRACT_FEATURE_ID="AFA-worldgen-P26-F08" as const;
export const WORLDGEN_LOCAL_LIMITATION_CLOSURE_COPILOT_FEATURE_ID="AFA-worldgen-P26-F09" as const;export const WORLDGEN_MULTIMODAL_LIMITATION_CLOSURE_COPILOT_FEATURE_ID="AFA-worldgen-P26-F10" as const;export const WORLDGEN_THROUGHPUT_LIMITATION_CLOSURE_COPILOT_FEATURE_ID="AFA-worldgen-P26-F11" as const;export const WORLDGEN_FEDERATED_LIMITATION_CLOSURE_COPILOT_FEATURE_ID="AFA-worldgen-P26-F12" as const;
export const WORLDGEN_LOCAL_LIMITATION_CLOSURE_WORKFLOW_FEATURE_ID="AFA-worldgen-P26-F13" as const;export const WORLDGEN_MULTIMODAL_LIMITATION_CLOSURE_WORKFLOW_FEATURE_ID="AFA-worldgen-P26-F14" as const;export const WORLDGEN_THROUGHPUT_LIMITATION_CLOSURE_WORKFLOW_FEATURE_ID="AFA-worldgen-P26-F15" as const;export const WORLDGEN_FEDERATED_LIMITATION_CLOSURE_WORKFLOW_FEATURE_ID="AFA-worldgen-P26-F16" as const;
export interface WorldgenLimitationClosureCard{schema_version:string;contract_version:string;feature_id:string;mode:string;scale:string;request_id:string;semantic_profile:string;disposition:string;case_order:string[];resolved_order:string[];unresolved_order:string[];blocked_order:string[];peer_order:string[];qualified_peer_order:string[];missing_peer_order:string[];omission_order:string[];uncertainty_order:string[];negative_evidence_order:string[];replay_identity:string;closure_digest:string;artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];provenance_digests:string[];boundary:string};effect_receipts:string[];raw_data_local:true;aggregate_only:true;boundary:string}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown)=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
function validate(r:WorldgenLimitationClosureCard,id:string){if(r.schema_version!==RESEARCH_CONTRACT_SCHEMA_VERSION||r.feature_id!==id||r.boundary!==PRECLINICAL_BOUNDARY||r.raw_data_local!==true||r.aggregate_only!==true||!r.case_order.length||!r.peer_order.length||!digest(r.replay_identity)||!digest(r.closure_digest)||r.artifact.content_type!==WORLDGEN_LIMITATION_CLOSURE_CONTENT_TYPE||r.artifact.content_hash!==r.closure_digest||r.artifact.boundary!==PRECLINICAL_BOUNDARY)throw new Error("limitation closure identity, locality, or digest is invalid");for(const v of [r.case_order,r.resolved_order,r.unresolved_order,r.blocked_order,r.peer_order,r.qualified_peer_order,r.missing_peer_order,r.omission_order,r.uncertainty_order,r.negative_evidence_order,r.effect_receipts])if(!ordered(v))throw new Error("closure vectors are not canonical");const cases=new Set(r.case_order),cp=new Set([...r.resolved_order,...r.unresolved_order,...r.blocked_order]),peers=new Set(r.peer_order),pp=new Set([...r.qualified_peer_order,...r.missing_peer_order]);if(cases.size!==cp.size||[...cases].some(x=>!cp.has(x))||peers.size!==pp.size||[...peers].some(x=>!pp.has(x)))throw new Error("closure states do not partition")}
export const validateWorldgenLocalLimitationClosure=(r:WorldgenLimitationClosureCard)=>validate(r,WORLDGEN_LOCAL_LIMITATION_CLOSURE_FEATURE_ID);export const validateWorldgenMultimodalLimitationClosure=(r:WorldgenLimitationClosureCard)=>validate(r,WORLDGEN_MULTIMODAL_LIMITATION_CLOSURE_FEATURE_ID);export const validateWorldgenThroughputLimitationClosure=(r:WorldgenLimitationClosureCard)=>validate(r,WORLDGEN_THROUGHPUT_LIMITATION_CLOSURE_FEATURE_ID);export const validateWorldgenFederatedLimitationClosure=(r:WorldgenLimitationClosureCard)=>validate(r,WORLDGEN_FEDERATED_LIMITATION_CLOSURE_FEATURE_ID);
export const worldgenLimitationClosureDigest=(r:WorldgenLimitationClosureCard)=>{validateWorldgenLocalLimitationClosure(r);return digestJsonSync(r)};export const worldgenLimitationClosureContractDigest=(r:WorldgenLimitationClosureCard)=>{validate(r,WORLDGEN_LOCAL_LIMITATION_CLOSURE_CONTRACT_FEATURE_ID);return digestJsonSync(r)};export const worldgenLimitationClosureCopilotDigest=(r:WorldgenLimitationClosureCard)=>{validate(r,WORLDGEN_LOCAL_LIMITATION_CLOSURE_COPILOT_FEATURE_ID);return digestJsonSync(r)};export const worldgenLimitationClosureWorkflowDigest=(r:WorldgenLimitationClosureCard)=>{validate(r,WORLDGEN_LOCAL_LIMITATION_CLOSURE_WORKFLOW_FEATURE_ID);return digestJsonSync(r)};
