/** Public TypeScript contracts for Megafactory P32 factory-lineage integrity cards. */
import {digestJsonSync} from "./tooling.js";
export const MEGAFACTORY_FACTORY_LINEAGE_INTEGRITY_CONTENT_TYPE="application/vnd.aurora.megafactory.factory-lineage-integrity-card-1+json" as const;
export const MEGAFACTORY_FACTORY_LINEAGE_INTEGRITY_BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions" as const;
export const MEGAFACTORY_LOCAL_FACTORY_LINEAGE_INTEGRITY_FEATURE_ID="AFA-megafactory-P32-F01" as const;export const MEGAFACTORY_MULTIMODAL_FACTORY_LINEAGE_INTEGRITY_FEATURE_ID="AFA-megafactory-P32-F02" as const;export const MEGAFACTORY_THROUGHPUT_FACTORY_LINEAGE_INTEGRITY_FEATURE_ID="AFA-megafactory-P32-F03" as const;export const MEGAFACTORY_FEDERATED_CONTINUAL_FACTORY_LINEAGE_INTEGRITY_FEATURE_ID="AFA-megafactory-P32-F04" as const;
export const MEGAFACTORY_LOCAL_FACTORY_LINEAGE_INTEGRITY_CONTRACT_FEATURE_ID="AFA-megafactory-P32-F05" as const;export const MEGAFACTORY_MULTIMODAL_FACTORY_LINEAGE_INTEGRITY_CONTRACT_FEATURE_ID="AFA-megafactory-P32-F06" as const;export const MEGAFACTORY_THROUGHPUT_FACTORY_LINEAGE_INTEGRITY_CONTRACT_FEATURE_ID="AFA-megafactory-P32-F07" as const;export const MEGAFACTORY_FEDERATED_CONTINUAL_FACTORY_LINEAGE_INTEGRITY_CONTRACT_FEATURE_ID="AFA-megafactory-P32-F08" as const;
export const MEGAFACTORY_LOCAL_FACTORY_LINEAGE_INTEGRITY_COPILOT_FEATURE_ID="AFA-megafactory-P32-F09" as const;export const MEGAFACTORY_MULTIMODAL_FACTORY_LINEAGE_INTEGRITY_COPILOT_FEATURE_ID="AFA-megafactory-P32-F10" as const;export const MEGAFACTORY_THROUGHPUT_FACTORY_LINEAGE_INTEGRITY_COPILOT_FEATURE_ID="AFA-megafactory-P32-F11" as const;export const MEGAFACTORY_FEDERATED_CONTINUAL_FACTORY_LINEAGE_INTEGRITY_COPILOT_FEATURE_ID="AFA-megafactory-P32-F12" as const;
export const MEGAFACTORY_LOCAL_FACTORY_LINEAGE_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-megafactory-P32-F13" as const;export const MEGAFACTORY_MULTIMODAL_FACTORY_LINEAGE_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-megafactory-P32-F14" as const;export const MEGAFACTORY_THROUGHPUT_FACTORY_LINEAGE_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-megafactory-P32-F15" as const;export const MEGAFACTORY_FEDERATED_CONTINUAL_FACTORY_LINEAGE_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-megafactory-P32-F16" as const;

export interface MegafactoryFactoryLineageIntegrityCard{schema_version:string;contract_version:string;feature_id:string;request_id:string;purpose:string;disposition:"qualified"|"partial"|"unknown"|"blocked";stage_order:string[];admitted_order:string[];rejected_order:string[];unknown_order:string[];omitted_order:string[];lineage_order:string[];consumer_order:string[];contract_order:string[];effect_order:string[];replay_identity:string;closure_digest:string;admitted_stage_count:number;total_stage_count:number;raw_data_local:true;aggregate_only:true;boundary:string;effect_receipts:string[];artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];evidence_digests:string[];boundary:string}}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
function validate(c:MegafactoryFactoryLineageIntegrityCard,id:string){if(c.schema_version!=="aurora-research-contract/1.0"||c.feature_id!==id||!c.request_id||!c.purpose||c.boundary!==MEGAFACTORY_FACTORY_LINEAGE_INTEGRITY_BOUNDARY||c.raw_data_local!==true||c.aggregate_only!==true||!digest(c.replay_identity)||!digest(c.closure_digest)||c.artifact.content_type!==MEGAFACTORY_FACTORY_LINEAGE_INTEGRITY_CONTENT_TYPE||c.artifact.content_hash!==c.closure_digest||c.artifact.boundary!==MEGAFACTORY_FACTORY_LINEAGE_INTEGRITY_BOUNDARY||c.admitted_stage_count>c.total_stage_count)throw new Error("factory identity, locality, artifact, digest, boundary, or count is incomplete");for(const v of [c.stage_order,c.admitted_order,c.rejected_order,c.unknown_order,c.omitted_order,c.lineage_order,c.consumer_order,c.contract_order,c.effect_order,c.effect_receipts])if(!ordered(v))throw new Error("factory vectors are not canonical");const ids=new Set(c.stage_order),states=new Set([...c.admitted_order,...c.rejected_order,...c.unknown_order,...c.omitted_order]);if(ids.size!==states.size||[...ids].some(x=>!states.has(x)))throw new Error("factory stage states do not partition stages");if(c.admitted_stage_count!==c.admitted_order.length)throw new Error("admitted stage count does not match admitted order")}
export const validateMegafactoryLocalFactoryLineageIntegrity=(c:MegafactoryFactoryLineageIntegrityCard)=>validate(c,MEGAFACTORY_LOCAL_FACTORY_LINEAGE_INTEGRITY_FEATURE_ID);export const validateMegafactoryMultimodalFactoryLineageIntegrity=(c:MegafactoryFactoryLineageIntegrityCard)=>validate(c,MEGAFACTORY_MULTIMODAL_FACTORY_LINEAGE_INTEGRITY_FEATURE_ID);export const validateMegafactoryThroughputFactoryLineageIntegrity=(c:MegafactoryFactoryLineageIntegrityCard)=>validate(c,MEGAFACTORY_THROUGHPUT_FACTORY_LINEAGE_INTEGRITY_FEATURE_ID);export const validateMegafactoryFederatedContinualFactoryLineageIntegrity=(c:MegafactoryFactoryLineageIntegrityCard)=>validate(c,MEGAFACTORY_FEDERATED_CONTINUAL_FACTORY_LINEAGE_INTEGRITY_FEATURE_ID);
export const megafactoryFactoryLineageIntegrityDigest=(c:MegafactoryFactoryLineageIntegrityCard)=>{validateMegafactoryLocalFactoryLineageIntegrity(c);return digestJsonSync(c)};export const megafactoryFactoryLineageIntegrityContractDigest=(c:MegafactoryFactoryLineageIntegrityCard)=>{validate(c,MEGAFACTORY_LOCAL_FACTORY_LINEAGE_INTEGRITY_CONTRACT_FEATURE_ID);return digestJsonSync(c)};export const megafactoryFactoryLineageIntegrityCopilotDigest=(c:MegafactoryFactoryLineageIntegrityCard)=>{validate(c,MEGAFACTORY_LOCAL_FACTORY_LINEAGE_INTEGRITY_COPILOT_FEATURE_ID);return digestJsonSync(c)};export const megafactoryFactoryLineageIntegrityWorkflowDigest=(c:MegafactoryFactoryLineageIntegrityCard)=>{validate(c,MEGAFACTORY_LOCAL_FACTORY_LINEAGE_INTEGRITY_WORKFLOW_FEATURE_ID);return digestJsonSync(c)};
