/** Public TypeScript contracts for Metrics P32 auditable-discovery-rate cards. */
import {digestJsonSync} from "./tooling.js";
export const METRICS_DISCOVERY_RATE_INTEGRITY_CONTENT_TYPE="application/vnd.aurora.metrics.discovery-rate-integrity-card-1+json" as const;
export const METRICS_DISCOVERY_RATE_INTEGRITY_BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions" as const;
export const METRICS_LOCAL_DISCOVERY_RATE_INTEGRITY_FEATURE_ID="AFA-metrics-P32-F01" as const;export const METRICS_MULTIMODAL_DISCOVERY_RATE_INTEGRITY_FEATURE_ID="AFA-metrics-P32-F02" as const;export const METRICS_THROUGHPUT_DISCOVERY_RATE_INTEGRITY_FEATURE_ID="AFA-metrics-P32-F03" as const;export const METRICS_FEDERATED_CONTINUAL_DISCOVERY_RATE_INTEGRITY_FEATURE_ID="AFA-metrics-P32-F04" as const;
export const METRICS_LOCAL_DISCOVERY_RATE_INTEGRITY_CONTRACT_FEATURE_ID="AFA-metrics-P32-F05" as const;export const METRICS_MULTIMODAL_DISCOVERY_RATE_INTEGRITY_CONTRACT_FEATURE_ID="AFA-metrics-P32-F06" as const;export const METRICS_THROUGHPUT_DISCOVERY_RATE_INTEGRITY_CONTRACT_FEATURE_ID="AFA-metrics-P32-F07" as const;export const METRICS_FEDERATED_CONTINUAL_DISCOVERY_RATE_INTEGRITY_CONTRACT_FEATURE_ID="AFA-metrics-P32-F08" as const;
export const METRICS_LOCAL_DISCOVERY_RATE_INTEGRITY_COPILOT_FEATURE_ID="AFA-metrics-P32-F09" as const;export const METRICS_MULTIMODAL_DISCOVERY_RATE_INTEGRITY_COPILOT_FEATURE_ID="AFA-metrics-P32-F10" as const;export const METRICS_THROUGHPUT_DISCOVERY_RATE_INTEGRITY_COPILOT_FEATURE_ID="AFA-metrics-P32-F11" as const;export const METRICS_FEDERATED_CONTINUAL_DISCOVERY_RATE_INTEGRITY_COPILOT_FEATURE_ID="AFA-metrics-P32-F12" as const;
export const METRICS_LOCAL_DISCOVERY_RATE_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-metrics-P32-F13" as const;export const METRICS_MULTIMODAL_DISCOVERY_RATE_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-metrics-P32-F14" as const;export const METRICS_THROUGHPUT_DISCOVERY_RATE_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-metrics-P32-F15" as const;export const METRICS_FEDERATED_CONTINUAL_DISCOVERY_RATE_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-metrics-P32-F16" as const;
export interface MetricsDiscoveryRateIntegrityCard{schema_version:string;contract_version:string;feature_id:string;request_id:string;purpose:string;disposition:"qualified"|"partial"|"unknown"|"blocked";observation_order:string[];qualified_order:string[];rejected_order:string[];unknown_order:string[];omitted_order:string[];baseline_order:string[];conclusion_order:string[];evidence_order:string[];replay_identity:string;closure_digest:string;discovery_numerator:number;discovery_denominator:number;cost_micros:number;duration_ms:number;raw_data_local:true;aggregate_only:true;boundary:string;effect_receipts:string[];artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];evidence_digests:string[];boundary:string}}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);function validate(c:MetricsDiscoveryRateIntegrityCard,id:string){if(c.schema_version!=="aurora-research-contract/1.0"||c.feature_id!==id||!c.request_id||!c.purpose||c.boundary!==METRICS_DISCOVERY_RATE_INTEGRITY_BOUNDARY||c.raw_data_local!==true||c.aggregate_only!==true||!digest(c.replay_identity)||!digest(c.closure_digest)||c.artifact.content_type!==METRICS_DISCOVERY_RATE_INTEGRITY_CONTENT_TYPE||c.artifact.content_hash!==c.closure_digest||c.artifact.boundary!==METRICS_DISCOVERY_RATE_INTEGRITY_BOUNDARY||c.discovery_numerator>c.discovery_denominator)throw new Error("discovery identity, locality, digest, artifact, boundary, or rate is incomplete");for(const v of [c.observation_order,c.qualified_order,c.rejected_order,c.unknown_order,c.omitted_order,c.baseline_order,c.conclusion_order,c.evidence_order,c.effect_receipts])if(!ordered(v))throw new Error("discovery vectors are not canonical");const ids=new Set(c.observation_order),states=new Set([...c.qualified_order,...c.rejected_order,...c.unknown_order,...c.omitted_order]);if(ids.size!==states.size||[...ids].some(x=>!states.has(x)))throw new Error("observation states do not partition")}
export const validateMetricsLocalDiscoveryRateIntegrity=(c:MetricsDiscoveryRateIntegrityCard)=>validate(c,METRICS_LOCAL_DISCOVERY_RATE_INTEGRITY_FEATURE_ID);export const validateMetricsMultimodalDiscoveryRateIntegrity=(c:MetricsDiscoveryRateIntegrityCard)=>validate(c,METRICS_MULTIMODAL_DISCOVERY_RATE_INTEGRITY_FEATURE_ID);export const validateMetricsThroughputDiscoveryRateIntegrity=(c:MetricsDiscoveryRateIntegrityCard)=>validate(c,METRICS_THROUGHPUT_DISCOVERY_RATE_INTEGRITY_FEATURE_ID);export const validateMetricsFederatedContinualDiscoveryRateIntegrity=(c:MetricsDiscoveryRateIntegrityCard)=>validate(c,METRICS_FEDERATED_CONTINUAL_DISCOVERY_RATE_INTEGRITY_FEATURE_ID);
export const metricsDiscoveryRateIntegrityDigest=(c:MetricsDiscoveryRateIntegrityCard)=>{validateMetricsLocalDiscoveryRateIntegrity(c);return digestJsonSync(c)};export const metricsDiscoveryRateIntegrityContractDigest=(c:MetricsDiscoveryRateIntegrityCard)=>{validate(c,METRICS_LOCAL_DISCOVERY_RATE_INTEGRITY_CONTRACT_FEATURE_ID);return digestJsonSync(c)};export const metricsDiscoveryRateIntegrityCopilotDigest=(c:MetricsDiscoveryRateIntegrityCard)=>{validate(c,METRICS_LOCAL_DISCOVERY_RATE_INTEGRITY_COPILOT_FEATURE_ID);return digestJsonSync(c)};export const metricsDiscoveryRateIntegrityWorkflowDigest=(c:MetricsDiscoveryRateIntegrityCard)=>{validate(c,METRICS_LOCAL_DISCOVERY_RATE_INTEGRITY_WORKFLOW_FEATURE_ID);return digestJsonSync(c)};
