/** Public TypeScript contracts for Mutation P32 evolution-integrity cards. */
import {digestJsonSync} from "./tooling.js";
export const MUTATION_EVOLUTION_INTEGRITY_CONTENT_TYPE="application/vnd.aurora.mutation.evolution-integrity-card-1+json" as const;
export const MUTATION_EVOLUTION_INTEGRITY_BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions" as const;
export const MUTATION_LOCAL_EVOLUTION_INTEGRITY_FEATURE_ID="AFA-mutation-P32-F01" as const;export const MUTATION_MULTIMODAL_EVOLUTION_INTEGRITY_FEATURE_ID="AFA-mutation-P32-F02" as const;export const MUTATION_THROUGHPUT_EVOLUTION_INTEGRITY_FEATURE_ID="AFA-mutation-P32-F03" as const;export const MUTATION_FEDERATED_CONTINUAL_EVOLUTION_INTEGRITY_FEATURE_ID="AFA-mutation-P32-F04" as const;
export const MUTATION_LOCAL_EVOLUTION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-mutation-P32-F05" as const;export const MUTATION_MULTIMODAL_EVOLUTION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-mutation-P32-F06" as const;export const MUTATION_THROUGHPUT_EVOLUTION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-mutation-P32-F07" as const;export const MUTATION_FEDERATED_CONTINUAL_EVOLUTION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-mutation-P32-F08" as const;
export const MUTATION_LOCAL_EVOLUTION_INTEGRITY_COPILOT_FEATURE_ID="AFA-mutation-P32-F09" as const;export const MUTATION_MULTIMODAL_EVOLUTION_INTEGRITY_COPILOT_FEATURE_ID="AFA-mutation-P32-F10" as const;export const MUTATION_THROUGHPUT_EVOLUTION_INTEGRITY_COPILOT_FEATURE_ID="AFA-mutation-P32-F11" as const;export const MUTATION_FEDERATED_CONTINUAL_EVOLUTION_INTEGRITY_COPILOT_FEATURE_ID="AFA-mutation-P32-F12" as const;
export const MUTATION_LOCAL_EVOLUTION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-mutation-P32-F13" as const;export const MUTATION_MULTIMODAL_EVOLUTION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-mutation-P32-F14" as const;export const MUTATION_THROUGHPUT_EVOLUTION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-mutation-P32-F15" as const;export const MUTATION_FEDERATED_CONTINUAL_EVOLUTION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-mutation-P32-F16" as const;
export interface MutationEvolutionIntegrityCard{schema_version:string;contract_version:string;feature_id:string;request_id:string;purpose:string;disposition:"qualified"|"partial"|"unknown"|"blocked";mutation_order:string[];accepted_order:string[];rejected_order:string[];unknown_order:string[];omitted_order:string[];parent_order:string[];effect_order:string[];lineage_order:string[];replay_identity:string;closure_digest:string;raw_data_local:true;aggregate_only:true;boundary:string;effect_receipts:string[];artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];evidence_digests:string[];boundary:string}}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);function validate(c:MutationEvolutionIntegrityCard,id:string){if(c.schema_version!=="aurora-research-contract/1.0"||c.feature_id!==id||!c.request_id||!c.purpose||c.boundary!==MUTATION_EVOLUTION_INTEGRITY_BOUNDARY||c.raw_data_local!==true||c.aggregate_only!==true||!digest(c.replay_identity)||!digest(c.closure_digest)||c.artifact.content_type!==MUTATION_EVOLUTION_INTEGRITY_CONTENT_TYPE||c.artifact.content_hash!==c.closure_digest||c.artifact.boundary!==MUTATION_EVOLUTION_INTEGRITY_BOUNDARY)throw new Error("evolution identity, locality, digest, artifact, or boundary is incomplete");for(const v of [c.mutation_order,c.accepted_order,c.rejected_order,c.unknown_order,c.omitted_order,c.parent_order,c.effect_order,c.lineage_order,c.effect_receipts])if(!ordered(v))throw new Error("evolution vectors are not canonical");const ids=new Set(c.mutation_order),states=new Set([...c.accepted_order,...c.rejected_order,...c.unknown_order,...c.omitted_order]);if(ids.size!==states.size||[...ids].some(x=>!states.has(x)))throw new Error("mutation states do not partition")}
export const validateMutationLocalEvolutionIntegrity=(c:MutationEvolutionIntegrityCard)=>validate(c,MUTATION_LOCAL_EVOLUTION_INTEGRITY_FEATURE_ID);export const validateMutationMultimodalEvolutionIntegrity=(c:MutationEvolutionIntegrityCard)=>validate(c,MUTATION_MULTIMODAL_EVOLUTION_INTEGRITY_FEATURE_ID);export const validateMutationThroughputEvolutionIntegrity=(c:MutationEvolutionIntegrityCard)=>validate(c,MUTATION_THROUGHPUT_EVOLUTION_INTEGRITY_FEATURE_ID);export const validateMutationFederatedContinualEvolutionIntegrity=(c:MutationEvolutionIntegrityCard)=>validate(c,MUTATION_FEDERATED_CONTINUAL_EVOLUTION_INTEGRITY_FEATURE_ID);
export const mutationEvolutionIntegrityDigest=(c:MutationEvolutionIntegrityCard)=>{validateMutationLocalEvolutionIntegrity(c);return digestJsonSync(c)};export const mutationEvolutionIntegrityContractDigest=(c:MutationEvolutionIntegrityCard)=>{validate(c,MUTATION_LOCAL_EVOLUTION_INTEGRITY_CONTRACT_FEATURE_ID);return digestJsonSync(c)};export const mutationEvolutionIntegrityCopilotDigest=(c:MutationEvolutionIntegrityCard)=>{validate(c,MUTATION_LOCAL_EVOLUTION_INTEGRITY_COPILOT_FEATURE_ID);return digestJsonSync(c)};export const mutationEvolutionIntegrityWorkflowDigest=(c:MutationEvolutionIntegrityCard)=>{validate(c,MUTATION_LOCAL_EVOLUTION_INTEGRITY_WORKFLOW_FEATURE_ID);return digestJsonSync(c)};
