/** Public TypeScript contracts for Worldgen P21 performance/reliability qualification. */
import { digestJsonSync } from "./tooling.js";
import { PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION } from "./research-contracts.js";

export const WORLDGEN_PERFORMANCE_RELIABILITY_CONTENT_TYPE = "application/vnd.aurora.worldgen.performance-reliability-receipt-1+json" as const;
export const WORLDGEN_PERFORMANCE_RELIABILITY_CONTRACT_CONTENT_TYPE = "application/vnd.aurora.worldgen.performance-reliability-contract-receipt+json" as const;
export const WORLDGEN_PERFORMANCE_RELIABILITY_COPILOT_CONTENT_TYPE = "application/vnd.aurora.worldgen.performance-reliability-copilot-receipt+json" as const;
export const WORLDGEN_PERFORMANCE_RELIABILITY_WORKFLOW_CONTENT_TYPE = "application/vnd.aurora.worldgen.performance-reliability-workflow-receipt+json" as const;

export const WORLDGEN_LOCAL_PERFORMANCE_RELIABILITY_FEATURE_ID = "AFA-worldgen-P21-F01" as const;
export const WORLDGEN_MULTIMODAL_PERFORMANCE_RELIABILITY_FEATURE_ID = "AFA-worldgen-P21-F02" as const;
export const WORLDGEN_THROUGHPUT_PERFORMANCE_RELIABILITY_FEATURE_ID = "AFA-worldgen-P21-F03" as const;
export const WORLDGEN_FEDERATED_PERFORMANCE_RELIABILITY_FEATURE_ID = "AFA-worldgen-P21-F04" as const;
export const WORLDGEN_LOCAL_PERFORMANCE_RELIABILITY_CONTRACT_FEATURE_ID = "AFA-worldgen-P21-F05" as const;
export const WORLDGEN_MULTIMODAL_PERFORMANCE_RELIABILITY_CONTRACT_FEATURE_ID = "AFA-worldgen-P21-F06" as const;
export const WORLDGEN_THROUGHPUT_PERFORMANCE_RELIABILITY_CONTRACT_FEATURE_ID = "AFA-worldgen-P21-F07" as const;
export const WORLDGEN_FEDERATED_PERFORMANCE_RELIABILITY_CONTRACT_FEATURE_ID = "AFA-worldgen-P21-F08" as const;
export const WORLDGEN_LOCAL_PERFORMANCE_RELIABILITY_COPILOT_FEATURE_ID = "AFA-worldgen-P21-F09" as const;
export const WORLDGEN_MULTIMODAL_PERFORMANCE_RELIABILITY_COPILOT_FEATURE_ID = "AFA-worldgen-P21-F10" as const;
export const WORLDGEN_THROUGHPUT_PERFORMANCE_RELIABILITY_COPILOT_FEATURE_ID = "AFA-worldgen-P21-F11" as const;
export const WORLDGEN_FEDERATED_PERFORMANCE_RELIABILITY_COPILOT_FEATURE_ID = "AFA-worldgen-P21-F12" as const;
export const WORLDGEN_LOCAL_PERFORMANCE_RELIABILITY_WORKFLOW_FEATURE_ID = "AFA-worldgen-P21-F13" as const;
export const WORLDGEN_MULTIMODAL_PERFORMANCE_RELIABILITY_WORKFLOW_FEATURE_ID = "AFA-worldgen-P21-F14" as const;
export const WORLDGEN_THROUGHPUT_PERFORMANCE_RELIABILITY_WORKFLOW_FEATURE_ID = "AFA-worldgen-P21-F15" as const;
export const WORLDGEN_FEDERATED_PERFORMANCE_RELIABILITY_WORKFLOW_FEATURE_ID = "AFA-worldgen-P21-F16" as const;

export interface WorldgenPerformanceReliabilityResult {
  schema_version:string; contract_version:string; feature_id:string; request_id:string; scope:string;
  disposition:"qualified"|"unresolved"|"blocked"; workload_order:string[]; dependable_order:string[]; degraded_order:string[]; blocked_order:string[];
  missing_order:string[]; retry_order:string[]; timeout_order:string[]; duplicate_event_order:string[]; omission_order:string[]; uncertainty_order:string[]; negative_evidence_order:string[];
  replay_identity:string; result_digest:string; artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];provenance_digests:string[];boundary:string};
  effect_receipts:string[]; raw_data_local:true; aggregate_only:true; boundary:string;
}
export interface WorldgenPerformanceReliabilityContractReceipt {schema_version:string;contract_version:string;feature_id:string;request_id:string;consumer:string;producer:string;namespace:string;semantic_profile:string;negotiated_version:string;compatibility:string;disposition:string;field_order:string[];retained_field_order:string[];missing_field_order:string[];degraded_field_order:string[];reliability_issue_order:string[];replay_identity:string;contract_digest:string;effect_receipts:string[];artifact:{content_type:string;content_hash:string;boundary:string};raw_data_local:true;aggregate_only:true;boundary:string}
export interface WorldgenPerformanceReliabilityCopilotReceipt {schema_version:string;contract_version:string;feature_id:string;request_id:string;disposition:string;action_order:string[];qualified_action_order:string[];denied_action_order:string[];reliability_disposition:string;reliability_digest:string;copilot_digest:string;replay_identity:string;omissions:string[];uncertainty_order:string[];negative_evidence_order:string[];effect_receipts:string[];artifact:{content_type:string;content_hash:string;boundary:string};raw_data_local:true;aggregate_only:true;boundary:string}
export interface WorldgenPerformanceReliabilityWorkflowReceipt {schema_version:string;contract_version:string;feature_id:string;workflow_id:string;disposition:string;stage_order:string[];completed_stage_order:string[];pending_stage_order:string[];compensation_order:string[];checkpoint_seq:number;budget_units:number;consumed_units:number;replay_identity:string;copilot:Record<string,unknown>;workflow_digest:string;artifact:{content_type:string;content_hash:string;boundary:string};effect_receipts:string[];raw_data_local:true;aggregate_only:true;boundary:string}

const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);
const digest=(v:unknown)=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
function validateResult(r:WorldgenPerformanceReliabilityResult,id:string):void{const ids=new Set(r.workload_order),parts=[...r.dependable_order,...r.degraded_order,...r.blocked_order];if(r.schema_version!==RESEARCH_CONTRACT_SCHEMA_VERSION||r.feature_id!==id||r.boundary!==PRECLINICAL_BOUNDARY||r.artifact.boundary!==PRECLINICAL_BOUNDARY||r.artifact.content_type!==WORLDGEN_PERFORMANCE_RELIABILITY_CONTENT_TYPE||r.raw_data_local!==true||r.aggregate_only!==true||!r.workload_order.length||parts.length!==ids.size||new Set(parts).size!==parts.length||parts.some(x=>!ids.has(x))||!digest(r.replay_identity)||!digest(r.result_digest)||r.artifact.content_hash!==r.result_digest)throw new Error("performance-reliability result identity, partition, locality, or digest is invalid");for(const values of [r.workload_order,r.dependable_order,r.degraded_order,r.blocked_order,r.missing_order,r.retry_order,r.timeout_order,r.duplicate_event_order,r.omission_order,r.uncertainty_order,r.negative_evidence_order,r.effect_receipts])if(!ordered(values))throw new Error("performance-reliability vectors are not canonical")}
export const validateWorldgenLocalPerformanceReliabilityResult=(r:WorldgenPerformanceReliabilityResult)=>validateResult(r,WORLDGEN_LOCAL_PERFORMANCE_RELIABILITY_FEATURE_ID); export const validateWorldgenMultimodalPerformanceReliabilityResult=(r:WorldgenPerformanceReliabilityResult)=>validateResult(r,WORLDGEN_MULTIMODAL_PERFORMANCE_RELIABILITY_FEATURE_ID); export const validateWorldgenThroughputPerformanceReliabilityResult=(r:WorldgenPerformanceReliabilityResult)=>validateResult(r,WORLDGEN_THROUGHPUT_PERFORMANCE_RELIABILITY_FEATURE_ID); export const validateWorldgenFederatedPerformanceReliabilityResult=(r:WorldgenPerformanceReliabilityResult)=>validateResult(r,WORLDGEN_FEDERATED_PERFORMANCE_RELIABILITY_FEATURE_ID);
export function validateWorldgenPerformanceReliabilityContractReceipt(r:WorldgenPerformanceReliabilityContractReceipt):void{if(r.schema_version!==RESEARCH_CONTRACT_SCHEMA_VERSION||r.boundary!==PRECLINICAL_BOUNDARY||r.artifact.boundary!==PRECLINICAL_BOUNDARY||r.artifact.content_type!==WORLDGEN_PERFORMANCE_RELIABILITY_CONTRACT_CONTENT_TYPE||r.raw_data_local!==true||r.aggregate_only!==true||!digest(r.contract_digest)||r.artifact.content_hash!==r.contract_digest)throw new Error("performance-reliability contract identity or digest is invalid");for(const values of [r.field_order,r.retained_field_order,r.missing_field_order,r.degraded_field_order,r.reliability_issue_order,r.effect_receipts])if(!ordered(values))throw new Error("performance-reliability contract vectors are not canonical")}
export function validateWorldgenPerformanceReliabilityCopilotReceipt(r:WorldgenPerformanceReliabilityCopilotReceipt):void{if(r.schema_version!==RESEARCH_CONTRACT_SCHEMA_VERSION||r.boundary!==PRECLINICAL_BOUNDARY||r.artifact.boundary!==PRECLINICAL_BOUNDARY||r.artifact.content_type!==WORLDGEN_PERFORMANCE_RELIABILITY_COPILOT_CONTENT_TYPE||r.raw_data_local!==true||r.aggregate_only!==true||!digest(r.copilot_digest)||r.artifact.content_hash!==r.copilot_digest)throw new Error("performance-reliability copilot identity or digest is invalid")}
export function validateWorldgenPerformanceReliabilityWorkflowReceipt(r:WorldgenPerformanceReliabilityWorkflowReceipt):void{if(r.schema_version!==RESEARCH_CONTRACT_SCHEMA_VERSION||r.boundary!==PRECLINICAL_BOUNDARY||r.artifact.boundary!==PRECLINICAL_BOUNDARY||r.artifact.content_type!==WORLDGEN_PERFORMANCE_RELIABILITY_WORKFLOW_CONTENT_TYPE||r.raw_data_local!==true||r.aggregate_only!==true||!digest(r.workflow_digest)||r.artifact.content_hash!==r.workflow_digest)throw new Error("performance-reliability workflow identity or digest is invalid")}
export const worldgenPerformanceReliabilityDigest=(r:WorldgenPerformanceReliabilityResult)=>{validateWorldgenLocalPerformanceReliabilityResult(r);return digestJsonSync(r)}; export const worldgenPerformanceReliabilityContractDigest=(r:WorldgenPerformanceReliabilityContractReceipt)=>{validateWorldgenPerformanceReliabilityContractReceipt(r);return digestJsonSync(r)}; export const worldgenPerformanceReliabilityCopilotDigest=(r:WorldgenPerformanceReliabilityCopilotReceipt)=>{validateWorldgenPerformanceReliabilityCopilotReceipt(r);return digestJsonSync(r)}; export const worldgenPerformanceReliabilityWorkflowDigest=(r:WorldgenPerformanceReliabilityWorkflowReceipt)=>{validateWorldgenPerformanceReliabilityWorkflowReceipt(r);return digestJsonSync(r)};
