/** Public TypeScript contracts for Worldgen P24 researcher/admin experience. */
import { digestJsonSync } from "./tooling.js";
import { PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION } from "./research-contracts.js";
export const WORLDGEN_RESEARCHER_ADMIN_EXPERIENCE_CONTENT_TYPE = "application/vnd.aurora.worldgen.researcher-admin-experience-receipt-1+json" as const;
export const WORLDGEN_LOCAL_RESEARCHER_ADMIN_EXPERIENCE_FEATURE_ID = "AFA-worldgen-P24-F01" as const;
export const WORLDGEN_MULTIMODAL_RESEARCHER_ADMIN_EXPERIENCE_FEATURE_ID = "AFA-worldgen-P24-F02" as const;
export const WORLDGEN_THROUGHPUT_RESEARCHER_ADMIN_EXPERIENCE_FEATURE_ID = "AFA-worldgen-P24-F03" as const;
export const WORLDGEN_FEDERATED_RESEARCHER_ADMIN_EXPERIENCE_FEATURE_ID = "AFA-worldgen-P24-F04" as const;
export const WORLDGEN_LOCAL_RESEARCHER_ADMIN_EXPERIENCE_CONTRACT_FEATURE_ID = "AFA-worldgen-P24-F05" as const;
export const WORLDGEN_MULTIMODAL_RESEARCHER_ADMIN_EXPERIENCE_CONTRACT_FEATURE_ID = "AFA-worldgen-P24-F06" as const;
export const WORLDGEN_THROUGHPUT_RESEARCHER_ADMIN_EXPERIENCE_CONTRACT_FEATURE_ID = "AFA-worldgen-P24-F07" as const;
export const WORLDGEN_FEDERATED_RESEARCHER_ADMIN_EXPERIENCE_CONTRACT_FEATURE_ID = "AFA-worldgen-P24-F08" as const;
export const WORLDGEN_LOCAL_RESEARCHER_ADMIN_EXPERIENCE_COPILOT_FEATURE_ID = "AFA-worldgen-P24-F09" as const;
export const WORLDGEN_MULTIMODAL_RESEARCHER_ADMIN_EXPERIENCE_COPILOT_FEATURE_ID = "AFA-worldgen-P24-F10" as const;
export const WORLDGEN_THROUGHPUT_RESEARCHER_ADMIN_EXPERIENCE_COPILOT_FEATURE_ID = "AFA-worldgen-P24-F11" as const;
export const WORLDGEN_FEDERATED_RESEARCHER_ADMIN_EXPERIENCE_COPILOT_FEATURE_ID = "AFA-worldgen-P24-F12" as const;
export const WORLDGEN_LOCAL_RESEARCHER_ADMIN_EXPERIENCE_WORKFLOW_FEATURE_ID = "AFA-worldgen-P24-F13" as const;
export const WORLDGEN_MULTIMODAL_RESEARCHER_ADMIN_EXPERIENCE_WORKFLOW_FEATURE_ID = "AFA-worldgen-P24-F14" as const;
export const WORLDGEN_THROUGHPUT_RESEARCHER_ADMIN_EXPERIENCE_WORKFLOW_FEATURE_ID = "AFA-worldgen-P24-F15" as const;
export const WORLDGEN_FEDERATED_RESEARCHER_ADMIN_EXPERIENCE_WORKFLOW_FEATURE_ID = "AFA-worldgen-P24-F16" as const;
export interface WorldgenResearchWorkspaceCard {schema_version:string;contract_version:string;feature_id:string;mode:string;scale:string;request_id:string;study_id:string;role:string;disposition:string;panel_order:string[];selected_panel_order:string[];hidden_panel_order:string[];omitted_panel_order:string[];unknown_panel_order:string[];denied_panel_order:string[];negative_panel_order:string[];required_panel_order:string[];action_order:string[];approved_action_order:string[];accessibility_order:string[];audit_order:string[];replay_identity:string;workspace_digest:string;artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];panel_digests:string[];boundary:string};effect_receipts:string[];raw_data_local:true;aggregate_only:true;boundary:string}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown)=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
function validate(r:WorldgenResearchWorkspaceCard,id:string):void{if(r.schema_version!==RESEARCH_CONTRACT_SCHEMA_VERSION||r.feature_id!==id||r.boundary!==PRECLINICAL_BOUNDARY||r.raw_data_local!==true||r.aggregate_only!==true||!r.panel_order.length||!digest(r.replay_identity)||!digest(r.workspace_digest)||r.artifact.boundary!==PRECLINICAL_BOUNDARY||r.artifact.content_type!==WORLDGEN_RESEARCHER_ADMIN_EXPERIENCE_CONTENT_TYPE||r.artifact.content_hash!==r.workspace_digest||JSON.stringify(r.artifact.semantic_loss)!==JSON.stringify(r.omitted_panel_order))throw new Error("research workspace identity, locality, or digest is invalid");for(const values of [r.panel_order,r.selected_panel_order,r.hidden_panel_order,r.omitted_panel_order,r.unknown_panel_order,r.denied_panel_order,r.negative_panel_order,r.required_panel_order,r.action_order,r.approved_action_order,r.accessibility_order,r.audit_order,r.effect_receipts])if(!ordered(values))throw new Error("research workspace vectors are not canonical");const ids=new Set(r.panel_order),parts=new Set([...r.selected_panel_order,...r.hidden_panel_order,...r.omitted_panel_order,...r.unknown_panel_order,...r.denied_panel_order]);if(ids.size!==parts.size||[...ids].some(x=>!parts.has(x)))throw new Error("panel states do not partition")}
export const validateWorldgenLocalResearcherAdminExperience=(r:WorldgenResearchWorkspaceCard)=>validate(r,WORLDGEN_LOCAL_RESEARCHER_ADMIN_EXPERIENCE_FEATURE_ID);export const validateWorldgenMultimodalResearcherAdminExperience=(r:WorldgenResearchWorkspaceCard)=>validate(r,WORLDGEN_MULTIMODAL_RESEARCHER_ADMIN_EXPERIENCE_FEATURE_ID);export const validateWorldgenThroughputResearcherAdminExperience=(r:WorldgenResearchWorkspaceCard)=>validate(r,WORLDGEN_THROUGHPUT_RESEARCHER_ADMIN_EXPERIENCE_FEATURE_ID);export const validateWorldgenFederatedResearcherAdminExperience=(r:WorldgenResearchWorkspaceCard)=>validate(r,WORLDGEN_FEDERATED_RESEARCHER_ADMIN_EXPERIENCE_FEATURE_ID);
export const worldgenResearcherAdminExperienceDigest=(r:WorldgenResearchWorkspaceCard)=>{validateWorldgenLocalResearcherAdminExperience(r);return digestJsonSync(r)};export const worldgenResearcherAdminExperienceContractDigest=(r:WorldgenResearchWorkspaceCard)=>{validate(r,WORLDGEN_LOCAL_RESEARCHER_ADMIN_EXPERIENCE_CONTRACT_FEATURE_ID);return digestJsonSync(r)};export const worldgenResearcherAdminExperienceCopilotDigest=(r:WorldgenResearchWorkspaceCard)=>{validate(r,WORLDGEN_LOCAL_RESEARCHER_ADMIN_EXPERIENCE_COPILOT_FEATURE_ID);return digestJsonSync(r)};export const worldgenResearcherAdminExperienceWorkflowDigest=(r:WorldgenResearchWorkspaceCard)=>{validate(r,WORLDGEN_LOCAL_RESEARCHER_ADMIN_EXPERIENCE_WORKFLOW_FEATURE_ID);return digestJsonSync(r)};
