/** Public TypeScript contracts for Worldgen P29 scale frontier. */
import {digestJsonSync} from "./tooling.js";import {PRECLINICAL_BOUNDARY,RESEARCH_CONTRACT_SCHEMA_VERSION} from "./research-contracts.js";
export const WORLDGEN_SCALE_FRONTIER_CONTENT_TYPE="application/vnd.aurora.worldgen.scale-frontier-receipt-1+json" as const;
export const WORLDGEN_LOCAL_SCALE_FRONTIER_FEATURE_ID="AFA-worldgen-P29-F01" as const;export const WORLDGEN_MULTIMODAL_SCALE_FRONTIER_FEATURE_ID="AFA-worldgen-P29-F02" as const;export const WORLDGEN_THROUGHPUT_SCALE_FRONTIER_FEATURE_ID="AFA-worldgen-P29-F03" as const;export const WORLDGEN_FEDERATED_SCALE_FRONTIER_FEATURE_ID="AFA-worldgen-P29-F04" as const;
export const WORLDGEN_LOCAL_SCALE_FRONTIER_CONTRACT_FEATURE_ID="AFA-worldgen-P29-F05" as const;export const WORLDGEN_MULTIMODAL_SCALE_FRONTIER_CONTRACT_FEATURE_ID="AFA-worldgen-P29-F06" as const;export const WORLDGEN_THROUGHPUT_SCALE_FRONTIER_CONTRACT_FEATURE_ID="AFA-worldgen-P29-F07" as const;export const WORLDGEN_FEDERATED_SCALE_FRONTIER_CONTRACT_FEATURE_ID="AFA-worldgen-P29-F08" as const;
export const WORLDGEN_LOCAL_SCALE_FRONTIER_COPILOT_FEATURE_ID="AFA-worldgen-P29-F09" as const;export const WORLDGEN_MULTIMODAL_SCALE_FRONTIER_COPILOT_FEATURE_ID="AFA-worldgen-P29-F10" as const;export const WORLDGEN_THROUGHPUT_SCALE_FRONTIER_COPILOT_FEATURE_ID="AFA-worldgen-P29-F11" as const;export const WORLDGEN_FEDERATED_SCALE_FRONTIER_COPILOT_FEATURE_ID="AFA-worldgen-P29-F12" as const;
export const WORLDGEN_LOCAL_SCALE_FRONTIER_WORKFLOW_FEATURE_ID="AFA-worldgen-P29-F13" as const;export const WORLDGEN_MULTIMODAL_SCALE_FRONTIER_WORKFLOW_FEATURE_ID="AFA-worldgen-P29-F14" as const;export const WORLDGEN_THROUGHPUT_SCALE_FRONTIER_WORKFLOW_FEATURE_ID="AFA-worldgen-P29-F15" as const;export const WORLDGEN_FEDERATED_SCALE_FRONTIER_WORKFLOW_FEATURE_ID="AFA-worldgen-P29-F16" as const;
export interface WorldgenScaleFrontierCard{schema_version:string;contract_version:string;feature_id:string;mode:string;scale:string;request_id:string;disposition:string;candidate_order:string[];selected_order:string[];rejected_order:string[];unknown_order:string[];omitted_order:string[];uncertainty_order:string[];negative_evidence_order:string[];scale_order:string[];slo_order:string[];replay_identity:string;frontier_digest:string;artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];benchmark_digests:string[];boundary:string};effect_receipts:string[];raw_data_local:true;aggregate_only:true;boundary:string}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown)=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
function validate(r:WorldgenScaleFrontierCard,id:string){if(r.schema_version!==RESEARCH_CONTRACT_SCHEMA_VERSION||r.feature_id!==id||r.boundary!==PRECLINICAL_BOUNDARY||r.raw_data_local!==true||r.aggregate_only!==true||!r.candidate_order.length||!digest(r.replay_identity)||!digest(r.frontier_digest)||r.artifact.content_type!==WORLDGEN_SCALE_FRONTIER_CONTENT_TYPE||r.artifact.content_hash!==r.frontier_digest||r.artifact.boundary!==PRECLINICAL_BOUNDARY)throw new Error("scale frontier identity, locality, or digest is invalid");for(const v of [r.candidate_order,r.selected_order,r.rejected_order,r.unknown_order,r.omitted_order,r.uncertainty_order,r.negative_evidence_order,r.scale_order,r.slo_order,r.effect_receipts])if(!ordered(v))throw new Error("scale vectors are not canonical");const ids=new Set(r.candidate_order),parts=new Set([...r.selected_order,...r.rejected_order,...r.unknown_order,...r.omitted_order]);if(ids.size!==parts.size||[...ids].some(x=>!parts.has(x)))throw new Error("scale states do not partition")}
export const validateWorldgenLocalScaleFrontier=(r:WorldgenScaleFrontierCard)=>validate(r,WORLDGEN_LOCAL_SCALE_FRONTIER_FEATURE_ID);export const validateWorldgenMultimodalScaleFrontier=(r:WorldgenScaleFrontierCard)=>validate(r,WORLDGEN_MULTIMODAL_SCALE_FRONTIER_FEATURE_ID);export const validateWorldgenThroughputScaleFrontier=(r:WorldgenScaleFrontierCard)=>validate(r,WORLDGEN_THROUGHPUT_SCALE_FRONTIER_FEATURE_ID);export const validateWorldgenFederatedScaleFrontier=(r:WorldgenScaleFrontierCard)=>validate(r,WORLDGEN_FEDERATED_SCALE_FRONTIER_FEATURE_ID);
export const worldgenScaleFrontierDigest=(r:WorldgenScaleFrontierCard)=>{validateWorldgenLocalScaleFrontier(r);return digestJsonSync(r)};export const worldgenScaleFrontierContractDigest=(r:WorldgenScaleFrontierCard)=>{validate(r,WORLDGEN_LOCAL_SCALE_FRONTIER_CONTRACT_FEATURE_ID);return digestJsonSync(r)};export const worldgenScaleFrontierCopilotDigest=(r:WorldgenScaleFrontierCard)=>{validate(r,WORLDGEN_LOCAL_SCALE_FRONTIER_COPILOT_FEATURE_ID);return digestJsonSync(r)};export const worldgenScaleFrontierWorkflowDigest=(r:WorldgenScaleFrontierCard)=>{validate(r,WORLDGEN_LOCAL_SCALE_FRONTIER_WORKFLOW_FEATURE_ID);return digestJsonSync(r)};
