/** Public TypeScript contracts for Worldgen P20 security/federation admission. */
import { digestJsonSync } from "./tooling.js";
import { PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION } from "./research-contracts.js";

export const WORLDGEN_SECURITY_FEDERATION_CONTENT_TYPE = "application/vnd.aurora.worldgen.security-federation-receipt-1+json" as const;
export const WORLDGEN_SECURITY_FEDERATION_CONTRACT_CONTENT_TYPE = "application/vnd.aurora.worldgen.security-federation-contract-receipt+json" as const;
export const WORLDGEN_SECURITY_FEDERATION_COPILOT_CONTENT_TYPE = "application/vnd.aurora.worldgen.security-federation-copilot-receipt+json" as const;
export const WORLDGEN_SECURITY_FEDERATION_WORKFLOW_CONTENT_TYPE = "application/vnd.aurora.worldgen.security-federation-workflow-receipt+json" as const;

export const WORLDGEN_LOCAL_SECURITY_FEDERATION_FEATURE_ID = "AFA-worldgen-P20-F01" as const;
export const WORLDGEN_MULTIMODAL_SECURITY_FEDERATION_FEATURE_ID = "AFA-worldgen-P20-F02" as const;
export const WORLDGEN_THROUGHPUT_SECURITY_FEDERATION_FEATURE_ID = "AFA-worldgen-P20-F03" as const;
export const WORLDGEN_FEDERATED_SECURITY_FEDERATION_FEATURE_ID = "AFA-worldgen-P20-F04" as const;
export const WORLDGEN_LOCAL_SECURITY_FEDERATION_CONTRACT_FEATURE_ID = "AFA-worldgen-P20-F05" as const;
export const WORLDGEN_MULTIMODAL_SECURITY_FEDERATION_CONTRACT_FEATURE_ID = "AFA-worldgen-P20-F06" as const;
export const WORLDGEN_THROUGHPUT_SECURITY_FEDERATION_CONTRACT_FEATURE_ID = "AFA-worldgen-P20-F07" as const;
export const WORLDGEN_FEDERATED_SECURITY_FEDERATION_CONTRACT_FEATURE_ID = "AFA-worldgen-P20-F08" as const;
export const WORLDGEN_LOCAL_SECURITY_FEDERATION_COPILOT_FEATURE_ID = "AFA-worldgen-P20-F09" as const;
export const WORLDGEN_MULTIMODAL_SECURITY_FEDERATION_COPILOT_FEATURE_ID = "AFA-worldgen-P20-F10" as const;
export const WORLDGEN_THROUGHPUT_SECURITY_FEDERATION_COPILOT_FEATURE_ID = "AFA-worldgen-P20-F11" as const;
export const WORLDGEN_FEDERATED_SECURITY_FEDERATION_COPILOT_FEATURE_ID = "AFA-worldgen-P20-F12" as const;
export const WORLDGEN_LOCAL_SECURITY_FEDERATION_WORKFLOW_FEATURE_ID = "AFA-worldgen-P20-F13" as const;
export const WORLDGEN_MULTIMODAL_SECURITY_FEDERATION_WORKFLOW_FEATURE_ID = "AFA-worldgen-P20-F14" as const;
export const WORLDGEN_THROUGHPUT_SECURITY_FEDERATION_WORKFLOW_FEATURE_ID = "AFA-worldgen-P20-F15" as const;
export const WORLDGEN_FEDERATED_SECURITY_FEDERATION_WORKFLOW_FEATURE_ID = "AFA-worldgen-P20-F16" as const;

export interface WorldgenSecurityFederationResult {
  schema_version:string; contract_version:string; feature_id:string; request_id:string; consumer:string; purpose:string; origin:string; destination:string; policy_epoch:string;
  disposition:"admitted"|"local_only"|"blocked"|"unresolved"; action_order:string[]; admitted_order:string[]; local_only_order:string[]; denied_order:string[]; unresolved_order:string[]; omission_order:string[]; threat_order:string[]; revocation_order:string[];
  replay_identity:string; federation_digest:string; artifact:{artifact_id:string;content_type:string;content_hash:string;provenance_digests:string[];semantic_loss:string[];boundary:string}; raw_data_local:true; aggregate_only:true; boundary:string;
}
export interface WorldgenSecurityFederationContractReceipt {schema_version:string;contract_version:string;feature_id:string;request_id:string;consumer:string;producer:string;namespace:string;semantic_profile:string;negotiated_version:string;compatibility:string;disposition:string;field_order:string[];retained_field_order:string[];missing_field_order:string[];redacted_field_order:string[];security_issue_order:string[];replay_identity:string;contract_digest:string;effect_receipts:string[];artifact:{content_type:string;content_hash:string;boundary:string};raw_data_local:true;aggregate_only:true;boundary:string}
export interface WorldgenSecurityFederationCopilotReceipt {schema_version:string;contract_version:string;feature_id:string;request_id:string;disposition:string;action_order:string[];admitted_action_order:string[];denied_action_order:string[];security_disposition:string;security_digest:string;copilot_digest:string;replay_identity:string;omissions:string[];threat_order:string[];revocation_order:string[];effect_receipts:string[];artifact:{content_type:string;content_hash:string;boundary:string};raw_data_local:true;aggregate_only:true;boundary:string}
export interface WorldgenSecurityFederationWorkflowReceipt {schema_version:string;contract_version:string;feature_id:string;workflow_id:string;disposition:string;stage_order:string[];completed_stage_order:string[];pending_stage_order:string[];compensation_order:string[];checkpoint_seq:number;budget_units:number;consumed_units:number;replay_identity:string;copilot:Record<string,unknown>;workflow_digest:string;artifact:{content_type:string;content_hash:string;boundary:string};effect_receipts:string[];raw_data_local:true;aggregate_only:true;boundary:string}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v); const digest=(v:unknown)=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
function validateResult(r:WorldgenSecurityFederationResult,id:string):void{const ids=new Set(r.action_order),parts=[...r.admitted_order,...r.local_only_order,...r.denied_order,...r.unresolved_order];if(r.schema_version!==RESEARCH_CONTRACT_SCHEMA_VERSION||r.feature_id!==id||r.boundary!==PRECLINICAL_BOUNDARY||r.artifact.boundary!==PRECLINICAL_BOUNDARY||r.artifact.content_type!==WORLDGEN_SECURITY_FEDERATION_CONTENT_TYPE||r.raw_data_local!==true||r.aggregate_only!==true||!r.action_order.length||parts.length!==ids.size||new Set(parts).size!==parts.length||parts.some(x=>!ids.has(x))||!digest(r.replay_identity)||!digest(r.federation_digest)||r.artifact.content_hash!==r.federation_digest)throw new Error("security-federation result identity, partition, locality, or digest is invalid");for(const values of [r.action_order,r.admitted_order,r.local_only_order,r.denied_order,r.unresolved_order,r.omission_order,r.threat_order,r.revocation_order])if(!ordered(values))throw new Error("security-federation vectors are not canonical")}
export function validateWorldgenLocalSecurityFederationResult(r:WorldgenSecurityFederationResult):void{validateResult(r,WORLDGEN_LOCAL_SECURITY_FEDERATION_FEATURE_ID)} export function validateWorldgenMultimodalSecurityFederationResult(r:WorldgenSecurityFederationResult):void{validateResult(r,WORLDGEN_MULTIMODAL_SECURITY_FEDERATION_FEATURE_ID)} export function validateWorldgenThroughputSecurityFederationResult(r:WorldgenSecurityFederationResult):void{validateResult(r,WORLDGEN_THROUGHPUT_SECURITY_FEDERATION_FEATURE_ID)} export function validateWorldgenFederatedSecurityFederationResult(r:WorldgenSecurityFederationResult):void{validateResult(r,WORLDGEN_FEDERATED_SECURITY_FEDERATION_FEATURE_ID)}
export function validateWorldgenSecurityFederationContractReceipt(r:WorldgenSecurityFederationContractReceipt):void{if(r.schema_version!==RESEARCH_CONTRACT_SCHEMA_VERSION||r.boundary!==PRECLINICAL_BOUNDARY||r.artifact.boundary!==PRECLINICAL_BOUNDARY||r.artifact.content_type!==WORLDGEN_SECURITY_FEDERATION_CONTRACT_CONTENT_TYPE||r.raw_data_local!==true||r.aggregate_only!==true||!digest(r.contract_digest)||r.artifact.content_hash!==r.contract_digest)throw new Error("security contract identity or digest is invalid")}
export function validateWorldgenSecurityFederationCopilotReceipt(r:WorldgenSecurityFederationCopilotReceipt):void{if(r.schema_version!==RESEARCH_CONTRACT_SCHEMA_VERSION||r.boundary!==PRECLINICAL_BOUNDARY||r.artifact.boundary!==PRECLINICAL_BOUNDARY||r.artifact.content_type!==WORLDGEN_SECURITY_FEDERATION_COPILOT_CONTENT_TYPE||r.raw_data_local!==true||r.aggregate_only!==true||!digest(r.copilot_digest)||r.artifact.content_hash!==r.copilot_digest)throw new Error("security copilot identity or digest is invalid")}
export function validateWorldgenSecurityFederationWorkflowReceipt(r:WorldgenSecurityFederationWorkflowReceipt):void{if(r.schema_version!==RESEARCH_CONTRACT_SCHEMA_VERSION||r.boundary!==PRECLINICAL_BOUNDARY||r.artifact.boundary!==PRECLINICAL_BOUNDARY||r.artifact.content_type!==WORLDGEN_SECURITY_FEDERATION_WORKFLOW_CONTENT_TYPE||r.raw_data_local!==true||r.aggregate_only!==true||!digest(r.workflow_digest)||r.artifact.content_hash!==r.workflow_digest)throw new Error("security workflow identity or digest is invalid")}
export const worldgenSecurityFederationDigest=(r:WorldgenSecurityFederationResult)=>{validateWorldgenLocalSecurityFederationResult(r);return digestJsonSync(r)};export const worldgenSecurityFederationContractDigest=(r:WorldgenSecurityFederationContractReceipt)=>{validateWorldgenSecurityFederationContractReceipt(r);return digestJsonSync(r)};export const worldgenSecurityFederationCopilotDigest=(r:WorldgenSecurityFederationCopilotReceipt)=>{validateWorldgenSecurityFederationCopilotReceipt(r);return digestJsonSync(r)};export const worldgenSecurityFederationWorkflowDigest=(r:WorldgenSecurityFederationWorkflowReceipt)=>{validateWorldgenSecurityFederationWorkflowReceipt(r);return digestJsonSync(r)};
