/** Public TypeScript contracts for Worldgen P28 semantic parity. */
import {digestJsonSync} from "./tooling.js";import {PRECLINICAL_BOUNDARY,RESEARCH_CONTRACT_SCHEMA_VERSION} from "./research-contracts.js";
export const WORLDGEN_SEMANTIC_PARITY_CONTENT_TYPE="application/vnd.aurora.worldgen.semantic-parity-receipt-1+json" as const;
export const WORLDGEN_LOCAL_SEMANTIC_PARITY_FEATURE_ID="AFA-worldgen-P28-F01" as const;export const WORLDGEN_MULTIMODAL_SEMANTIC_PARITY_FEATURE_ID="AFA-worldgen-P28-F02" as const;export const WORLDGEN_THROUGHPUT_SEMANTIC_PARITY_FEATURE_ID="AFA-worldgen-P28-F03" as const;export const WORLDGEN_FEDERATED_SEMANTIC_PARITY_FEATURE_ID="AFA-worldgen-P28-F04" as const;
export const WORLDGEN_LOCAL_SEMANTIC_PARITY_CONTRACT_FEATURE_ID="AFA-worldgen-P28-F05" as const;export const WORLDGEN_MULTIMODAL_SEMANTIC_PARITY_CONTRACT_FEATURE_ID="AFA-worldgen-P28-F06" as const;export const WORLDGEN_THROUGHPUT_SEMANTIC_PARITY_CONTRACT_FEATURE_ID="AFA-worldgen-P28-F07" as const;export const WORLDGEN_FEDERATED_SEMANTIC_PARITY_CONTRACT_FEATURE_ID="AFA-worldgen-P28-F08" as const;
export const WORLDGEN_LOCAL_SEMANTIC_PARITY_COPILOT_FEATURE_ID="AFA-worldgen-P28-F09" as const;export const WORLDGEN_MULTIMODAL_SEMANTIC_PARITY_COPILOT_FEATURE_ID="AFA-worldgen-P28-F10" as const;export const WORLDGEN_THROUGHPUT_SEMANTIC_PARITY_COPILOT_FEATURE_ID="AFA-worldgen-P28-F11" as const;export const WORLDGEN_FEDERATED_SEMANTIC_PARITY_COPILOT_FEATURE_ID="AFA-worldgen-P28-F12" as const;
export const WORLDGEN_LOCAL_SEMANTIC_PARITY_WORKFLOW_FEATURE_ID="AFA-worldgen-P28-F13" as const;export const WORLDGEN_MULTIMODAL_SEMANTIC_PARITY_WORKFLOW_FEATURE_ID="AFA-worldgen-P28-F14" as const;export const WORLDGEN_THROUGHPUT_SEMANTIC_PARITY_WORKFLOW_FEATURE_ID="AFA-worldgen-P28-F15" as const;export const WORLDGEN_FEDERATED_SEMANTIC_PARITY_WORKFLOW_FEATURE_ID="AFA-worldgen-P28-F16" as const;
export interface WorldgenSemanticParityCard{schema_version:string;contract_version:string;feature_id:string;mode:string;scale:string;request_id:string;disposition:string;language_order:string[];artifact_order:string[];matched_order:string[];mismatched_order:string[];omitted_order:string[];unknown_order:string[];negative_evidence_order:string[];field_order:string[];semantic_loss_order:string[];replay_identity:string;parity_digest:string;artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];provenance_digests:string[];boundary:string};effect_receipts:string[];raw_data_local:true;aggregate_only:true;boundary:string}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown)=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
function validate(r:WorldgenSemanticParityCard,id:string){if(r.schema_version!==RESEARCH_CONTRACT_SCHEMA_VERSION||r.feature_id!==id||r.boundary!==PRECLINICAL_BOUNDARY||r.raw_data_local!==true||r.aggregate_only!==true||!r.artifact_order.length||!digest(r.replay_identity)||!digest(r.parity_digest)||r.artifact.content_type!==WORLDGEN_SEMANTIC_PARITY_CONTENT_TYPE||r.artifact.content_hash!==r.parity_digest||r.artifact.boundary!==PRECLINICAL_BOUNDARY)throw new Error("semantic parity identity, locality, or digest is invalid");for(const v of [r.language_order,r.artifact_order,r.matched_order,r.mismatched_order,r.omitted_order,r.unknown_order,r.negative_evidence_order,r.field_order,r.semantic_loss_order,r.effect_receipts])if(!ordered(v))throw new Error("parity vectors are not canonical");const ids=new Set(r.artifact_order),parts=new Set([...r.matched_order,...r.mismatched_order,...r.omitted_order,...r.unknown_order]);if(ids.size!==parts.size||[...ids].some(x=>!parts.has(x)))throw new Error("parity states do not partition")}
export const validateWorldgenLocalSemanticParity=(r:WorldgenSemanticParityCard)=>validate(r,WORLDGEN_LOCAL_SEMANTIC_PARITY_FEATURE_ID);export const validateWorldgenMultimodalSemanticParity=(r:WorldgenSemanticParityCard)=>validate(r,WORLDGEN_MULTIMODAL_SEMANTIC_PARITY_FEATURE_ID);export const validateWorldgenThroughputSemanticParity=(r:WorldgenSemanticParityCard)=>validate(r,WORLDGEN_THROUGHPUT_SEMANTIC_PARITY_FEATURE_ID);export const validateWorldgenFederatedSemanticParity=(r:WorldgenSemanticParityCard)=>validate(r,WORLDGEN_FEDERATED_SEMANTIC_PARITY_FEATURE_ID);
export const worldgenSemanticParityDigest=(r:WorldgenSemanticParityCard)=>{validateWorldgenLocalSemanticParity(r);return digestJsonSync(r)};export const worldgenSemanticParityContractDigest=(r:WorldgenSemanticParityCard)=>{validate(r,WORLDGEN_LOCAL_SEMANTIC_PARITY_CONTRACT_FEATURE_ID);return digestJsonSync(r)};export const worldgenSemanticParityCopilotDigest=(r:WorldgenSemanticParityCard)=>{validate(r,WORLDGEN_LOCAL_SEMANTIC_PARITY_COPILOT_FEATURE_ID);return digestJsonSync(r)};export const worldgenSemanticParityWorkflowDigest=(r:WorldgenSemanticParityCard)=>{validate(r,WORLDGEN_LOCAL_SEMANTIC_PARITY_WORKFLOW_FEATURE_ID);return digestJsonSync(r)};
