/** Public TypeScript contracts for Standards P32 migration-integrity cards. */
import {digestJsonSync} from "./tooling.js";

export const STANDARDS_MIGRATION_INTEGRITY_CONTENT_TYPE="application/vnd.aurora.standards.migration-integrity-card-1+json" as const;
export const STANDARDS_MIGRATION_INTEGRITY_BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions" as const;
export const STANDARDS_LOCAL_MIGRATION_INTEGRITY_FEATURE_ID="AFA-standards-P32-F01" as const;export const STANDARDS_MULTIMODAL_MIGRATION_INTEGRITY_FEATURE_ID="AFA-standards-P32-F02" as const;export const STANDARDS_THROUGHPUT_MIGRATION_INTEGRITY_FEATURE_ID="AFA-standards-P32-F03" as const;export const STANDARDS_FEDERATED_CONTINUAL_MIGRATION_INTEGRITY_FEATURE_ID="AFA-standards-P32-F04" as const;
export const STANDARDS_LOCAL_MIGRATION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-standards-P32-F05" as const;export const STANDARDS_MULTIMODAL_MIGRATION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-standards-P32-F06" as const;export const STANDARDS_THROUGHPUT_MIGRATION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-standards-P32-F07" as const;export const STANDARDS_FEDERATED_CONTINUAL_MIGRATION_INTEGRITY_CONTRACT_FEATURE_ID="AFA-standards-P32-F08" as const;
export const STANDARDS_LOCAL_MIGRATION_INTEGRITY_COPILOT_FEATURE_ID="AFA-standards-P32-F09" as const;export const STANDARDS_MULTIMODAL_MIGRATION_INTEGRITY_COPILOT_FEATURE_ID="AFA-standards-P32-F10" as const;export const STANDARDS_THROUGHPUT_MIGRATION_INTEGRITY_COPILOT_FEATURE_ID="AFA-standards-P32-F11" as const;export const STANDARDS_FEDERATED_CONTINUAL_MIGRATION_INTEGRITY_COPILOT_FEATURE_ID="AFA-standards-P32-F12" as const;
export const STANDARDS_LOCAL_MIGRATION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-standards-P32-F13" as const;export const STANDARDS_MULTIMODAL_MIGRATION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-standards-P32-F14" as const;export const STANDARDS_THROUGHPUT_MIGRATION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-standards-P32-F15" as const;export const STANDARDS_FEDERATED_CONTINUAL_MIGRATION_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-standards-P32-F16" as const;

export interface StandardsMigrationIntegrityCard{schema_version:string;contract_version:string;feature_id:string;request_id:string;purpose:string;disposition:"qualified"|"partial"|"unknown"|"blocked";object_order:string[];accepted_order:string[];rejected_order:string[];unknown_order:string[];omitted_order:string[];standard_order:string[];version_order:string[];coordinate_order:string[];unit_order:string[];loss_order:string[];replay_identity:string;closure_digest:string;raw_data_local:true;aggregate_only:true;boundary:string;effect_receipts:string[];artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];evidence_digests:string[];boundary:string}}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
function validate(c:StandardsMigrationIntegrityCard,id:string){if(c.schema_version!=="aurora-research-contract/1.0"||c.feature_id!==id||!c.request_id||!c.purpose||c.boundary!==STANDARDS_MIGRATION_INTEGRITY_BOUNDARY||c.raw_data_local!==true||c.aggregate_only!==true||!c.object_order.length||!digest(c.replay_identity)||!digest(c.closure_digest)||c.artifact.content_type!==STANDARDS_MIGRATION_INTEGRITY_CONTENT_TYPE||c.artifact.content_hash!==c.closure_digest||c.artifact.boundary!==STANDARDS_MIGRATION_INTEGRITY_BOUNDARY)throw new Error("standards identity, locality, digest, artifact, or boundary is incomplete");for(const v of [c.object_order,c.accepted_order,c.rejected_order,c.unknown_order,c.omitted_order,c.standard_order,c.version_order,c.coordinate_order,c.unit_order,c.loss_order,c.effect_receipts])if(!ordered(v))throw new Error("standards vectors are not canonical");const ids=new Set(c.object_order),states=new Set([...c.accepted_order,...c.rejected_order,...c.unknown_order,...c.omitted_order]);if(ids.size!==states.size||[...ids].some(x=>!states.has(x)))throw new Error("object states do not partition")}
export const validateStandardsLocalMigrationIntegrity=(c:StandardsMigrationIntegrityCard)=>validate(c,STANDARDS_LOCAL_MIGRATION_INTEGRITY_FEATURE_ID);export const validateStandardsMultimodalMigrationIntegrity=(c:StandardsMigrationIntegrityCard)=>validate(c,STANDARDS_MULTIMODAL_MIGRATION_INTEGRITY_FEATURE_ID);export const validateStandardsThroughputMigrationIntegrity=(c:StandardsMigrationIntegrityCard)=>validate(c,STANDARDS_THROUGHPUT_MIGRATION_INTEGRITY_FEATURE_ID);export const validateStandardsFederatedContinualMigrationIntegrity=(c:StandardsMigrationIntegrityCard)=>validate(c,STANDARDS_FEDERATED_CONTINUAL_MIGRATION_INTEGRITY_FEATURE_ID);
export const standardsMigrationIntegrityDigest=(c:StandardsMigrationIntegrityCard)=>{validateStandardsLocalMigrationIntegrity(c);return digestJsonSync(c)};export const standardsMigrationIntegrityContractDigest=(c:StandardsMigrationIntegrityCard)=>{validate(c,STANDARDS_LOCAL_MIGRATION_INTEGRITY_CONTRACT_FEATURE_ID);return digestJsonSync(c)};export const standardsMigrationIntegrityCopilotDigest=(c:StandardsMigrationIntegrityCard)=>{validate(c,STANDARDS_LOCAL_MIGRATION_INTEGRITY_COPILOT_FEATURE_ID);return digestJsonSync(c)};export const standardsMigrationIntegrityWorkflowDigest=(c:StandardsMigrationIntegrityCard)=>{validate(c,STANDARDS_LOCAL_MIGRATION_INTEGRITY_WORKFLOW_FEATURE_ID);return digestJsonSync(c)};
