/** Public TypeScript contracts for Sweep P32 audit-integrity cards. */
import {digestJsonSync} from "./tooling.js";
export const SWEEP_AUDIT_INTEGRITY_CONTENT_TYPE="application/vnd.aurora.sweep.audit-integrity-card-1+json" as const;
export const SWEEP_AUDIT_INTEGRITY_BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions" as const;
export const SWEEP_LOCAL_AUDIT_INTEGRITY_FEATURE_ID="AFA-sweep-P32-F01" as const;export const SWEEP_MULTIMODAL_AUDIT_INTEGRITY_FEATURE_ID="AFA-sweep-P32-F02" as const;export const SWEEP_THROUGHPUT_AUDIT_INTEGRITY_FEATURE_ID="AFA-sweep-P32-F03" as const;export const SWEEP_FEDERATED_CONTINUAL_AUDIT_INTEGRITY_FEATURE_ID="AFA-sweep-P32-F04" as const;
export const SWEEP_LOCAL_AUDIT_INTEGRITY_CONTRACT_FEATURE_ID="AFA-sweep-P32-F05" as const;export const SWEEP_MULTIMODAL_AUDIT_INTEGRITY_CONTRACT_FEATURE_ID="AFA-sweep-P32-F06" as const;export const SWEEP_THROUGHPUT_AUDIT_INTEGRITY_CONTRACT_FEATURE_ID="AFA-sweep-P32-F07" as const;export const SWEEP_FEDERATED_CONTINUAL_AUDIT_INTEGRITY_CONTRACT_FEATURE_ID="AFA-sweep-P32-F08" as const;
export const SWEEP_LOCAL_AUDIT_INTEGRITY_COPILOT_FEATURE_ID="AFA-sweep-P32-F09" as const;export const SWEEP_MULTIMODAL_AUDIT_INTEGRITY_COPILOT_FEATURE_ID="AFA-sweep-P32-F10" as const;export const SWEEP_THROUGHPUT_AUDIT_INTEGRITY_COPILOT_FEATURE_ID="AFA-sweep-P32-F11" as const;export const SWEEP_FEDERATED_CONTINUAL_AUDIT_INTEGRITY_COPILOT_FEATURE_ID="AFA-sweep-P32-F12" as const;
export const SWEEP_LOCAL_AUDIT_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-sweep-P32-F13" as const;export const SWEEP_MULTIMODAL_AUDIT_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-sweep-P32-F14" as const;export const SWEEP_THROUGHPUT_AUDIT_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-sweep-P32-F15" as const;export const SWEEP_FEDERATED_CONTINUAL_AUDIT_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-sweep-P32-F16" as const;
export interface SweepAuditIntegrityCard{schema_version:string;contract_version:string;feature_id:string;request_id:string;purpose:string;disposition:"qualified"|"partial"|"unknown"|"blocked";subject_order:string[];clean_order:string[];drift_order:string[];unknown_order:string[];omitted_order:string[];source_order:string[];status_order:string[];evidence_order:string[];replay_identity:string;closure_digest:string;raw_data_local:true;aggregate_only:true;boundary:string;effect_receipts:string[];artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];evidence_digests:string[];boundary:string}}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
function validate(c:SweepAuditIntegrityCard,id:string){if(c.schema_version!=="aurora-research-contract/1.0"||c.feature_id!==id||!c.request_id||!c.purpose||c.boundary!==SWEEP_AUDIT_INTEGRITY_BOUNDARY||c.raw_data_local!==true||c.aggregate_only!==true||!digest(c.replay_identity)||!digest(c.closure_digest)||c.artifact.content_type!==SWEEP_AUDIT_INTEGRITY_CONTENT_TYPE||c.artifact.content_hash!==c.closure_digest||c.artifact.boundary!==SWEEP_AUDIT_INTEGRITY_BOUNDARY)throw new Error("audit identity, locality, digest, artifact, or boundary is incomplete");for(const v of [c.subject_order,c.clean_order,c.drift_order,c.unknown_order,c.omitted_order,c.source_order,c.status_order,c.evidence_order,c.effect_receipts])if(!ordered(v))throw new Error("audit vectors are not canonical");const ids=new Set(c.subject_order),states=new Set([...c.clean_order,...c.drift_order,...c.unknown_order,...c.omitted_order]);if(ids.size!==states.size||[...ids].some(x=>!states.has(x)))throw new Error("subject states do not partition")}
export const validateSweepLocalAuditIntegrity=(c:SweepAuditIntegrityCard)=>validate(c,SWEEP_LOCAL_AUDIT_INTEGRITY_FEATURE_ID);export const validateSweepMultimodalAuditIntegrity=(c:SweepAuditIntegrityCard)=>validate(c,SWEEP_MULTIMODAL_AUDIT_INTEGRITY_FEATURE_ID);export const validateSweepThroughputAuditIntegrity=(c:SweepAuditIntegrityCard)=>validate(c,SWEEP_THROUGHPUT_AUDIT_INTEGRITY_FEATURE_ID);export const validateSweepFederatedContinualAuditIntegrity=(c:SweepAuditIntegrityCard)=>validate(c,SWEEP_FEDERATED_CONTINUAL_AUDIT_INTEGRITY_FEATURE_ID);
export const sweepAuditIntegrityDigest=(c:SweepAuditIntegrityCard)=>{validateSweepLocalAuditIntegrity(c);return digestJsonSync(c)};export const sweepAuditIntegrityContractDigest=(c:SweepAuditIntegrityCard)=>{validate(c,SWEEP_LOCAL_AUDIT_INTEGRITY_CONTRACT_FEATURE_ID);return digestJsonSync(c)};export const sweepAuditIntegrityCopilotDigest=(c:SweepAuditIntegrityCard)=>{validate(c,SWEEP_LOCAL_AUDIT_INTEGRITY_COPILOT_FEATURE_ID);return digestJsonSync(c)};export const sweepAuditIntegrityWorkflowDigest=(c:SweepAuditIntegrityCard)=>{validate(c,SWEEP_LOCAL_AUDIT_INTEGRITY_WORKFLOW_FEATURE_ID);return digestJsonSync(c)};
