/** Public TypeScript contracts for Tokens P32 compression-integrity cards. */
import {digestJsonSync} from "./tooling.js";
export const TOKENS_COMPRESSION_INTEGRITY_CONTENT_TYPE = "application/vnd.aurora.tokens.compression-integrity-card-1+json" as const;
export const TOKENS_COMPRESSION_INTEGRITY_BOUNDARY = "preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions" as const;
export const TOKENS_LOCAL_COMPRESSION_INTEGRITY_FEATURE_ID = "AFA-tokens-P32-F01" as const;
export const TOKENS_MULTIMODAL_COMPRESSION_INTEGRITY_FEATURE_ID = "AFA-tokens-P32-F02" as const;
export const TOKENS_THROUGHPUT_COMPRESSION_INTEGRITY_FEATURE_ID = "AFA-tokens-P32-F03" as const;
export const TOKENS_FEDERATED_COMPRESSION_INTEGRITY_FEATURE_ID = "AFA-tokens-P32-F04" as const;
export const TOKENS_LOCAL_COMPRESSION_INTEGRITY_CONTRACT_FEATURE_ID = "AFA-tokens-P32-F05" as const;
export const TOKENS_MULTIMODAL_COMPRESSION_INTEGRITY_CONTRACT_FEATURE_ID = "AFA-tokens-P32-F06" as const;
export const TOKENS_THROUGHPUT_COMPRESSION_INTEGRITY_CONTRACT_FEATURE_ID = "AFA-tokens-P32-F07" as const;
export const TOKENS_FEDERATED_COMPRESSION_INTEGRITY_CONTRACT_FEATURE_ID = "AFA-tokens-P32-F08" as const;
export const TOKENS_LOCAL_COMPRESSION_INTEGRITY_COPILOT_FEATURE_ID = "AFA-tokens-P32-F09" as const;
export const TOKENS_MULTIMODAL_COMPRESSION_INTEGRITY_COPILOT_FEATURE_ID = "AFA-tokens-P32-F10" as const;
export const TOKENS_THROUGHPUT_COMPRESSION_INTEGRITY_COPILOT_FEATURE_ID = "AFA-tokens-P32-F11" as const;
export const TOKENS_FEDERATED_COMPRESSION_INTEGRITY_COPILOT_FEATURE_ID = "AFA-tokens-P32-F12" as const;
export const TOKENS_LOCAL_COMPRESSION_INTEGRITY_WORKFLOW_FEATURE_ID = "AFA-tokens-P32-F13" as const;
export const TOKENS_MULTIMODAL_COMPRESSION_INTEGRITY_WORKFLOW_FEATURE_ID = "AFA-tokens-P32-F14" as const;
export const TOKENS_THROUGHPUT_COMPRESSION_INTEGRITY_WORKFLOW_FEATURE_ID = "AFA-tokens-P32-F15" as const;
export const TOKENS_FEDERATED_COMPRESSION_INTEGRITY_WORKFLOW_FEATURE_ID = "AFA-tokens-P32-F16" as const;
export interface TokensCompressionIntegrityCard { schema_version:string; contract_version:string; feature_id:string; mode:string; scale:string; request_id:string; purpose:string; disposition:"qualified"|"partial"|"unknown"|"blocked"; claim_order:string[]; qualified_order:string[]; over_budget_order:string[]; unknown_order:string[]; omitted_order:string[]; preserved_obligation_order:string[]; dropped_obligation_order:string[]; token_savings_order:string[]; negative_evidence_order:string[]; replay_identity:string; closure_digest:string; artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];source_digests:string[];boundary:string}; effect_receipts:string[]; raw_data_local:true; aggregate_only:true; boundary:string }
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v); const digest=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
function validate(card:TokensCompressionIntegrityCard,id:string):void { if(card.schema_version!=="1.0.0"||card.feature_id!==id||card.boundary!==TOKENS_COMPRESSION_INTEGRITY_BOUNDARY||card.raw_data_local!==true||card.aggregate_only!==true||!card.claim_order.length||!digest(card.replay_identity)||!digest(card.closure_digest)||card.artifact.content_type!==TOKENS_COMPRESSION_INTEGRITY_CONTENT_TYPE||card.artifact.content_hash!==card.closure_digest||card.artifact.boundary!==TOKENS_COMPRESSION_INTEGRITY_BOUNDARY) throw new Error("compression identity, locality, digest, artifact, or boundary is incomplete"); for(const v of [card.claim_order,card.qualified_order,card.over_budget_order,card.unknown_order,card.omitted_order,card.preserved_obligation_order,card.dropped_obligation_order,card.token_savings_order,card.negative_evidence_order,card.effect_receipts]) if(!ordered(v)) throw new Error("compression vectors are not canonical"); const ids=new Set(card.claim_order), states=new Set([...card.qualified_order,...card.over_budget_order,...card.unknown_order,...card.omitted_order]); if(ids.size!==states.size||[...ids].some((x)=>!states.has(x))) throw new Error("claim states do not partition"); }
export const validateTokensLocalCompressionIntegrity=(c:TokensCompressionIntegrityCard)=>validate(c,TOKENS_LOCAL_COMPRESSION_INTEGRITY_FEATURE_ID); export const validateTokensMultimodalCompressionIntegrity=(c:TokensCompressionIntegrityCard)=>validate(c,TOKENS_MULTIMODAL_COMPRESSION_INTEGRITY_FEATURE_ID); export const validateTokensThroughputCompressionIntegrity=(c:TokensCompressionIntegrityCard)=>validate(c,TOKENS_THROUGHPUT_COMPRESSION_INTEGRITY_FEATURE_ID); export const validateTokensFederatedCompressionIntegrity=(c:TokensCompressionIntegrityCard)=>validate(c,TOKENS_FEDERATED_COMPRESSION_INTEGRITY_FEATURE_ID);
export const tokensCompressionIntegrityDigest=(c:TokensCompressionIntegrityCard)=>{validateTokensLocalCompressionIntegrity(c);return digestJsonSync(c)}; export const tokensCompressionIntegrityContractDigest=(c:TokensCompressionIntegrityCard)=>{validate(c,TOKENS_LOCAL_COMPRESSION_INTEGRITY_CONTRACT_FEATURE_ID);return digestJsonSync(c)}; export const tokensCompressionIntegrityCopilotDigest=(c:TokensCompressionIntegrityCard)=>{validate(c,TOKENS_LOCAL_COMPRESSION_INTEGRITY_COPILOT_FEATURE_ID);return digestJsonSync(c)}; export const tokensCompressionIntegrityWorkflowDigest=(c:TokensCompressionIntegrityCard)=>{validate(c,TOKENS_LOCAL_COMPRESSION_INTEGRITY_WORKFLOW_FEATURE_ID);return digestJsonSync(c)};
