/** Public TypeScript contracts for Weave P32 capability-manifest admission integrity cards. */
import {digestJsonSync} from "./tooling.js";

export const WEAVE_CAPABILITY_MANIFEST_INTEGRITY_CONTENT_TYPE="application/vnd.aurora.weave.capability-manifest-integrity-card-1+json" as const;
export const WEAVE_CAPABILITY_MANIFEST_INTEGRITY_BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions" as const;
export const WEAVE_LOCAL_CAPABILITY_MANIFEST_INTEGRITY_FEATURE_ID="AFA-weave-P32-F01" as const;export const WEAVE_MULTIMODAL_CAPABILITY_MANIFEST_INTEGRITY_FEATURE_ID="AFA-weave-P32-F02" as const;export const WEAVE_THROUGHPUT_CAPABILITY_MANIFEST_INTEGRITY_FEATURE_ID="AFA-weave-P32-F03" as const;export const WEAVE_FEDERATED_CONTINUAL_CAPABILITY_MANIFEST_INTEGRITY_FEATURE_ID="AFA-weave-P32-F04" as const;
export const WEAVE_LOCAL_CAPABILITY_MANIFEST_INTEGRITY_CONTRACT_FEATURE_ID="AFA-weave-P32-F05" as const;export const WEAVE_MULTIMODAL_CAPABILITY_MANIFEST_INTEGRITY_CONTRACT_FEATURE_ID="AFA-weave-P32-F06" as const;export const WEAVE_THROUGHPUT_CAPABILITY_MANIFEST_INTEGRITY_CONTRACT_FEATURE_ID="AFA-weave-P32-F07" as const;export const WEAVE_FEDERATED_CONTINUAL_CAPABILITY_MANIFEST_INTEGRITY_CONTRACT_FEATURE_ID="AFA-weave-P32-F08" as const;
export const WEAVE_LOCAL_CAPABILITY_MANIFEST_INTEGRITY_COPILOT_FEATURE_ID="AFA-weave-P32-F09" as const;export const WEAVE_MULTIMODAL_CAPABILITY_MANIFEST_INTEGRITY_COPILOT_FEATURE_ID="AFA-weave-P32-F10" as const;export const WEAVE_THROUGHPUT_CAPABILITY_MANIFEST_INTEGRITY_COPILOT_FEATURE_ID="AFA-weave-P32-F11" as const;export const WEAVE_FEDERATED_CONTINUAL_CAPABILITY_MANIFEST_INTEGRITY_COPILOT_FEATURE_ID="AFA-weave-P32-F12" as const;
export const WEAVE_LOCAL_CAPABILITY_MANIFEST_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-weave-P32-F13" as const;export const WEAVE_MULTIMODAL_CAPABILITY_MANIFEST_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-weave-P32-F14" as const;export const WEAVE_THROUGHPUT_CAPABILITY_MANIFEST_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-weave-P32-F15" as const;export const WEAVE_FEDERATED_CONTINUAL_CAPABILITY_MANIFEST_INTEGRITY_WORKFLOW_FEATURE_ID="AFA-weave-P32-F16" as const;

export interface WeaveCapabilityManifestIntegrityCard{schema_version:string;contract_version:string;feature_id:string;request_id:string;purpose:string;disposition:"admitted"|"partial"|"unknown"|"blocked";capability_order:string[];admitted_order:string[];rejected_order:string[];unknown_order:string[];omitted_order:string[];consumer_order:string[];owner_order:string[];schema_order:string[];effect_order:string[];replay_identity:string;closure_digest:string;admitted_capability_count:number;total_capability_count:number;raw_data_local:true;aggregate_only:true;boundary:string;effect_receipts:string[];artifact:{artifact_id:string;content_type:string;content_hash:string;semantic_loss:string[];evidence_digests:string[];boundary:string}}
const ordered=(v:string[])=>JSON.stringify([...new Set(v)].sort())===JSON.stringify(v);const digest=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
function validate(c:WeaveCapabilityManifestIntegrityCard,id:string){if(c.schema_version!=="aurora-research-contract/1.0"||c.feature_id!==id||!c.request_id||!c.purpose||c.boundary!==WEAVE_CAPABILITY_MANIFEST_INTEGRITY_BOUNDARY||c.raw_data_local!==true||c.aggregate_only!==true||!digest(c.replay_identity)||!digest(c.closure_digest)||c.artifact.content_type!==WEAVE_CAPABILITY_MANIFEST_INTEGRITY_CONTENT_TYPE||c.artifact.content_hash!==c.closure_digest||c.artifact.boundary!==WEAVE_CAPABILITY_MANIFEST_INTEGRITY_BOUNDARY||c.admitted_capability_count>c.total_capability_count)throw new Error("capability identity, locality, artifact, digest, boundary, or count is incomplete");for(const v of [c.capability_order,c.admitted_order,c.rejected_order,c.unknown_order,c.omitted_order,c.consumer_order,c.owner_order,c.schema_order,c.effect_order,c.effect_receipts])if(!ordered(v))throw new Error("capability vectors are not canonical");const ids=new Set(c.capability_order),states=new Set([...c.admitted_order,...c.rejected_order,...c.unknown_order,...c.omitted_order]);if(ids.size!==states.size||[...ids].some(x=>!states.has(x)))throw new Error("capability states do not partition manifests");if(c.admitted_capability_count!==c.admitted_order.length)throw new Error("admitted capability count does not match admitted order")}
export const validateWeaveLocalCapabilityManifestIntegrity=(c:WeaveCapabilityManifestIntegrityCard)=>validate(c,WEAVE_LOCAL_CAPABILITY_MANIFEST_INTEGRITY_FEATURE_ID);export const validateWeaveMultimodalCapabilityManifestIntegrity=(c:WeaveCapabilityManifestIntegrityCard)=>validate(c,WEAVE_MULTIMODAL_CAPABILITY_MANIFEST_INTEGRITY_FEATURE_ID);export const validateWeaveThroughputCapabilityManifestIntegrity=(c:WeaveCapabilityManifestIntegrityCard)=>validate(c,WEAVE_THROUGHPUT_CAPABILITY_MANIFEST_INTEGRITY_FEATURE_ID);export const validateWeaveFederatedContinualCapabilityManifestIntegrity=(c:WeaveCapabilityManifestIntegrityCard)=>validate(c,WEAVE_FEDERATED_CONTINUAL_CAPABILITY_MANIFEST_INTEGRITY_FEATURE_ID);
export const weaveCapabilityManifestIntegrityDigest=(c:WeaveCapabilityManifestIntegrityCard)=>{validateWeaveLocalCapabilityManifestIntegrity(c);return digestJsonSync(c)};export const weaveCapabilityManifestIntegrityContractDigest=(c:WeaveCapabilityManifestIntegrityCard)=>{validate(c,WEAVE_LOCAL_CAPABILITY_MANIFEST_INTEGRITY_CONTRACT_FEATURE_ID);return digestJsonSync(c)};export const weaveCapabilityManifestIntegrityCopilotDigest=(c:WeaveCapabilityManifestIntegrityCard)=>{validate(c,WEAVE_LOCAL_CAPABILITY_MANIFEST_INTEGRITY_COPILOT_FEATURE_ID);return digestJsonSync(c)};export const weaveCapabilityManifestIntegrityWorkflowDigest=(c:WeaveCapabilityManifestIntegrityCard)=>{validate(c,WEAVE_LOCAL_CAPABILITY_MANIFEST_INTEGRITY_WORKFLOW_FEATURE_ID);return digestJsonSync(c)};
