"""Dependency-free Python SDK for the AURORA/Prism MCP server.

The package intentionally depends only on Python's standard library. It is an integration layer
above the Rust kernel: it transports exact MCP arguments and returns the server's evidence-bearing
JSON without recreating domain semantics or silently converting refusals into ordinary values.
"""

from .async_client import AsyncClient
from .analytics import (
    AnalyticsDirection,
    AnalyticsEvidence,
    AnalyticsRequest,
    CalibrationObservation,
    MetricObservation,
    PairedObservation,
    analytics_request,
)
from .authoring import (
    AcceptanceResult,
    AuthoringError,
    DecisionCell,
    DecisionCellBuilder,
    InputRef,
    MutationPlan,
    MutationSpec,
    PackArtifact,
    PackBuilder,
    ValidationIssue,
    ValidationReport,
    canonical_bytes,
    canonical_json,
    content_digest,
    validate_pack,
)
from .client import Client, ClientConfig
from .errors import (
    ApiError,
    ArgumentError,
    LifecycleError,
    ProcessExited,
    ProtocolError,
    RemoteError,
    ResponseTimeout,
    SdkError,
    ToolRefusal,
    TransportError,
)
from .http_client import ApiClient, AsyncApiClient
from .models import Session, ToolResult
from .oracle import (
    Admissibility,
    EvidenceTier,
    EvaluationReproductionRequest,
    EvaluationTrajectoryRequest,
    EvaluationWorldlineRequest,
    Finding,
    Independence,
    Judgement,
    JudgementBuilder,
    MissingnessAuditRequest,
    OracleCombineRequest,
    OracleManifest,
    OracleRef,
    OracleVersion,
    Position,
    PositionDistribution,
    ReferencePanelRequest,
    ReferenceStandardAuditRequest,
    ValidityWindow,
)
from .workspace import AsyncWorkspace, Workspace

__version__ = "0.1.0"

__all__ = [
    "ArgumentError",
    "ApiClient",
    "ApiError",
    "AcceptanceResult",
    "AsyncClient",
    "AsyncApiClient",
    "AsyncWorkspace",
    "Admissibility",
    "AnalyticsDirection",
    "AnalyticsEvidence",
    "AnalyticsRequest",
    "AuthoringError",
    "DecisionCell",
    "DecisionCellBuilder",
    "EvidenceTier",
    "EvaluationReproductionRequest",
    "EvaluationTrajectoryRequest",
    "EvaluationWorldlineRequest",
    "Finding",
    "Independence",
    "Judgement",
    "JudgementBuilder",
    "Client",
    "ClientConfig",
    "CalibrationObservation",
    "LifecycleError",
    "InputRef",
    "MutationPlan",
    "MutationSpec",
    "MetricObservation",
    "MissingnessAuditRequest",
    "OracleCombineRequest",
    "OracleManifest",
    "OracleRef",
    "OracleVersion",
    "Position",
    "PositionDistribution",
    "ProcessExited",
    "PackArtifact",
    "PackBuilder",
    "PairedObservation",
    "ProtocolError",
    "RemoteError",
    "ResponseTimeout",
    "ReferencePanelRequest",
    "ReferenceStandardAuditRequest",
    "SdkError",
    "Session",
    "ToolRefusal",
    "ToolResult",
    "TransportError",
    "ValidityWindow",
    "ValidationIssue",
    "ValidationReport",
    "Workspace",
    "canonical_bytes",
    "canonical_json",
    "content_digest",
    "analytics_request",
    "validate_pack",
    "__version__",
]
