"""Dependency-free Python SDK for the AURORA/Prism MCP server.

The package intentionally depends only on Python's standard library. It is an integration layer
above the Rust kernel: it transports exact MCP arguments and returns the server's evidence-bearing
JSON without recreating domain semantics or silently converting refusals into ordinary values.
"""

from .async_client import AsyncClient
from .anndata import AnnDataAdapter, AnnDataAuditResult, AnnDataFinding, audit_anndata
from .analytics import (
    AnalyticsDirection,
    AnalyticsEvidence,
    AnalyticsRequest,
    CalibrationObservation,
    MetricObservation,
    PairedObservation,
    analytics_request,
)
from .biological import (
    AdapterDescriptor,
    AdapterExecution,
    AdapterPlan,
    AdapterPlanCandidate,
    AdapterPlanRequest,
    AdapterRegistry,
    ConformanceLevel,
    PlanStatus,
    SourceKind,
    adapter_plan,
)
from .benchmark import (
    BenchmarkObservation,
    BootstrapInterval,
    DistributionSummary,
    PairedBenchmarkObservation,
    PairedEffect,
    ResamplingUnit,
    bootstrap_mean,
    paired_effect,
    summarize_distribution,
)
from .bids import BidsAdapter, BidsAuditResult, BidsFinding, audit_bids
from .authoring import (
    AcceptanceResult,
    AuthoringError,
    DecisionCell,
    DecisionCellBuilder,
    InputRef,
    MutationPlan,
    MutationSpec,
    PackArtifact,
    PackBuilder,
    ValidationIssue,
    ValidationReport,
    canonical_bytes,
    canonical_json,
    content_digest,
    validate_pack,
)
from .client import Client, ClientConfig
from .capability import CapabilityQuery, CapabilityRouteNeed, CapabilityRouteRequest
from .dicom import DicomAdapter, DicomAuditResult, DicomFinding, audit_dicom
from .errors import (
    ApiError,
    ArgumentError,
    LifecycleError,
    ProcessExited,
    ProtocolError,
    RemoteError,
    ResponseTimeout,
    SdkError,
    ToolRefusal,
    TransportError,
)
from .http_client import ApiClient, AsyncApiClient
from .models import Session, ToolResult
from .mission import MissionBinding, MissionPolicy, MissionRequest, MissionStep
from .nifti import NiftiAdapter, NiftiAuditResult, NiftiFinding, audit_nifti
from .oracle import (
    Admissibility,
    EvidenceTier,
    EvaluationReproductionRequest,
    EvaluationTrajectoryRequest,
    EvaluationWorldlineRequest,
    Finding,
    Independence,
    Judgement,
    JudgementBuilder,
    MissingnessAuditRequest,
    OracleCombineRequest,
    OracleManifest,
    OracleRef,
    OracleVersion,
    Position,
    PositionDistribution,
    ReferencePanelRequest,
    ReferenceStandardAuditRequest,
    ValidityWindow,
)
from .workspace import AsyncWorkspace, Workspace
from .workbench import WorkbenchRequest
from .vcf import VcfAdapter, VcfLoss, VcfParseError, VcfParseResult, parse_vcf

__version__ = "0.1.0"

__all__ = [
    "ArgumentError",
    "ApiClient",
    "ApiError",
    "AcceptanceResult",
    "AdapterDescriptor",
    "AdapterExecution",
    "AdapterPlan",
    "AdapterPlanCandidate",
    "AdapterPlanRequest",
    "AdapterRegistry",
    "BenchmarkObservation",
    "BidsAdapter",
    "BidsAuditResult",
    "BidsFinding",
    "BootstrapInterval",
    "AsyncClient",
    "AsyncApiClient",
    "AsyncWorkspace",
    "Admissibility",
    "AnalyticsDirection",
    "AnalyticsEvidence",
    "AnalyticsRequest",
    "AnnDataAdapter",
    "AnnDataAuditResult",
    "AnnDataFinding",
    "AuthoringError",
    "DecisionCell",
    "DecisionCellBuilder",
    "DistributionSummary",
    "EvidenceTier",
    "EvaluationReproductionRequest",
    "EvaluationTrajectoryRequest",
    "EvaluationWorldlineRequest",
    "Finding",
    "Independence",
    "Judgement",
    "JudgementBuilder",
    "Client",
    "ClientConfig",
    "DicomAdapter",
    "DicomAuditResult",
    "DicomFinding",
    "ConformanceLevel",
    "CalibrationObservation",
    "CapabilityQuery",
    "CapabilityRouteNeed",
    "CapabilityRouteRequest",
    "LifecycleError",
    "InputRef",
    "MutationPlan",
    "MutationSpec",
    "MetricObservation",
    "MissionBinding",
    "MissionPolicy",
    "MissionRequest",
    "MissionStep",
    "NiftiAdapter",
    "NiftiAuditResult",
    "NiftiFinding",
    "MissingnessAuditRequest",
    "OracleCombineRequest",
    "OracleManifest",
    "OracleRef",
    "OracleVersion",
    "Position",
    "PositionDistribution",
    "PlanStatus",
    "ProcessExited",
    "PackArtifact",
    "PackBuilder",
    "PairedObservation",
    "PairedBenchmarkObservation",
    "PairedEffect",
    "ProtocolError",
    "RemoteError",
    "ResponseTimeout",
    "ResamplingUnit",
    "ReferencePanelRequest",
    "ReferenceStandardAuditRequest",
    "SdkError",
    "Session",
    "SourceKind",
    "ToolRefusal",
    "ToolResult",
    "TransportError",
    "ValidityWindow",
    "VcfLoss",
    "VcfAdapter",
    "VcfParseError",
    "VcfParseResult",
    "ValidationIssue",
    "ValidationReport",
    "Workspace",
    "WorkbenchRequest",
    "canonical_bytes",
    "canonical_json",
    "content_digest",
    "analytics_request",
    "adapter_plan",
    "audit_bids",
    "audit_dicom",
    "audit_nifti",
    "audit_anndata",
    "bootstrap_mean",
    "parse_vcf",
    "paired_effect",
    "summarize_distribution",
    "validate_pack",
    "__version__",
]
