"""Dependency-free Python SDK for the AURORA/Prism MCP server.

The package intentionally depends only on Python's standard library. It is an integration layer
above the Rust kernel: it transports exact MCP arguments and returns the server's evidence-bearing
JSON without recreating domain semantics or silently converting refusals into ordinary values.
"""

from .async_client import AsyncClient
from .anndata import AnnDataAdapter, AnnDataAuditResult, AnnDataFinding, audit_anndata
from .alignment import AlignmentAdapter, AlignmentAuditResult, AlignmentFinding, audit_alignments
from .adapter_runtime import (
    AdapterExecutionResult,
    AdapterRuntime,
    BatchStatus,
    ProjectionBatchRequest,
    ProjectionBatchResult,
    ProjectionRequest,
    RuntimeStatus,
    execute_projection,
    execute_projection_batch,
)
from .analytics import (
    AnalyticsDirection,
    AnalyticsEvidence,
    AnalyticsRequest,
    CalibrationObservation,
    MetricObservation,
    PairedObservation,
    analytics_request,
)
from .biological import (
    AdapterDescriptor,
    AdapterExecution,
    AdapterPlan,
    AdapterPlanCandidate,
    AdapterPlanRequest,
    AdapterRegistry,
    ConformanceLevel,
    PlanStatus,
    SourceKind,
    adapter_plan,
)
from .benchmark import (
    BenchmarkObservation,
    BootstrapInterval,
    DistributionSummary,
    PairedBenchmarkObservation,
    PairedEffect,
    ResamplingUnit,
    bootstrap_mean,
    paired_effect,
    summarize_distribution,
)
from .bids import BidsAdapter, BidsAuditResult, BidsFinding, audit_bids
from .bioql import BIOQL_SCHEMA, MAX_BIOQL_QUERY_BYTES, MAX_BIOQL_SCHEMA_BYTES, BioQlCompileRequest
from .authoring import (
    AcceptanceResult,
    AuthoringError,
    DecisionCell,
    DecisionCellBuilder,
    InputRef,
    MutationPlan,
    MutationSpec,
    PackArtifact,
    PackBuilder,
    ValidationIssue,
    ValidationReport,
    canonical_bytes,
    canonical_json,
    content_digest,
    validate_pack,
)
from .client import Client, ClientConfig
from .capability import CapabilityQuery, CapabilityRouteNeed, CapabilityRouteRequest
from .dicom import DicomAdapter, DicomAuditResult, DicomFinding, audit_dicom
from .domain_requests import (
    MAX_DOMAIN_REQUEST_BYTES,
    MAX_LAB_ACTIONS,
    MAX_LAB_ITEMS,
    MAX_ROUTING_EVIDENCE,
    LabPlanRequest,
    RoutingDecisionRequest,
    WorldClaimCheckRequest,
)
from .errors import (
    ApiError,
    ArgumentError,
    LifecycleError,
    ProcessExited,
    ProtocolError,
    RemoteError,
    ResponseTimeout,
    SdkError,
    ToolRefusal,
    TransportError,
)
from .evidence import (
    BioCapabilityEvidenceAuditRequest,
    ClaimRequest,
    EVIDENCE_DIMENSIONS,
    EVIDENCE_STATUSES,
    EvidenceItem,
    EvidenceStatus,
)
from .fasta import FastaAdapter, FastaFinding, FastaParseError, FastaParseResult, parse_fasta
from .fastq import FastqAdapter, FastqFinding, FastqParseError, FastqParseResult, parse_fastq
from .fhir import FhirAdapter, FhirAuditResult, FhirFinding, audit_fhir, parse_fhir_json, parse_fhir_ndjson
from .gff3 import Gff3Adapter, Gff3Finding, Gff3ParseError, Gff3ParseResult, parse_gff3
from .http_client import ApiClient, AsyncApiClient
from .models import Session, ToolResult
from .mzml import MzmlAdapter, MzmlFinding, MzmlParseError, MzmlParseResult, parse_mzml
from .pdb import PdbAdapter, PdbFinding, PdbParseError, PdbParseResult, parse_pdb
from .sam import SamAdapter, SamFinding, SamParseError, SamParseResult, parse_sam
from .sdf import SdfAdapter, SdfFinding, SdfParseError, SdfParseResult, parse_sdf
from .mission import MissionBinding, MissionPolicy, MissionRequest, MissionStep
from .nifti import NiftiAdapter, NiftiAuditResult, NiftiFinding, audit_nifti
from .ome_zarr import OmeAuditResult, OmeFinding, OmeZarrAdapter, audit_ome_zarr
from .oracle import (
    Admissibility,
    EvidenceTier,
    EvaluationReproductionRequest,
    EvaluationTrajectoryRequest,
    EvaluationWorldlineRequest,
    Finding,
    Independence,
    Judgement,
    JudgementBuilder,
    MissingnessAuditRequest,
    OracleCombineRequest,
    OracleManifest,
    OracleRef,
    OracleVersion,
    Position,
    PositionDistribution,
    ReferencePanelRequest,
    ReferenceStandardAuditRequest,
    ValidityWindow,
)
from .optional_readers import (
    OptionalDependencyUnavailable,
    read_alignment_file,
    read_anndata_projection,
    read_dicom_projection,
    read_fasta,
    read_fastq,
    read_fhir_json,
    read_fhir_ndjson,
    read_gff3,
    read_indexed_vcf,
    read_mzml,
    read_pdb,
    read_sam,
    read_sdf,
    read_nifti_header,
    read_ome_zarr,
)
from .workspace import AsyncWorkspace, Workspace
from .workbench import WorkbenchRequest
from .vcf import VcfAdapter, VcfLoss, VcfParseError, VcfParseResult, parse_vcf

__version__ = "0.1.0"

__all__ = [
    "ArgumentError",
    "BioCapabilityEvidenceAuditRequest",
    "BioQlCompileRequest",
    "ApiClient",
    "ApiError",
    "AcceptanceResult",
    "AdapterDescriptor",
    "AdapterExecution",
    "AdapterPlan",
    "AdapterPlanCandidate",
    "AdapterPlanRequest",
    "AdapterRegistry",
    "BenchmarkObservation",
    "BidsAdapter",
    "BidsAuditResult",
    "BidsFinding",
    "BIOQL_SCHEMA",
    "MAX_BIOQL_QUERY_BYTES",
    "MAX_BIOQL_SCHEMA_BYTES",
    "BootstrapInterval",
    "AsyncClient",
    "AsyncApiClient",
    "AsyncWorkspace",
    "Admissibility",
    "AnalyticsDirection",
    "AnalyticsEvidence",
    "AnalyticsRequest",
    "AnnDataAdapter",
    "AnnDataAuditResult",
    "AnnDataFinding",
    "AlignmentAdapter",
    "AlignmentAuditResult",
    "AlignmentFinding",
    "AdapterExecutionResult",
    "AdapterRuntime",
    "BatchStatus",
    "AuthoringError",
    "DecisionCell",
    "DecisionCellBuilder",
    "DistributionSummary",
    "EvidenceTier",
    "EvaluationReproductionRequest",
    "EvaluationTrajectoryRequest",
    "EvaluationWorldlineRequest",
    "Finding",
    "FastaAdapter",
    "FastaFinding",
    "FastaParseError",
    "FastaParseResult",
    "FhirAdapter",
    "FhirAuditResult",
    "FhirFinding",
    "Gff3Adapter",
    "Gff3Finding",
    "Gff3ParseError",
    "Gff3ParseResult",
    "FastqAdapter",
    "FastqFinding",
    "FastqParseError",
    "FastqParseResult",
    "MzmlAdapter",
    "MzmlFinding",
    "MzmlParseError",
    "MzmlParseResult",
    "PdbAdapter",
    "PdbFinding",
    "PdbParseError",
    "PdbParseResult",
    "SamAdapter",
    "SamFinding",
    "SamParseError",
    "SamParseResult",
    "SdfAdapter",
    "SdfFinding",
    "SdfParseError",
    "SdfParseResult",
    "Independence",
    "Judgement",
    "JudgementBuilder",
    "Client",
    "ClientConfig",
    "ClaimRequest",
    "DicomAdapter",
    "DicomAuditResult",
    "DicomFinding",
    "LabPlanRequest",
    "RoutingDecisionRequest",
    "WorldClaimCheckRequest",
    "MAX_DOMAIN_REQUEST_BYTES",
    "MAX_LAB_ACTIONS",
    "MAX_LAB_ITEMS",
    "MAX_ROUTING_EVIDENCE",
    "EVIDENCE_DIMENSIONS",
    "EVIDENCE_STATUSES",
    "EvidenceItem",
    "EvidenceStatus",
    "ConformanceLevel",
    "CalibrationObservation",
    "CapabilityQuery",
    "CapabilityRouteNeed",
    "CapabilityRouteRequest",
    "LifecycleError",
    "InputRef",
    "MutationPlan",
    "MutationSpec",
    "MetricObservation",
    "MissionBinding",
    "MissionPolicy",
    "MissionRequest",
    "MissionStep",
    "NiftiAdapter",
    "NiftiAuditResult",
    "NiftiFinding",
    "OmeAuditResult",
    "OmeFinding",
    "OmeZarrAdapter",
    "MissingnessAuditRequest",
    "OracleCombineRequest",
    "OracleManifest",
    "OracleRef",
    "OracleVersion",
    "OptionalDependencyUnavailable",
    "Position",
    "PositionDistribution",
    "PlanStatus",
    "ProcessExited",
    "PackArtifact",
    "PackBuilder",
    "PairedObservation",
    "PairedBenchmarkObservation",
    "PairedEffect",
    "ProtocolError",
    "RemoteError",
    "ResponseTimeout",
    "ResamplingUnit",
    "ReferencePanelRequest",
    "ReferenceStandardAuditRequest",
    "SdkError",
    "Session",
    "SourceKind",
    "ToolRefusal",
    "ToolResult",
    "TransportError",
    "ValidityWindow",
    "VcfLoss",
    "VcfAdapter",
    "VcfParseError",
    "VcfParseResult",
    "ValidationIssue",
    "ValidationReport",
    "Workspace",
    "WorkbenchRequest",
    "canonical_bytes",
    "canonical_json",
    "content_digest",
    "analytics_request",
    "adapter_plan",
    "audit_bids",
    "audit_dicom",
    "audit_nifti",
    "audit_ome_zarr",
    "audit_anndata",
    "audit_alignments",
    "audit_fhir",
    "execute_projection",
    "execute_projection_batch",
    "ProjectionBatchRequest",
    "ProjectionBatchResult",
    "ProjectionRequest",
    "RuntimeStatus",
    "bootstrap_mean",
    "parse_vcf",
    "parse_fastq",
    "parse_fasta",
    "parse_mzml",
    "parse_gff3",
    "parse_pdb",
    "parse_sam",
    "parse_sdf",
    "parse_fhir_json",
    "parse_fhir_ndjson",
    "read_anndata_projection",
    "read_alignment_file",
    "read_dicom_projection",
    "read_fasta",
    "read_fhir_json",
    "read_fhir_ndjson",
    "read_gff3",
    "read_mzml",
    "read_pdb",
    "read_sam",
    "read_sdf",
    "read_indexed_vcf",
    "read_nifti_header",
    "read_ome_zarr",
    "paired_effect",
    "summarize_distribution",
    "validate_pack",
    "__version__",
]
