"""Python parity surface for AFA-adapter-P02-F27."""
from __future__ import annotations
from dataclasses import dataclass
import re
from typing import Any, Mapping, Sequence
from .adapter_throughput_retrieval_synthesis_research_workbench import render_throughput_retrieval_synthesis_research_workbench
from .research_contracts import PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError, research_artifact_digest

FEATURE_ID="AFA-adapter-P02-F27"; CONTRACT_VERSION="adapter-throughput-retrieval-synthesis-assurance-harness/1.0"; INPUT_SCHEMA="ScopedRetrievalQuery3@1"; OUTPUT_SCHEMA="EvidenceSynthesis5@1"
def _canonical(values:Sequence[str])->bool:return tuple(sorted(set(values)))==tuple(values)

@dataclass(frozen=True)
class ThroughputRetrievalSynthesisAssuranceHarnessReceipt:
    request_id:str; baseline_id:str; scope:str; batch_id:str; checkpoint_seq:int; capacity:int; queue_digest:str; verdict:str; check_order:tuple[str,...]; passed_checks:tuple[str,...]; counterexamples:tuple[str,...]; candidate_order:tuple[str,...]; selected_order:tuple[str,...]; omitted_order:tuple[str,...]; overflow_order:tuple[str,...]; uncertainty_order:tuple[str,...]; negative_order:tuple[str,...]; contradictory_order:tuple[str,...]; replay_identity:str; workbench_digest:str; assurance_digest:str; omissions:tuple[str,...]; uncertainty:tuple[str,...]; effect_receipts:tuple[str,...]; artifact:dict[str,Any]; schema_version:str=RESEARCH_CONTRACT_SCHEMA_VERSION; contract_version:str=CONTRACT_VERSION; feature_id:str=FEATURE_ID; raw_data_local:bool=True; boundary:str=PRECLINICAL_BOUNDARY
    def validate(self)->None:
        if (self.schema_version,self.contract_version,self.feature_id)!=(RESEARCH_CONTRACT_SCHEMA_VERSION,CONTRACT_VERSION,FEATURE_ID) or self.boundary!=PRECLINICAL_BOUNDARY or not self.raw_data_local or not self.request_id.strip() or not self.baseline_id.strip() or not self.scope.strip() or not self.batch_id.strip() or self.checkpoint_seq<=0 or self.capacity<=0 or not self.queue_digest or not self.check_order or not self.candidate_order or not self.effect_receipts: raise ResearchContractError("throughput assurance identity, queue, checks, candidates, locality, or effects are incomplete")
        for values in (self.check_order,self.passed_checks,self.counterexamples,self.candidate_order,self.selected_order,self.omitted_order,self.overflow_order,self.uncertainty_order,self.negative_order,self.contradictory_order,self.omissions,self.uncertainty,self.effect_receipts):
            if not _canonical(values): raise ResearchContractError("throughput assurance ordering is not canonical")
        if any(x not in self.omitted_order for x in self.overflow_order) or any(x not in self.candidate_order for x in (*self.selected_order,*self.omitted_order)): raise ResearchContractError("throughput evidence state is not covered by candidates")
        for value in (self.queue_digest,self.replay_identity,self.workbench_digest,self.assurance_digest,self.artifact.get("content_hash")):
            if not isinstance(value,str) or not re.fullmatch(r"[0-9a-f]{64}",value): raise ResearchContractError("throughput assurance digest is invalid")
        if any(not e.startswith("assure:throughput-retrieval-synthesis:") and e!="block:unsafe-release" for e in self.effect_receipts): raise ResearchContractError("throughput assurance effect is outside release gate")

def assure_throughput_retrieval_synthesis(*,workbench_kwargs:Mapping[str,Any],baseline_id:str,expected_scope:str,expected_batch_id:str,minimum_checkpoint_seq:int,minimum_capacity:int,policy_allow:bool,protected_closure:bool,provenance_complete:bool,evidence_complete:bool,replay_identity:str,boundary:str=PRECLINICAL_BOUNDARY)->ThroughputRetrievalSynthesisAssuranceHarnessReceipt:
    if not baseline_id.strip() or not expected_scope.strip() or not expected_batch_id.strip() or minimum_checkpoint_seq<=0 or minimum_capacity<=0 or not re.fullmatch(r"[0-9a-f]{64}",replay_identity) or boundary!=PRECLINICAL_BOUNDARY: raise ResearchContractError("throughput assurance identity, queue, replay, or boundary is invalid")
    wb=render_throughput_retrieval_synthesis_research_workbench(**dict(workbench_kwargs))
    if wb.scope!=expected_scope or wb.batch_id!=expected_batch_id or wb.checkpoint_seq<minimum_checkpoint_seq or wb.capacity<minimum_capacity or wb.replay_identity!=replay_identity: raise ResearchContractError("throughput workbench does not match assurance queue or replay contract")
    checks=tuple(sorted(("batch and checkpoint identity are continuous","bounded capacity and overflow are explicit","evidence states preserve selected, omitted, uncertain, negative, and contradictory items","provenance and replay identities are content-addressed","raw throughput observations remain institution-local","typed workbench receipt validates","requested scope matches the workbench scope"))); passed=set(); counter=set(); omissions=set(wb.omissions); uncertainty=set(wb.uncertainty)
    for ok,success,failure,is_uncertain in ((policy_allow,"policy authorization","policy authorization denied",False),(protected_closure,"protected closure","protected closure incomplete",True),(provenance_complete,"provenance completeness","provenance completeness failed",False),(evidence_complete,"evidence completeness","evidence completeness is unknown",True)):
        if ok: passed.add(success)
        else: counter.add(failure); (uncertainty if is_uncertain else omissions).add(failure)
    if wb.disposition=="passed" and not counter: passed.add("workbench disposition qualified")
    else: counter.add("workbench did not establish a qualified throughput disposition")
    verdict="blocked" if not policy_allow or not protected_closure else ("passed" if not counter else "unknown"); effect=f"assure:throughput-retrieval-synthesis:{baseline_id}" if verdict=="passed" else "block:unsafe-release"
    payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"feature_id":FEATURE_ID,"request_id":wb.request_id,"baseline_id":baseline_id,"scope":expected_scope,"batch_id":wb.batch_id,"checkpoint_seq":wb.checkpoint_seq,"capacity":wb.capacity,"queue_digest":wb.queue_digest,"verdict":verdict,"check_order":list(checks),"passed_checks":sorted(passed),"counterexamples":sorted(counter),"candidate_order":list(wb.candidate_order),"selected_order":list(wb.selected_order),"omitted_order":list(wb.omitted_order),"overflow_order":list(wb.overflow_order),"uncertainty_order":list(wb.uncertainty_order),"negative_order":list(wb.negative_order),"contradictory_order":list(wb.contradictory_order),"replay_identity":replay_identity,"workbench_digest":wb.workbench_digest,"omissions":sorted(omissions),"uncertainty":sorted(uncertainty),"raw_data_local":True,"boundary":PRECLINICAL_BOUNDARY}; ad=research_artifact_digest(payload)
    receipt=ThroughputRetrievalSynthesisAssuranceHarnessReceipt(request_id=wb.request_id,baseline_id=baseline_id,scope=expected_scope,batch_id=wb.batch_id,checkpoint_seq=wb.checkpoint_seq,capacity=wb.capacity,queue_digest=wb.queue_digest,verdict=verdict,check_order=checks,passed_checks=tuple(sorted(passed)),counterexamples=tuple(sorted(counter)),candidate_order=tuple(wb.candidate_order),selected_order=tuple(wb.selected_order),omitted_order=tuple(wb.omitted_order),overflow_order=tuple(wb.overflow_order),uncertainty_order=tuple(wb.uncertainty_order),negative_order=tuple(wb.negative_order),contradictory_order=tuple(wb.contradictory_order),replay_identity=replay_identity,workbench_digest=wb.workbench_digest,assurance_digest=ad,omissions=tuple(sorted(omissions)),uncertainty=tuple(sorted(uncertainty)),effect_receipts=(effect,),artifact={"content_hash":research_artifact_digest({**payload,"assurance_digest":ad}),"media_type":"application/vnd.aurora.throughput-retrieval-synthesis-assurance+json"}); receipt.validate(); return receipt
__all__=["FEATURE_ID","CONTRACT_VERSION","ThroughputRetrievalSynthesisAssuranceHarnessReceipt","assure_throughput_retrieval_synthesis"]
