"""Deterministic Python parity for Adaptive P32 posterior-integrity cards."""
from __future__ import annotations
import hashlib,json,re
from typing import Any,Mapping
from .research_contracts import RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions";CONTENT_TYPE="application/vnd.aurora.adaptive.posterior-integrity-card-1+json"
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return isinstance(v,list) and v==sorted(set(v))
def manifest(*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"adaptive","consumers":["panel scheduler","evaluation engine","coverage gate","release auditor"],"behavior":f"qualify clustered adaptive posterior at {scale} ({mode})","value":"prevents parent-cluster inflation and unknown outcomes from becoming false precision","input_schema":"PosteriorIntegrityRequest4@1","output_schema":"PosteriorIntegrityCard7@1","effects":["emit:posterior-card","retain:cluster-penalty","block:unsafe-evaluation"],"permissions":["read:local-panel"],"determinism":"byte_stable","autonomy_tier":"A1","boundary":BOUNDARY}
def validate(o:Mapping[str,Any],*,feature_id:str|None=None)->None:
 a=o.get("artifact",{});bad=o.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or feature_id is not None and o.get("feature_id")!=feature_id or o.get("boundary")!=BOUNDARY or o.get("raw_data_local") is not True or o.get("aggregate_only") is not True or not o.get("observation_order") or not _digest(o.get("replay_identity")) or not _digest(o.get("closure_digest")) or a.get("content_type")!=CONTENT_TYPE or a.get("content_hash")!=o.get("closure_digest") or a.get("boundary")!=BOUNDARY
 if bad:raise ResearchContractError("posterior identity, locality, digest, artifact, or boundary is incomplete")
 for k in ("observation_order","accepted_order","rejected_order","unknown_order","omitted_order","capability_order","parent_order","effective_n_order","cluster_penalty_order","negative_evidence_order","effect_receipts"):
  if not _ordered(o.get(k,[])):raise ResearchContractError("posterior vectors are not canonical")
 ids=set(o["observation_order"]);states=set(o["accepted_order"])|set(o["rejected_order"])|set(o["unknown_order"])|set(o["omitted_order"])
 if len(o["observation_order"])!=len(ids) or states!=ids:raise ResearchContractError("observation states do not partition")
def qualify(request:Mapping[str,Any],*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:
 if not isinstance(request.get("request_id"),str) or not request["request_id"].strip() or not isinstance(request.get("purpose"),str) or not request["purpose"].strip() or not request.get("observations") or not request.get("required_observation_order") or not request.get("required_capability_order") or not isinstance(request.get("minimum_effective_n_milli"),int) or request["minimum_effective_n_milli"]<=0 or not isinstance(request.get("maximum_parent_fraction_milli"),int) or request["maximum_parent_fraction_milli"]>1000 or not _digest(request.get("replay_identity")) or request.get("boundary")!=BOUNDARY or request.get("raw_data_local") is not True or request.get("aggregate_only") is not True or not _ordered(request["required_observation_order"]) or not _ordered(request["required_capability_order"]) or not _ordered(request.get("adversarial_events",[])):raise ResearchContractError("posterior identity, requirements, thresholds, digest, ordering, locality, or boundary is invalid")
 rows=sorted(request["observations"],key=lambda o:o.get("observation_id",""));order=[];accepted=set();rejected=set();unknown=set();omitted=set();capabilities=set();parents=set();ns=set();penalties=set();negative=set();digests=set();seen=set()
 for o in rows:
  oid=o.get("observation_id","")
  if oid in seen or not isinstance(oid,str) or not oid.strip() or not isinstance(o.get("capability_id"),str) or not o["capability_id"].strip() or not isinstance(o.get("parent_id"),str) or not o["parent_id"].strip() or not _digest(o.get("evidence_digest")) or o.get("local") is not True or o.get("aggregate_only") is not True:raise ResearchContractError("observation identity, outcome, evidence, or locality is invalid")
  seen.add(oid);order.append(oid);capabilities.add(o["capability_id"]);parents.add(o["parent_id"]);ns.add(f"{oid}:{o.get('effective_n_milli',0)}");penalties.add(f"{oid}:{o.get('parent_fraction_milli',0)}");digests.add(o["evidence_digest"])
  if o.get("negative_result") is True:negative.add(f"{oid}:negative-result")
  if o.get("policy_epoch",0)==0 or o.get("outcome")=="unknown":unknown.add(oid)
  elif o.get("effective_n_milli",0)<request["minimum_effective_n_milli"] or o.get("parent_fraction_milli",0)>request["maximum_parent_fraction_milli"] or o.get("outcome")=="contradicted":rejected.add(oid)
  elif o["evidence_digest"]==request["replay_identity"] or oid not in request["required_observation_order"]:omitted.add(oid)
  else:accepted.add(oid)
 global_block=not all(request.get(k) is True for k in ("policy_allowed","protected_closure","signed_approval","raw_data_local","aggregate_only")) or bool(request.get("adversarial_events")) or request.get("action_count",0)>request.get("action_budget",0)
 if global_block:omitted.update(order);accepted.clear();rejected.clear();unknown.clear()
 missing=not set(request["required_observation_order"])<=seen or not set(request["required_capability_order"])<=capabilities;disposition="blocked" if global_block else "unknown" if missing else "partial" if rejected or unknown or omitted else "qualified"
 payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"mode":mode,"scale":scale,"request_id":request["request_id"],"purpose":request["purpose"],"disposition":disposition,"observation_order":order,"accepted_order":sorted(accepted),"rejected_order":sorted(rejected),"unknown_order":sorted(unknown),"omitted_order":sorted(omitted),"capability_order":sorted(capabilities),"parent_order":sorted(parents),"effective_n_order":sorted(ns),"cluster_penalty_order":sorted(penalties),"negative_evidence_order":sorted(negative),"replay_identity":request["replay_identity"],"raw_data_local":True,"aggregate_only":True,"boundary":BOUNDARY};d=_hash(payload);payload["closure_digest"]=d;payload["artifact"]={"artifact_id":f"adaptive-posterior:{request['request_id']}","content_type":CONTENT_TYPE,"content_hash":d,"semantic_loss":sorted(payload["omitted_order"]),"evidence_digests":sorted(digests),"boundary":BOUNDARY};payload["effect_receipts"]=[f"emit:posterior-card:{request['request_id']}"] if disposition=="qualified" else ["block:unsafe-evaluation"];validate(payload,feature_id=feature_id);return payload
PanelObservation4=dict[str,Any];PosteriorIntegrityRequest4=dict[str,Any];PosteriorIntegrityCard7=dict[str,Any];PosteriorIntegrityArtifact4=dict[str,Any];PosteriorIntegrityError=ResearchContractError
__all__=["BOUNDARY","CONTENT_TYPE","PanelObservation4","PosteriorIntegrityRequest4","PosteriorIntegrityCard7","PosteriorIntegrityArtifact4","PosteriorIntegrityError","manifest","qualify","validate"]
