"""Python parity surface for AFA-adapter-P01-F12."""
from __future__ import annotations
from dataclasses import dataclass
import re
from typing import Any, Sequence
from .research_contracts import ADAPTER_FEDERATED_CONTINUAL_EVIDENCE_SURVEILLANCE_RESEARCH_COPILOT_CONTRACT_VERSION, ADAPTER_FEDERATED_CONTINUAL_EVIDENCE_SURVEILLANCE_RESEARCH_COPILOT_FEATURE_ID, PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError, research_artifact_digest

@dataclass(frozen=True)
class FederatedCopilotEvidenceContribution:
    peer_id: str; institution_id: str; source_id: str; semantic_profile: str; artifact_kind: str; digest: str | None; signed: bool = True; permitted_artifact: bool = True; aggregate_only: bool = True; evidence_state: str = "supported"; negative_result: bool = False

@dataclass(frozen=True)
class FederatedContinualEvidenceSurveillanceResearchCopilotReceipt:
    request_id: str; agent_id: str; federation_id: str; purpose: str; endpoint: str; disposition: str; peer_order: tuple[str,...]; candidate_order: tuple[str,...]; selected_order: tuple[str,...]; unresolved_order: tuple[str,...]; denied_order: tuple[str,...]; aggregate_order: tuple[str,...]; replay_identity: str; federation_digest: str; envelope_digest: str; evidence_digest: str; provenance_digest: str; run_digest: str; omissions: tuple[str,...]; uncertainty: tuple[str,...]; negative_evidence: tuple[str,...]; tool_receipts: tuple[str,...]; effect_receipts: tuple[str,...]; qualified_set: dict[str,Any]; artifact: dict[str,Any]; schema_version: str = RESEARCH_CONTRACT_SCHEMA_VERSION; contract_version: str = ADAPTER_FEDERATED_CONTINUAL_EVIDENCE_SURVEILLANCE_RESEARCH_COPILOT_CONTRACT_VERSION; feature_id: str = ADAPTER_FEDERATED_CONTINUAL_EVIDENCE_SURVEILLANCE_RESEARCH_COPILOT_FEATURE_ID; raw_data_local: bool = True; boundary: str = PRECLINICAL_BOUNDARY
    def validate(self)->None:
        if self.schema_version!=RESEARCH_CONTRACT_SCHEMA_VERSION or self.contract_version!=ADAPTER_FEDERATED_CONTINUAL_EVIDENCE_SURVEILLANCE_RESEARCH_COPILOT_CONTRACT_VERSION or self.feature_id!=ADAPTER_FEDERATED_CONTINUAL_EVIDENCE_SURVEILLANCE_RESEARCH_COPILOT_FEATURE_ID or self.boundary!=PRECLINICAL_BOUNDARY or not self.raw_data_local or not self.request_id.strip() or not self.agent_id.strip() or not self.federation_id.strip() or not self.purpose.strip() or not self.endpoint.strip() or not self.candidate_order or not self.effect_receipts or self.qualified_set.get("federation_id")!=self.federation_id or self.qualified_set.get("purpose")!=self.purpose: raise ResearchContractError("federation identity, locality, candidates, effects, or qualified-set linkage is incomplete")
        for values in (self.peer_order,self.candidate_order,self.selected_order,self.unresolved_order,self.denied_order,self.aggregate_order,self.omissions,self.uncertainty,self.negative_evidence,self.tool_receipts,self.effect_receipts,tuple(self.qualified_set.get("peer_order",())),tuple(self.qualified_set.get("selected_order",())),tuple(self.qualified_set.get("aggregate_order",())),tuple(self.qualified_set.get("omissions",())),tuple(self.qualified_set.get("uncertainty",())),tuple(self.qualified_set.get("negative_order",()))):
            if tuple(sorted(set(values)))!=values: raise ResearchContractError("federated ordering is not canonical")
        if set(self.selected_order)|set(self.unresolved_order)|set(self.denied_order)!=set(self.candidate_order) or tuple(self.qualified_set.get("selected_order",()))!=self.selected_order or tuple(self.qualified_set.get("aggregate_order",()))!=self.aggregate_order: raise ResearchContractError("federated states do not partition candidates")
        for value in (self.replay_identity,self.federation_digest,self.envelope_digest,self.evidence_digest,self.provenance_digest,self.run_digest,self.artifact.get("content_hash")):
            if not isinstance(value,str) or not re.fullmatch(r"[0-9a-f]{64}",value): raise ResearchContractError("federated digest is invalid")
        if any(not effect.startswith("dry-run:bounded-tool:") and not effect.startswith("invoke:declared-tool:") and effect!="block:unsafe-release" for effect in self.effect_receipts): raise ResearchContractError("federated effect is outside declared-tool gate")
        if self.disposition=="blocked" and self.effect_receipts!=("block:unsafe-release",): raise ResearchContractError("blocked federation must be explicitly blocked")

def run_federated_continual_evidence_surveillance_research_copilot(*,request_id:str,agent_id:str,federation_id:str,purpose:str,endpoint:str,semantic_profile:str,allowed_artifacts:Sequence[str],min_peer_quorum:int,declared_tools:Sequence[str],requested_tool:str,max_tool_calls:int,dry_run:bool,approval_reference:str|None,approval_granted:bool,contributions:Sequence[FederatedCopilotEvidenceContribution],policy_allow:bool=True,protected_closure:bool=True,raw_data_local:bool=True,replay_identity:str)->FederatedContinualEvidenceSurveillanceResearchCopilotReceipt:
    if not request_id.strip() or not agent_id.strip() or not federation_id.strip() or not purpose.strip() or not endpoint.strip() or min_peer_quorum<=0 or max_tool_calls<=0 or not declared_tools or requested_tool not in declared_tools or not contributions or not raw_data_local or not re.fullmatch(r"[0-9a-f]{64}",replay_identity): raise ResearchContractError("federation identity, quorum, tools, contributions, locality, or replay is invalid")
    ordered=tuple(sorted(contributions,key=lambda item:(item.peer_id,item.source_id))); peers=tuple(sorted({item.peer_id for item in ordered})); candidates=tuple(item.source_id for item in ordered)
    if len(set(candidates))!=len(candidates) or any(not item.peer_id.strip() or not item.institution_id.strip() or not item.source_id.strip() for item in ordered): raise ResearchContractError("peer, institution, and source identities must be unique and non-empty")
    selected:set[str]=set(); unresolved:set[str]=set(); denied:set[str]=set(); aggregate:set[str]=set(); omissions:set[str]=set(); uncertainty:set[str]=set(); negative:set[str]=set(); digests:dict[str,str]={}
    for item in ordered:
        if not policy_allow or not protected_closure: denied.add(item.source_id); omissions.add(f"source:{item.source_id}:policy-or-closure")
        elif item.semantic_profile!=semantic_profile: denied.add(item.source_id); omissions.add(f"source:{item.source_id}:semantic-profile-mismatch")
        elif not item.signed or not item.permitted_artifact or not item.aggregate_only or item.artifact_kind not in allowed_artifacts: denied.add(item.source_id); omissions.add(f"source:{item.source_id}:signer-permission-or-artifact-gate")
        elif item.digest is None: unresolved.add(item.source_id); omissions.add(f"source:{item.source_id}:content-digest-missing")
        elif item.evidence_state in {"unknown","speculative"}: unresolved.add(item.source_id); uncertainty.add(f"source:{item.source_id}:unknown-not-asserted")
        elif item.evidence_state=="contradicted": denied.add(item.source_id); negative.add(f"source:{item.source_id}:contradicted")
        else: selected.add(item.source_id); aggregate.add(item.source_id); digests[item.source_id]=item.digest; negative.add(f"source:{item.source_id}:negative-result") if item.negative_result else None
    if len(peers)<min_peer_quorum: omissions.add("control:peer-quorum-incomplete")
    approval_missing=not dry_run and (not approval_granted or not (approval_reference or "").strip()); omissions.add("control:signed-approval-required") if approval_missing else None
    disposition="blocked" if not policy_allow or not protected_closure or not raw_data_local or len(peers)<min_peer_quorum or approval_missing else "unknown" if not selected else "partial" if unresolved or denied else "completed"
    selected_order=tuple(sorted(selected)); unresolved_order=tuple(sorted(unresolved)); denied_order=tuple(sorted(denied)); aggregate_order=tuple(sorted(aggregate)); omissions_order=tuple(sorted(omissions)); uncertainty_order=tuple(sorted(uncertainty)); negative_order=tuple(sorted(negative)); tool_receipts=(f"tool:{requested_tool}:denied",) if disposition=="blocked" else (f"tool:{requested_tool}:dry-run",) if dry_run else (f"tool:{requested_tool}:bounded-call:1/{max_tool_calls}",)
    federation_digest=research_artifact_digest({"federation_id":federation_id,"purpose":purpose,"endpoint":endpoint,"peer_order":list(peers),"min_peer_quorum":min_peer_quorum}); envelope_digest=research_artifact_digest({"allowed_artifacts":list(allowed_artifacts),"semantic_profile":semantic_profile,"aggregate_order":list(aggregate_order),"raw_data_local":raw_data_local}); evidence_digest=research_artifact_digest({"candidate_order":list(candidates),"selected_order":list(selected_order),"unresolved_order":list(unresolved_order),"denied_order":list(denied_order)}); provenance_digest=research_artifact_digest({"request_id":request_id,"agent_id":agent_id,"replay_identity":replay_identity,"federation_digest":federation_digest,"envelope_digest":envelope_digest,"evidence_digest":evidence_digest}); run_digest=research_artifact_digest({"request_id":request_id,"dry_run":dry_run,"tool_receipts":list(tool_receipts),"provenance_digest":provenance_digest})
    qualified={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"set_id":f"qualified-evidence-federated-continual-copilot:{request_id}","federation_id":federation_id,"purpose":purpose,"peer_order":list(peers),"selected_order":list(selected_order),"selected_digests":[digests[item] for item in selected_order],"aggregate_order":list(aggregate_order),"omissions":list(omissions_order),"uncertainty":list(uncertainty_order),"negative_order":list(negative_order),"evidence_state":"supported" if disposition=="completed" else "unknown","tool_mode":"dry_run" if dry_run else "bounded_invocation","boundary":PRECLINICAL_BOUNDARY}; artifact={"content_hash":research_artifact_digest(qualified),"media_type":"application/vnd.aurora.qualified-evidence-set3+json"}
    receipt=FederatedContinualEvidenceSurveillanceResearchCopilotReceipt(request_id,agent_id,federation_id,purpose,endpoint,disposition,peers,candidates,selected_order,unresolved_order,denied_order,aggregate_order,replay_identity,federation_digest,envelope_digest,evidence_digest,provenance_digest,run_digest,omissions_order,uncertainty_order,negative_order,tool_receipts,("block:unsafe-release",) if disposition=="blocked" else (f"dry-run:bounded-tool:{agent_id}",) if dry_run else (f"invoke:declared-tool:{agent_id}",),qualified,artifact); receipt.validate(); return receipt
