"""Python parity surface for AFA-adapter-P02-F25."""
from __future__ import annotations
from dataclasses import dataclass
import re
from typing import Any, Mapping
from .adapter_local_retrieval_synthesis_research_workbench import render_local_retrieval_synthesis_research_workbench
from .research_contracts import PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError, research_artifact_digest
FEATURE_ID="AFA-adapter-P02-F25"; CONTRACT_VERSION="adapter-local-retrieval-synthesis-assurance-harness/1.0"; INPUT_SCHEMA="ScopedRetrievalQuery1@1"; OUTPUT_SCHEMA="EvidenceSynthesis5@1"
@dataclass(frozen=True)
class LocalRetrievalSynthesisAssuranceHarnessReceipt:
    request_id:str; baseline_id:str; scope:str; verdict:str; check_order:tuple[str,...]; passed_checks:tuple[str,...]; counterexamples:tuple[str,...]; candidate_order:tuple[str,...]; selected_order:tuple[str,...]; omitted_order:tuple[str,...]; uncertainty_order:tuple[str,...]; negative_order:tuple[str,...]; contradictory_order:tuple[str,...]; replay_identity:str; workbench_digest:str; assurance_digest:str; omissions:tuple[str,...]; uncertainty:tuple[str,...]; effect_receipts:tuple[str,...]; artifact:dict[str,Any]; schema_version:str=RESEARCH_CONTRACT_SCHEMA_VERSION; contract_version:str=CONTRACT_VERSION; feature_id:str=FEATURE_ID; raw_data_local:bool=True; boundary:str=PRECLINICAL_BOUNDARY
    def validate(self)->None:
        if (self.schema_version,self.contract_version,self.feature_id)!=(RESEARCH_CONTRACT_SCHEMA_VERSION,CONTRACT_VERSION,FEATURE_ID) or self.boundary!=PRECLINICAL_BOUNDARY or not self.raw_data_local or not self.request_id.strip() or not self.baseline_id.strip() or not self.scope.strip() or not self.check_order or not self.candidate_order or not self.effect_receipts: raise ResearchContractError("assurance identity, checks, candidates, locality, or effects are incomplete")
        for values in (self.check_order,self.passed_checks,self.counterexamples,self.candidate_order,self.selected_order,self.omitted_order,self.uncertainty_order,self.negative_order,self.contradictory_order,self.omissions,self.uncertainty,self.effect_receipts):
            if tuple(sorted(set(values)))!=values: raise ResearchContractError("assurance ordering is not canonical")
        for value in (self.replay_identity,self.workbench_digest,self.assurance_digest,self.artifact.get("content_hash")):
            if not isinstance(value,str) or not re.fullmatch(r"[0-9a-f]{64}",value): raise ResearchContractError("assurance digest is invalid")
def assure_local_retrieval_synthesis(*,workbench_kwargs:Mapping[str,Any],baseline_id:str,expected_scope:str,policy_allow:bool,protected_closure:bool,provenance_complete:bool,evidence_complete:bool,replay_identity:str,boundary:str=PRECLINICAL_BOUNDARY)->LocalRetrievalSynthesisAssuranceHarnessReceipt:
    if not baseline_id.strip() or not expected_scope.strip() or not re.fullmatch(r"[0-9a-f]{64}",replay_identity) or boundary!=PRECLINICAL_BOUNDARY: raise ResearchContractError("assurance identity, scope, replay, or boundary is invalid")
    wb=render_local_retrieval_synthesis_research_workbench(**dict(workbench_kwargs)); checks=tuple(sorted(("negative and omitted evidence remain visible","raw data remains institution-local","replay identity is content-addressed","scope matches requested research scope","typed workbench receipt validates"))); passed=[]; counter=[]; omissions=list(wb.omissions); uncertainty=list(wb.uncertainty)
    for ok,label,kind in ((policy_allow,"policy authorization","omission"),(protected_closure,"protected closure","uncertainty"),(provenance_complete,"provenance completeness","omission"),(evidence_complete,"evidence completeness","uncertainty")):
        if ok: passed.append(label)
        else: counter.append(label+" failed"); (omissions if kind=="omission" else uncertainty).append(label)
    if not counter and wb.disposition=="passed": passed.append("workbench disposition qualified")
    else: counter.append("workbench did not establish a qualified disposition")
    passed=tuple(sorted(set(passed))); counter=tuple(sorted(set(counter))); omissions=tuple(sorted(set(omissions))); uncertainty=tuple(sorted(set(uncertainty))); verdict="passed" if not counter else ("blocked" if len(passed)<2 else "unknown"); effect="assure:local-retrieval-synthesis" if verdict=="passed" else "block:unsafe-release"; payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"feature_id":FEATURE_ID,"request_id":wb.request_id,"baseline_id":baseline_id,"scope":expected_scope,"verdict":verdict,"check_order":list(checks),"passed_checks":list(passed),"counterexamples":list(counter),"candidate_order":list(wb.candidate_order),"selected_order":list(wb.selected_order),"omitted_order":list(wb.omitted_order),"uncertainty_order":list(wb.uncertainty_order),"negative_order":list(wb.negative_order),"contradictory_order":list(wb.contradictory_order),"replay_identity":replay_identity,"workbench_digest":wb.workbench_digest,"omissions":list(omissions),"uncertainty":list(uncertainty),"raw_data_local":True,"boundary":PRECLINICAL_BOUNDARY}; ad=research_artifact_digest(payload); receipt=LocalRetrievalSynthesisAssuranceHarnessReceipt(request_id=wb.request_id,baseline_id=baseline_id,scope=expected_scope,verdict=verdict,check_order=checks,passed_checks=passed,counterexamples=counter,candidate_order=tuple(wb.candidate_order),selected_order=tuple(wb.selected_order),omitted_order=tuple(wb.omitted_order),uncertainty_order=tuple(wb.uncertainty_order),negative_order=tuple(wb.negative_order),contradictory_order=tuple(wb.contradictory_order),replay_identity=replay_identity,workbench_digest=wb.workbench_digest,assurance_digest=ad,omissions=omissions,uncertainty=uncertainty,effect_receipts=(effect,),artifact={"content_hash":research_artifact_digest({**payload,"assurance_digest":ad}),"media_type":"application/vnd.aurora.local-retrieval-synthesis-assurance+json"}); receipt.validate(); return receipt
__all__=["FEATURE_ID","CONTRACT_VERSION","LocalRetrievalSynthesisAssuranceHarnessReceipt","assure_local_retrieval_synthesis"]
