"""Python parity surface for AFA-adapter-P02-F32."""
from __future__ import annotations
from dataclasses import dataclass
import re
from typing import Any, Mapping, Sequence
from .adapter_federated_continual_retrieval_synthesis_research_workbench import render_federated_continual_retrieval_synthesis_research_workbench
from .research_contracts import PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError, research_artifact_digest

FEATURE_ID="AFA-adapter-P02-F32"; CONTRACT_VERSION="adapter-federated-continual-retrieval-synthesis-federated-control-plane/1.0"; INPUT_SCHEMA="ScopedRetrievalQuery4@1"; OUTPUT_SCHEMA="EvidenceSynthesis5@1"
def _canonical(values:Sequence[str])->bool: return tuple(sorted(set(values)))==tuple(values)
def _digest(value:Any)->bool: return isinstance(value,str) and re.fullmatch(r"[0-9a-f]{64}",value) is not None
def _saturated(active:int,capacity:int)->bool: return active*100>=capacity*90

@dataclass(frozen=True)
class FederatedContinualRetrievalSynthesisFederatedControlPlaneReceipt:
    request_id:str; service_id:str; federation_id:str; purpose:str; peer_ids:tuple[str,...]; min_peer_quorum:int; aggregate_only:bool; capacity:int; active_runs:int; checkpoint_seq:int; admission:str; scope:str; endpoint:str; workflow_run_digest:str; workbench_digest:str; health_digest:str; replay_identity:str; control_digest:str; omissions:tuple[str,...]; uncertainty:tuple[str,...]; counterexamples:tuple[str,...]; effect_receipts:tuple[str,...]; artifact:dict[str,Any]; schema_version:str=RESEARCH_CONTRACT_SCHEMA_VERSION; contract_version:str=CONTRACT_VERSION; feature_id:str=FEATURE_ID; raw_data_local:bool=True; boundary:str=PRECLINICAL_BOUNDARY
    def validate(self)->None:
        if (self.schema_version,self.contract_version,self.feature_id)!=(RESEARCH_CONTRACT_SCHEMA_VERSION,CONTRACT_VERSION,FEATURE_ID) or self.boundary!=PRECLINICAL_BOUNDARY or not self.raw_data_local or not self.request_id.strip() or not self.service_id.strip() or not self.federation_id.strip() or not self.purpose.strip() or self.min_peer_quorum<=0 or len(self.peer_ids)<self.min_peer_quorum or not _canonical(self.peer_ids) or not self.aggregate_only or self.capacity<=0 or self.active_runs>self.capacity or self.checkpoint_seq<=0 or self.admission not in {"admitted","degraded","approval_required","blocked"} or not self.scope.strip() or not self.endpoint.strip() or not self.effect_receipts: raise ResearchContractError("continual federated control identity, quorum, checkpoint, capacity, locality, endpoint, or effects are incomplete")
        for values in (self.omissions,self.uncertainty,self.counterexamples,self.effect_receipts):
            if not _canonical(values): raise ResearchContractError("continual federated control ordering is not canonical")
        for value in (self.workflow_run_digest,self.workbench_digest,self.health_digest,self.replay_identity,self.control_digest,self.artifact.get("content_hash")):
            if not _digest(value): raise ResearchContractError("continual federated control digest is invalid")
        if self.artifact.get("media_type")!="application/vnd.aurora.federated-continual-retrieval-synthesis-federated-control-plane+json": raise ResearchContractError("continual federated control artifact media type is invalid")
        if any(not e.startswith("operate:continual-federated-control-plane:") and not e.startswith("approval-required:") and e!="block:unsafe-release" for e in self.effect_receipts): raise ResearchContractError("continual federated control effect is outside admission gate")

def operate_federated_continual_retrieval_synthesis_federated_control_plane(*,workbench_kwargs:Mapping[str,Any],service_id:str,federation_id:str,purpose:str,peer_ids:Sequence[str],min_peer_quorum:int,capacity:int,active_runs:int,expected_scope:str,expected_checkpoint_seq:int,signed_approval:bool,policy_allow:bool,protected_closure:bool,federation_permitted:bool,health_digest:str,replay_identity:str,boundary:str=PRECLINICAL_BOUNDARY)->FederatedContinualRetrievalSynthesisFederatedControlPlaneReceipt:
    peers=tuple(peer_ids)
    if not service_id.strip() or not federation_id.strip() or not purpose.strip() or min_peer_quorum<=0 or len(peers)<min_peer_quorum or not _canonical(peers) or capacity<=0 or active_runs>capacity or not expected_scope.strip() or expected_checkpoint_seq<=0 or not _digest(health_digest) or not _digest(replay_identity) or boundary!=PRECLINICAL_BOUNDARY: raise ResearchContractError("continual federated control identity, quorum, checkpoint, capacity, replay, or boundary is invalid")
    wb=render_federated_continual_retrieval_synthesis_research_workbench(**dict(workbench_kwargs))
    if wb.scope!=expected_scope or wb.federation_id!=federation_id or wb.purpose!=purpose or tuple(wb.peer_ids)!=peers or wb.min_peer_quorum!=min_peer_quorum or not _digest(wb.workflow_run_digest) or wb.replay_identity!=replay_identity: raise ResearchContractError("continual workbench does not match control-plane federation, scope, quorum, workflow, or replay contract")
    omissions=set(wb.omissions); uncertainty=set(wb.uncertainty); counter=set()
    if not policy_allow: counter.add("policy authorization denied"); omissions.add("policy authorization")
    if not protected_closure: counter.add("protected closure incomplete"); uncertainty.add("protected closure")
    if not signed_approval: counter.add("signed approval missing"); uncertainty.add("signed approval")
    if not federation_permitted: counter.add("federation permission denied"); omissions.add("federation permission")
    if _saturated(active_runs,capacity): uncertainty.add("capacity headroom is exhausted")
    admission="blocked" if not policy_allow or not federation_permitted else ("approval_required" if not signed_approval or not protected_closure else ("degraded" if _saturated(active_runs,capacity) else "admitted")); effect=f"operate:continual-federated-control-plane:{service_id}" if admission=="admitted" else (f"approval-required:{service_id}" if admission=="approval_required" else "block:unsafe-release"); omissions=tuple(sorted(omissions)); uncertainty=tuple(sorted(uncertainty)); counter=tuple(sorted(counter)); payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"feature_id":FEATURE_ID,"request_id":wb.request_id,"service_id":service_id,"federation_id":federation_id,"purpose":purpose,"peer_ids":list(peers),"min_peer_quorum":min_peer_quorum,"aggregate_only":True,"capacity":capacity,"active_runs":active_runs,"checkpoint_seq":expected_checkpoint_seq,"admission":admission,"scope":wb.scope,"endpoint":wb.endpoint,"workflow_run_digest":wb.workflow_run_digest,"workbench_digest":wb.workbench_digest,"health_digest":health_digest,"replay_identity":replay_identity,"omissions":list(omissions),"uncertainty":list(uncertainty),"counterexamples":list(counter),"raw_data_local":True,"boundary":PRECLINICAL_BOUNDARY}; cd=research_artifact_digest(payload); receipt=FederatedContinualRetrievalSynthesisFederatedControlPlaneReceipt(request_id=wb.request_id,service_id=service_id,federation_id=federation_id,purpose=purpose,peer_ids=peers,min_peer_quorum=min_peer_quorum,aggregate_only=True,capacity=capacity,active_runs=active_runs,checkpoint_seq=expected_checkpoint_seq,admission=admission,scope=wb.scope,endpoint=wb.endpoint,workflow_run_digest=wb.workflow_run_digest,workbench_digest=wb.workbench_digest,health_digest=health_digest,replay_identity=replay_identity,control_digest=cd,omissions=omissions,uncertainty=uncertainty,counterexamples=counter,effect_receipts=(effect,),artifact={"content_hash":research_artifact_digest({**payload,"control_digest":cd}),"media_type":"application/vnd.aurora.federated-continual-retrieval-synthesis-federated-control-plane+json"}); receipt.validate(); return receipt
__all__=["FEATURE_ID","CONTRACT_VERSION","FederatedContinualRetrievalSynthesisFederatedControlPlaneReceipt","operate_federated_continual_retrieval_synthesis_federated_control_plane"]
