"""Python parity for Adapter P32 gateway-integrity cards."""
from __future__ import annotations
import hashlib,json,re
from typing import Any,Mapping
from .research_contracts import RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions";CONTENT_TYPE="application/vnd.aurora.adapter.gateway-integrity-card-1+json"
GatewayEndpoint4=dict[str,Any];GatewayIntegrityRequest4=dict[str,Any];GatewayIntegrityCard7=dict[str,Any];GatewayIntegrityArtifact4=dict[str,Any];GatewayIntegrityError=ResearchContractError
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return isinstance(v,list) and v==sorted(set(v))
def manifest(*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"adapter","consumers":["protocol gateway","schema registry","workflow compiler","research workbench"],"behavior":f"qualify gateway compatibility at {scale} ({mode})","value":"prevents incompatible protocols, unapproved capabilities, and non-local data routes from entering research workflows","input_schema":"GatewayIntegrityRequest4@1","output_schema":"GatewayIntegrityCard7@1","effects":["emit:gateway-card","retain:compatibility-witness","block:unsafe-gateway"],"permissions":["read:local-capability-manifest"],"determinism":"byte_stable","autonomy_tier":"A1","boundary":BOUNDARY}
def validate(o:Mapping[str,Any],*,feature_id:str|None=None)->None:
 a=o.get("artifact",{});bad=o.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or(feature_id is not None and o.get("feature_id")!=feature_id)or not o.get("request_id")or not o.get("purpose")or o.get("boundary")!=BOUNDARY or a.get("boundary")!=BOUNDARY or o.get("raw_data_local") is not True or o.get("aggregate_only") is not True or not _digest(o.get("replay_identity")) or not _digest(o.get("closure_digest")) or a.get("content_type")!=CONTENT_TYPE or a.get("content_hash")!=o.get("closure_digest")
 if bad:raise ResearchContractError("gateway identity, locality, artifact, digest, or boundary is incomplete")
 for k in("endpoint_order","accepted_order","rejected_order","unknown_order","omitted_order","protocol_order","schema_order","capability_order","version_order","effect_receipts"):
  if not _ordered(o.get(k,[])):raise ResearchContractError("gateway vectors are not canonical")
 ids=set(o["endpoint_order"]);states=set(o["accepted_order"])|set(o["rejected_order"])|set(o["unknown_order"])|set(o["omitted_order"])
 if len(o["endpoint_order"])!=len(ids)or states!=ids:raise ResearchContractError("endpoint states do not partition")
def qualify(request:Mapping[str,Any],*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:
 if request.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or not request.get("request_id","").strip() or not request.get("purpose","").strip() or not request.get("endpoints") or not request.get("required_endpoint_order") or not _ordered(request["required_endpoint_order"]) or not _ordered(request.get("required_protocol_order",[])) or not _digest(request.get("replay_identity")) or request.get("boundary")!=BOUNDARY or request.get("raw_data_local") is not True or request.get("aggregate_only") is not True or not _ordered(request.get("adversarial_events",[])) or request.get("endpoint_budget",0)<=0:raise ResearchContractError("gateway identity, ordering, digest, locality, boundary, or budget is invalid")
 rows=sorted(request["endpoints"],key=lambda a:a.get("endpoint_id",""));seen=set();accepted=set();rejected=set();unknown=set();omitted=set();protocols=set();schemas=set();capabilities=set();versions=set();evidence=set()
 for e in rows:
  eid=e.get("endpoint_id","")
  if not eid.strip()or eid in seen or not e.get("protocol","").strip()or not e.get("schema","").strip()or not e.get("capability","").strip()or not e.get("version","").strip()or not _digest(e.get("checksum"))or not e.get("evidence_state","").strip()or e.get("local") is not True or e.get("aggregate_only") is not True:raise ResearchContractError("endpoint identity, protocol, schema, capability, version, evidence, digest, or locality is invalid")
  seen.add(eid);protocols.add(f"{eid}:{e['protocol']}");schemas.add(f"{eid}:{e['schema']}");capabilities.add(f"{eid}:{e['capability']}");versions.add(f"{eid}:{e['version']}");evidence.add(e["checksum"])
  if e["evidence_state"]=="unknown"or e["checksum"]==request["replay_identity"]:unknown.add(eid)
  elif e.get("approved") is not True or e["protocol"]=="unknown"or e["schema"]=="unknown":rejected.add(eid)
  elif eid not in request["required_endpoint_order"]:omitted.add(eid)
  else:accepted.add(eid)
 missing=[x for x in request["required_endpoint_order"] if x not in seen];global_block=not all(request.get(k) is True for k in("policy_allowed","protected_closure","signed_manifest","raw_data_local","aggregate_only"))or bool(request.get("adversarial_events"))or len(rows)>request["endpoint_budget"]
 if global_block:omitted.update(seen);accepted.clear();rejected.clear();unknown.clear()
 disposition="blocked" if global_block else "unknown" if missing or unknown else "partial" if rejected or omitted else "qualified";payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"request_id":request["request_id"],"purpose":request["purpose"],"disposition":disposition,"endpoint_order":sorted(seen),"accepted_order":sorted(accepted),"rejected_order":sorted(rejected),"unknown_order":sorted(unknown),"omitted_order":sorted(omitted),"protocol_order":sorted(protocols),"schema_order":sorted(schemas),"capability_order":sorted(capabilities),"version_order":sorted(versions),"replay_identity":request["replay_identity"],"raw_data_local":True,"aggregate_only":True,"boundary":BOUNDARY};d=_hash(payload);payload["closure_digest"]=d;payload["effect_receipts"]=[f"approve:gateway:{request['request_id']}"] if disposition=="qualified" else ["block:unsafe-gateway"];payload["artifact"]={"artifact_id":f"adapter-gateway:{request['request_id']}","content_type":CONTENT_TYPE,"content_hash":d,"semantic_loss":payload["omitted_order"],"evidence_digests":sorted(evidence),"boundary":BOUNDARY};validate(payload,feature_id=feature_id);return payload
__all__=["BOUNDARY","CONTENT_TYPE","GatewayEndpoint4","GatewayIntegrityRequest4","GatewayIntegrityCard7","GatewayIntegrityArtifact4","GatewayIntegrityError","manifest","qualify","validate"]
