"""Deterministic Python parity for Baseline P32 counterfactual-integrity cards."""
from __future__ import annotations
import hashlib, json, re
from typing import Any, Mapping
from .research_contracts import RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError
BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions"; CONTENT_TYPE="application/vnd.aurora.baseline.counterfactual-integrity-card-1+json"
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return isinstance(v,list) and v==sorted(set(v))
def manifest(*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"baseline","consumers":["evaluation engine","experiment designer","interpretation compiler","release auditor"],"behavior":f"qualify matched counterfactual baseline at {scale} ({mode})","value":"prevents unfair or incomparable baseline claims from masquerading as research advances","input_schema":"CounterfactualIntegrityRequest4@1","output_schema":"CounterfactualIntegrityCard7@1","effects":["emit:baseline-card","retain:negative-evidence","block:unfair-comparison"],"permissions":["read:local-benchmark"],"determinism":"byte_stable","autonomy_tier":"A1","boundary":BOUNDARY}
def validate(o:Mapping[str,Any],*,feature_id:str|None=None)->None:
 a=o.get("artifact",{});bad=o.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or feature_id is not None and o.get("feature_id")!=feature_id or o.get("boundary")!=BOUNDARY or o.get("raw_data_local") is not True or o.get("aggregate_only") is not True or not o.get("arm_order") or not _digest(o.get("replay_identity")) or not _digest(o.get("closure_digest")) or a.get("content_type")!=CONTENT_TYPE or a.get("content_hash")!=o.get("closure_digest") or a.get("boundary")!=BOUNDARY
 if bad:raise ResearchContractError("baseline identity, locality, digest, artifact, or boundary is incomplete")
 for k in ("arm_order","matched_order","rejected_order","unknown_order","omitted_order","strategy_order","metric_order","uncertainty_order","negative_evidence_order","effect_receipts"):
  if not _ordered(o.get(k,[])):raise ResearchContractError("baseline vectors are not canonical")
 ids=set(o["arm_order"]);states=set(o["matched_order"])|set(o["rejected_order"])|set(o["unknown_order"])|set(o["omitted_order"])
 if len(o["arm_order"])!=len(ids) or states!=ids:raise ResearchContractError("arm states do not partition")
def qualify(request:Mapping[str,Any],*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:
 if not isinstance(request.get("request_id"),str) or not request["request_id"].strip() or not isinstance(request.get("purpose"),str) or not request["purpose"].strip() or not request.get("arms") or not request.get("required_arm_order") or not request.get("required_strategy_order") or not _digest(request.get("benchmark_digest")) or not _digest(request.get("replay_identity")) or request.get("boundary")!=BOUNDARY or request.get("raw_data_local") is not True or request.get("aggregate_only") is not True or not _ordered(request["required_arm_order"]) or not _ordered(request["required_strategy_order"]) or not _ordered(request.get("adversarial_events",[])):raise ResearchContractError("baseline identity, requirements, digests, ordering, locality, or boundary is invalid")
 rows=sorted(request["arms"],key=lambda a:a.get("arm_id",""));order=[];matched=set();rejected=set();unknown=set();omitted=set();strategies=set();metrics=set();uncertainty=set();negative=set();benchmarks=set();seen=set()
 for a in rows:
  aid=a.get("arm_id","")
  if aid in seen or not isinstance(aid,str) or not aid.strip() or not isinstance(a.get("strategy"),str) or not a["strategy"].strip() or not _digest(a.get("benchmark_digest")) or a.get("local") is not True or a.get("aggregate_only") is not True:raise ResearchContractError("arm identity, strategy, benchmark, or locality is invalid")
  seen.add(aid);order.append(aid);strategies.add(a["strategy"]);metrics.add(f"{aid}:{a.get('metric_milli',0)}");uncertainty.add(f"{aid}:{a.get('uncertainty_milli',0)}");benchmarks.add(a["benchmark_digest"])
  if a.get("negative_result") is True:negative.add(f"{aid}:negative-result")
  if a.get("policy_epoch",0)==0 or a.get("evidence_state")=="unknown":unknown.add(aid)
  elif a.get("matched") is not True or a["benchmark_digest"]!=request["benchmark_digest"] or a["strategy"] not in request["required_strategy_order"]:rejected.add(aid)
  elif a["benchmark_digest"]==request["replay_identity"] or aid not in request["required_arm_order"]:omitted.add(aid)
  else:matched.add(aid)
 global_block=not all(request.get(k) is True for k in ("policy_allowed","protected_closure","signed_approval","raw_data_local","aggregate_only")) or bool(request.get("adversarial_events")) or request.get("action_count",0)>request.get("action_budget",0)
 if global_block:omitted.update(order);matched.clear();rejected.clear();unknown.clear()
 missing=not set(request["required_arm_order"])<=seen or not set(request["required_strategy_order"])<=strategies;disposition="blocked" if global_block else "unknown" if missing else "partial" if rejected or unknown or omitted else "qualified"
 payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"mode":mode,"scale":scale,"request_id":request["request_id"],"purpose":request["purpose"],"disposition":disposition,"arm_order":order,"matched_order":sorted(matched),"rejected_order":sorted(rejected),"unknown_order":sorted(unknown),"omitted_order":sorted(omitted),"strategy_order":sorted(strategies),"metric_order":sorted(metrics),"uncertainty_order":sorted(uncertainty),"negative_evidence_order":sorted(negative),"replay_identity":request["replay_identity"],"raw_data_local":True,"aggregate_only":True,"boundary":BOUNDARY};d=_hash(payload);payload["closure_digest"]=d;payload["artifact"]={"artifact_id":f"baseline-counterfactual:{request['request_id']}","content_type":CONTENT_TYPE,"content_hash":d,"semantic_loss":sorted(payload["omitted_order"]),"benchmark_digests":sorted(benchmarks),"boundary":BOUNDARY};payload["effect_receipts"]=[f"emit:baseline-card:{request['request_id']}"] if disposition=="qualified" else ["block:unfair-comparison"];validate(payload,feature_id=feature_id);return payload
BaselineArm4=dict[str,Any];CounterfactualIntegrityRequest4=dict[str,Any];CounterfactualIntegrityCard7=dict[str,Any];CounterfactualIntegrityArtifact4=dict[str,Any];CounterfactualIntegrityError=ResearchContractError
__all__=["BOUNDARY","CONTENT_TYPE","BaselineArm4","CounterfactualIntegrityRequest4","CounterfactualIntegrityCard7","CounterfactualIntegrityArtifact4","CounterfactualIntegrityError","manifest","qualify","validate"]
