"""Python parity surface for ``AFA-bioethics-P27-F26``."""
from __future__ import annotations
from dataclasses import dataclass
import hashlib, json, re
from typing import Any, Mapping, Sequence
from .research_contracts import PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError

FEATURE_ID = "AFA-bioethics-P27-F26"; CONTRACT_VERSION = "bioethics-multimodal-dependency-composition-assurance-harness/1.0"; INPUT_SCHEMA = "BioethicsCompositionRequest2@1"; OUTPUT_SCHEMA = "BioethicsCompositionReceipt7@1"; CONTENT_TYPE = "application/vnd.aurora.bioethics-composition-receipt-7+json"
def _digest(value: Any) -> bool: return isinstance(value, str) and re.fullmatch(r"[0-9a-f]{64}", value) is not None
def _canonical(values: Sequence[str]) -> bool: return tuple(values) == tuple(sorted(set(values)))
def _hash(value: Any) -> str: return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()).hexdigest()

@dataclass(frozen=True)
class BioethicsCompositionResult:
    composition_id: str; federation_id: str; institution_id: str; semantic_profile: str; disposition: str; dependency_order: tuple[str,...]; admitted_order: tuple[str,...]; unresolved_order: tuple[str,...]; blocked_order: tuple[str,...]; missing_dependency_order: tuple[str,...]; contradiction_order: tuple[str,...]; omission_order: tuple[str,...]; uncertainty_order: tuple[str,...]; negative_evidence_order: tuple[str,...]; replay_identity: str; composition_digest: str; artifact: dict[str,Any]; effect_receipts: tuple[str,...]; raw_data_local: bool=True; aggregate_only: bool=True; boundary: str=PRECLINICAL_BOUNDARY; schema_version: str=RESEARCH_CONTRACT_SCHEMA_VERSION; contract_version: str=CONTRACT_VERSION; feature_id: str=FEATURE_ID
    def to_dict(self) -> dict[str,Any]: return {"schema_version":self.schema_version,"contract_version":self.contract_version,"feature_id":self.feature_id,"composition_id":self.composition_id,"federation_id":self.federation_id,"institution_id":self.institution_id,"semantic_profile":self.semantic_profile,"disposition":self.disposition,"dependency_order":list(self.dependency_order),"admitted_order":list(self.admitted_order),"unresolved_order":list(self.unresolved_order),"blocked_order":list(self.blocked_order),"missing_dependency_order":list(self.missing_dependency_order),"contradiction_order":list(self.contradiction_order),"omission_order":list(self.omission_order),"uncertainty_order":list(self.uncertainty_order),"negative_evidence_order":list(self.negative_evidence_order),"replay_identity":self.replay_identity,"composition_digest":self.composition_digest,"artifact":self.artifact,"effect_receipts":list(self.effect_receipts),"raw_data_local":self.raw_data_local,"aggregate_only":self.aggregate_only,"boundary":self.boundary}
    def validate(self) -> None:
        if (self.schema_version,self.contract_version,self.feature_id)!=(RESEARCH_CONTRACT_SCHEMA_VERSION,CONTRACT_VERSION,FEATURE_ID) or self.boundary!=PRECLINICAL_BOUNDARY or self.artifact.get("boundary")!=PRECLINICAL_BOUNDARY or not self.raw_data_local or not self.aggregate_only or not all(value.strip() for value in (self.composition_id,self.federation_id,self.institution_id,self.semantic_profile)) or not self.dependency_order or not self.effect_receipts or self.disposition not in {"qualified","unresolved","blocked"}: raise ResearchContractError("composition identity, locality, dependencies, or effects are incomplete")
        for values in (self.dependency_order,self.admitted_order,self.unresolved_order,self.blocked_order,self.missing_dependency_order,self.contradiction_order,self.omission_order,self.uncertainty_order,self.negative_evidence_order,self.effect_receipts):
            if not _canonical(values): raise ResearchContractError("composition ordering is not canonical")
        parts=[*self.admitted_order,*self.unresolved_order,*self.blocked_order]
        if set(parts)!=set(self.dependency_order) or len(parts)!=len(set(parts)): raise ResearchContractError("composition states do not partition dependencies")
        if not all(_digest(value) for value in (self.replay_identity,self.composition_digest,self.artifact.get("content_hash"))): raise ResearchContractError("composition digest is invalid")
        if self.artifact.get("content_type")!=CONTENT_TYPE: raise ResearchContractError("bioethics composition artifact type is invalid")
        if self.disposition=="qualified" and self.effect_receipts!=(f"exchange:permitted-summaries:{self.composition_id}",f"manage:local-capability:{self.composition_id}"): raise ResearchContractError("qualified composition effects are invalid")
        if self.disposition!="qualified" and self.effect_receipts!=("block:unsafe-release",): raise ResearchContractError("non-qualified composition must block release")

def bioethics_dependency_composition_manifest() -> dict[str,Any]: return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":FEATURE_ID,"version":CONTRACT_VERSION,"owner_crate":"bioethics","consumers":["consortium operator","bioethicist","downstream research workflow"],"behavior":"verifies multimodal preclinical dependency closure, comparability, evidence, locality, and policy gates without inferring ethics or executing research","value":"turns missing, contradictory, or unauthorized cross-crate dependencies into deterministic release evidence instead of silent composition","input_schema":INPUT_SCHEMA,"output_schema":OUTPUT_SCHEMA,"effects":["execute_local_computation","write_local_artifact","federation_export"],"autonomy_tier":"A1","boundary":PRECLINICAL_BOUNDARY}

def evaluate_bioethics_composition(*, composition_id:str, federation_id:str, institution_id:str, semantic_profile:str, required_dependency_order:Sequence[str], comparability_digest:str, replay_identity:str, dependencies:Sequence[Mapping[str,Any]], policy_allow:bool, protected_closure:bool, signed_approval:bool, federation_approved:bool, raw_data_local:bool, aggregate_only:bool, adversarial_events:Sequence[str]=(), boundary:str=PRECLINICAL_BOUNDARY) -> BioethicsCompositionResult:
    if not all(value.strip() for value in (composition_id,federation_id,institution_id,semantic_profile)) or not required_dependency_order or not _canonical(required_dependency_order) or not dependencies or not _digest(comparability_digest) or not _digest(replay_identity) or not _canonical(adversarial_events) or not raw_data_local or not aggregate_only or boundary!=PRECLINICAL_BOUNDARY: raise ResearchContractError("composition identity, required closure, digests, locality, or boundary is invalid")
    rows=[dict(row) for row in dependencies]; seen:set[str]=set()
    for row in rows:
        dep_id=str(row.get("dependency_id",""))
        if not dep_id.strip() or dep_id in seen or not str(row.get("owning_crate","")).strip() or not str(row.get("version","")).strip() or not str(row.get("role","")).strip() or not row.get("study_order") or not _canonical(row["study_order"]) or not str(row.get("semantic_profile","")).strip() or not _digest(row.get("capability_digest")) or not _digest(row.get("provenance_digest")) or not _canonical(row.get("omissions",())) or not _canonical(row.get("conflicts",())): raise ResearchContractError(f"dependency {dep_id} is malformed or duplicated")
        seen.add(dep_id)
    rows.sort(key=lambda row:str(row["dependency_id"])); order=tuple(str(row["dependency_id"]) for row in rows); required=set(required_dependency_order); known=set(order); admitted:set[str]=set(); unresolved:set[str]=set(); blocked:set[str]=set(); missing=required-known; contradiction:set[str]=set(); omissions:set[str]=set(); uncertainty:set[str]=set(); negative:set[str]=set()
    for row in rows:
        dep_id=str(row["dependency_id"]); omissions.update(f"{dep_id}:{item}" for item in row.get("omissions",())); uncertainty.update(f"{dep_id}:{item}" for item in row.get("conflicts",())); state=str(row.get("evidence_state",""))
        if state=="contradicted": contradiction.add(dep_id); blocked.add(dep_id)
        elif not row.get("local_only") or not row.get("permitted") or not row.get("signed"):
            blocked.add(dep_id)
            if not row.get("local_only"): negative.add(f"{dep_id}:raw-data-not-local")
            if not row.get("permitted"): negative.add(f"{dep_id}:policy-denied")
            if not row.get("signed"): uncertainty.add(f"{dep_id}:unsigned-capability")
        elif str(row["semantic_profile"])!=semantic_profile or row.get("omissions") or row.get("conflicts") or state not in {"proven","supported"}: unresolved.add(dep_id)
        else: admitted.add(dep_id)
    for dep_id in missing: omissions.add(f"{dep_id}:required-dependency-missing")
    if not policy_allow: negative.add("request:policy-denied")
    if not protected_closure: uncertainty.add("request:protected-closure-incomplete")
    if not signed_approval: uncertainty.add("request:signed-approval-missing")
    if not federation_approved: uncertainty.add("request:federation-approval-missing")
    negative.update(f"adversarial:{event}" for event in adversarial_events); global_block=not policy_allow or not protected_closure or not signed_approval or not federation_approved or not raw_data_local or not aggregate_only or bool(adversarial_events)
    if global_block: blocked.update(order); admitted.clear(); unresolved.clear(); missing.clear(); omissions.add("request:composition-release-gate-blocked")
    disposition="blocked" if global_block else "unresolved" if not admitted or missing or not required.issubset(admitted) else "qualified"; ao,uo,bo,mo,co=tuple(sorted(admitted)),tuple(sorted(unresolved)),tuple(sorted(blocked)),tuple(sorted(missing)),tuple(sorted(contradiction)); oo,uu,nn=tuple(sorted(omissions)),tuple(sorted(uncertainty)),tuple(sorted(negative)); effects=(f"exchange:permitted-summaries:{composition_id}",f"manage:local-capability:{composition_id}") if disposition=="qualified" else ("block:unsafe-release",); payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"feature_id":FEATURE_ID,"composition_id":composition_id,"federation_id":federation_id,"institution_id":institution_id,"semantic_profile":semantic_profile,"disposition":disposition,"dependency_order":list(order),"admitted_order":list(ao),"unresolved_order":list(uo),"blocked_order":list(bo),"missing_dependency_order":list(mo),"contradiction_order":list(co),"omission_order":list(oo),"uncertainty_order":list(uu),"negative_evidence_order":list(nn),"replay_identity":replay_identity,"effect_receipts":list(effects),"raw_data_local":raw_data_local,"aggregate_only":aggregate_only,"boundary":PRECLINICAL_BOUNDARY}; digest=_hash(payload); artifact={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"artifact_id":f"bioethics-composition:{composition_id}","content_type":CONTENT_TYPE,"content_hash":digest,"semantic_loss":[],"provenance":[{"source_id":f"federation:{federation_id}","relation":"derived-from-dependency-attestations","digest":replay_identity}],"boundary":PRECLINICAL_BOUNDARY}; result=BioethicsCompositionResult(composition_id,federation_id,institution_id,semantic_profile,disposition,order,ao,uo,bo,mo,co,oo,uu,nn,replay_identity,digest,artifact,effects); result.validate(); return result

def bioethics_dependency_composition_digest(result:BioethicsCompositionResult)->str: result.validate(); return _hash(result.to_dict())
__all__=["FEATURE_ID","CONTRACT_VERSION","INPUT_SCHEMA","OUTPUT_SCHEMA","BioethicsCompositionResult","bioethics_dependency_composition_manifest","evaluate_bioethics_composition","bioethics_dependency_composition_digest"]
