"""Parity implementation for ``AFA-bioethics-P32-F26``."""
from __future__ import annotations
import hashlib, json, re
from typing import Any, Mapping
from .research_contracts import PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError

FEATURE_ID="AFA-bioethics-P32-F26"; CONTRACT_VERSION="bioethics-multimodal-bounded-evolution-assurance/1.0"; INPUT_SCHEMA="BioethicsEvolutionCandidate2@1"; OUTPUT_SCHEMA="BioethicsEvolutionDecision7@1"; CONTENT_TYPE="application/vnd.aurora.bioethics-evolution-decision-7+json"
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return v==sorted(set(v))
def multimodal_bounded_evolution_assurance_manifest()->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":FEATURE_ID,"version":CONTRACT_VERSION,"owner_crate":"bioethics","consumers":["release governance board","research governance specialist","verification engineer"],"behavior":"verify multimodal capability-evolution declarations with ethics, compatibility, benchmark, provenance, replay, policy, locality, and protected-closure gates without mutating a release","value":"prevents unsafe or ethically incomplete evolution claims from becoming an implementation or release decision","input_schema":INPUT_SCHEMA,"output_schema":OUTPUT_SCHEMA,"effects":["read:local-data","write:local-artifact"],"permissions":["evaluate:capability-runs"],"autonomy_tier":"A1","boundary":PRECLINICAL_BOUNDARY}
def validate_bioethics_evolution(output:Mapping[str,Any])->None:
 a=output.get("artifact",{}); keys=("candidate_order","approved_order","unresolved_order","blocked_order","unknown_order","incomparability_order","benchmark_failed_order","ethics_failed_order","omission_order","uncertainty_order","negative_evidence_order","effect_receipts")
 if output.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or output.get("contract_version")!=CONTRACT_VERSION or output.get("feature_id")!=FEATURE_ID or output.get("boundary")!=PRECLINICAL_BOUNDARY or a.get("boundary")!=PRECLINICAL_BOUNDARY or a.get("content_type")!=CONTENT_TYPE or output.get("raw_data_local") is not True or output.get("aggregate_only") is not True or output.get("disposition") not in {"qualified","unresolved","blocked","unknown"} or not output.get("candidate_order") or not output.get("effect_receipts"):raise ResearchContractError("evolution decision identity, locality, disposition, candidates, or effects are incomplete")
 if any(not _ordered(output.get(k,[])) for k in keys):raise ResearchContractError("evolution decision ordering is not canonical")
 ids=set(output["candidate_order"]); parts=output["approved_order"]+output["unresolved_order"]+output["blocked_order"]+output["unknown_order"]
 if len(ids)!=len(output["candidate_order"]) or len(parts)!=len(ids) or set(parts)!=ids:raise ResearchContractError("candidate dispositions do not partition")
 if not all(_digest(output.get(k)) for k in ("replay_identity","decision_digest")) or a.get("content_hash")!=output.get("decision_digest"):raise ResearchContractError("evolution digest is invalid")
def assure_multimodal_bounded_evolution(request:Mapping[str,Any])->dict[str,Any]:
 if request.get("schema_version")!=INPUT_SCHEMA or not request.get("request_id") or not request.get("candidates") or not request.get("required_study_order") or not request.get("required_modality_order") or not _digest(request.get("replay_identity")) or request.get("boundary")!=PRECLINICAL_BOUNDARY or request.get("raw_data_local") is not True or request.get("aggregate_only") is not True:raise ResearchContractError("evolution identity, study/modality closure, replay, locality, or boundary is invalid")
 cs=sorted((dict(c) for c in request["candidates"]),key=lambda c:c.get("candidate_id","")); ids=[c["candidate_id"] for c in cs]
 approved=set(); unresolved=set(); blocked=set(); unknown=set(); incomparability=set(); benchmark_failed=set(); ethics_failed=set(); omissions=set(); uncertainty=set(); negative=set()
 for c in cs:
  cid=c["candidate_id"]; missing_s=sorted(set(request["required_study_order"])-set(c.get("study_order",[]))); missing_m=sorted(set(request["required_modality_order"])-set(c.get("modality_order",[])))
  if c.get("negative_result"):negative.add(f"{cid}:negative-result")
  ethics=not c.get("privacy_reviewed") or not c.get("dual_use_reviewed") or not c.get("human_subject_free") or not c.get("policy_allowed") or not c.get("protected_closure") or not c.get("raw_data_local") or not c.get("aggregate_only") or c.get("semantic_profile")!=request["semantic_profile"] or not _digest(c.get("provenance_digest"))
  if ethics:blocked.add(cid); ethics_failed.add(cid); omissions.add(f"{cid}:ethics-policy-locality-blocked")
  elif c.get("from_version")!=request["current_version"] or not c.get("compatible") or missing_s or missing_m:unresolved.add(cid); incomparability.add(cid); omissions.update(f"{cid}:missing-study:{x}" for x in missing_s); omissions.update(f"{cid}:missing-modality:{x}" for x in missing_m)
  elif not c.get("benchmark_pass"):unresolved.add(cid); benchmark_failed.add(cid); negative.add(f"{cid}:benchmark-failed")
  elif c.get("evidence_state") in {"unknown","speculative"}:unknown.add(cid); uncertainty.add(f"{cid}:evidence-unresolved")
  elif c.get("evidence_state")=="contradicted":unknown.add(cid); negative.add(f"{cid}:contradicted-evidence")
  else:approved.add(cid)
 global_block=not all(request.get(k) is True for k in ("policy_allow","protected_closure","institutional_authorized","raw_data_local","aggregate_only"))
 if global_block:blocked.update(ids);approved.clear();unresolved.clear();unknown.clear();omissions.add("request:governance-or-locality-blocked")
 disp="blocked" if global_block or (blocked and not approved) else "unresolved" if unresolved or unknown or blocked else "qualified"; omissions.add("request:evolution-release-not-ready") if disp!="qualified" else None
 payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"feature_id":FEATURE_ID,"request_id":request["request_id"],"consumer":request.get("consumer",""),"purpose":request.get("purpose",""),"current_version":request["current_version"],"disposition":disp,"candidate_order":ids,"approved_order":sorted(approved),"unresolved_order":sorted(unresolved),"blocked_order":sorted(blocked),"unknown_order":sorted(unknown),"incomparability_order":sorted(incomparability),"benchmark_failed_order":sorted(benchmark_failed),"ethics_failed_order":sorted(ethics_failed),"omission_order":sorted(omissions),"uncertainty_order":sorted(uncertainty),"negative_evidence_order":sorted(negative),"replay_identity":request["replay_identity"],"raw_data_local":True,"aggregate_only":True,"boundary":PRECLINICAL_BOUNDARY}; d=_hash(payload); payload["decision_digest"]=d; payload["artifact"]={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"artifact_id":f"bioethics-evolution-decision:{request['request_id']}","content_type":CONTENT_TYPE,"content_hash":d,"semantic_loss":[],"provenance":[],"boundary":PRECLINICAL_BOUNDARY}; payload["effect_receipts"]=[f"observe:bounded-evolution:{request['request_id']}"] if disp=="qualified" else ["block:unsafe-release"]; validate_bioethics_evolution(payload); return payload
__all__=["FEATURE_ID","CONTRACT_VERSION","INPUT_SCHEMA","OUTPUT_SCHEMA","CONTENT_TYPE","multimodal_bounded_evolution_assurance_manifest","assure_multimodal_bounded_evolution","validate_bioethics_evolution"]
