"""Python parity for Bioethics P32 typed ethical-boundary cards."""
from __future__ import annotations
import hashlib,json,re
from typing import Any,Mapping
from .research_contracts import RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions";CONTENT_TYPE="application/vnd.aurora.bioethics.boundary-integrity-card-1+json"
EthicsClaim4=dict[str,Any];BoundaryIntegrityRequest4=dict[str,Any];BoundaryIntegrityCard7=dict[str,Any];BoundaryIntegrityArtifact4=dict[str,Any];BoundaryIntegrityError=ResearchContractError
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return isinstance(v,list) and v==sorted(set(v))
def manifest(*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"bioethics","consumers":["ethics steward","protocol gate","research operator","release board"],"behavior":f"qualify preclinical ethical boundaries at {scale} ({mode})","value":"prevents out-of-scope, under-reviewed, prohibited, or unresolved ethical claims from authorizing research workflows","input_schema":"BoundaryIntegrityRequest4@1","output_schema":"BoundaryIntegrityCard7@1","effects":["emit:boundary-card","retain:ethical-evidence","block:unsafe-boundary"],"permissions":["read:local-ethics-record"],"determinism":"byte_stable","autonomy_tier":"A1","boundary":BOUNDARY}
def validate(o:Mapping[str,Any],*,feature_id:str|None=None)->None:
 a=o.get("artifact",{});bad=o.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or(feature_id is not None and o.get("feature_id")!=feature_id)or not o.get("request_id")or not o.get("purpose")or o.get("boundary")!=BOUNDARY or a.get("boundary")!=BOUNDARY or o.get("raw_data_local") is not True or o.get("aggregate_only") is not True or not _digest(o.get("replay_identity")) or not _digest(o.get("closure_digest")) or a.get("content_type")!=CONTENT_TYPE or a.get("content_hash")!=o.get("closure_digest")
 if bad:raise ResearchContractError("boundary identity, locality, artifact, digest, or boundary is incomplete")
 for k in("claim_order","accepted_order","rejected_order","unknown_order","omitted_order","domain_order","reviewer_order","risk_order","prohibited_order","effect_receipts"):
  if not _ordered(o.get(k,[])):raise ResearchContractError("boundary vectors are not canonical")
 ids=set(o["claim_order"]);states=set(o["accepted_order"])|set(o["rejected_order"])|set(o["unknown_order"])|set(o["omitted_order"])
 if len(o["claim_order"])!=len(ids)or states!=ids:raise ResearchContractError("claim states do not partition")
def qualify(request:Mapping[str,Any],*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:
 if request.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or not request.get("request_id","").strip() or not request.get("purpose","").strip() or not request.get("claims") or not request.get("required_claim_order") or not _ordered(request["required_claim_order"]) or not _ordered(request.get("required_domain_order",[])) or not _ordered(request.get("reviewer_order",[])) or request.get("minimum_reviewer_quorum",0)<=0 or not _digest(request.get("replay_identity")) or request.get("boundary")!=BOUNDARY or request.get("raw_data_local") is not True or request.get("aggregate_only") is not True or not _ordered(request.get("adversarial_events",[])) or request.get("claim_budget",0)<=0:raise ResearchContractError("boundary identity, ordering, quorum, digest, locality, boundary, or budget is invalid")
 rows=sorted(request["claims"],key=lambda a:a.get("claim_id",""));seen=set();accepted=set();rejected=set();unknown=set();omitted=set();domains=set();reviewers=set();risks=set();prohibited=set();evidence=set()
 for i in rows:
  cid=i.get("claim_id","")
  if not cid.strip()or cid in seen or not i.get("domain","").strip()or not i.get("evidence_state","").strip()or not i.get("reviewer","").strip()or i.get("scope")!=BOUNDARY or i.get("risk_tier",99)>4 or i.get("local") is not True or i.get("aggregate_only") is not True:raise ResearchContractError("claim identity, domain, scope, risk, reviewer, evidence, or locality is invalid")
  seen.add(cid);domains.add(f"{cid}:{i['domain']}");reviewers.add(f"{cid}:{i['reviewer']}");risks.add(f"{cid}:{i['risk_tier']}");evidence.add(cid);prohibited.add(f"{cid}:prohibited") if i.get("prohibited") else None
  if i["evidence_state"]=="unknown"or i["reviewer"]=="unverified":unknown.add(cid)
  elif i.get("prohibited") or i.get("risk_tier",0)>=4:rejected.add(cid)
  elif cid not in request["required_claim_order"]:omitted.add(cid)
  else:accepted.add(cid)
 missing=[x for x in request["required_claim_order"] if x not in seen];global_block=not all(request.get(k) is True for k in("policy_allowed","protected_closure","signed_review","raw_data_local","aggregate_only"))or bool(request.get("adversarial_events"))or len(rows)>request["claim_budget"]or len(request["reviewer_order"])<request["minimum_reviewer_quorum"]
 if global_block:omitted.update(seen);accepted.clear();rejected.clear();unknown.clear()
 disposition="blocked" if global_block else "unknown" if missing or unknown else "partial" if rejected or omitted else "qualified";payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"request_id":request["request_id"],"purpose":request["purpose"],"disposition":disposition,"claim_order":sorted(seen),"accepted_order":sorted(accepted),"rejected_order":sorted(rejected),"unknown_order":sorted(unknown),"omitted_order":sorted(omitted),"domain_order":sorted(domains),"reviewer_order":sorted(reviewers),"risk_order":sorted(risks),"prohibited_order":sorted(prohibited),"replay_identity":request["replay_identity"],"raw_data_local":True,"aggregate_only":True,"boundary":BOUNDARY};d=_hash(payload);payload["closure_digest"]=d;payload["effect_receipts"]=[f"approve:boundary:{request['request_id']}"] if disposition=="qualified" else ["block:unsafe-boundary"];payload["artifact"]={"artifact_id":f"bioethics-boundary:{request['request_id']}","content_type":CONTENT_TYPE,"content_hash":d,"semantic_loss":payload["omitted_order"],"evidence_digests":sorted(evidence),"boundary":BOUNDARY};validate(payload,feature_id=feature_id);return payload
__all__=["BOUNDARY","CONTENT_TYPE","EthicsClaim4","BoundaryIntegrityRequest4","BoundaryIntegrityCard7","BoundaryIntegrityArtifact4","BoundaryIntegrityError","manifest","qualify","validate"]
