"""Python parity surface for ``AFA-bioethics-P25-F28``."""
from __future__ import annotations
from dataclasses import dataclass
import hashlib, json, re
from typing import Any, Mapping, Sequence
from .research_contracts import PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError

FEATURE_ID="AFA-bioethics-P25-F28"; CONTRACT_VERSION="bioethics-federated-continual-contract-frontier-assurance-harness/1.0"; INPUT_SCHEMA="BioethicsContractInput4@1"; OUTPUT_SCHEMA="BioethicsCapabilityManifest7@1"; CONTENT_TYPE="application/vnd.aurora.bioethics-capability-manifest-7+json"
def _digest(value:Any)->bool:return isinstance(value,str) and re.fullmatch(r"[0-9a-f]{64}",value) is not None
def _canonical(values:Sequence[str])->bool:return tuple(values)==tuple(sorted(set(values)))
def _hash(value:Any)->str:return hashlib.sha256(json.dumps(value,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()

@dataclass(frozen=True)
class BioethicsCapabilityManifestResult:
    request_id:str; federation_id:str; semantic_profile:str; disposition:str; capability_order:tuple[str,...]; selected_order:tuple[str,...]; unresolved_order:tuple[str,...]; blocked_order:tuple[str,...]; missing_capability_order:tuple[str,...]; omission_order:tuple[str,...]; uncertainty_order:tuple[str,...]; negative_evidence_order:tuple[str,...]; replay_identity:str; manifest_digest:str; artifact:dict[str,Any]; effect_receipts:tuple[str,...]; raw_data_local:bool=True; aggregate_only:bool=True; boundary:str=PRECLINICAL_BOUNDARY; schema_version:str=RESEARCH_CONTRACT_SCHEMA_VERSION; contract_version:str=CONTRACT_VERSION; feature_id:str=FEATURE_ID
    def to_dict(self)->dict[str,Any]:return {"schema_version":self.schema_version,"contract_version":self.contract_version,"feature_id":self.feature_id,"request_id":self.request_id,"federation_id":self.federation_id,"semantic_profile":self.semantic_profile,"disposition":self.disposition,"capability_order":list(self.capability_order),"selected_order":list(self.selected_order),"unresolved_order":list(self.unresolved_order),"blocked_order":list(self.blocked_order),"missing_capability_order":list(self.missing_capability_order),"omission_order":list(self.omission_order),"uncertainty_order":list(self.uncertainty_order),"negative_evidence_order":list(self.negative_evidence_order),"replay_identity":self.replay_identity,"manifest_digest":self.manifest_digest,"artifact":self.artifact,"effect_receipts":list(self.effect_receipts),"raw_data_local":self.raw_data_local,"aggregate_only":self.aggregate_only,"boundary":self.boundary}
    def validate(self)->None:
        if (self.schema_version,self.contract_version,self.feature_id)!=(RESEARCH_CONTRACT_SCHEMA_VERSION,CONTRACT_VERSION,FEATURE_ID) or self.boundary!=PRECLINICAL_BOUNDARY or self.artifact.get("boundary")!=PRECLINICAL_BOUNDARY or not self.raw_data_local or not self.aggregate_only or not all(v.strip() for v in (self.request_id,self.federation_id,self.semantic_profile)) or not self.capability_order or not self.effect_receipts or self.disposition not in {"qualified","unresolved","blocked"}:raise ResearchContractError("frontier identity, locality, capabilities, or effects are incomplete")
        for values in (self.capability_order,self.selected_order,self.unresolved_order,self.blocked_order,self.missing_capability_order,self.omission_order,self.uncertainty_order,self.negative_evidence_order,self.effect_receipts):
            if not _canonical(values):raise ResearchContractError("frontier ordering is not canonical")
        parts=[*self.selected_order,*self.unresolved_order,*self.blocked_order]
        if set(parts)!=set(self.capability_order) or len(parts)!=len(set(parts)):raise ResearchContractError("frontier states do not partition capabilities")
        if not all(_digest(v) for v in (self.replay_identity,self.manifest_digest,self.artifact.get("content_hash"))):raise ResearchContractError("frontier digest is invalid")
        if self.artifact.get("content_type")!=CONTENT_TYPE:raise ResearchContractError("frontier artifact type is invalid")
        if self.disposition=="qualified" and self.effect_receipts!=(f"verify:bioethics-capability-frontier:{self.request_id}",):raise ResearchContractError("qualified frontier effect is invalid")
        if self.disposition!="qualified" and self.effect_receipts!=("block:unsafe-release",):raise ResearchContractError("non-qualified frontier must block release")

def contract_frontier_assurance_manifest()->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":FEATURE_ID,"version":CONTRACT_VERSION,"owner_crate":"bioethics","consumers":["consortium operator","bioethicist","downstream research workflow"],"behavior":"verifies a versioned bioethics capability frontier under explicit evidence, compatibility, provenance, policy, and federation gates without inferring ethics or executing research","value":"prevents revoked, semantically drifting, unsigned, or incomplete capability declarations from silently entering a federated preclinical workflow","input_schema":INPUT_SCHEMA,"output_schema":OUTPUT_SCHEMA,"effects":["execute_local_computation","write_local_artifact","federation_export"],"autonomy_tier":"A1","boundary":PRECLINICAL_BOUNDARY}

def assure_contract_frontier(*,request_id:str,federation_id:str,semantic_profile:str,required_capability_order:Sequence[str],replay_identity:str,descriptors:Sequence[Mapping[str,Any]],policy_allow:bool,protected_closure:bool,signed_approval:bool,federation_approved:bool,raw_data_local:bool,aggregate_only:bool,adversarial_events:Sequence[str]=(),boundary:str=PRECLINICAL_BOUNDARY)->BioethicsCapabilityManifestResult:
    if not all(v.strip() for v in (request_id,federation_id,semantic_profile)) or not required_capability_order or not _canonical(required_capability_order) or not descriptors or not _digest(replay_identity) or not _canonical(adversarial_events) or not raw_data_local or not aggregate_only or boundary!=PRECLINICAL_BOUNDARY:raise ResearchContractError("contract input identity, closure, replay, locality, or boundary is invalid")
    rows=[dict(x) for x in descriptors];seen:set[str]=set()
    for row in rows:
        cid=str(row.get("capability_id",""))
        if not cid.strip() or cid in seen or not str(row.get("version","")).strip() or not str(row.get("input_schema","")).strip() or not str(row.get("output_schema","")).strip() or not str(row.get("semantic_profile","")).strip() or not row.get("surface_order") or not _canonical(row["surface_order"]) or not _canonical(row.get("permission_order",())) or not _digest(row.get("capability_digest")) or not _digest(row.get("provenance_digest")) or not _digest(row.get("replay_identity")) or not _canonical(row.get("omissions",())) or not _canonical(row.get("uncertainty",())):raise ResearchContractError(f"capability {cid} is malformed or duplicated")
        seen.add(cid)
    rows.sort(key=lambda x:str(x["capability_id"])); order=tuple(str(x["capability_id"]) for x in rows); required=set(required_capability_order); selected:set[str]=set();unresolved:set[str]=set();blocked:set[str]=set();missing=required-set(order);omissions:set[str]=set();uncertainty:set[str]=set();negative:set[str]=set()
    for row in rows:
        cid=str(row["capability_id"]); state=str(row.get("evidence_state","")); omissions.update(f"{cid}:{v}" for v in row.get("omissions",())); uncertainty.update(f"{cid}:{v}" for v in row.get("uncertainty",()))
        if row.get("revoked") or not row.get("local_only") or not row.get("permitted") or not row.get("approved"): blocked.add(cid); negative.update({f"{cid}:revoked"} if row.get("revoked") else set()); uncertainty.update({f"{cid}:approval-missing"} if not row.get("approved") else set())
        elif str(row["semantic_profile"])!=semantic_profile or str(row.get("replay_identity"))!=replay_identity or row.get("omissions") or row.get("uncertainty") or state not in {"proven","supported"}: unresolved.add(cid); uncertainty.update({f"{cid}:replay-mismatch"} if str(row.get("replay_identity"))!=replay_identity else set())
        else:selected.add(cid)
    for cid in missing:omissions.add(f"{cid}:required-capability-missing")
    if not policy_allow:negative.add("request:policy-denied")
    if not protected_closure:uncertainty.add("request:protected-closure-incomplete")
    if not signed_approval:uncertainty.add("request:signed-approval-missing")
    if not federation_approved:uncertainty.add("request:federation-approval-missing")
    negative.update(f"adversarial:{event}" for event in adversarial_events);global_block=not policy_allow or not protected_closure or not signed_approval or not federation_approved or not raw_data_local or not aggregate_only or bool(adversarial_events)
    if global_block:blocked.update(order);selected.clear();unresolved.clear();missing.clear();omissions.add("request:frontier-release-gate-blocked")
    disposition="blocked" if global_block else "qualified" if required.issubset(selected) and not unresolved and not blocked else "unresolved";so,uo,bo,mo=tuple(sorted(selected)),tuple(sorted(unresolved)),tuple(sorted(blocked)),tuple(sorted(missing));oo,uu,nn=tuple(sorted(omissions)),tuple(sorted(uncertainty)),tuple(sorted(negative));effects=(f"verify:bioethics-capability-frontier:{request_id}",) if disposition=="qualified" else ("block:unsafe-release",);payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"feature_id":FEATURE_ID,"request_id":request_id,"federation_id":federation_id,"semantic_profile":semantic_profile,"disposition":disposition,"capability_order":list(order),"selected_order":list(so),"unresolved_order":list(uo),"blocked_order":list(bo),"missing_capability_order":list(mo),"omission_order":list(oo),"uncertainty_order":list(uu),"negative_evidence_order":list(nn),"replay_identity":replay_identity,"effect_receipts":list(effects),"raw_data_local":raw_data_local,"aggregate_only":aggregate_only,"boundary":PRECLINICAL_BOUNDARY};digest=_hash(payload);artifact={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"artifact_id":f"bioethics-capability-frontier:{request_id}","content_type":CONTENT_TYPE,"content_hash":digest,"semantic_loss":[],"provenance":[],"boundary":PRECLINICAL_BOUNDARY};result=BioethicsCapabilityManifestResult(request_id,federation_id,semantic_profile,disposition,order,so,uo,bo,mo,oo,uu,nn,replay_identity,digest,artifact,effects);result.validate();return result
def bioethicsContractFrontierDigest(result:BioethicsCapabilityManifestResult)->str:result.validate();return _hash(result.to_dict())
__all__=["FEATURE_ID","CONTRACT_VERSION","INPUT_SCHEMA","OUTPUT_SCHEMA","BioethicsCapabilityManifestResult","contract_frontier_assurance_manifest","assure_contract_frontier","bioethicsContractFrontierDigest"]
