"""Python parity surface for ``AFA-bioir-P11-F30``."""
from __future__ import annotations
from dataclasses import dataclass
import hashlib,json,re
from typing import Any,Mapping,Sequence
from .research_contracts import PRECLINICAL_BOUNDARY,RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
FEATURE_ID="AFA-bioir-P11-F30";CONTRACT_VERSION="bioir-multimodal-laboratory-integration-control-plane/1.0";INPUT_SCHEMA="InstrumentActionRequest2@1";OUTPUT_SCHEMA="InstrumentActionReceipt8@1";CONTENT_TYPE="application/vnd.aurora.instrument-action-receipt-8+json"
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _canonical(v:Sequence[str])->bool:return tuple(v)==tuple(sorted(set(v)))
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
@dataclass(frozen=True)
class BioirInstrumentActionReceipt:
 request_id:str;federation_id:str;operation:str;decision:str;candidate_order:tuple[str,...];selected_instrument_id:str|None;selected_site_id:str|None;selected_protocol_profile:str|None;satisfied_capability_order:tuple[str,...];missing_capability_order:tuple[str,...];missing_interlock_order:tuple[str,...];preflight_order:tuple[str,...];omissions:tuple[str,...];uncertainty:tuple[str,...];negative_evidence:tuple[str,...];replay_identity:str;receipt_digest:str;artifact:dict[str,Any];effect_receipts:tuple[str,...];executed:bool=False;raw_data_local:bool=True;aggregate_only:bool=True;boundary:str=PRECLINICAL_BOUNDARY;schema_version:str=RESEARCH_CONTRACT_SCHEMA_VERSION;contract_version:str=CONTRACT_VERSION;feature_id:str=FEATURE_ID
 def to_dict(self)->dict[str,Any]:return {"schema_version":self.schema_version,"contract_version":self.contract_version,"feature_id":self.feature_id,"request_id":self.request_id,"federation_id":self.federation_id,"operation":self.operation,"decision":self.decision,"candidate_order":list(self.candidate_order),"selected_instrument_id":self.selected_instrument_id,"selected_site_id":self.selected_site_id,"selected_protocol_profile":self.selected_protocol_profile,"satisfied_capability_order":list(self.satisfied_capability_order),"missing_capability_order":list(self.missing_capability_order),"missing_interlock_order":list(self.missing_interlock_order),"preflight_order":list(self.preflight_order),"omissions":list(self.omissions),"uncertainty":list(self.uncertainty),"negative_evidence":list(self.negative_evidence),"replay_identity":self.replay_identity,"receipt_digest":self.receipt_digest,"artifact":self.artifact,"effect_receipts":list(self.effect_receipts),"executed":self.executed,"raw_data_local":self.raw_data_local,"aggregate_only":self.aggregate_only,"boundary":self.boundary}
 def validate(self)->None:
  if (self.schema_version,self.contract_version,self.feature_id)!=(RESEARCH_CONTRACT_SCHEMA_VERSION,CONTRACT_VERSION,FEATURE_ID) or self.boundary!=PRECLINICAL_BOUNDARY or self.artifact.get("boundary")!=PRECLINICAL_BOUNDARY or not self.raw_data_local or not self.aggregate_only or self.executed or not all(v.strip() for v in (self.request_id,self.federation_id,self.operation)) or self.decision not in {"qualified","unresolved","blocked"} or not self.candidate_order or not self.preflight_order or not self.effect_receipts:raise ResearchContractError("instrument receipt identity, non-execution, locality, preflight, or effects are incomplete")
  for vals in (self.candidate_order,self.satisfied_capability_order,self.missing_capability_order,self.missing_interlock_order,self.preflight_order,self.omissions,self.uncertainty,self.negative_evidence,self.effect_receipts):
   if not _canonical(vals):raise ResearchContractError("instrument receipt ordering is not canonical")
  for v in (self.replay_identity,self.receipt_digest,self.artifact.get("content_hash")):
   if not _digest(v):raise ResearchContractError("instrument receipt digest is invalid")
  if self.artifact.get("content_type")!=CONTENT_TYPE:raise ResearchContractError("instrument receipt artifact type is invalid")
  if self.decision=="qualified" and (self.selected_instrument_id is None or self.selected_site_id is None or self.effect_receipts!=(f"exchange:permitted-summaries:{self.request_id}",f"manage:local-capability:{self.request_id}")):raise ResearchContractError("qualified instrument effects or selection are invalid")
  if self.decision!="qualified" and self.effect_receipts!=("block:unsafe-release",):raise ResearchContractError("non-qualified instrument receipt must block release")
def preflight_instrument_action(*,request_id:str,federation_id:str,operation:str,required_capability_order:Sequence[str],required_interlock_order:Sequence[str],target_instrument_id:str|None,semantic_profile:str,study_order:Sequence[str],modality_order:Sequence[str],capabilities:Sequence[Mapping[str,Any]],replay_identity:str,policy_allow:bool,protected_closure:bool,signed_approval:bool,federation_approved:bool,network_available:bool,raw_data_local:bool,aggregate_only:bool,budget:int,max_budget:int,adversarial_events:Sequence[str]=(),boundary:str=PRECLINICAL_BOUNDARY)->BioirInstrumentActionReceipt:
 if not all(v.strip() for v in (request_id,federation_id,operation,semantic_profile)) or not required_capability_order or not required_interlock_order or not study_order or not modality_order or not capabilities or not _canonical(required_capability_order) or not _canonical(required_interlock_order) or not _canonical(study_order) or not _canonical(modality_order) or not _canonical(adversarial_events) or not _digest(replay_identity) or budget<=0 or max_budget<=0 or boundary!=PRECLINICAL_BOUNDARY or not raw_data_local or not aggregate_only:raise ResearchContractError("instrument request identity, closure, digest, budget, locality, or boundary is invalid")
 rows=[dict(x) for x in capabilities];seen:set[str]=set()
 for row in rows:
  cid=f"{row.get('instrument_id','')}@{row.get('site_id','')}"
  if not str(row.get("instrument_id","")).strip() or not str(row.get("site_id","")).strip() or not str(row.get("protocol_profile","")).strip() or not row.get("supported_operation_order") or not _canonical(row["supported_operation_order"]) or not _canonical(row.get("interlock_order",())) or not str(row.get("semantic_profile","")).strip() or not _digest(row.get("calibration_digest")) or not _digest(row.get("provenance_digest")) or not _digest(row.get("replay_identity")) or cid in seen:raise ResearchContractError(f"instrument capability {cid} is malformed or duplicated")
  seen.add(cid)
 rows.sort(key=lambda x:(str(x["instrument_id"]),str(x["site_id"])));order=tuple(f"{x['instrument_id']}@{x['site_id']}" for x in rows);required_caps=set(required_capability_order);required_interlocks=set(required_interlock_order);match=next((x for x in rows if (target_instrument_id is None or target_instrument_id==x["instrument_id"]) and x["semantic_profile"]==semantic_profile and operation in x["supported_operation_order"] and required_caps<=set(x["supported_operation_order"]) and required_interlocks<=set(x.get("interlock_order",())) and x.get("permitted") and x.get("raw_data_local")),None);selected_id=match.get("instrument_id") if match else None;selected_site=match.get("site_id") if match else None;selected_profile=match.get("protocol_profile") if match else None;satisfied=tuple(required_capability_order) if match else ();missing_caps=tuple(sorted(x for x in required_capability_order if not match or x not in match["supported_operation_order"]));missing_interlocks=tuple(sorted(x for x in required_interlock_order if not match or x not in match.get("interlock_order",())));omissions:set[str]=set();uncertainty:set[str]=set();negative:set[str]=set()
 if not match:omissions.add("instrument:capability-or-interlock-match-missing");uncertainty.add("instrument:visible-capability-absence-is-not-impossibility")
 if not policy_allow:negative.add("request:policy-denied")
 if not protected_closure:uncertainty.add("request:protected-closure-incomplete")
 if not signed_approval:uncertainty.add("request:signed-approval-missing")
 if not federation_approved:uncertainty.add("request:federation-approval-missing")
 if not network_available:negative.add("request:network-unavailable")
 if budget>max_budget:omissions.add("request:budget-ceiling-exceeded")
 negative.update(f"adversarial:{x}" for x in adversarial_events);global_block=not policy_allow or not protected_closure or not signed_approval or not federation_approved or not network_available or not raw_data_local or not aggregate_only or budget>max_budget or bool(adversarial_events);decision="blocked" if global_block else ("qualified" if match else "unresolved");preflight=tuple(sorted(("calibration-and-provenance-digests-bound","capability-manifest-verified","hardware-execution-explicitly-not-performed","operation-and-interlock-closure-verified","policy-authority-federation-gates-evaluated")));effects=(f"exchange:permitted-summaries:{request_id}",f"manage:local-capability:{request_id}") if decision=="qualified" else ("block:unsafe-release",)
 payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"feature_id":FEATURE_ID,"request_id":request_id,"federation_id":federation_id,"operation":operation,"decision":decision,"candidate_order":list(order),"selected_instrument_id":selected_id,"selected_site_id":selected_site,"selected_protocol_profile":selected_profile,"satisfied_capability_order":list(satisfied),"missing_capability_order":list(missing_caps),"missing_interlock_order":list(missing_interlocks),"preflight_order":list(preflight),"omissions":sorted(omissions),"uncertainty":sorted(uncertainty),"negative_evidence":sorted(negative),"replay_identity":replay_identity,"effect_receipts":list(effects),"executed":False,"raw_data_local":True,"aggregate_only":True,"boundary":PRECLINICAL_BOUNDARY};d=_hash(payload);artifact={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"artifact_id":f"bioir-instrument-action:{request_id}","content_type":CONTENT_TYPE,"content_hash":d,"semantic_loss":[],"provenance":[],"boundary":PRECLINICAL_BOUNDARY};result=BioirInstrumentActionReceipt(request_id,federation_id,operation,decision,order,selected_id,selected_site,selected_profile,satisfied,missing_caps,missing_interlocks,preflight,tuple(sorted(omissions)),tuple(sorted(uncertainty)),tuple(sorted(negative)),replay_identity,d,artifact,effects);result.validate();return result
def bioir_laboratory_control_digest(result:BioirInstrumentActionReceipt)->str:result.validate();return _hash(result.to_dict())
__all__=["FEATURE_ID","CONTRACT_VERSION","INPUT_SCHEMA","OUTPUT_SCHEMA","BioirInstrumentActionReceipt","preflight_instrument_action","bioir_laboratory_control_digest"]
