"""Federated continual knowledge-representation parity contract."""
from __future__ import annotations
from dataclasses import dataclass
import re
from typing import Any, Mapping, Sequence
from .research_contracts import FEDERATED_CONTINUAL_KNOWLEDGE_REPRESENTATION_INFERENCE_ENGINE_CONTRACT_VERSION, FEDERATED_CONTINUAL_KNOWLEDGE_REPRESENTATION_INFERENCE_ENGINE_FEATURE_ID, PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError, research_artifact_digest

@dataclass(frozen=True)
class FederatedKnowledgePeer:
    peer_id:str; institution_id:str; claims_digest:str; world_digest:str; evidence_digest:str|None; provenance_digest:str|None; replay_identity:str; semantic_profile:str="profile:v1"; fresh:bool=True; comparable:bool=True; permitted_summary:bool=True; signed_approval:bool=True; policy_allow:bool=True; state:str="supported"; raw_data_local:bool=True; boundary:str=PRECLINICAL_BOUNDARY

@dataclass(frozen=True)
class FederatedKnowledgeReceipt:
    request_id:str; federation_id:str; disposition:str; candidate_order:tuple[str,...]; qualified_order:tuple[str,...]; unresolved_order:tuple[str,...]; denied_order:tuple[str,...]; exchange_order:tuple[str,...]; semantic_profile_order:tuple[str,...]; freshness_order:tuple[str,...]; quorum_required:int; quorum_met:bool; run_digest:str; evidence_digest:str; provenance_digest:str; replay_identity:str; witness_order:tuple[str,...]; counterexample_order:tuple[str,...]; omissions:tuple[str,...]; uncertainty:tuple[str,...]; negative_evidence:tuple[str,...]; effect_receipts:tuple[str,...]; artifact:Mapping[str,Any]; feature_id:str=FEDERATED_CONTINUAL_KNOWLEDGE_REPRESENTATION_INFERENCE_ENGINE_FEATURE_ID; contract_version:str=FEDERATED_CONTINUAL_KNOWLEDGE_REPRESENTATION_INFERENCE_ENGINE_CONTRACT_VERSION; schema_version:str=RESEARCH_CONTRACT_SCHEMA_VERSION; raw_data_local:bool=True; boundary:str=PRECLINICAL_BOUNDARY
    def validate(self)->None:
        if self.schema_version!=RESEARCH_CONTRACT_SCHEMA_VERSION or self.contract_version!=FEDERATED_CONTINUAL_KNOWLEDGE_REPRESENTATION_INFERENCE_ENGINE_CONTRACT_VERSION or self.feature_id!=FEDERATED_CONTINUAL_KNOWLEDGE_REPRESENTATION_INFERENCE_ENGINE_FEATURE_ID: raise ResearchContractError("federated knowledge schema mismatch")
        if self.boundary!=PRECLINICAL_BOUNDARY or not self.raw_data_local or not self.request_id.strip() or not self.federation_id.strip() or not self.candidate_order or self.quorum_required<=0 or not self.effect_receipts: raise ResearchContractError("federated knowledge identity, quorum, locality, or effects are incomplete")
        for values in (self.candidate_order,self.qualified_order,self.unresolved_order,self.denied_order,self.semantic_profile_order,self.freshness_order,self.witness_order,self.counterexample_order,self.omissions,self.uncertainty,self.negative_evidence,self.effect_receipts):
            if tuple(sorted(set(values)))!=values: raise ResearchContractError("federated knowledge ordering is not canonical")
        if tuple(sorted(set(self.exchange_order)))!=self.exchange_order: raise ResearchContractError("federated knowledge exchange ordering is not canonical")
        classified=set(self.qualified_order)|set(self.unresolved_order)|set(self.denied_order)
        if classified!=set(self.candidate_order): raise ResearchContractError("federated knowledge states do not partition peers")
        if len(self.exchange_order)!=len(self.qualified_order): raise ResearchContractError("federated knowledge exchange mismatch")
        for value in (*self.exchange_order,self.run_digest,self.evidence_digest,self.provenance_digest,self.replay_identity,self.artifact.get("content_hash")):
            if not isinstance(value,str) or not re.fullmatch(r"[0-9a-f]{64}",value): raise ResearchContractError("federated knowledge digest invalid")
        if any(not e.startswith("read:local-federated-knowledge:") and e!="block:unsafe-release" for e in self.effect_receipts): raise ResearchContractError("federated knowledge effect invalid")
    def digest(self)->str:
        self.validate(); return research_artifact_digest({"schema_version":self.schema_version,"contract_version":self.contract_version,"feature_id":self.feature_id,"request_id":self.request_id,"federation_id":self.federation_id,"disposition":self.disposition,"candidate_order":list(self.candidate_order),"qualified_order":list(self.qualified_order),"unresolved_order":list(self.unresolved_order),"denied_order":list(self.denied_order),"exchange_order":list(self.exchange_order),"semantic_profile_order":list(self.semantic_profile_order),"freshness_order":list(self.freshness_order),"quorum_required":self.quorum_required,"quorum_met":self.quorum_met,"run_digest":self.run_digest,"evidence_digest":self.evidence_digest,"provenance_digest":self.provenance_digest,"replay_identity":self.replay_identity,"witness_order":list(self.witness_order),"counterexample_order":list(self.counterexample_order),"omissions":list(self.omissions),"uncertainty":list(self.uncertainty),"negative_evidence":list(self.negative_evidence),"effect_receipts":list(self.effect_receipts),"artifact":dict(self.artifact),"raw_data_local":self.raw_data_local,"boundary":self.boundary})

def infer_federated_continual_knowledge_representation(*,request_id:str,federation_id:str,peers:Sequence[FederatedKnowledgePeer],min_quorum:int,replay_identity:str,policy_allow:bool=True,protected_closure:bool=True,raw_data_local:bool=True,signed_approval:bool=True)->FederatedKnowledgeReceipt:
    if not request_id.strip() or not federation_id.strip() or not peers or min_quorum<=0 or min_quorum>len(peers) or not re.fullmatch(r"[0-9a-f]{64}",replay_identity) or not raw_data_local: raise ResearchContractError("federated knowledge identity, peer set, quorum, replay, or locality is invalid")
    ordered=tuple(sorted(p.peer_id for p in peers))
    if len(set(ordered))!=len(peers) or any(not v.strip() for v in ordered): raise ResearchContractError("federated peer identifiers must be unique and non-empty")
    pmap={p.peer_id:p for p in peers}; qualified:set[str]=set(); unresolved:set[str]=set(); denied:set[str]=set(); exchange:list[str]=[]; profiles:set[str]=set(); fresh:set[str]=set(); witnesses={"gate:typed-federated-knowledge","gate:freshness","gate:semantic-comparability","gate:quorum","gate:replay-identity","gate:purpose-bound-summary","gate:locality"}; counter:set[str]=set(); omissions:set[str]=set(); uncertainty:set[str]=set(); negative:set[str]=set(); global_open=policy_allow and protected_closure and raw_data_local and signed_approval
    for pid in ordered:
        p=pmap[pid]
        if not global_open or not p.policy_allow or not p.signed_approval or not p.permitted_summary or not p.raw_data_local or p.boundary!=PRECLINICAL_BOUNDARY: denied.add(pid); counter.add(f"counterexample:{pid}:policy-approval-purpose-locality")
        elif not p.fresh: unresolved.add(pid); omissions.add(f"peer:{pid}:stale-knowledge")
        elif not p.comparable or not p.semantic_profile.strip(): denied.add(pid); counter.add(f"counterexample:{pid}:semantic-profile-mismatch")
        elif p.replay_identity!=replay_identity: unresolved.add(pid); uncertainty.add(f"peer:{pid}:replay-mismatch")
        elif p.evidence_digest is None or p.provenance_digest is None: unresolved.add(pid); omissions.add(f"peer:{pid}:evidence-or-provenance-missing")
        elif p.state in {"unknown","speculative"}: unresolved.add(pid); uncertainty.add(f"peer:{pid}:unknown-not-asserted")
        elif p.state=="contradicted": denied.add(pid); negative.add(f"peer:{pid}:contradicted")
        else: qualified.add(pid); profiles.add(p.semantic_profile); fresh.add(pid); exchange.append(research_artifact_digest({"peer_id":p.peer_id,"institution_id":p.institution_id,"claims_digest":p.claims_digest,"world_digest":p.world_digest,"evidence_digest":p.evidence_digest,"provenance_digest":p.provenance_digest,"semantic_profile":p.semantic_profile,"replay_identity":p.replay_identity}))
    quorum_met=len(qualified)>=min_quorum
    if not quorum_met: omissions.add("federation:quorum-incomplete"); uncertainty.add(f"quorum:required-{min_quorum}:observed-{len(qualified)}")
    if not policy_allow: counter.add("counterexample:policy-denied"); omissions.add("control:policy-denied")
    if not protected_closure: counter.add("counterexample:protected-closure-incomplete"); omissions.add("control:protected-closure-incomplete")
    if unresolved: witnesses.add("gate:partial-peer-results-retained")
    exchange_order=tuple(sorted(exchange)); disposition="denied" if not global_open or denied else "unresolved" if not quorum_met else "partial" if unresolved else "completed"; evidence=research_artifact_digest({"candidate_order":list(ordered),"qualified_order":sorted(qualified),"unresolved_order":sorted(unresolved),"denied_order":sorted(denied)}); provenance=research_artifact_digest({"federation_id":federation_id,"exchange_order":list(exchange_order),"replay_identity":replay_identity}); run=research_artifact_digest({"feature_id":FEDERATED_CONTINUAL_KNOWLEDGE_REPRESENTATION_INFERENCE_ENGINE_FEATURE_ID,"request_id":request_id,"disposition":disposition,"qualified_order":sorted(qualified),"unresolved_order":sorted(unresolved),"denied_order":sorted(denied),"quorum_met":quorum_met,"evidence_digest":evidence,"provenance_digest":provenance,"replay_identity":replay_identity}); artifact={"content_hash":research_artifact_digest({"request_id":request_id,"run_digest":run}),"media_type":"application/vnd.aurora.federated-continual-knowledge-world+json"}; receipt=FederatedKnowledgeReceipt(request_id=request_id,federation_id=federation_id,disposition=disposition,candidate_order=ordered,qualified_order=tuple(sorted(qualified)),unresolved_order=tuple(sorted(unresolved)),denied_order=tuple(sorted(denied)),exchange_order=exchange_order,semantic_profile_order=tuple(sorted(profiles)),freshness_order=tuple(sorted(fresh)),quorum_required=min_quorum,quorum_met=quorum_met,run_digest=run,evidence_digest=evidence,provenance_digest=provenance,replay_identity=replay_identity,witness_order=tuple(sorted(witnesses)),counterexample_order=tuple(sorted(counter)),omissions=tuple(sorted(omissions)),uncertainty=tuple(sorted(uncertainty)),negative_evidence=tuple(sorted(negative)),effect_receipts=(f"read:local-federated-knowledge:{request_id}",) if disposition=="completed" else ("block:unsafe-release",),artifact=artifact,raw_data_local=raw_data_local); receipt.validate(); return receipt
