"""Python parity contract for the federated researcher workbench."""
from __future__ import annotations
from dataclasses import dataclass
import re
from typing import Any, Mapping
from .research_contracts import PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError, research_artifact_digest
FEDERATED_RESEARCH_WORKBENCH_FEATURE_ID = "AFA-brain-P01-F20"
FEDERATED_RESEARCH_WORKBENCH_CONTRACT_VERSION = "brain-federated-research-workbench/1.0"
@dataclass(frozen=True)
class BrainFederatedResearchWorkbenchReceipt:
    request_id: str; workspace_id: str; federation_id: str; institution_id: str; purpose: str; endpoint: str; disposition: str; view_order: tuple[str,...]; panel_order: tuple[str,...]; action_receipts: tuple[str,...]; candidate_order: tuple[str,...]; admitted_order: tuple[str,...]; blocked_order: tuple[str,...]; unknown_order: tuple[str,...]; aggregate_order: tuple[str,...]; evidence_digest: str; envelope_digest: str; workbench_digest: str; replay_identity: str; budget_units: int; omissions: tuple[str,...]; uncertainty: tuple[str,...]; negative_evidence: tuple[str,...]; effect_receipts: tuple[str,...]; artifact: Mapping[str,Any]; feature_id: str = FEDERATED_RESEARCH_WORKBENCH_FEATURE_ID; contract_version: str = FEDERATED_RESEARCH_WORKBENCH_CONTRACT_VERSION; schema_version: str = RESEARCH_CONTRACT_SCHEMA_VERSION; raw_data_local: bool = True; boundary: str = PRECLINICAL_BOUNDARY
    def validate(self) -> None:
        if self.schema_version != RESEARCH_CONTRACT_SCHEMA_VERSION or self.feature_id != FEDERATED_RESEARCH_WORKBENCH_FEATURE_ID or self.contract_version != FEDERATED_RESEARCH_WORKBENCH_CONTRACT_VERSION: raise ResearchContractError("federated workbench schema, feature, or version mismatch")
        if self.boundary != PRECLINICAL_BOUNDARY or not self.raw_data_local or not self.request_id.strip() or not self.workspace_id.strip() or not self.federation_id.strip() or not self.institution_id.strip() or not self.purpose.strip() or not self.endpoint.strip() or not self.view_order or not self.panel_order or not self.action_receipts or not self.candidate_order or not self.effect_receipts or self.budget_units <= 0: raise ResearchContractError("federated workbench identity, views, evidence, locality, budget, or effects are incomplete")
        if any(v not in self.candidate_order for v in (*self.admitted_order,*self.blocked_order,*self.unknown_order)): raise ResearchContractError("federated workbench state is not covered by candidates")
        for values in (self.view_order,self.panel_order,self.action_receipts,self.candidate_order,self.admitted_order,self.blocked_order,self.unknown_order,self.aggregate_order,self.omissions,self.uncertainty,self.negative_evidence,self.effect_receipts):
            if tuple(sorted(set(values))) != values: raise ResearchContractError("federated workbench ordering is invalid")
        for value in (self.evidence_digest,self.envelope_digest,self.workbench_digest,self.replay_identity,self.artifact.get("content_hash")):
            if not isinstance(value,str) or not re.fullmatch(r"[0-9a-f]{64}",value): raise ResearchContractError("federated workbench digest is invalid")
        if any(not e.startswith("view:local-federated-artifacts:") and e != "block:unsafe-release" for e in self.effect_receipts): raise ResearchContractError("federated workbench effect is not read-only")
    def digest(self) -> str:
        self.validate(); return research_artifact_digest({"schema_version":self.schema_version,"contract_version":self.contract_version,"feature_id":self.feature_id,"request_id":self.request_id,"workspace_id":self.workspace_id,"federation_id":self.federation_id,"institution_id":self.institution_id,"purpose":self.purpose,"endpoint":self.endpoint,"disposition":self.disposition,"view_order":list(self.view_order),"panel_order":list(self.panel_order),"action_receipts":list(self.action_receipts),"candidate_order":list(self.candidate_order),"admitted_order":list(self.admitted_order),"blocked_order":list(self.blocked_order),"unknown_order":list(self.unknown_order),"aggregate_order":list(self.aggregate_order),"evidence_digest":self.evidence_digest,"envelope_digest":self.envelope_digest,"workbench_digest":self.workbench_digest,"replay_identity":self.replay_identity,"budget_units":self.budget_units,"omissions":list(self.omissions),"uncertainty":list(self.uncertainty),"negative_evidence":list(self.negative_evidence),"effect_receipts":list(self.effect_receipts),"artifact":dict(self.artifact),"raw_data_local":self.raw_data_local,"boundary":self.boundary})
