"""High-throughput context protocol parity contract."""
from __future__ import annotations
from dataclasses import dataclass
import re
from typing import Any, Mapping, Sequence
from .research_contracts import THROUGHPUT_CONTEXT_PROTOCOL_ADAPTER_CONTRACT_VERSION, THROUGHPUT_CONTEXT_PROTOCOL_ADAPTER_FEATURE_ID, PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError, research_artifact_digest

PROTOCOL_VERSION = "aurora-research-context-throughput/1.0"; ROUTE = "/v1/research/context/throughput/compile"; METHOD = "POST"; RESPONSE_SCHEMA = "ThroughputContextProtocolResponse1@1"

@dataclass(frozen=True)
class ThroughputContextProtocolJob:
    job_id: str; context_digest: str; section_digest: str; replay_identity: str; state: str = "supported"; ready: bool = True; cost_units: int = 1; raw_data_local: bool = True; boundary: str = PRECLINICAL_BOUNDARY

@dataclass(frozen=True)
class ThroughputContextProtocolReceipt:
    request_id: str; protocol_version: str; method: str; route: str; content_type: str; idempotency_key: str; response_schema: str; status_code: int; disposition: str; batch_id: str; partition: str; candidate_order: tuple[str,...]; admitted_order: tuple[str,...]; blocked_order: tuple[str,...]; unknown_order: tuple[str,...]; checkpoint_seq: int; queue_digest: str; context_digest: str; section_digest: str; request_digest: str; response_digest: str; replay_identity: str; omissions: tuple[str,...]; uncertainty: tuple[str,...]; negative_evidence: tuple[str,...]; effect_receipts: tuple[str,...]; artifact: Mapping[str,Any]; feature_id: str = THROUGHPUT_CONTEXT_PROTOCOL_ADAPTER_FEATURE_ID; contract_version: str = THROUGHPUT_CONTEXT_PROTOCOL_ADAPTER_CONTRACT_VERSION; schema_version: str = RESEARCH_CONTRACT_SCHEMA_VERSION; raw_data_local: bool = True; boundary: str = PRECLINICAL_BOUNDARY
    def validate(self)->None:
        if self.schema_version!=RESEARCH_CONTRACT_SCHEMA_VERSION or self.feature_id!=THROUGHPUT_CONTEXT_PROTOCOL_ADAPTER_FEATURE_ID or self.contract_version!=THROUGHPUT_CONTEXT_PROTOCOL_ADAPTER_CONTRACT_VERSION: raise ResearchContractError("throughput context protocol schema, feature, or version mismatch")
        if self.boundary!=PRECLINICAL_BOUNDARY or not self.raw_data_local or not self.request_id.strip() or self.protocol_version!=PROTOCOL_VERSION or self.method!=METHOD or self.route!=ROUTE or self.content_type!="application/json" or not self.idempotency_key.strip() or not self.response_schema==RESPONSE_SCHEMA or not self.batch_id.strip() or not self.partition.strip() or not self.candidate_order or not self.effect_receipts or self.status_code not in {200,202,206,403,422} or self.disposition not in {"ready","partial","unknown","blocked"}: raise ResearchContractError("throughput context protocol identity, route, queue, idempotency, locality, or effects are incomplete")
        if any(v not in self.candidate_order for v in (*self.admitted_order,*self.blocked_order,*self.unknown_order)): raise ResearchContractError("throughput context protocol state is not covered by candidates")
        for values in (self.candidate_order,self.admitted_order,self.blocked_order,self.unknown_order,self.omissions,self.uncertainty,self.negative_evidence,self.effect_receipts):
            if tuple(sorted(set(values)))!=values: raise ResearchContractError("throughput context protocol ordering is not canonical")
        for value in (self.queue_digest,self.context_digest,self.section_digest,self.request_digest,self.response_digest,self.replay_identity,self.artifact.get("content_hash")):
            if not isinstance(value,str) or not re.fullmatch(r"[0-9a-f]{64}",value): raise ResearchContractError("throughput context protocol digest is invalid")
        if any(not e.startswith("protocol:local-throughput-context-response:") and e!="block:unsafe-release" for e in self.effect_receipts): raise ResearchContractError("throughput context protocol effect is outside local response gate")
    def digest(self)->str:
        self.validate(); return research_artifact_digest({"schema_version":self.schema_version,"contract_version":self.contract_version,"feature_id":self.feature_id,"request_id":self.request_id,"protocol_version":self.protocol_version,"method":self.method,"route":self.route,"content_type":self.content_type,"idempotency_key":self.idempotency_key,"response_schema":self.response_schema,"status_code":self.status_code,"disposition":self.disposition,"batch_id":self.batch_id,"partition":self.partition,"candidate_order":list(self.candidate_order),"admitted_order":list(self.admitted_order),"blocked_order":list(self.blocked_order),"unknown_order":list(self.unknown_order),"checkpoint_seq":self.checkpoint_seq,"queue_digest":self.queue_digest,"context_digest":self.context_digest,"section_digest":self.section_digest,"request_digest":self.request_digest,"response_digest":self.response_digest,"replay_identity":self.replay_identity,"omissions":list(self.omissions),"uncertainty":list(self.uncertainty),"negative_evidence":list(self.negative_evidence),"effect_receipts":list(self.effect_receipts),"artifact":dict(self.artifact),"raw_data_local":self.raw_data_local,"boundary":self.boundary})

def serve_throughput_context_protocol(*, request_id:str,batch_id:str,partition:str,jobs:Sequence[ThroughputContextProtocolJob],max_concurrency:int,budget_units:int,idempotency_key:str,replay_identity:str,policy_allow:bool=True,protected_closure:bool=True,raw_data_local:bool=True,protocol_version:str=PROTOCOL_VERSION,method:str=METHOD,route:str=ROUTE,content_type:str="application/json",response_schema:str=RESPONSE_SCHEMA)->ThroughputContextProtocolReceipt:
    if not request_id.strip() or not batch_id.strip() or not partition.strip() or not jobs or max_concurrency<=0 or budget_units<=0 or not idempotency_key.strip() or not re.fullmatch(r"[0-9a-f]{64}",replay_identity) or (protocol_version,method,route,content_type,response_schema)!=(PROTOCOL_VERSION,METHOD,ROUTE,"application/json",RESPONSE_SCHEMA): raise ResearchContractError("throughput context protocol identity, route, queue, budget, replay, or version is invalid")
    ordered=tuple(sorted(jobs,key=lambda j:j.job_id)); candidate=tuple(j.job_id for j in ordered)
    if any(not x.strip() for x in candidate) or len(set(candidate))!=len(candidate): raise ResearchContractError("throughput context protocol job identifiers must be unique and non-empty")
    admitted:set[str]=set(); blocked:set[str]=set(); unknown:set[str]=set(); omissions:set[str]=set(); uncertainty:set[str]=set(); negative:set[str]=set(); consumed=0; open_gate=policy_allow and protected_closure and raw_data_local
    for job in ordered:
        if not open_gate or not job.raw_data_local or job.boundary!=PRECLINICAL_BOUNDARY: blocked.add(job.job_id); omissions.add(f"job:{job.job_id}:policy-locality-blocked")
        elif job.replay_identity!=replay_identity: unknown.add(job.job_id); uncertainty.add(f"job:{job.job_id}:replay-mismatch")
        elif not job.ready: unknown.add(job.job_id); uncertainty.add(f"job:{job.job_id}:not-ready")
        elif job.state in {"speculative","unknown"}: unknown.add(job.job_id); uncertainty.add(f"job:{job.job_id}:evidence-uncertain")
        elif job.state not in {"proven","supported"}: blocked.add(job.job_id); negative.add(f"job:{job.job_id}:contradicted")
        elif len(admitted)>=max_concurrency: unknown.add(job.job_id); uncertainty.add(f"job:{job.job_id}:concurrency-window")
        elif consumed+job.cost_units>budget_units: blocked.add(job.job_id); omissions.add(f"job:{job.job_id}:budget-exhausted")
        else: admitted.add(job.job_id); consumed+=job.cost_units
    disposition="blocked" if not open_gate else "ready" if len(admitted)==len(candidate) else "unknown" if unknown else "partial"; status=403 if not open_gate else 200 if disposition=="ready" else 206 if disposition=="partial" else 202
    if not policy_allow: omissions.add("protocol:policy-denied")
    if not protected_closure: omissions.add("protocol:protected-closure-incomplete")
    if not raw_data_local: omissions.add("protocol:raw-data-locality-failed")
    queue_digest=research_artifact_digest({"candidate_order":list(candidate),"admitted_order":sorted(admitted),"blocked_order":sorted(blocked),"unknown_order":sorted(unknown),"max_concurrency":max_concurrency,"budget_units":budget_units,"consumed":consumed,"replay_identity":replay_identity}); context_digest=research_artifact_digest({"batch_id":batch_id,"queue_digest":queue_digest,"replay_identity":replay_identity}); section_digest=research_artifact_digest({"partition":partition,"context_digest":context_digest,"admitted_order":sorted(admitted)}); request_digest=research_artifact_digest({"request_id":request_id,"batch_id":batch_id,"partition":partition,"candidate_order":list(candidate),"replay_identity":replay_identity}); response_digest=research_artifact_digest({"protocol_version":PROTOCOL_VERSION,"route":ROUTE,"request_id":request_id,"status_code":status,"disposition":disposition,"queue_digest":queue_digest,"replay_identity":replay_identity}); artifact={"content_hash":research_artifact_digest({"request_id":request_id,"section_digest":section_digest}),"media_type":"application/vnd.aurora.throughput-context-protocol-response+json"}
    receipt=ThroughputContextProtocolReceipt(request_id=request_id,protocol_version=PROTOCOL_VERSION,method=METHOD,route=ROUTE,content_type="application/json",idempotency_key=idempotency_key,response_schema=RESPONSE_SCHEMA,status_code=status,disposition=disposition,batch_id=batch_id,partition=partition,candidate_order=candidate,admitted_order=tuple(sorted(admitted)),blocked_order=tuple(sorted(blocked)),unknown_order=tuple(sorted(unknown)),checkpoint_seq=len(ordered),queue_digest=queue_digest,context_digest=context_digest,section_digest=section_digest,request_digest=request_digest,response_digest=response_digest,replay_identity=replay_identity,omissions=tuple(sorted(omissions)),uncertainty=tuple(sorted(uncertainty)),negative_evidence=tuple(sorted(negative)),effect_receipts=(f"protocol:local-throughput-context-response:{idempotency_key}",) if open_gate else ("block:unsafe-release",),artifact=artifact); receipt.validate(); return receipt
