"""Multimodal multi-study knowledge-representation parity contract."""
from __future__ import annotations
from dataclasses import dataclass
import re
from typing import Any, Mapping, Sequence
from .research_contracts import MULTIMODAL_KNOWLEDGE_REPRESENTATION_INFERENCE_ENGINE_CONTRACT_VERSION, MULTIMODAL_KNOWLEDGE_REPRESENTATION_INFERENCE_ENGINE_FEATURE_ID, PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError, research_artifact_digest

@dataclass(frozen=True)
class MultimodalKnowledgeClaim:
    claim_id: str; study_id: str; modality: str; semantic_profile: str; subject: str; predicate: str; object: str; evidence_digest: str | None; provenance_digest: str | None; comparable: bool = True; state: str = "supported"; boundary: str = PRECLINICAL_BOUNDARY

@dataclass(frozen=True)
class MultimodalKnowledgeReceipt:
    request_id: str; disposition: str; candidate_order: tuple[str,...]; admitted_order: tuple[str,...]; unresolved_order: tuple[str,...]; denied_order: tuple[str,...]; study_order: tuple[str,...]; modality_order: tuple[str,...]; coverage_order: tuple[str,...]; comparability_order: tuple[str,...]; world_digest: str; evidence_digest: str; provenance_digest: str; replay_identity: str; witness_order: tuple[str,...]; counterexample_order: tuple[str,...]; omissions: tuple[str,...]; uncertainty: tuple[str,...]; negative_evidence: tuple[str,...]; effect_receipts: tuple[str,...]; artifact: Mapping[str,Any]; feature_id: str = MULTIMODAL_KNOWLEDGE_REPRESENTATION_INFERENCE_ENGINE_FEATURE_ID; contract_version: str = MULTIMODAL_KNOWLEDGE_REPRESENTATION_INFERENCE_ENGINE_CONTRACT_VERSION; schema_version: str = RESEARCH_CONTRACT_SCHEMA_VERSION; raw_data_local: bool = True; boundary: str = PRECLINICAL_BOUNDARY
    def validate(self) -> None:
        if self.schema_version != RESEARCH_CONTRACT_SCHEMA_VERSION or self.contract_version != MULTIMODAL_KNOWLEDGE_REPRESENTATION_INFERENCE_ENGINE_CONTRACT_VERSION or self.feature_id != MULTIMODAL_KNOWLEDGE_REPRESENTATION_INFERENCE_ENGINE_FEATURE_ID: raise ResearchContractError("multimodal knowledge schema, feature, or version mismatch")
        if self.boundary != PRECLINICAL_BOUNDARY or not self.raw_data_local or not self.request_id.strip() or not self.candidate_order or len(self.study_order)<2 or len(self.modality_order)<2 or not self.effect_receipts: raise ResearchContractError("multimodal knowledge identity, coverage, locality, or effects are incomplete")
        for values in (self.candidate_order,self.admitted_order,self.unresolved_order,self.denied_order,self.study_order,self.modality_order,self.coverage_order,self.comparability_order,self.witness_order,self.counterexample_order,self.omissions,self.uncertainty,self.negative_evidence,self.effect_receipts):
            if tuple(sorted(set(values))) != values: raise ResearchContractError("multimodal knowledge ordering is not canonical")
        classified=set(self.admitted_order)|set(self.unresolved_order)|set(self.denied_order)
        if classified != set(self.candidate_order): raise ResearchContractError("multimodal knowledge states do not partition claims")
        for value in (self.world_digest,self.evidence_digest,self.provenance_digest,self.replay_identity,self.artifact.get("content_hash")):
            if not isinstance(value,str) or not re.fullmatch(r"[0-9a-f]{64}",value): raise ResearchContractError("multimodal knowledge digest is invalid")
        if any(not e.startswith("read:local-multimodal-knowledge-world:") and e != "block:unsafe-release" for e in self.effect_receipts): raise ResearchContractError("multimodal knowledge effect is outside read-only gate")
    def digest(self) -> str:
        self.validate(); return research_artifact_digest({"schema_version":self.schema_version,"contract_version":self.contract_version,"feature_id":self.feature_id,"request_id":self.request_id,"disposition":self.disposition,"candidate_order":list(self.candidate_order),"admitted_order":list(self.admitted_order),"unresolved_order":list(self.unresolved_order),"denied_order":list(self.denied_order),"study_order":list(self.study_order),"modality_order":list(self.modality_order),"coverage_order":list(self.coverage_order),"comparability_order":list(self.comparability_order),"world_digest":self.world_digest,"evidence_digest":self.evidence_digest,"provenance_digest":self.provenance_digest,"replay_identity":self.replay_identity,"witness_order":list(self.witness_order),"counterexample_order":list(self.counterexample_order),"omissions":list(self.omissions),"uncertainty":list(self.uncertainty),"negative_evidence":list(self.negative_evidence),"effect_receipts":list(self.effect_receipts),"artifact":dict(self.artifact),"raw_data_local":self.raw_data_local,"boundary":self.boundary})

def infer_multimodal_knowledge_representation(*, request_id: str, claims: Sequence[MultimodalKnowledgeClaim], required_studies: Sequence[str], required_modalities: Sequence[str], replay_identity: str, policy_allow: bool = True, protected_closure: bool = True, raw_data_local: bool = True) -> MultimodalKnowledgeReceipt:
    if not request_id.strip() or not claims or len(required_studies)<2 or len(required_modalities)<2 or not re.fullmatch(r"[0-9a-f]{64}",replay_identity) or not raw_data_local: raise ResearchContractError("multimodal knowledge identity, coverage, replay, or locality is invalid")
    ordered=tuple(sorted(c.claim_id for c in claims))
    if len(set(ordered)) != len(claims) or any(not v.strip() for v in ordered): raise ResearchContractError("multimodal claim identifiers must be unique and non-empty")
    cmap={c.claim_id:c for c in claims}; admitted:set[str]=set(); unresolved:set[str]=set(); denied:set[str]=set(); studies:set[str]=set(); modalities:set[str]=set(); profiles:set[str]=set(); facts:list[dict[str,Any]]=[]; witnesses={"gate:typed-multimodal-claims","gate:study-coverage","gate:modality-coverage","gate:comparability","gate:evidence-provenance","gate:locality"}; counter:set[str]=set(); omissions:set[str]=set(); uncertainty:set[str]=set(); negative:set[str]=set()
    for cid in ordered:
        c=cmap[cid]
        if not policy_allow or not protected_closure or c.boundary != PRECLINICAL_BOUNDARY: denied.add(cid); counter.add(f"counterexample:{cid}:policy-closure")
        elif not c.comparable or not c.semantic_profile.strip(): denied.add(cid); counter.add(f"counterexample:{cid}:incomparable-semantic-profile")
        elif c.evidence_digest is None or c.provenance_digest is None: unresolved.add(cid); omissions.add(f"claim:{cid}:evidence-or-provenance-missing")
        elif c.state in {"unknown","speculative"}: unresolved.add(cid); uncertainty.add(f"claim:{cid}:unknown-not-asserted")
        elif c.state == "contradicted": denied.add(cid); negative.add(f"claim:{cid}:contradicted")
        else: admitted.add(cid); studies.add(c.study_id); modalities.add(c.modality); profiles.add(c.semantic_profile); facts.append({"claim_id":c.claim_id,"study_id":c.study_id,"modality":c.modality,"semantic_profile":c.semantic_profile,"subject":c.subject,"predicate":c.predicate,"object":c.object,"evidence_digest":c.evidence_digest,"provenance_digest":c.provenance_digest})
    for req in required_studies:
        if req not in studies: omissions.add(f"study:{req}:coverage-missing"); uncertainty.add(f"study:{req}:unresolved")
    for req in required_modalities:
        if req not in modalities: omissions.add(f"modality:{req}:coverage-missing"); uncertainty.add(f"modality:{req}:unresolved")
    if len(profiles)>1: denied.update(admitted); admitted.clear(); counter.add("counterexample:semantic-profile-conflict")
    if not policy_allow: omissions.add("control:policy-denied")
    if not protected_closure: omissions.add("control:protected-closure-incomplete")
    if unresolved or len(studies)<len(required_studies) or len(modalities)<len(required_modalities): witnesses.add("gate:coverage-omissions-retained")
    report_studies=set(studies)|set(required_studies); report_modalities=set(modalities)|set(required_modalities); coverage=tuple(sorted(set(required_studies)|set(required_modalities))); comparability=tuple(sorted(profiles)); disposition="denied" if not policy_allow or not protected_closure or len(denied)==len(ordered) else "unresolved" if not admitted else "partial" if unresolved or denied or any(x not in studies and x not in modalities for x in coverage) else "completed"; facts.sort(key=lambda f:f["claim_id"]); world=research_artifact_digest({"facts":facts,"study_order":sorted(studies),"modality_order":sorted(modalities),"comparability_order":list(comparability)}); evidence=research_artifact_digest({"candidate_order":list(ordered),"admitted_order":sorted(admitted),"unresolved_order":sorted(unresolved),"denied_order":sorted(denied)}); provenance=research_artifact_digest({"request_id":request_id,"world_digest":world,"replay_identity":replay_identity}); artifact={"content_hash":research_artifact_digest({"request_id":request_id,"world_digest":world}),"media_type":"application/vnd.aurora.multimodal-typed-knowledge-world+json"}; receipt=MultimodalKnowledgeReceipt(request_id=request_id,disposition=disposition,candidate_order=ordered,admitted_order=tuple(sorted(admitted)),unresolved_order=tuple(sorted(unresolved)),denied_order=tuple(sorted(denied)),study_order=tuple(sorted(report_studies)),modality_order=tuple(sorted(report_modalities)),coverage_order=coverage,comparability_order=comparability,world_digest=world,evidence_digest=evidence,provenance_digest=provenance,replay_identity=replay_identity,witness_order=tuple(sorted(witnesses)),counterexample_order=tuple(sorted(counter)),omissions=tuple(sorted(omissions)),uncertainty=tuple(sorted(uncertainty)),negative_evidence=tuple(sorted(negative)),effect_receipts=(f"read:local-multimodal-knowledge-world:{request_id}",) if disposition in {"completed","partial"} else ("block:unsafe-release",),artifact=artifact,raw_data_local=raw_data_local); receipt.validate(); return receipt
