"""Python parity for Backends P32 capability-negotiation integrity cards."""
from __future__ import annotations
import hashlib,json,re
from typing import Any,Mapping
from .research_contracts import RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions";CONTENT_TYPE="application/vnd.aurora.backends.capability-negotiation-integrity-card-1+json"
BackendCandidate4=dict[str,Any];BackendRequest4=dict[str,Any];BackendCard7=dict[str,Any];BackendArtifact4=dict[str,Any];CapabilityNegotiationIntegrityError=ResearchContractError
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return isinstance(v,list) and v==sorted(set(v))
def manifest(*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"backends","consumers":["runtime scheduler","backend portfolio","execution compiler","research workbench"],"behavior":f"negotiate typed backend capabilities at {scale} ({mode})","value":"selects only evidenced, deterministic, policy-authorized engines while preserving refusals and replay identity","input_schema":"BackendRequest4@1","output_schema":"BackendCard7@1","effects":["emit:capability-card","retain:backend-refusal","block:unsafe-execution"],"permissions":["read:local-backend-manifests"],"determinism":"byte_stable","autonomy_tier":"A1","boundary":BOUNDARY}
def validate(o:Mapping[str,Any],*,feature_id:str|None=None)->None:
 a=o.get("artifact",{});bad=o.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or(feature_id is not None and o.get("feature_id")!=feature_id)or not o.get("request_id")or not o.get("purpose")or o.get("boundary")!=BOUNDARY or a.get("boundary")!=BOUNDARY or o.get("raw_data_local") is not True or o.get("aggregate_only") is not True or not _digest(o.get("replay_identity")) or not _digest(o.get("closure_digest")) or a.get("content_type")!=CONTENT_TYPE or a.get("content_hash")!=o.get("closure_digest")
 if bad:raise ResearchContractError("backend identity, locality, artifact, digest, or boundary is incomplete")
 for k in("backend_order","selected_order","rejected_order","unknown_order","omitted_order","runtime_order","version_order","capability_order","determinism_order","effect_receipts"):
  if not _ordered(o.get(k,[])):raise ResearchContractError("backend vectors are not canonical")
 ids=set(o["backend_order"]);states=set(o["selected_order"])|set(o["rejected_order"])|set(o["unknown_order"])|set(o["omitted_order"])
 if len(o["backend_order"])!=len(ids)or states!=ids:raise ResearchContractError("backend states do not partition candidates")
 if o.get("selected_backend") is not None and o["selected_backend"] not in o["selected_order"]:raise ResearchContractError("selected backend is not in selected order")
def negotiate(request:Mapping[str,Any],*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:
 if request.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or not request.get("request_id","").strip() or not request.get("purpose","").strip() or not request.get("candidates") or not request.get("required_backend_order") or not _ordered(request["required_backend_order"]) or not _digest(request.get("semantic_profile_digest")) or not _digest(request.get("replay_identity")) or request.get("boundary")!=BOUNDARY or request.get("raw_data_local") is not True or request.get("aggregate_only") is not True or not _ordered(request.get("adversarial_events",[])) or request.get("backend_budget",0)<=0:raise ResearchContractError("backend identity, ordering, semantic profile, digest, locality, boundary, or budget is invalid")
 rows=sorted(request["candidates"],key=lambda a:a.get("backend_id",""));seen=set();selected=set();rejected=set();unknown=set();omitted=set();runtimes=set();versions=set();capabilities=set();determinism=set()
 for c in rows:
  bid=c.get("backend_id","")
  if not bid.strip()or bid in seen or not c.get("runtime","").strip()or not c.get("version","").strip()or not _digest(c.get("capability_digest"))or not c.get("determinism","").strip()or not c.get("evidence_state","").strip()or c.get("local") is not True or c.get("aggregate_only") is not True:raise ResearchContractError("backend identity, capability digest, evidence, or locality is invalid")
  seen.add(bid);runtimes.add(f"{bid}:{c['runtime']}");versions.add(f"{bid}:{c['version']}");capabilities.add(f"{bid}:{c['capability_digest']}");determinism.add(f"{bid}:{c['determinism']}")
  if c["evidence_state"]=="unknown"or c["capability_digest"]==request["replay_identity"]:unknown.add(bid)
  elif c["capability_digest"]!=request["semantic_profile_digest"]or c["determinism"]!="byte_stable":rejected.add(bid)
  elif bid not in request["required_backend_order"]:omitted.add(bid)
  else:selected.add(bid)
 missing=[x for x in request["required_backend_order"] if x not in seen];global_block=not all(request.get(k) is True for k in("policy_allowed","protected_closure","signed_manifest","raw_data_local","aggregate_only"))or bool(request.get("adversarial_events"))or len(rows)>request["backend_budget"]
 if global_block:omitted.update(seen);selected.clear();rejected.clear();unknown.clear()
 disposition="blocked" if global_block else "unknown" if missing or unknown else "partial" if not selected or rejected or omitted else "selected";selected_backend=next((x for x in request["required_backend_order"] if x in selected),None);body={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"request_id":request["request_id"],"purpose":request["purpose"],"disposition":disposition,"backend_order":sorted(seen)};d=_hash(body);payload={**body,"selected_order":sorted(selected),"rejected_order":sorted(rejected),"unknown_order":sorted(unknown),"omitted_order":sorted(omitted),"runtime_order":sorted(runtimes),"version_order":sorted(versions),"capability_order":sorted(capabilities),"determinism_order":sorted(determinism),"replay_identity":request["replay_identity"],"closure_digest":d,"selected_backend":selected_backend,"raw_data_local":True,"aggregate_only":True,"boundary":BOUNDARY,"effect_receipts":[f"select:backend:{request['request_id']}"] if disposition=="selected" else ["block:unsafe-execution"],"artifact":{"artifact_id":f"backends-capability-negotiation:{request['request_id']}","content_type":CONTENT_TYPE,"content_hash":d,"semantic_loss":sorted(omitted),"evidence_digests":sorted(capabilities),"boundary":BOUNDARY}};validate(payload,feature_id=feature_id);return payload
__all__=["BOUNDARY","CONTENT_TYPE","BackendCandidate4","BackendRequest4","BackendCard7","BackendArtifact4","CapabilityNegotiationIntegrityError","manifest","negotiate","validate"]
