"""Python parity surface for ``AFA-cli-P14-F24``."""
from __future__ import annotations

from dataclasses import dataclass
import hashlib, json, re
from typing import Any, Mapping, Sequence

from .research_contracts import PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError

FEATURE_ID="AFA-cli-P14-F24"; CONTRACT_VERSION="cli-federated-continual-interpretation-visualization-interoperability-gateway/1.0"; INPUT_SCHEMA="EvidenceBackedResult5@1"; OUTPUT_SCHEMA="InteractiveInterpretation7@1"; CONTENT_TYPE="application/vnd.aurora.interactive-interpretation+json"
def _digest(value:Any)->bool:return isinstance(value,str) and re.fullmatch(r"[0-9a-f]{64}",value) is not None
def _canonical(values:Sequence[str])->bool:return tuple(values)==tuple(sorted(set(values)))
def _hash(value:Any)->str:return hashlib.sha256(json.dumps(value,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()

@dataclass(frozen=True)
class CliInterpretationGatewayEnvelope:
    request_id:str; federation_id:str; source_institution:str; target_institution:str; purpose:str; semantic_profile:str; disposition:str; panel_order:tuple[str,...]; ranked_order:tuple[str,...]; exchanged_order:tuple[str,...]; unresolved_order:tuple[str,...]; blocked_order:tuple[str,...]; missing_panel_order:tuple[str,...]; missing_study_order:tuple[str,...]; missing_modality_order:tuple[str,...]; omission_order:tuple[str,...]; uncertainty_order:tuple[str,...]; contradiction_order:tuple[str,...]; negative_evidence_order:tuple[str,...]; adversarial_event_order:tuple[str,...]; replay_identity:str; envelope_digest:str; artifact:dict[str,Any]; effect_receipts:tuple[str,...]; schema_version:str=RESEARCH_CONTRACT_SCHEMA_VERSION; contract_version:str=CONTRACT_VERSION; feature_id:str=FEATURE_ID; raw_data_local:bool=True; aggregate_only:bool=True; boundary:str=PRECLINICAL_BOUNDARY
    def to_dict(self)->dict[str,Any]:
        return {"schema_version":self.schema_version,"contract_version":self.contract_version,"feature_id":self.feature_id,"request_id":self.request_id,"federation_id":self.federation_id,"source_institution":self.source_institution,"target_institution":self.target_institution,"purpose":self.purpose,"semantic_profile":self.semantic_profile,"disposition":self.disposition,"panel_order":list(self.panel_order),"ranked_order":list(self.ranked_order),"exchanged_order":list(self.exchanged_order),"unresolved_order":list(self.unresolved_order),"blocked_order":list(self.blocked_order),"missing_panel_order":list(self.missing_panel_order),"missing_study_order":list(self.missing_study_order),"missing_modality_order":list(self.missing_modality_order),"omission_order":list(self.omission_order),"uncertainty_order":list(self.uncertainty_order),"contradiction_order":list(self.contradiction_order),"negative_evidence_order":list(self.negative_evidence_order),"adversarial_event_order":list(self.adversarial_event_order),"replay_identity":self.replay_identity,"envelope_digest":self.envelope_digest,"artifact":self.artifact,"effect_receipts":list(self.effect_receipts),"raw_data_local":self.raw_data_local,"aggregate_only":self.aggregate_only,"boundary":self.boundary}
    def validate(self)->None:
        if (self.schema_version,self.contract_version,self.feature_id)!=(RESEARCH_CONTRACT_SCHEMA_VERSION,CONTRACT_VERSION,FEATURE_ID) or self.boundary!=PRECLINICAL_BOUNDARY or self.artifact.get("boundary")!=PRECLINICAL_BOUNDARY or not self.raw_data_local or not self.aggregate_only or not self.request_id.strip() or not self.federation_id.strip() or not self.source_institution.strip() or not self.target_institution.strip() or self.source_institution==self.target_institution or not self.purpose.strip() or not self.semantic_profile.strip() or self.disposition not in {"qualified","unresolved","blocked"} or not self.panel_order or len(self.ranked_order)!=len(self.panel_order) or not self.effect_receipts: raise ResearchContractError("interpretation envelope identity, locality, partitions, disposition, or effects are incomplete")
        for values in (self.panel_order,self.exchanged_order,self.unresolved_order,self.blocked_order,self.missing_panel_order,self.missing_study_order,self.missing_modality_order,self.omission_order,self.uncertainty_order,self.contradiction_order,self.negative_evidence_order,self.adversarial_event_order,self.effect_receipts):
            if not _canonical(values): raise ResearchContractError("interpretation envelope ordering is not canonical")
        panels=set(self.panel_order); partitions=self.exchanged_order+self.unresolved_order+self.blocked_order
        if any(item not in panels for item in partitions) or len(partitions)!=len(panels) or len(set(partitions))!=len(partitions) or any(item in panels for item in self.missing_panel_order) or set(self.ranked_order)!=panels: raise ResearchContractError("interpretation panel states do not partition observed panels")
        for value in (self.replay_identity,self.envelope_digest,self.artifact.get("content_hash")):
            if not _digest(value): raise ResearchContractError("interpretation envelope digest is invalid")
        if self.artifact.get("content_type")!=CONTENT_TYPE: raise ResearchContractError("interpretation envelope artifact type is invalid")
        if self.disposition=="qualified" and (len(self.effect_receipts)!=1 or not self.effect_receipts[0].startswith("exchange:interpretation-artifact:")): raise ResearchContractError("qualified interpretation exchange effect is invalid")
        if self.disposition!="qualified" and self.effect_receipts!=("block:unsafe-release",): raise ResearchContractError("non-qualified interpretation exchange must block release")

def assure_interpretation_exchange(*,request_id:str,federation_id:str,source_institution:str,target_institution:str,purpose:str,semantic_profile:str,required_panel_order:Sequence[str],required_study_order:Sequence[str],required_modality_order:Sequence[str],panels:Sequence[Mapping[str,Any]],replay_identity:str,policy_allow:bool,protected_closure:bool,signed_approval:bool,federation_approved:bool,raw_data_local:bool,aggregate_only:bool,budget:int,max_budget:int,adversarial_events:Sequence[str]=(),boundary:str=PRECLINICAL_BOUNDARY)->CliInterpretationGatewayEnvelope:
    if not request_id.strip() or not federation_id.strip() or not source_institution.strip() or not target_institution.strip() or source_institution==target_institution or not purpose.strip() or not semantic_profile.strip() or not required_panel_order or not required_study_order or not required_modality_order or not panels or not _canonical(required_panel_order) or not _canonical(required_study_order) or not _canonical(required_modality_order) or not _canonical(adversarial_events) or not _digest(replay_identity) or budget<=0 or max_budget<=0 or boundary!=PRECLINICAL_BOUNDARY or not raw_data_local or not aggregate_only: raise ResearchContractError("interpretation request identity, federation, requirements, budget, locality, or boundary is invalid")
    rows=[dict(panel) for panel in panels]; seen:set[str]=set()
    for panel in rows:
        pid=str(panel.get("panel_id",""))
        if not pid.strip() or not str(panel.get("label","")).strip() or pid in seen or not panel.get("study_order") or not panel.get("modality_order") or not _canonical(panel["study_order"]) or not _canonical(panel["modality_order"]) or not 0<=int(panel.get("interpretation_score_milli",-1))<=1000 or not _digest(panel.get("result_digest")) or not _digest(panel.get("visualization_digest")) or (panel.get("provenance_digest") is not None and not _digest(panel.get("provenance_digest"))) or not _digest(panel.get("replay_identity")) or not str(panel.get("semantic_profile","")).strip() or not _canonical(panel.get("omissions",())) or not _canonical(panel.get("uncertainty",())): raise ResearchContractError(f"panel {pid} is malformed or duplicated")
        seen.add(pid)
    rows.sort(key=lambda panel:(-int(panel["interpretation_score_milli"]),str(panel["panel_id"]))); ranked_order=tuple(str(panel["panel_id"]) for panel in rows); panel_order=tuple(sorted(ranked_order)); required=set(required_panel_order); missing_panel_order=tuple(sorted(required-set(panel_order))); studies=set(required_study_order); modalities=set(required_modality_order); exchanged:set[str]=set(); unresolved:set[str]=set(); blocked:set[str]=set(); omissions:set[str]=set(); uncertainty:set[str]=set(); contradiction:set[str]=set(); negative:set[str]=set()
    for panel in rows:
        pid=str(panel["panel_id"]); state=str(panel.get("evidence_state",""));
        if panel.get("negative_result"): negative.add(f"{pid}:negative-result")
        omissions.update(f"{pid}:{item}" for item in panel.get("omissions",())); uncertainty.update(f"{pid}:{item}" for item in panel.get("uncertainty",()))
        if state=="contradicted": blocked.add(pid); contradiction.add(f"{pid}:contradicted-evidence"); continue
        if state in {"unknown","speculative"}: unresolved.add(pid); uncertainty.add(f"{pid}:evidence-unresolved"); continue
        pstudies=set(panel["study_order"]); pmodalities=set(panel["modality_order"]); complete=bool(str(panel.get("label","")).strip()) and panel.get("semantic_profile")==semantic_profile and panel.get("replay_identity")==replay_identity and _digest(panel.get("result_digest")) and _digest(panel.get("visualization_digest")) and panel.get("provenance_digest") is not None and studies<=pstudies and modalities<=pmodalities and bool(panel.get("comparable")) and not panel.get("omissions") and not panel.get("uncertainty") and bool(panel.get("local_data")) and bool(panel.get("permitted")) and int(panel["interpretation_score_milli"])>=600
        if complete and state in {"proven","supported"}: exchanged.add(pid)
        else:
            unresolved.add(pid)
            if panel.get("provenance_digest") is None: omissions.add(f"{pid}:provenance-missing")
            if not studies<=pstudies: omissions.add(f"{pid}:required-study-coverage-incomplete")
            if not modalities<=pmodalities: omissions.add(f"{pid}:required-modality-coverage-incomplete")
            if int(panel["interpretation_score_milli"])<600: uncertainty.add(f"{pid}:interpretation-threshold-not-met")
            if not panel.get("local_data") or not panel.get("permitted"): blocked.add(pid); unresolved.discard(pid); omissions.add(f"{pid}:locality-or-permission-denied")
    missing_study_order=tuple(sorted(study for study in required_study_order if not any(study in panel.get("study_order",()) for panel in rows))); missing_modality_order=tuple(sorted(modality for modality in required_modality_order if not any(modality in panel.get("modality_order",()) for panel in rows))); omissions.update(f"{item}:required-panel-missing" for item in missing_panel_order); omissions.update(f"required-study-missing:{item}" for item in missing_study_order); omissions.update(f"required-modality-missing:{item}" for item in missing_modality_order); negative.update(f"adversarial:{item}" for item in adversarial_events); global_block=not policy_allow or not protected_closure or not signed_approval or not federation_approved or not raw_data_local or not aggregate_only or budget>max_budget or bool(adversarial_events); uncertainty.update(("request:policy-denied",) if not policy_allow else ()); uncertainty.update(("request:protected-closure-incomplete",) if not protected_closure else ()); uncertainty.update(("request:institutional-approval-incomplete",) if not signed_approval or not federation_approved else ()); omissions.update(("request:budget-ceiling-exceeded",) if budget>max_budget else ()); disposition="blocked" if global_block else ("qualified" if not missing_panel_order and not missing_study_order and not missing_modality_order and exchanged and not unresolved and not blocked else "unresolved"); exchanged_order,unresolved_order,blocked_order=tuple(sorted(exchanged)),tuple(sorted(unresolved)),tuple(sorted(blocked)); omission_order,uncertainty_order,contradiction_order,negative_order=tuple(sorted(omissions)),tuple(sorted(uncertainty)),tuple(sorted(contradiction)),tuple(sorted(negative)); effects=(f"exchange:interpretation-artifact:{request_id}",) if disposition=="qualified" else ("block:unsafe-release",)
    payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"feature_id":FEATURE_ID,"request_id":request_id,"federation_id":federation_id,"source_institution":source_institution,"target_institution":target_institution,"purpose":purpose,"semantic_profile":semantic_profile,"disposition":disposition,"panel_order":list(panel_order),"ranked_order":list(ranked_order),"exchanged_order":list(exchanged_order),"unresolved_order":list(unresolved_order),"blocked_order":list(blocked_order),"missing_panel_order":list(missing_panel_order),"missing_study_order":list(missing_study_order),"missing_modality_order":list(missing_modality_order),"omission_order":list(omission_order),"uncertainty_order":list(uncertainty_order),"contradiction_order":list(contradiction_order),"negative_evidence_order":list(negative_order),"adversarial_event_order":list(adversarial_events),"replay_identity":replay_identity,"effect_receipts":list(effects),"raw_data_local":raw_data_local,"aggregate_only":aggregate_only,"boundary":PRECLINICAL_BOUNDARY}; envelope_digest=_hash(payload); artifact={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"artifact_id":f"cli-interpretation:{request_id}","content_type":CONTENT_TYPE,"content_hash":envelope_digest,"semantic_loss":[],"provenance":[{"source_id":f"federation:{federation_id}","relation":"derived-from-local-interpretation-manifest","digest":replay_identity}],"boundary":PRECLINICAL_BOUNDARY}; envelope=CliInterpretationGatewayEnvelope(request_id=request_id,federation_id=federation_id,source_institution=source_institution,target_institution=target_institution,purpose=purpose,semantic_profile=semantic_profile,disposition=disposition,panel_order=panel_order,ranked_order=ranked_order,exchanged_order=exchanged_order,unresolved_order=unresolved_order,blocked_order=blocked_order,missing_panel_order=missing_panel_order,missing_study_order=missing_study_order,missing_modality_order=missing_modality_order,omission_order=omission_order,uncertainty_order=uncertainty_order,contradiction_order=contradiction_order,negative_evidence_order=negative_order,adversarial_event_order=tuple(adversarial_events),replay_identity=replay_identity,envelope_digest=envelope_digest,artifact=artifact,effect_receipts=effects); envelope.validate(); return envelope

def cli_interpretation_gateway_digest(envelope:CliInterpretationGatewayEnvelope)->str: envelope.validate(); return _hash(envelope.to_dict())
__all__=["FEATURE_ID","CONTRACT_VERSION","INPUT_SCHEMA","OUTPUT_SCHEMA","CliInterpretationGatewayEnvelope","assure_interpretation_exchange","cli_interpretation_gateway_digest"]
