"""Python parity for ``AFA-cli-P07-F04`` quality-control inference."""
from __future__ import annotations
import hashlib, json, re
from dataclasses import dataclass
from typing import Any, Mapping
from .research_contracts import PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError

FEATURE_ID="AFA-cli-P07-F04"; CONTRACT_VERSION="cli-federated-continual-quality-control-inference-engine/1.0"; INPUT_SCHEMA="QualityInferenceRequest4@1"; OUTPUT_SCHEMA="QualityInferenceReceipt7@1"; CONTENT_TYPE="application/vnd.aurora.quality-inference-receipt-7+json"
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return v==sorted(set(v))
@dataclass(frozen=True)
class QualityInferenceReceipt7:
 value:dict[str,Any]
 def to_dict(self)->dict[str,Any]:return dict(self.value)
 def validate(self)->None:
  v=self.value;a=v.get("artifact",{})
  if v.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or v.get("contract_version")!=CONTRACT_VERSION or v.get("feature_id")!=FEATURE_ID or v.get("boundary")!=PRECLINICAL_BOUNDARY or a.get("boundary")!=PRECLINICAL_BOUNDARY or v.get("raw_data_local") is not True or v.get("aggregate_only") is not True or v.get("checkpoint",0)<=0 or v.get("disposition") not in {"qualified","unresolved","blocked"} or not all(str(v.get(k,"")).strip() for k in ("request_id","federation_id","requester","purpose","semantic_profile")) or not v.get("observation_order") or not v.get("peer_order") or not v.get("effect_receipts"):raise ResearchContractError("quality inference identity, locality, observations, peers, disposition, or effects are incomplete")
  fields=("observation_order","passed_observation_order","failed_observation_order","unknown_observation_order","contradicted_observation_order","missing_observation_order","missing_modality_order","peer_order","qualified_peer_order","missing_peer_order","omission_order","uncertainty_order","negative_evidence_order","adversarial_event_order","effect_receipts")
  if any(not _ordered(v.get(k,[])) for k in fields):raise ResearchContractError("quality inference ordering is not canonical")
  if set(v["observation_order"])!=set(v["passed_observation_order"])|set(v["failed_observation_order"])|set(v["unknown_observation_order"])|set(v["contradicted_observation_order"])|set(v["missing_observation_order"]):raise ResearchContractError("quality observation states do not partition")
  if set(v["peer_order"])!=set(v["qualified_peer_order"])|set(v["missing_peer_order"]):raise ResearchContractError("quality peer states do not partition")
  if a.get("content_type")!=CONTENT_TYPE or a.get("content_hash")!=v.get("inference_digest") or not all(_digest(x) for x in [v.get("replay_identity"),v.get("inference_digest"),a.get("content_hash"),*a.get("provenance_digests",[])]):raise ResearchContractError("quality inference artifact digest is invalid")
def capability_manifest()->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":FEATURE_ID,"version":CONTRACT_VERSION,"owner_crate":"cli","consumers":["quality-control researcher","CLI operator","federation steward"],"behavior":"fuses typed quality summaries into a deterministic cross-site quality verdict","value":"prevents missing, contradictory, or unmeasured quality evidence from becoming a release pass","input_schema":INPUT_SCHEMA,"output_schema":OUTPUT_SCHEMA,"effects":["retain:quality-inference","exchange:aggregate-quality-summary"],"permissions":["retain:quality-receipts","exchange:aggregate-quality"],"autonomy_tier":"A2","boundary":PRECLINICAL_BOUNDARY}
def infer_quality(request:Mapping[str,Any])->QualityInferenceReceipt7:
 r=request
 if not all(str(r.get(k,"")).strip() for k in ("request_id","federation_id","requester","purpose","semantic_profile")) or not r.get("required_observation_order") or not r.get("required_modality_order") or not r.get("observations") or not r.get("peers") or int(r.get("checkpoint",0))<=0 or int(r.get("minimum_peer_quorum",0))<=0 or r.get("boundary")!=PRECLINICAL_BOUNDARY or r.get("raw_data_local") is not True or r.get("aggregate_only") is not True or not _digest(r.get("replay_identity")):raise ResearchContractError("quality inference request identity, observations, peers, checkpoint, replay, locality, or boundary is invalid")
 obs=sorted((dict(x) for x in r["observations"]),key=lambda x:str(x.get("observation_id",""))); ids=[str(x.get("observation_id","")) for x in obs]
 if len(set(ids))!=len(ids) or any(not x.get("observation_id") or not x.get("study_id") or not x.get("modality") or x.get("modality") not in r["required_modality_order"] or x.get("semantic_profile")!=r["semantic_profile"] or not all(_digest(x.get(k)) for k in ("baseline_digest","artifact_digest","provenance_digest","replay_identity")) or x.get("replay_identity")!=r["replay_identity"] or x.get("local_data") is not True for x in obs):raise ResearchContractError("quality evidence identity, modality, profile, digests, replay, or locality is invalid")
 required=set(r["required_observation_order"]);seen=set(ids);passed=set();failed=set();unknown=set();contradicted=set();missing=required-seen;modalities={x["modality"] for x in obs};missing_modality=set(r["required_modality_order"])-modalities;omissions={f"observation:{x}:missing" for x in missing}|{f"modality:{x}:missing" for x in missing_modality};uncertainty={f"observation:{x}:missing" for x in missing}|{f"modality:{x}:missing" for x in missing_modality};negative=set();adversarial=set(r.get("adversarial_events",[]))
 for x in obs:
  oid=x["observation_id"]
  if x.get("negative_result"):negative.add(f"observation:{oid}:negative-result")
  if x.get("evidence_state")=="contradicted":contradicted.add(oid);negative.add(f"observation:{oid}:contradicted")
  elif x.get("evidence_state") in {"unknown","unmeasured","speculative"}:unknown.add(oid);uncertainty.add(f"observation:{oid}:evidence-state")
  elif int(x.get("observed_milli",0))>=int(x.get("threshold_milli",0)):passed.add(oid)
  else:failed.add(oid);omissions.add(f"observation:{oid}:threshold-failed")
 peers=sorted((dict(x) for x in r["peers"]),key=lambda x:str(x.get("peer_id","")));peer_ids=[str(x.get("peer_id","")) for x in peers];qualified={x["peer_id"] for x in peers if x.get("semantic_profile")==r["semantic_profile"] and int(x.get("checkpoint",0))==int(r["checkpoint"]) and x.get("signed") is True and x.get("aggregate_only") is True and x.get("raw_data_local") is True and x.get("evidence_state") in {"proven","supported"}};missing_peers=set(peer_ids)-qualified;uncertainty|={f"peer:{x}:not-qualified" for x in missing_peers};global_block=not all(r.get(k) is True for k in ("policy_allow","protected_closure","signed_approval","raw_data_local","aggregate_only")) or bool(adversarial)
 if r.get("policy_allow") is not True:negative.add("request:policy-denied")
 if r.get("protected_closure") is not True:uncertainty.add("request:protected-closure-incomplete")
 if r.get("signed_approval") is not True:uncertainty.add("request:signed-approval-missing")
 omissions|={f"adversarial:{x}" for x in adversarial};disposition="blocked" if global_block or contradicted else "unresolved" if missing or missing_modality or unknown or failed or len(qualified)<int(r["minimum_peer_quorum"]) else "qualified"; omissions.add("request:quality-not-release-ready") if disposition!="qualified" else None
 payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"feature_id":FEATURE_ID,"request_id":r["request_id"],"federation_id":r["federation_id"],"requester":r["requester"],"purpose":r["purpose"],"semantic_profile":r["semantic_profile"],"checkpoint":int(r["checkpoint"]),"disposition":disposition,"observation_order":ids,"passed_observation_order":sorted(passed),"failed_observation_order":sorted(failed),"unknown_observation_order":sorted(unknown),"contradicted_observation_order":sorted(contradicted),"missing_observation_order":sorted(missing),"missing_modality_order":sorted(missing_modality),"peer_order":peer_ids,"qualified_peer_order":sorted(qualified),"missing_peer_order":sorted(missing_peers),"omission_order":sorted(omissions),"uncertainty_order":sorted(uncertainty),"negative_evidence_order":sorted(negative),"adversarial_event_order":sorted(adversarial),"replay_identity":r["replay_identity"],"boundary":PRECLINICAL_BOUNDARY};d=_hash(payload);result={**payload,"inference_digest":d,"artifact":{"artifact_id":f"quality-inference-receipt-7:{r['request_id']}","content_type":CONTENT_TYPE,"content_hash":d,"semantic_loss":[],"provenance_digests":sorted({x["provenance_digest"] for x in obs}),"boundary":PRECLINICAL_BOUNDARY},"effect_receipts":[f"retain:quality-inference:{r['request_id']}",f"exchange:aggregate-quality-summary:{r['request_id']}"] if disposition=="qualified" else ["block:unsafe-release"],"raw_data_local":True,"aggregate_only":True};q=QualityInferenceReceipt7(result);q.validate();return q
__all__=["FEATURE_ID","CONTRACT_VERSION","QualityInferenceReceipt7","capability_manifest","infer_quality"]
