"""Python parity for Dataops P32 typed multimodal-ingestion integrity cards."""
from __future__ import annotations
import hashlib,json,re
from typing import Any,Mapping
from .research_contracts import RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions";CONTENT_TYPE="application/vnd.aurora.dataops.ingestion-integrity-card-1+json"
DataAsset4=dict[str,Any];IngestionIntegrityRequest4=dict[str,Any];IngestionIntegrityCard7=dict[str,Any];IngestionIntegrityArtifact4=dict[str,Any];IngestionIntegrityError=ResearchContractError
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return isinstance(v,list) and v==sorted(set(v))
def manifest(*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"dataops","consumers":["ingestion gateway","QC workbench","lineage ledger","federation admission"],"behavior":f"qualify typed multimodal ingestion at {scale} ({mode})","value":"prevents low-quality, unlineaged, semantically incompatible, or non-local assets from entering research workflows","input_schema":"IngestionIntegrityRequest4@1","output_schema":"IngestionIntegrityCard7@1","effects":["emit:ingestion-card","retain:lineage-witness","block:unsafe-asset"],"permissions":["read:local-asset-metadata"],"determinism":"byte_stable","autonomy_tier":"A1","boundary":BOUNDARY}
def validate(o:Mapping[str,Any],*,feature_id:str|None=None)->None:
 a=o.get("artifact",{});bad=o.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or(feature_id is not None and o.get("feature_id")!=feature_id)or o.get("boundary")!=BOUNDARY or a.get("boundary")!=BOUNDARY or o.get("raw_data_local") is not True or o.get("aggregate_only") is not True or not _digest(o.get("replay_identity")) or not _digest(o.get("closure_digest")) or a.get("content_type")!=CONTENT_TYPE or a.get("content_hash")!=o.get("closure_digest")
 if bad:raise ResearchContractError("ingestion identity, locality, artifact, digest, or boundary is incomplete")
 for k in("asset_order","accepted_order","rejected_order","unknown_order","omitted_order","modality_order","dimension_order","ontology_order","qc_order","lineage_order","negative_order","effect_receipts"):
  if not _ordered(o.get(k,[])):raise ResearchContractError("ingestion vectors are not canonical")
 ids=set(o["asset_order"]);states=set(o["accepted_order"])|set(o["rejected_order"])|set(o["unknown_order"])|set(o["omitted_order"])
 if len(o["asset_order"])!=len(ids)or states!=ids:raise ResearchContractError("asset states do not partition")
def qualify(request:Mapping[str,Any],*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:
 if request.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or not request.get("request_id","").strip() or not request.get("purpose","").strip() or not request.get("assets") or not request.get("required_asset_order") or not _ordered(request["required_asset_order"]) or not _ordered(request.get("required_modality_order",[])) or not _digest(request.get("replay_identity")) or request.get("boundary")!=BOUNDARY or request.get("raw_data_local") is not True or request.get("aggregate_only") is not True or not _ordered(request.get("adversarial_events",[])) or request.get("asset_budget",0)<=0:raise ResearchContractError("ingestion identity, ordering, digest, locality, boundary, or budget is invalid")
 rows=sorted(request["assets"],key=lambda a:a.get("asset_id",""));seen=set();accepted=set();rejected=set();unknown=set();omitted=set();modalities=set();dimensions=set();ontologies=set();qc=set();lineage=set();negative=set();evidence=set()
 for a in rows:
  aid=a.get("asset_id","")
  if not aid.strip()or aid in seen or not a.get("modality","").strip()or not a.get("dimensions","").strip()or not a.get("unit","").strip()or not a.get("ontology","").strip()or not _digest(a.get("lineage_digest"))or not _digest(a.get("checksum"))or not a.get("evidence_state","").strip()or a.get("local") is not True or a.get("aggregate_only") is not True:raise ResearchContractError("asset identity, dimensions, ontology, digest, evidence, or locality is invalid")
  seen.add(aid);modalities.add(f"{aid}:{a['modality']}");dimensions.add(f"{aid}:{a['dimensions']}");ontologies.add(f"{aid}:{a['ontology']}");qc.add(f"{aid}:{a.get('qc_score_milli',0)}");lineage.add(f"{aid}:{a['lineage_digest']}");evidence.add(a["checksum"]);negative.add(f"{aid}:negative-result") if a.get("negative_result") else None
  if a["evidence_state"]=="unknown"or a["lineage_digest"]==request["replay_identity"]:unknown.add(aid)
  elif a.get("qc_score_milli",0)<a.get("qc_threshold_milli",0)or a["ontology"]=="unknown":rejected.add(aid)
  elif aid not in request["required_asset_order"]:omitted.add(aid)
  else:accepted.add(aid)
 missing=[x for x in request["required_asset_order"] if x not in seen];global_block=not all(request.get(k) is True for k in("policy_allowed","protected_closure","signed_manifest","raw_data_local","aggregate_only"))or bool(request.get("adversarial_events"))or len(rows)>request["asset_budget"]
 if global_block:omitted.update(seen);accepted.clear();rejected.clear();unknown.clear()
 disposition="blocked" if global_block else "unknown" if missing or unknown else "partial" if rejected or omitted else "qualified";payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"request_id":request["request_id"],"purpose":request["purpose"],"disposition":disposition,"asset_order":sorted(seen),"accepted_order":sorted(accepted),"rejected_order":sorted(rejected),"unknown_order":sorted(unknown),"omitted_order":sorted(omitted),"modality_order":sorted(modalities),"dimension_order":sorted(dimensions),"ontology_order":sorted(ontologies),"qc_order":sorted(qc),"lineage_order":sorted(lineage),"negative_order":sorted(negative),"replay_identity":request["replay_identity"],"raw_data_local":True,"aggregate_only":True,"boundary":BOUNDARY};d=_hash(payload);payload["closure_digest"]=d;payload["effect_receipts"]=[f"approve:ingestion:{request['request_id']}"] if disposition=="qualified" else ["block:unsafe-asset"];payload["artifact"]={"artifact_id":f"dataops-ingestion:{request['request_id']}","content_type":CONTENT_TYPE,"content_hash":d,"semantic_loss":payload["omitted_order"],"evidence_digests":sorted(evidence),"boundary":BOUNDARY};validate(payload,feature_id=feature_id);return payload
__all__=["BOUNDARY","CONTENT_TYPE","DataAsset4","IngestionIntegrityRequest4","IngestionIntegrityCard7","IngestionIntegrityArtifact4","IngestionIntegrityError","manifest","qualify","validate"]
