"""Cross-language contract for ``AFA-devplat-P26-F26``."""
from __future__ import annotations
import hashlib,json,re
from dataclasses import dataclass
from typing import Any,Mapping
from .research_contracts import PRECLINICAL_BOUNDARY,RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError

FEATURE_ID="AFA-devplat-P26-F26";CONTRACT_VERSION="devplat-multimodal-limitation-closure-assurance/1.0";INPUT_SCHEMA="DevplatLimitationCase2@1";OUTPUT_SCHEMA="DevplatClosureReceipt7@1";CONTENT_TYPE="application/vnd.aurora.devplat-closure-receipt-7+json";MAX_LIMITATIONS=8192
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _ordered(v:list[str])->bool:return v==sorted(set(v))
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _partition(u:list[str],parts:list[list[str]],m:str)->None:
 s=set(u);flat=sum(parts,[])
 if len(s)!=len(u) or len(flat)!=len(s) or len(set(flat))!=len(flat) or any(x not in s for x in flat):raise ResearchContractError(m)
@dataclass(frozen=True)
class DevplatClosureReceipt7:
 value:dict[str,Any]
 def to_dict(self)->dict[str,Any]:return dict(self.value)
 def validate(self)->None:
  v=self.value;a=v.get("artifact",{});text=("request_id","requester","purpose","semantic_profile")
  if not(v.get("schema_version")==RESEARCH_CONTRACT_SCHEMA_VERSION and v.get("contract_version")==CONTRACT_VERSION and v.get("feature_id")==FEATURE_ID and v.get("boundary")==PRECLINICAL_BOUNDARY and a.get("boundary")==PRECLINICAL_BOUNDARY and a.get("content_type")==CONTENT_TYPE and v.get("raw_data_local") is True and v.get("aggregate_only") is True and v.get("autonomy_tier")=="a1" and all(isinstance(v.get(k),str) and v[k].strip() for k in text) and v.get("ranked_limitation_order") and v.get("workflow_order") and v.get("site_order") and v.get("reasons") and v.get("effect_receipts") and v.get("disposition") in {"qualified","unresolved","blocked"}):raise ResearchContractError("limitation-closure identity, closure, locality, autonomy, or effects are incomplete")
  fields=("ranked_limitation_order","selected_limitation_order","unresolved_limitation_order","blocked_limitation_order","missing_limitation_order","workflow_order","selected_workflow_order","unresolved_workflow_order","blocked_workflow_order","missing_workflow_order","site_order","selected_site_order","unresolved_site_order","blocked_site_order","missing_site_order","closure_criteria_order","satisfied_criteria_order","counterexample_order","uncertainty_order","omission_order","negative_evidence_order","contradiction_order","adversarial_event_order")
  if any(not _ordered(list(v.get(k,[]))) for k in fields):raise ResearchContractError("limitation-closure ordering is not canonical")
  _partition(sorted(set(v["ranked_limitation_order"])|set(v.get("missing_limitation_order",[]))),[v["selected_limitation_order"],v["unresolved_limitation_order"],v["blocked_limitation_order"],v["missing_limitation_order"]],"limitation states do not form a complete partition")
  for u,p,m in (("workflow_order",("selected_workflow_order","unresolved_workflow_order","blocked_workflow_order","missing_workflow_order"),"workflow states do not form a complete partition"),("site_order",("selected_site_order","unresolved_site_order","blocked_site_order","missing_site_order"),"site states do not form a complete partition")):_partition(v[u],[list(v.get(x,[])) for x in p],m)
  if not all(_digest(v.get(k)) for k in ("replay_identity","provenance_digest","closure_digest")) or a.get("content_hash")!=v.get("closure_digest"):raise ResearchContractError("limitation-closure digest is inconsistent")
  if any(not(e.startswith("close:declared-limitation:") or e=="block:unsafe-release") for e in v["effect_receipts"]):raise ResearchContractError("limitation-closure effect is outside bounded gate")
  if v["disposition"]=="qualified" and v["effect_receipts"]!=[f"close:declared-limitation:{v['request_id']}"]:raise ResearchContractError("qualified limitation-closure effect is invalid")
  if v["disposition"]!="qualified" and v["effect_receipts"]!=["block:unsafe-release"]:raise ResearchContractError("non-qualified limitation-closure must block")
 def digest(self)->str:self.validate();return _hash(self.value)
def devplat_multimodal_limitation_closure_manifest()->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":FEATURE_ID,"version":CONTRACT_VERSION,"owner_crate":"devplat","consumers":["consortium administrator","limitation steward","independent evaluator"],"behavior":"verifies multimodal multi-study limitation and closure attestations with deterministic release gates","value":"makes cross-study limitation closure, counterexamples, omission, provenance, replay, policy, and release gates auditable before a research program proceeds","input_schema":INPUT_SCHEMA,"output_schema":OUTPUT_SCHEMA,"effects":["execute_local_computation","write_local_artifact"],"permissions":["close:declared-limitation"],"authority_requirements":[{"role":"consortium administrator","reason":"limitation closure changes release posture and requires explicit authority"}],"autonomy_tier":"A1","boundary":PRECLINICAL_BOUNDARY}
def _validate_request(q:Mapping[str,Any])->None:
 axes=("required_limitation_order","required_workflow_order","required_site_order");text=("request_id","requester","purpose","semantic_profile")
 if not(q.get("schema_version")==RESEARCH_CONTRACT_SCHEMA_VERSION and all(isinstance(q.get(k),str) and q[k].strip() for k in text) and all(q.get(k) for k in axes) and all(_ordered(list(q[k])) for k in axes) and _ordered(list(q.get("adversarial_event_order",[]))) and all(q.get(k,0)>0 for k in ("minimum_limitation_count","minimum_workflow_count","minimum_site_count","max_limitations")) and q["max_limitations"]<=MAX_LIMITATIONS and _digest(q.get("replay_identity")) and all(q.get(k) is True for k in ("policy_allow","protected_closure","signed_approval","raw_data_local","aggregate_only")) and q.get("boundary")==PRECLINICAL_BOUNDARY and q.get("limitations") and len(q["limitations"])<=MAX_LIMITATIONS):raise ResearchContractError("limitation-closure identity, closure, policy, capacity, replay, locality, or bounds are invalid")
 seen=set()
 for x in q["limitations"]:
  if not(all(isinstance(x.get(k),str) and x[k].strip() for k in ("limitation_id","workflow_id","site_id","claim_scope")) and x.get("semantic_profile")==q["semantic_profile"] and all(_digest(x.get(k)) for k in ("evidence_digest","provenance_digest","replay_identity")) and all(_ordered(list(x.get(k,[]))) for k in ("closure_criteria_order","satisfied_criteria_order","counterexample_order","uncertainty_order","omission_order")) and x["limitation_id"] not in seen):raise ResearchContractError("limitation identity, profile, digest, criteria, or ordering is invalid")
  seen.add(x["limitation_id"])
def assure_devplat_multimodal_limitation_closure(q:Mapping[str,Any])->DevplatClosureReceipt7:
 _validate_request(q);rank={"proven":0,"supported":1,"speculative":2,"unknown":3,"contradicted":4};rows=sorted((dict(x) for x in q["limitations"]),key=lambda x:(rank.get(x.get("evidence_state"),5),bool(x.get("stale")),x["limitation_id"]));ranked=[x["limitation_id"] for x in rows];required=set(q["required_limitation_order"]);selected=set();unresolved=set();blocked=set();uncertainty=set();omission=set();negative=set();contradiction=set();criteria=set();satisfied=set();counterexamples=set()
 for x in rows:
  criteria.update(x.get("closure_criteria_order",[]));satisfied.update(x.get("satisfied_criteria_order",[]));counterexamples.update(x.get("counterexample_order",[]));uncertainty.update(x.get("uncertainty_order",[]));omission.update(x.get("omission_order",[]));
  if x.get("negative_result") is True:negative.add(x["limitation_id"])
  if x.get("evidence_state")=="contradicted":contradiction.add(x["limitation_id"])
  hard=any(x.get(k) is not True for k in ("policy_allowed","protected_closure","signed_attestation","raw_data_local","aggregate_only")) or x.get("revoked") is True;soft=bool(x.get("stale")) or x.get("replay_identity")!=q["replay_identity"] or bool(x.get("uncertainty_order")) or bool(x.get("omission_order")) or not set(x.get("closure_criteria_order",[])).issubset(set(x.get("satisfied_criteria_order",[]))) or x.get("evidence_state") in {"unknown","speculative"};(blocked if hard or x.get("evidence_state")=="contradicted" else unresolved if soft else selected).add(x["limitation_id"])
 missing=required-set(ranked);omission.update(f"missing required limitation: {x}" for x in missing);workflows=set(q["required_workflow_order"])|{x["workflow_id"] for x in rows};sites=set(q["required_site_order"])|{x["site_id"] for x in rows}
 def group(field,u,state):return {v for v in u if any(x[field]==v and x["limitation_id"] in state for x in rows)}
 sw,uw,bw=group("workflow_id",workflows,selected),group("workflow_id",workflows,unresolved),group("workflow_id",workflows,blocked);mw=workflows-sw-uw-bw;ss,us,bs=group("site_id",sites,selected),group("site_id",sites,unresolved),group("site_id",sites,blocked);ms=sites-ss-us-bs;global_open=all(q.get(k) is True for k in ("policy_allow","protected_closure","signed_approval","raw_data_local","aggregate_only")) and not q.get("adversarial_event_order");admitted=len(selected)+len(unresolved);gate=not global_open or blocked or missing or bw or mw or bs or ms or admitted<q["minimum_limitation_count"] or len(sw)+len(uw)<q["minimum_workflow_count"] or len(ss)+len(us)<q["minimum_site_count"] or len(selected)>q["max_limitations"];disposition="blocked" if gate else ("unresolved" if unresolved or uw or us else "qualified");effects=[f"close:declared-limitation:{q['request_id']}"] if disposition=="qualified" else ["block:unsafe-release"]
 p={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"feature_id":FEATURE_ID,"request_id":q["request_id"],"requester":q["requester"],"purpose":q["purpose"],"semantic_profile":q["semantic_profile"],"disposition":disposition,"ranked_limitation_order":ranked,"selected_limitation_order":sorted(selected),"unresolved_limitation_order":sorted(unresolved),"blocked_limitation_order":sorted(blocked),"missing_limitation_order":sorted(missing),"workflow_order":sorted(workflows),"selected_workflow_order":sorted(sw),"unresolved_workflow_order":sorted(uw),"blocked_workflow_order":sorted(bw),"missing_workflow_order":sorted(mw),"site_order":sorted(sites),"selected_site_order":sorted(ss),"unresolved_site_order":sorted(us),"blocked_site_order":sorted(bs),"missing_site_order":sorted(ms),"closure_criteria_order":sorted(criteria),"satisfied_criteria_order":sorted(satisfied),"counterexample_order":sorted(counterexamples),"uncertainty_order":sorted(uncertainty),"omission_order":sorted(omission),"negative_evidence_order":sorted(negative),"contradiction_order":sorted(contradiction),"adversarial_event_order":sorted(q.get("adversarial_event_order",[])),"replay_identity":q["replay_identity"],"provenance_digest":_hash(sorted(x["provenance_digest"] for x in rows)),"reasons":["all limitation criteria, policy, replay, provenance, and locality gates passed" if disposition=="qualified" else "limitation closure remains blocked or unresolved"],"effect_receipts":effects,"raw_data_local":True,"aggregate_only":True,"autonomy_tier":"a1","boundary":PRECLINICAL_BOUNDARY};d=_hash(p);p["closure_digest"]=d;p["artifact"]={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"artifact_id":f"limitation-closure:{q['request_id']}","content_type":CONTENT_TYPE,"content_hash":d,"semantic_loss":[],"provenance":[],"boundary":PRECLINICAL_BOUNDARY};r=DevplatClosureReceipt7(p);r.validate();return r
def devplatMultimodalLimitationClosureDigest(receipt:DevplatClosureReceipt7)->str:return receipt.digest()
__all__=["FEATURE_ID","CONTRACT_VERSION","INPUT_SCHEMA","OUTPUT_SCHEMA","CONTENT_TYPE","DevplatClosureReceipt7","devplat_multimodal_limitation_closure_manifest","assure_devplat_multimodal_limitation_closure","devplatMultimodalLimitationClosureDigest"]
