"""Python parity for Metrics P32 auditable-discovery-rate integrity cards."""
from __future__ import annotations
import hashlib,json,re
from typing import Any,Mapping
from .research_contracts import RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions";CONTENT_TYPE="application/vnd.aurora.metrics.discovery-rate-integrity-card-1+json"
DiscoveryObservation4=dict[str,Any];DiscoveryRateRequest4=dict[str,Any];DiscoveryRateCard7=dict[str,Any];DiscoveryRateArtifact4=dict[str,Any];DiscoveryRateIntegrityError=ResearchContractError
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return isinstance(v,list) and v==sorted(set(v))
def manifest(*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"metrics","consumers":["evaluation engine","research program steward","benchmark operator","research workbench"],"behavior":f"qualify auditable discovery-rate measurements at {scale} ({mode})","value":"measures independently reproducible, policy-compliant research conclusions per unit cost and time against a fixed baseline without inflating automation volume","input_schema":"DiscoveryRateRequest4@1","output_schema":"DiscoveryRateCard7@1","effects":["emit:evaluation-card","retain:negative-rate-evidence","block:unsafe-release"],"permissions":["read:local-evaluation-fixtures"],"determinism":"byte_stable","autonomy_tier":"A1","boundary":BOUNDARY}
def validate(o:Mapping[str,Any],*,feature_id:str|None=None)->None:
 a=o.get("artifact",{});bad=o.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or(feature_id is not None and o.get("feature_id")!=feature_id)or not o.get("request_id")or not o.get("purpose")or o.get("boundary")!=BOUNDARY or a.get("boundary")!=BOUNDARY or o.get("raw_data_local") is not True or o.get("aggregate_only") is not True or not _digest(o.get("replay_identity")) or not _digest(o.get("closure_digest")) or a.get("content_type")!=CONTENT_TYPE or a.get("content_hash")!=o.get("closure_digest") or o.get("discovery_numerator",0)>o.get("discovery_denominator",0)
 if bad:raise ResearchContractError("discovery identity, locality, artifact, digest, boundary, or rate is incomplete")
 for k in("observation_order","qualified_order","rejected_order","unknown_order","omitted_order","baseline_order","conclusion_order","evidence_order","effect_receipts"):
  if not _ordered(o.get(k,[])):raise ResearchContractError("discovery vectors are not canonical")
 ids=set(o["observation_order"]);states=set(o["qualified_order"])|set(o["rejected_order"])|set(o["unknown_order"])|set(o["omitted_order"])
 if len(o["observation_order"])!=len(ids)or states!=ids:raise ResearchContractError("observation states do not partition")
def qualify(request:Mapping[str,Any],*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:
 if request.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or not request.get("request_id","").strip() or not request.get("purpose","").strip() or not request.get("observations") or not request.get("required_observation_order") or not _ordered(request["required_observation_order"]) or not _digest(request.get("replay_identity")) or not _digest(request.get("baseline_digest")) or not _digest(request.get("benchmark_world_digest")) or not request.get("metric_version","").strip() or request.get("boundary")!=BOUNDARY or request.get("raw_data_local") is not True or request.get("aggregate_only") is not True or not _ordered(request.get("adversarial_events",[])) or request.get("observation_budget",0)<=0:raise ResearchContractError("discovery identity, ordering, baseline, digest, locality, boundary, or budget is invalid")
 rows=sorted(request["observations"],key=lambda a:a.get("observation_id",""));seen=set();qualified=set();rejected=set();unknown=set();omitted=set();baselines=set();conclusions=set();evidence=set();cost=duration=0
 for o in rows:
  oid=o.get("observation_id","")
  if not oid.strip()or oid in seen or not _digest(o.get("conclusion_digest"))or not _digest(o.get("baseline_digest"))or not _digest(o.get("benchmark_world_digest"))or not o.get("evidence_state","").strip()or o.get("local") is not True or o.get("aggregate_only") is not True:raise ResearchContractError("observation identity, digests, evidence, or locality is invalid")
  seen.add(oid);baselines.add(f"{oid}:{o['baseline_digest']}");conclusions.add(f"{oid}:{o['conclusion_digest']}");evidence.add(o["conclusion_digest"]);cost+=int(o.get("cost_micros",0));duration+=int(o.get("duration_ms",0))
  if o["evidence_state"]=="unknown"or o["conclusion_digest"]==request["replay_identity"]:unknown.add(oid)
  elif o["baseline_digest"]!=request["baseline_digest"]or o["benchmark_world_digest"]!=request["benchmark_world_digest"]or o.get("independently_reproduced") is not True or o.get("policy_compliant") is not True:rejected.add(oid)
  elif oid not in request["required_observation_order"]:omitted.add(oid)
  else:qualified.add(oid)
 missing=[x for x in request["required_observation_order"] if x not in seen];global_block=not all(request.get(k) is True for k in("policy_allowed","protected_closure","signed_manifest","raw_data_local","aggregate_only"))or bool(request.get("adversarial_events"))or len(rows)>request["observation_budget"]
 if global_block:omitted.update(seen);qualified.clear();rejected.clear();unknown.clear()
 disposition="blocked" if global_block else "unknown" if missing or unknown else "partial" if rejected or omitted else "qualified";payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"request_id":request["request_id"],"purpose":request["purpose"],"disposition":disposition,"observation_order":sorted(seen),"qualified_order":sorted(qualified),"rejected_order":sorted(rejected),"unknown_order":sorted(unknown),"omitted_order":sorted(omitted),"baseline_order":sorted(baselines),"conclusion_order":sorted(conclusions),"evidence_order":sorted(evidence),"replay_identity":request["replay_identity"],"raw_data_local":True,"aggregate_only":True,"boundary":BOUNDARY};d=_hash(payload);payload["closure_digest"]=d;payload["discovery_numerator"]=len(qualified);payload["discovery_denominator"]=len(rows);payload["cost_micros"]=cost;payload["duration_ms"]=duration;payload["effect_receipts"]=[f"approve:discovery-rate:{request['request_id']}"] if disposition=="qualified" else ["block:unsafe-release"];payload["artifact"]={"artifact_id":f"metrics-discovery-rate:{request['request_id']}","content_type":CONTENT_TYPE,"content_hash":d,"semantic_loss":payload["omitted_order"],"evidence_digests":sorted(evidence),"boundary":BOUNDARY};validate(payload,feature_id=feature_id);return payload
__all__=["BOUNDARY","CONTENT_TYPE","DiscoveryObservation4","DiscoveryRateRequest4","DiscoveryRateCard7","DiscoveryRateArtifact4","DiscoveryRateIntegrityError","manifest","qualify","validate"]
