"""Python parity surface for AFA-foundation-P08-F27."""
from __future__ import annotations
from dataclasses import dataclass
import hashlib, json, re
from typing import Any, Mapping, Sequence
from .research_contracts import PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError

FEATURE_ID="AFA-foundation-P08-F27"; CONTRACT_VERSION="foundation-prospective-mechanism-exploration-assurance/1.0"; INPUT_SCHEMA="MechanismCandidateBatch1@1"; OUTPUT_SCHEMA="MechanismAssuranceReceipt1@1"
def _digest(value:Any)->bool:return isinstance(value,str) and re.fullmatch(r"[0-9a-f]{64}",value) is not None
def _canonical(values:Sequence[str])->bool:return tuple(sorted(set(values)))==tuple(values)
def _hash(value:Any)->str:return hashlib.sha256(json.dumps(value,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()

@dataclass(frozen=True)
class MechanismExplorationAssuranceReceipt:
    request_id:str; consumer:str; scope:str; batch_id:str; baseline_id:str; algorithm_version:str; capacity:int; active_jobs:int; verdict:str; candidate_order:tuple[str,...]; admitted_order:tuple[str,...]; blocked_order:tuple[str,...]; unknown_order:tuple[str,...]; required_order:tuple[str,...]; check_order:tuple[str,...]; passed_checks:tuple[str,...]; counterexamples:tuple[str,...]; omissions:tuple[str,...]; uncertainty:tuple[str,...]; negative_evidence:tuple[str,...]; replay_identity:str; assurance_digest:str; effect_receipts:tuple[str,...]; artifact:dict[str,Any]; schema_version:str=RESEARCH_CONTRACT_SCHEMA_VERSION; contract_version:str=CONTRACT_VERSION; feature_id:str=FEATURE_ID; raw_data_local:bool=True; boundary:str=PRECLINICAL_BOUNDARY
    def validate(self)->None:
        if (self.schema_version,self.contract_version,self.feature_id)!=(RESEARCH_CONTRACT_SCHEMA_VERSION,CONTRACT_VERSION,FEATURE_ID) or self.boundary!=PRECLINICAL_BOUNDARY or not self.raw_data_local or not self.request_id.strip() or not self.consumer.strip() or not self.scope.strip() or not self.batch_id.strip() or not self.baseline_id.strip() or not self.algorithm_version.strip() or self.capacity<=0 or self.active_jobs>self.capacity or self.verdict not in {"qualified","conditional","unknown","blocked"} or not self.candidate_order or not self.effect_receipts: raise ResearchContractError("mechanism assurance identity, capacity, candidates, verdict, locality, or effects are incomplete")
        for values in (self.candidate_order,self.admitted_order,self.blocked_order,self.unknown_order,self.required_order,self.check_order,self.passed_checks,self.counterexamples,self.omissions,self.uncertainty,self.negative_evidence,self.effect_receipts):
            if not _canonical(values): raise ResearchContractError("mechanism assurance ordering is not canonical")
        for value in (self.replay_identity,self.assurance_digest,self.artifact.get("content_hash")):
            if not _digest(value): raise ResearchContractError("mechanism assurance digest is invalid")
        if self.artifact.get("media_type")!="application/vnd.aurora.foundation-mechanism-exploration-assurance+json": raise ResearchContractError("mechanism assurance artifact media type is invalid")
        if self.verdict=="qualified" and self.effect_receipts!=("assure:foundation-mechanism-exploration",): raise ResearchContractError("qualified mechanism assurance effect is invalid")
        if self.verdict!="qualified" and self.effect_receipts!=("block:unsafe-release",): raise ResearchContractError("non-qualified mechanism assurance must block release")

def assure_mechanism_exploration(*,request_id:str,consumer:str,scope:str,batch_id:str,baseline_id:str,algorithm_version:str,min_support_score:int,capacity:int,active_jobs:int,candidates:Sequence[Mapping[str,Any]],required_mechanism_ids:Sequence[str],policy_allow:bool,protected_closure:bool,signed_approval:bool,raw_data_local:bool,replay_identity:str,boundary:str=PRECLINICAL_BOUNDARY)->MechanismExplorationAssuranceReceipt:
    if not request_id.strip() or not consumer.strip() or not scope.strip() or not batch_id.strip() or not baseline_id.strip() or not algorithm_version.strip() or capacity<=0 or active_jobs>capacity or not candidates or not raw_data_local or not _digest(replay_identity) or boundary!=PRECLINICAL_BOUNDARY or not _canonical(required_mechanism_ids): raise ResearchContractError("mechanism assurance identity, capacity, candidates, locality, replay, or boundary is invalid")
    rows=sorted((dict(c) for c in candidates),key=lambda c:(-int(c.get("support_score",0)),str(c.get("mechanism_id","")))); ids=tuple(sorted(str(c.get("mechanism_id","")) for c in rows)); admitted=[];blocked=[];unknown=[]; omissions=[]; uncertainty=[]; negative=[]
    for c in rows:
        mid=str(c.get("mechanism_id","")); state=str(c.get("evidence_state","")); complete=all(_digest(c.get(k)) for k in ("evidence_digest","provenance_digest","artifact_digest","comparability_digest"));
        if not complete: blocked.append(mid); omissions.append(f"{mid}:typed-evidence-or-provenance"); continue
        if c.get("negative_result"): negative.append(f"{mid}:negative-result")
        if state=="supported" and int(c.get("support_score",0))>=min_support_score: admitted.append(mid)
        elif state in {"unknown","speculative"}: unknown.append(mid); uncertainty.append(f"{mid}:evidence-unknown-or-unmeasured")
        else: blocked.append(mid); omissions.append(f"{mid}:contradicted-or-below-support-threshold")
    admitted=tuple(sorted(set(admitted))); blocked=tuple(sorted(set(blocked))); unknown=tuple(sorted(set(unknown))); omissions=tuple(sorted(set(omissions))); uncertainty=tuple(sorted(set(uncertainty))); negative=tuple(sorted(set(negative))); missing=tuple(sorted(set(required_mechanism_ids)-set(admitted))); counter=tuple(sorted(f"required mechanism not admitted: {x}" for x in missing)); checks=tuple(sorted(("baseline and algorithm binding","candidate identities and canonical ordering","negative and unknown evidence retention","replay identity binding","typed evidence, provenance, artifact, and comparability digests"))); verdict="blocked" if not policy_allow or not protected_closure or not signed_approval else ("unknown" if not admitted else ("conditional" if missing or _saturated(active_jobs,capacity) else "qualified")); uncertainty=tuple(sorted(set(uncertainty+(("capacity headroom is exhausted",) if _saturated(active_jobs,capacity) else ()) ))); passed=checks if verdict=="qualified" else (); effect=("assure:foundation-mechanism-exploration",) if verdict=="qualified" else ("block:unsafe-release",); payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"feature_id":FEATURE_ID,"request_id":request_id,"consumer":consumer,"scope":scope,"batch_id":batch_id,"baseline_id":baseline_id,"algorithm_version":algorithm_version,"capacity":capacity,"active_jobs":active_jobs,"verdict":verdict,"candidate_order":list(ids),"admitted_order":list(admitted),"blocked_order":list(blocked),"unknown_order":list(unknown),"required_order":list(required_mechanism_ids),"check_order":list(checks),"passed_checks":list(passed),"counterexamples":list(counter),"omissions":list(omissions),"uncertainty":list(uncertainty),"negative_evidence":list(negative),"replay_identity":replay_identity,"raw_data_local":True,"boundary":PRECLINICAL_BOUNDARY}; ad=_hash(payload); receipt=MechanismExplorationAssuranceReceipt(request_id=request_id,consumer=consumer,scope=scope,batch_id=batch_id,baseline_id=baseline_id,algorithm_version=algorithm_version,capacity=capacity,active_jobs=active_jobs,verdict=verdict,candidate_order=ids,admitted_order=admitted,blocked_order=blocked,unknown_order=unknown,required_order=tuple(required_mechanism_ids),check_order=checks,passed_checks=passed,counterexamples=counter,omissions=omissions,uncertainty=uncertainty,negative_evidence=negative,replay_identity=replay_identity,assurance_digest=ad,effect_receipts=effect,artifact={"content_hash":_hash({**payload,"assurance_digest":ad}),"media_type":"application/vnd.aurora.foundation-mechanism-exploration-assurance+json"}); receipt.validate(); return receipt
def _saturated(active:int,capacity:int)->bool:return active*100>=capacity*90
__all__=["FEATURE_ID","CONTRACT_VERSION","MechanismExplorationAssuranceReceipt","assure_mechanism_exploration"]
