"""Python parity surface for ``AFA-governance-P14-F28``."""
from __future__ import annotations
from dataclasses import dataclass
import hashlib, json, re
from typing import Any, Mapping, Sequence
from .research_contracts import PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError
FEATURE_ID="AFA-governance-P14-F28"; CONTRACT_VERSION="governance-federated-continual-interpretation-assurance/1.0"; INPUT_SCHEMA="EvidenceBackedResult2@1"; OUTPUT_SCHEMA="InteractiveInterpretation7@1"; CONTENT_TYPE="application/vnd.aurora.interactive-interpretation-7+json"
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _canonical(v:Sequence[str])->bool:return tuple(v)==tuple(sorted(set(v)))
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
@dataclass(frozen=True)
class GovernanceFederatedInterpretationReceipt:
 request_id:str;semantic_profile:str;disposition:str;candidate_order:tuple[str,...];qualified_order:tuple[str,...];unresolved_order:tuple[str,...];blocked_order:tuple[str,...];incomparable_order:tuple[str,...];missing_study_order:tuple[str,...];missing_modality_order:tuple[str,...];omission_order:tuple[str,...];uncertainty_order:tuple[str,...];negative_evidence_order:tuple[str,...];replay_identity:str;interpretation_digest:str;artifact:dict[str,Any];effect_receipts:tuple[str,...];raw_data_local:bool=True;aggregate_only:bool=True;boundary:str=PRECLINICAL_BOUNDARY;schema_version:str=RESEARCH_CONTRACT_SCHEMA_VERSION;contract_version:str=CONTRACT_VERSION;feature_id:str=FEATURE_ID
 def to_dict(self)->dict[str,Any]:
  return {"schema_version":self.schema_version,"contract_version":self.contract_version,"feature_id":self.feature_id,"request_id":self.request_id,"semantic_profile":self.semantic_profile,"disposition":self.disposition,"candidate_order":list(self.candidate_order),"qualified_order":list(self.qualified_order),"unresolved_order":list(self.unresolved_order),"blocked_order":list(self.blocked_order),"incomparable_order":list(self.incomparable_order),"missing_study_order":list(self.missing_study_order),"missing_modality_order":list(self.missing_modality_order),"omission_order":list(self.omission_order),"uncertainty_order":list(self.uncertainty_order),"negative_evidence_order":list(self.negative_evidence_order),"replay_identity":self.replay_identity,"interpretation_digest":self.interpretation_digest,"artifact":self.artifact,"effect_receipts":list(self.effect_receipts),"raw_data_local":self.raw_data_local,"aggregate_only":self.aggregate_only,"boundary":self.boundary}
 def validate(self)->None:
  if (self.schema_version,self.contract_version,self.feature_id)!=(RESEARCH_CONTRACT_SCHEMA_VERSION,CONTRACT_VERSION,FEATURE_ID) or self.boundary!=PRECLINICAL_BOUNDARY or self.artifact.get("boundary")!=PRECLINICAL_BOUNDARY or not self.raw_data_local or not self.aggregate_only or not all(v.strip() for v in (self.request_id,self.semantic_profile)) or not self.candidate_order or not self.effect_receipts or self.disposition not in {"qualified","unresolved","blocked"}:raise ResearchContractError("interpretation assurance identity, locality, candidates, or effects are incomplete")
  for values in (self.candidate_order,self.qualified_order,self.unresolved_order,self.blocked_order,self.incomparable_order,self.missing_study_order,self.missing_modality_order,self.omission_order,self.uncertainty_order,self.negative_evidence_order,self.effect_receipts):
   if not _canonical(values):raise ResearchContractError("interpretation assurance ordering is not canonical")
  parts=[*self.qualified_order,*self.unresolved_order,*self.blocked_order]
  if set(parts)!=set(self.candidate_order) or len(parts)!=len(set(parts)):raise ResearchContractError("interpretation states do not partition candidates")
  if not all(_digest(v) for v in (self.replay_identity,self.interpretation_digest,self.artifact.get("content_hash"))):raise ResearchContractError("interpretation assurance digest is invalid")
  if self.artifact.get("content_type")!=CONTENT_TYPE:raise ResearchContractError("interpretation artifact type is invalid")
  if self.effect_receipts!=("block:unsafe-release",):raise ResearchContractError("interpretation assurance must expose release gate receipt")
def governance_federated_interpretation_manifest()->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":FEATURE_ID,"version":CONTRACT_VERSION,"owner_crate":"governance","consumers":["release governance board","visualization reviewer","research software operator"],"behavior":"verifies federated continual typed multimodal interpretations with comparability and explicit release-gate witnesses","value":"prevents an attractive visualization from hiding incomparable, missing, contradictory, or unproven preclinical evidence","input_schema":INPUT_SCHEMA,"output_schema":OUTPUT_SCHEMA,"effects":["block:unsafe-release"],"autonomy_tier":"A1","boundary":PRECLINICAL_BOUNDARY}
def assure_governance_federated_interpretation(*,request_id:str,semantic_profile:str,required_study_order:Sequence[str],required_modality_order:Sequence[str],comparability_digest:str,replay_identity:str,candidates:Sequence[Mapping[str,Any]],budget_units:int,policy_allow:bool,protected_closure:bool,signed_approval:bool,raw_data_local:bool,aggregate_only:bool,adversarial_events:Sequence[str]=(),boundary:str=PRECLINICAL_BOUNDARY)->GovernanceFederatedInterpretationReceipt:
 if not all(v.strip() for v in (request_id,semantic_profile)) or not required_study_order or not required_modality_order or not candidates or not _canonical(required_study_order) or not _canonical(required_modality_order) or not _canonical(adversarial_events) or not _digest(comparability_digest) or not _digest(replay_identity) or budget_units<=0 or not raw_data_local or not aggregate_only or boundary!=PRECLINICAL_BOUNDARY:raise ResearchContractError("interpretation request identity, study/modality closure, digests, budget, locality, or boundary is invalid")
 rows=[dict(x) for x in candidates]; seen=set()
 for row in rows:
  rid=str(row.get("result_id",""));
  if not rid.strip() or rid in seen or not str(row.get("study_id","")).strip() or not str(row.get("modality","")).strip() or not str(row.get("semantic_profile","")).strip() or not all(_digest(row.get(k)) for k in ("comparability_digest","evidence_digest","provenance_digest","artifact_digest")) or int(row.get("cost_units",0))<=0 or not _canonical(row.get("omissions",())) or not _canonical(row.get("uncertainty",())):raise ResearchContractError(f"interpretation candidate {rid} is malformed or duplicated")
  seen.add(rid)
 rows.sort(key=lambda x:(-int(x.get("support_score_milli",0)),str(x["result_id"]))); order=tuple(sorted(str(x["result_id"]) for x in rows)); qualified:set[str]=set(); unresolved:set[str]=set(); blocked:set[str]=set(); incomparable:set[str]=set(); omissions:set[str]=set(); uncertainty:set[str]=set(); negative:set[str]=set(); spent=0
 for row in rows:
  rid=str(row["result_id"]); state=str(row.get("evidence_state","")); omissions.update(f"{rid}:{v}" for v in row.get("omissions",())); uncertainty.update(f"{rid}:{v}" for v in row.get("uncertainty",()))
  if row.get("negative_result"):negative.add(f"{rid}:negative-result")
  if row["comparability_digest"]!=comparability_digest or row["semantic_profile"]!=semantic_profile:incomparable.add(rid);unresolved.add(rid);omissions.add(f"{rid}:comparability-mismatch")
  elif state=="contradicted" or not row.get("local_data") or not row.get("permitted"):blocked.add(rid)
  elif state in {"unknown","speculative"} or row.get("omissions") or row.get("uncertainty"):unresolved.add(rid)
  elif spent+int(row["cost_units"])>budget_units:unresolved.add(rid);omissions.add(f"{rid}:budget-exhausted")
  else:spent+=int(row["cost_units"]);qualified.add(rid)
 observed_studies={str(x["study_id"]) for x in rows if str(x["result_id"]) in qualified};observed_modalities={str(x["modality"]) for x in rows if str(x["result_id"]) in qualified};missing_study=tuple(sorted(set(required_study_order)-observed_studies));missing_modality=tuple(sorted(set(required_modality_order)-observed_modalities));omissions.update(f"{x}:required-study-missing" for x in missing_study);omissions.update(f"{x}:required-modality-missing" for x in missing_modality);negative.update(f"adversarial:{x}" for x in adversarial_events)
 global_block=not policy_allow or not protected_closure or not signed_approval or not raw_data_local or not aggregate_only or bool(adversarial_events)
 if not policy_allow:negative.add("request:policy-denied")
 if not protected_closure:uncertainty.add("request:protected-closure-incomplete")
 if not signed_approval:uncertainty.add("request:signed-approval-missing")
 if global_block:blocked.update(order);qualified.clear();unresolved.clear();incomparable.clear();omissions.add("request:release-gate-blocked")
 disposition="blocked" if global_block else "qualified" if qualified and not missing_study and not missing_modality else "unresolved";qo,uo,bo=tuple(sorted(qualified)),tuple(sorted(unresolved)),tuple(sorted(blocked));io=tuple(sorted(incomparable));oo,uu,nn=tuple(sorted(omissions)),tuple(sorted(uncertainty)),tuple(sorted(negative));effects=("block:unsafe-release",);payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"feature_id":FEATURE_ID,"request_id":request_id,"semantic_profile":semantic_profile,"disposition":disposition,"candidate_order":list(order),"qualified_order":list(qo),"unresolved_order":list(uo),"blocked_order":list(bo),"incomparable_order":list(io),"missing_study_order":list(missing_study),"missing_modality_order":list(missing_modality),"omission_order":list(oo),"uncertainty_order":list(uu),"negative_evidence_order":list(nn),"replay_identity":replay_identity,"effect_receipts":list(effects),"raw_data_local":raw_data_local,"aggregate_only":aggregate_only,"boundary":PRECLINICAL_BOUNDARY};d=_hash(payload);artifact={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"artifact_id":f"interactive-interpretation:{request_id}","content_type":CONTENT_TYPE,"content_hash":d,"semantic_loss":[],"provenance":[],"boundary":PRECLINICAL_BOUNDARY};result=GovernanceFederatedInterpretationReceipt(request_id,semantic_profile,disposition,order,qo,uo,bo,io,missing_study,missing_modality,oo,uu,nn,replay_identity,d,artifact,effects);result.validate();return result
def governanceFederatedInterpretationDigest(result:GovernanceFederatedInterpretationReceipt)->str:result.validate();return _hash(result.to_dict())
__all__=["FEATURE_ID","CONTRACT_VERSION","INPUT_SCHEMA","OUTPUT_SCHEMA","GovernanceFederatedInterpretationReceipt","governance_federated_interpretation_manifest","assure_governance_federated_interpretation","governanceFederatedInterpretationDigest"]
