"""Python parity for ``AFA-ids-P11-F16`` laboratory integration fabric."""
from __future__ import annotations
import hashlib,json,re
from dataclasses import dataclass
from typing import Any,Mapping
from .research_contracts import PRECLINICAL_BOUNDARY,RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
FEATURE_ID="AFA-ids-P11-F16"; CONTRACT_VERSION="ids-federated-continual-laboratory-integration-workflow-fabric/1.0"; INPUT_SCHEMA="LaboratoryIntegrationRequest6@1"; OUTPUT_SCHEMA="LaboratoryIntegrationReport9@1"; CONTENT_TYPE="application/vnd.aurora.laboratory-integration-report-9+json"
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return tuple(v)==tuple(sorted(set(v)))
@dataclass(frozen=True)
class LaboratoryIntegrationReport9:
 value:dict[str,Any]
 def to_dict(self)->dict[str,Any]:return dict(self.value)
 def validate(self)->None:
  v=self.value
  if v.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or v.get("contract_version")!=CONTRACT_VERSION or v.get("feature_id")!=FEATURE_ID or v.get("boundary")!=PRECLINICAL_BOUNDARY or v.get("raw_data_local") is not True or v.get("aggregate_only") is not True or not all(str(v.get(k,"")).strip() for k in ("request_id","federation_id","workflow_id","requester","purpose","semantic_profile")) or int(v.get("checkpoint",0))<=0 or not v.get("instrument_order") or not v.get("action_order") or not v.get("peer_order") or not v.get("effect_receipts") or v.get("disposition") not in {"qualified","unresolved","blocked"}:raise ResearchContractError("laboratory integration identity, locality, instruments, actions, peers, or effects are incomplete")
  fields=("instrument_order","ready_instrument_order","unresolved_instrument_order","blocked_instrument_order","action_order","ready_action_order","unresolved_action_order","blocked_action_order","peer_order","qualified_peer_order","missing_peer_order","interlock_order","emergency_stop_order","compensation_order","omission_order","uncertainty_order","negative_evidence_order","effect_receipts")
  if any(not _ordered(v.get(k,[])) for k in fields):raise ResearchContractError("laboratory integration ordering is not canonical")
  instruments=set(v["instrument_order"]);ip=[*v["ready_instrument_order"],*v["unresolved_instrument_order"],*v["blocked_instrument_order"]]; actions=set(v["action_order"]);ap=[*v["ready_action_order"],*v["unresolved_action_order"],*v["blocked_action_order"]]; peers=set(v["peer_order"]);pp=[*v["qualified_peer_order"],*v["missing_peer_order"]]
  if len(ip)!=len(instruments) or set(ip)!=instruments or len(set(ip))!=len(ip) or len(ap)!=len(actions) or set(ap)!=actions or len(set(ap))!=len(ap) or len(pp)!=len(peers) or set(pp)!=peers or len(set(pp))!=len(pp):raise ResearchContractError("laboratory integration states do not partition")
  a=v.get("artifact",{}); ds=[v.get("replay_identity"),v.get("integration_digest"),a.get("content_hash"),*a.get("provenance_digests",[])];
  if not all(_digest(x) for x in ds) or a.get("content_type")!=CONTENT_TYPE or a.get("boundary")!=PRECLINICAL_BOUNDARY or a.get("content_hash")!=v.get("integration_digest"):raise ResearchContractError("laboratory integration artifact or digest is invalid")
  if any(not e.startswith(("exchange:permitted-summaries:","manage:local-capability:")) and e!="block:unsafe-release" for e in v["effect_receipts"]):raise ResearchContractError("laboratory integration effect is outside governed gate")
def laboratory_integration_manifest()->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":FEATURE_ID,"version":CONTRACT_VERSION,"owner_crate":"ids","consumers":["laboratory integration engineer","instrument safety officer","federation steward"],"behavior":"compiles federated instrument and action attestations into a fail-closed preflight workflow","value":"makes interlocks, emergency stops, compensation, permissions, evidence, and federation closure auditable before a physical gateway","input_schema":INPUT_SCHEMA,"output_schema":OUTPUT_SCHEMA,"effects":["exchange:permitted-summaries","manage:local-capability"],"permissions":["read:instrument-capability-attestations"],"autonomy_tier":"A2","boundary":PRECLINICAL_BOUNDARY}
def integrate_laboratory_workflow(req:Mapping[str,Any])->LaboratoryIntegrationReport9:
 if not all(str(req.get(k,"")).strip() for k in ("request_id","federation_id","workflow_id","requester","purpose","semantic_profile","required_protocol_version")) or not req.get("instruments") or not req.get("actions") or not req.get("peers") or int(req.get("checkpoint",0))<=0 or int(req.get("max_budget_units",0))<=0 or int(req.get("minimum_peer_quorum",0))<=0 or req.get("boundary")!=PRECLINICAL_BOUNDARY or req.get("raw_data_local") is not True or req.get("aggregate_only") is not True or not _digest(req.get("replay_identity")):raise ResearchContractError("laboratory integration request identity, bounds, instruments, actions, peers, budget, locality, replay, or boundary is invalid")
 instruments=sorted((dict(x) for x in req["instruments"]),key=lambda x:str(x.get("instrument_id",""))); ids=[str(x.get("instrument_id","")) for x in instruments]; actions=sorted((dict(x) for x in req["actions"]),key=lambda x:(int(x.get("sequence",0)),str(x.get("action_id","")))); aids=[str(x.get("action_id","")) for x in actions]; peers=sorted((dict(x) for x in req["peers"]),key=lambda x:str(x.get("peer_id",""))); pids=[str(x.get("peer_id","")) for x in peers]
 if len(set(ids))!=len(ids) or len(set(aids))!=len(aids) or len(set(pids))!=len(pids) or any(not x.get("instrument_id") or not x.get("site_id") or not x.get("protocol_version") or not all(_digest(x.get(k)) for k in ("calibration_digest","firmware_digest","provenance_digest")) for x in instruments) or any(not x.get("action_id") or not x.get("instrument_id") or not x.get("effect_class") or not x.get("input_schema") or not x.get("output_schema") or int(x.get("estimated_units",0))<=0 or not all(_digest(x.get(k)) for k in ("action_digest","provenance_digest","replay_identity")) for x in actions) or any(not x.get("peer_id") or not x.get("origin") or not x.get("workflow_id") or not _digest(x.get("report_digest")) for x in peers):raise ResearchContractError("laboratory integration instrument, action, or peer identity is invalid")
 ready_i:set[str]=set(); unresolved_i:set[str]=set(); blocked_i:set[str]=set(); interlocks:set[str]=set(); emergency:set[str]=set(); unc:set[str]=set(); neg:set[str]=set()
 for i in instruments:
  iid=i["instrument_id"]; interlocks.add(f"{iid}:{'ready' if i.get('interlock_ready') else 'missing'}"); emergency.add(f"{iid}:{'ready' if i.get('emergency_stop_ready') else 'missing'}"); hard=i.get("interlock_ready") is not True or i.get("emergency_stop_ready") is not True or i.get("deterministic") is not True or i.get("local_only") is not True or i.get("permitted") is not True or i.get("signed") is not True or i.get("evidence_state")=="contradicted"; 
  if hard:
   if i.get("evidence_state")=="contradicted" or i.get("local_only") is not True or i.get("interlock_ready") is not True or i.get("emergency_stop_ready") is not True:blocked_i.add(iid)
   else:unresolved_i.add(iid)
   neg.add(f"instrument:{iid}:contradicted") if i.get("evidence_state")=="contradicted" else None
  elif i.get("evidence_state") not in {"proven","supported"}:unresolved_i.add(iid);unc.add(f"instrument:{iid}:evidence-state")
  else:ready_i.add(iid)
 imap={i["instrument_id"]:i for i in instruments}; ready_a:set[str]=set(); unresolved_a:set[str]=set(); blocked_a:set[str]=set(); compensation:set[str]=set(); omissions:set[str]=set(); total=0
 for a in actions:
  aid=a["action_id"]; total+=int(a["estimated_units"]); compensation.add(f"{aid}:{a['compensation']}") if str(a.get("compensation","")).strip() else omissions.add(f"action:{aid}:missing-compensation"); negative=a.get("negative_result"); neg.add(f"action:{aid}:negative-result") if negative else None; instrument_ok=a.get("instrument_id") in ready_i; hard=not instrument_ok or a.get("local_only") is not True or a.get("deterministic") is not True or a.get("signed_approval") is not True or a.get("evidence_state")=="contradicted" or a.get("replay_identity")!=req["replay_identity"]
  if hard:
   blocked_a.add(aid) if a.get("evidence_state")=="contradicted" or not instrument_ok else unresolved_a.add(aid); neg.add(f"action:{aid}:contradicted") if a.get("evidence_state")=="contradicted" else None
  elif a.get("evidence_state") not in {"proven","supported"}:unresolved_a.add(aid);unc.add(f"action:{aid}:evidence-state")
  else:ready_a.add(aid)
 qp={p["peer_id"] for p in peers if p.get("workflow_id")==req["workflow_id"] and p.get("semantic_profile")==req["semantic_profile"] and int(p.get("checkpoint",0))==int(req["checkpoint"]) and p.get("signed") is True and p.get("aggregate_only") is True and p.get("raw_data_local") is True and p.get("evidence_state") in {"proven","supported"}};mp=set(pids)-qp;unc.update(f"peer:{p}:not-qualified" for p in mp)
 if total>int(req["max_budget_units"]):omissions.add(f"request:budget-exceeded:{total}")
 if len(qp)<int(req["minimum_peer_quorum"]):unc.add("peer:minimum-quorum-unmet")
 global_block=not all(req.get(k) is True for k in ("policy_allow","protected_closure","signed_approval","federation_approved","raw_data_local","aggregate_only"));neg.add("request:policy-denied") if req.get("policy_allow") is not True else None;unc.add("request:protected-closure-incomplete") if req.get("protected_closure") is not True else None;unc.add("request:signed-approval-missing") if req.get("signed_approval") is not True else None;unc.add("request:federation-approval-missing") if req.get("federation_approved") is not True else None
 disposition="blocked" if global_block or blocked_i or blocked_a else "unresolved" if len(qp)<int(req["minimum_peer_quorum"]) or unresolved_i or unresolved_a or omissions or not ready_a else "qualified"
 if global_block:blocked_i.update(ids);blocked_a.update(aids);ready_i.clear();unresolved_i.clear();ready_a.clear();unresolved_a.clear()
 if disposition!="qualified":omissions.add("request:preflight-not-release-ready")
 payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"feature_id":FEATURE_ID,"request_id":req["request_id"],"federation_id":req["federation_id"],"workflow_id":req["workflow_id"],"requester":req["requester"],"purpose":req["purpose"],"semantic_profile":req["semantic_profile"],"checkpoint":int(req["checkpoint"]),"disposition":disposition,"instrument_order":ids,"ready_instrument_order":sorted(ready_i),"unresolved_instrument_order":sorted(unresolved_i),"blocked_instrument_order":sorted(blocked_i),"action_order":aids,"ready_action_order":sorted(ready_a),"unresolved_action_order":sorted(unresolved_a),"blocked_action_order":sorted(blocked_a),"peer_order":pids,"qualified_peer_order":sorted(qp),"missing_peer_order":sorted(mp),"interlock_order":sorted(interlocks),"emergency_stop_order":sorted(emergency),"compensation_order":sorted(compensation),"omission_order":sorted(omissions),"uncertainty_order":sorted(unc),"negative_evidence_order":sorted(neg),"total_units":total,"replay_identity":req["replay_identity"],"boundary":PRECLINICAL_BOUNDARY}; digest=_hash(payload); result={**payload,"integration_digest":digest,"artifact":{"artifact_id":f"laboratory-integration-report-9:{req['request_id']}","content_type":CONTENT_TYPE,"content_hash":digest,"semantic_loss":[],"provenance_digests":sorted({x["provenance_digest"] for x in instruments}|{x["provenance_digest"] for x in actions}),"boundary":PRECLINICAL_BOUNDARY},"effect_receipts":[f"exchange:permitted-summaries:{req['request_id']}",f"manage:local-capability:{req['request_id']}"] if disposition=="qualified" else ["block:unsafe-release"],"raw_data_local":True,"aggregate_only":True}; receipt=LaboratoryIntegrationReport9(result);receipt.validate();return receipt
def idsLaboratoryIntegrationDigest(receipt:LaboratoryIntegrationReport9)->str:receipt.validate();return _hash(receipt.to_dict())
__all__=["FEATURE_ID","CONTRACT_VERSION","INPUT_SCHEMA","OUTPUT_SCHEMA","CONTENT_TYPE","LaboratoryIntegrationReport9","laboratory_integration_manifest","integrate_laboratory_workflow","idsLaboratoryIntegrationDigest"]
