"""Python parity for ``AFA-ids-P08-F26`` mechanism exploration assurance."""
from __future__ import annotations
import hashlib,json,re
from dataclasses import dataclass
from typing import Any,Mapping,Sequence
from .research_contracts import PRECLINICAL_BOUNDARY,RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
FEATURE_ID="AFA-ids-P08-F26"; CONTRACT_VERSION="ids-multimodal-mechanism-exploration-assurance-harness/1.0"; INPUT_SCHEMA="MechanismQuestion2@1"; OUTPUT_SCHEMA="MechanismPortfolio7@1"; CONTENT_TYPE="application/vnd.aurora.mechanism-portfolio-7+json"
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return tuple(v)==tuple(sorted(set(v)))
@dataclass(frozen=True)
class MechanismPortfolio7:
    value:dict[str,Any]
    def to_dict(self)->dict[str,Any]:return dict(self.value)
    def validate(self)->None:
        v=self.value
        if v.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or v.get("contract_version")!=CONTRACT_VERSION or v.get("feature_id")!=FEATURE_ID or v.get("boundary")!=PRECLINICAL_BOUNDARY or v.get("raw_data_local") is not True or v.get("aggregate_only") is not True or not all(str(v.get(k,"")).strip() for k in ("request_id","question_id","federation_id","requester","purpose","semantic_profile")) or int(v.get("checkpoint",0))<=0 or not v.get("candidate_order") or not v.get("peer_order") or not v.get("effect_receipts") or v.get("disposition") not in {"qualified","unresolved","blocked"}:raise ResearchContractError("mechanism identity, checkpoint, locality, candidates, peers, or effects are incomplete")
        fields=("candidate_order","selected_order","competing_order","unresolved_order","blocked_order","missing_study_order","missing_modality_order","peer_order","qualified_peer_order","missing_peer_order","omission_order","uncertainty_order","negative_evidence_order","effect_receipts")
        if any(not _ordered(v.get(k,[])) for k in fields):raise ResearchContractError("mechanism ordering is not canonical")
        if set(v["candidate_order"])!=set(v["selected_order"])|set(v["competing_order"])|set(v["unresolved_order"])|set(v["blocked_order"]):raise ResearchContractError("candidate states do not partition")
        if set(v["peer_order"])!=set(v["qualified_peer_order"])|set(v["missing_peer_order"]):raise ResearchContractError("peer states do not partition")
        a=v.get("artifact",{});ds=[v.get("replay_identity"),v.get("portfolio_digest"),a.get("content_hash"),*a.get("provenance_digests",[])]
        if not all(_digest(x) for x in ds) or len(v["selected_order"])+len(v["competing_order"])!=len(v.get("support_scores_milli",[])) or len(v["selected_order"])+len(v["competing_order"])!=len(v.get("novelty_scores_milli",[])) or a.get("content_type")!=CONTENT_TYPE or a.get("boundary")!=PRECLINICAL_BOUNDARY or a.get("content_hash")!=v.get("portfolio_digest"):raise ResearchContractError("mechanism artifact, digest, or score cardinality is invalid")
        if any(not e.startswith("verify:mechanism-portfolio:") and e!="block:unsafe-release" for e in v["effect_receipts"]):raise ResearchContractError("mechanism effect is outside governed gate")
def mechanism_exploration_manifest()->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":FEATURE_ID,"version":CONTRACT_VERSION,"owner_crate":"ids","consumers":["downstream AURORA crate maintainer","mechanism scientist","independent validation partner"],"behavior":"verifies bounded multimodal mechanism candidates and peer attestations under comparability, closure, provenance, replay, and policy gates","value":"preserves competing explanations and negative evidence while preventing incomplete mechanism portfolios from becoming conclusions","input_schema":INPUT_SCHEMA,"output_schema":OUTPUT_SCHEMA,"effects":["verify:mechanism-portfolio"],"permissions":["evaluate:capability-runs"],"autonomy_tier":"A1","boundary":PRECLINICAL_BOUNDARY}
def assure_mechanism_exploration(request:Mapping[str,Any],candidates:Sequence[Mapping[str,Any]],peers:Sequence[Mapping[str,Any]])->MechanismPortfolio7:
    if not all(str(request.get(k,"")).strip() for k in ("request_id","question_id","federation_id","requester","purpose","semantic_profile")) or not request.get("required_studies") or not request.get("required_modalities") or not 0<=int(request.get("minimum_support_milli",-1))<=1000 or int(request.get("minimum_peer_quorum",0))<=0 or int(request.get("checkpoint",0))<=0 or int(request.get("budget_units",0))<=0 or request.get("boundary")!=PRECLINICAL_BOUNDARY or request.get("raw_data_local") is not True or request.get("aggregate_only") is not True or not _digest(request.get("replay_identity")) or not candidates or not peers:raise ResearchContractError("mechanism identity, closure, threshold, quorum, checkpoint, budget, replay, locality, candidates, peers, or boundary is invalid")
    rows=sorted((dict(x) for x in candidates),key=lambda x:(-(int(x.get("support_milli",0))+int(x.get("novelty_milli",0))),str(x.get("candidate_id",""))));ids=[str(x.get("candidate_id","")) for x in rows]
    if len(set(ids))!=len(ids) or any(not x.get("candidate_id") or not x.get("mechanism_id") or not x.get("origin") or not all(_digest(x.get(k)) for k in ("content_digest","provenance_digest","replay_identity")) for x in rows):raise ResearchContractError("candidate identity, uniqueness, origin, or digest is invalid")
    ps=sorted((dict(x) for x in peers),key=lambda x:str(x.get("peer_id","")));peer_ids=[str(x.get("peer_id","")) for x in ps]
    if len(set(peer_ids))!=len(ps) or any(not x.get("peer_id") or not x.get("origin") or not _digest(x.get("portfolio_digest")) for x in ps):raise ResearchContractError("peer identity, uniqueness, origin, or digest is invalid")
    qp={x["peer_id"] for x in ps if x.get("question_id")==request["question_id"] and x.get("federation_id")==request["federation_id"] and x.get("semantic_profile")==request["semantic_profile"] and int(x.get("checkpoint",0))==int(request["checkpoint"]) and x.get("signed") is True and x.get("aggregate_only") is True and x.get("raw_data_local") is True and x.get("evidence_state") in {"proven","supported"}};mp=set(peer_ids)-qp;unc={f"peer:{x}:not-qualified" for x in mp};selected:set[str]=set();competing:set[str]=set();unresolved:set[str]=set();blocked:set[str]=set();ms:set[str]=set();mm:set[str]=set();om:set[str]=set();neg:set[str]=set();scores:list[int]=[];nov:list[int]=[]
    for x in rows:
        cid=x["candidate_id"];om.update(f"{cid}:{r}" for r in x.get("omission_reasons",[]));neg.add(f"{cid}:negative-result") if x.get("negative_result") else None;neg.add(f"{cid}:counterevidence") if x.get("counterevidence") else None;missing_s=[s for s in request["required_studies"] if s not in x.get("study_ids",[])];missing_m=[m for m in request["required_modalities"] if m not in x.get("modality_ids",[])];ms.add(f"{cid}:missing:{len(missing_s)}") if missing_s else None;mm.add(f"{cid}:missing:{len(missing_m)}") if missing_m else None;reasons=[]
        if x.get("semantic_profile")!=request["semantic_profile"]:reasons.append("semantic-profile-mismatch")
        if missing_s:reasons.append("study-closure-incomplete")
        if missing_m:reasons.append("modality-closure-incomplete")
        if int(x.get("support_milli",0))<int(request["minimum_support_milli"]):reasons.append("support-threshold-failed")
        if x.get("replay_identity")!=request["replay_identity"]:reasons.append("replay-identity-mismatch")
        if x.get("signed") is not True or x.get("permitted") is not True:reasons.append("authorization-missing")
        if x.get("raw_data_local") is not True or x.get("aggregate_only") is not True:reasons.append("locality-or-aggregate-only-failed")
        if x.get("evidence_state")=="contradicted":blocked.add(cid);neg.add(f"{cid}:contradicted")
        elif x.get("evidence_state") not in {"proven","supported"} or reasons:unresolved.add(cid);unc.add(f"{cid}:unresolved")
        elif not selected:selected.add(cid);scores.append(int(x.get("support_milli",0)));nov.append(int(x.get("novelty_milli",0)))
        else:competing.add(cid);scores.append(int(x.get("support_milli",0)));nov.append(int(x.get("novelty_milli",0)))
    global_block=not all(request.get(k) is True for k in ("policy_allow","protected_closure","signed_approval","federation_approved","raw_data_local","aggregate_only"));neg.add("request:policy-denied") if request.get("policy_allow") is not True else None;unc.add("request:protected-closure-incomplete") if request.get("protected_closure") is not True else None;unc.add("request:signed-approval-missing") if request.get("signed_approval") is not True else None;unc.add("request:federation-approval-missing") if request.get("federation_approved") is not True else None;disposition="blocked" if global_block or blocked else "unresolved" if not selected or ms or mm or len(qp)<int(request["minimum_peer_quorum"]) else "qualified"
    if global_block:blocked.update(ids);selected.clear();competing.clear();unresolved.clear();scores.clear();nov.clear()
    om.add("request:mechanism-gates-incomplete") if disposition!="qualified" else None;payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"feature_id":FEATURE_ID,"request_id":request["request_id"],"question_id":request["question_id"],"federation_id":request["federation_id"],"requester":request["requester"],"purpose":request["purpose"],"semantic_profile":request["semantic_profile"],"checkpoint":int(request["checkpoint"]),"disposition":disposition,"candidate_order":ids,"selected_order":sorted(selected),"competing_order":sorted(competing),"unresolved_order":sorted(unresolved),"blocked_order":sorted(blocked),"missing_study_order":sorted(ms),"missing_modality_order":sorted(mm),"peer_order":peer_ids,"qualified_peer_order":sorted(qp),"missing_peer_order":sorted(mp),"omission_order":sorted(om),"uncertainty_order":sorted(unc),"negative_evidence_order":sorted(neg),"support_scores_milli":scores,"novelty_scores_milli":nov,"replay_identity":request["replay_identity"],"boundary":PRECLINICAL_BOUNDARY};digest=_hash(payload);result={**payload,"portfolio_digest":digest,"artifact":{"artifact_id":f"mechanism-portfolio-7:{request['request_id']}","content_type":CONTENT_TYPE,"content_hash":digest,"semantic_loss":[],"provenance_digests":sorted({x["provenance_digest"] for x in rows}),"boundary":PRECLINICAL_BOUNDARY},"effect_receipts":[f"verify:mechanism-portfolio:{request['request_id']}"] if disposition=="qualified" else ["block:unsafe-release"],"raw_data_local":True,"aggregate_only":True};receipt=MechanismPortfolio7(result);receipt.validate();return receipt
def idsMechanismExplorationDigest(receipt:MechanismPortfolio7)->str:receipt.validate();return _hash(receipt.to_dict())
__all__=["FEATURE_ID","CONTRACT_VERSION","INPUT_SCHEMA","OUTPUT_SCHEMA","CONTENT_TYPE","MechanismPortfolio7","mechanism_exploration_manifest","assure_mechanism_exploration","idsMechanismExplorationDigest"]
