"""Python parity for ``AFA-ids-P12-F20`` computational execution workbench."""
from __future__ import annotations
import hashlib,json,re
from dataclasses import dataclass
from typing import Any,Mapping
from .research_contracts import PRECLINICAL_BOUNDARY,RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
FEATURE_ID="AFA-ids-P12-F20"; CONTRACT_VERSION="ids-federated-continual-computational-execution-research-workbench/1.0"; INPUT_SCHEMA="ComputationalExecutionRequest6@1"; OUTPUT_SCHEMA="ComputationalExecutionReport9@1"; CONTENT_TYPE="application/vnd.aurora.computational-execution-report-9+json"
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return tuple(v)==tuple(sorted(set(v)))
@dataclass(frozen=True)
class ComputationalExecutionReport9:
 value:dict[str,Any]
 def to_dict(self)->dict[str,Any]:return dict(self.value)
 def validate(self)->None:
  v=self.value
  if v.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or v.get("contract_version")!=CONTRACT_VERSION or v.get("feature_id")!=FEATURE_ID or v.get("boundary")!=PRECLINICAL_BOUNDARY or v.get("raw_data_local") is not True or v.get("aggregate_only") is not True or not all(str(v.get(k,"")).strip() for k in ("request_id","federation_id","workflow_id","requester","purpose","semantic_profile")) or int(v.get("checkpoint",0))<=0 or not v.get("node_order") or not v.get("peer_order") or not v.get("effect_receipts") or v.get("disposition") not in {"qualified","unresolved","blocked"}:raise ResearchContractError("computational execution identity, locality, nodes, peers, or effects are incomplete")
  fields=("node_order","planned_node_order","unresolved_node_order","blocked_node_order","cycle_order","missing_dependency_order","peer_order","qualified_peer_order","missing_peer_order","retry_order","omission_order","uncertainty_order","negative_evidence_order","effect_receipts")
  if any(not _ordered(v.get(k,[])) for k in fields):raise ResearchContractError("computational execution ordering is not canonical")
  nodes=set(v["node_order"]); parts=[*v["planned_node_order"],*v["unresolved_node_order"],*v["blocked_node_order"]]; peers=set(v["peer_order"]); pp=[*v["qualified_peer_order"],*v["missing_peer_order"]]
  if len(parts)!=len(nodes) or set(parts)!=nodes or len(set(parts))!=len(parts) or len(pp)!=len(peers) or set(pp)!=peers or len(set(pp))!=len(pp):raise ResearchContractError("computational execution states do not partition")
  a=v.get("artifact",{});ds=[v.get("replay_identity"),v.get("execution_digest"),a.get("content_hash"),*a.get("provenance_digests",[])]
  if not all(_digest(x) for x in ds) or a.get("content_type")!=CONTENT_TYPE or a.get("boundary")!=PRECLINICAL_BOUNDARY or a.get("content_hash")!=v.get("execution_digest"):raise ResearchContractError("computational execution artifact or digest is invalid")
  if any(not e.startswith(("exchange:permitted-summaries:","manage:local-capability:")) and e!="block:unsafe-release" for e in v["effect_receipts"]):raise ResearchContractError("computational execution effect is outside governed gate")
def computational_execution_manifest()->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":FEATURE_ID,"version":CONTRACT_VERSION,"owner_crate":"ids","consumers":["computational biologist","workflow compiler engineer","federation steward"],"behavior":"compiles federated workflow node attestations into a deterministic dry-run execution plan","value":"exposes dependency, cycle, budget, provenance, replay, peer, and policy gates before any job dispatch","input_schema":INPUT_SCHEMA,"output_schema":OUTPUT_SCHEMA,"effects":["exchange:permitted-summaries","manage:local-capability"],"permissions":["read:local-workflow-manifests"],"autonomy_tier":"A1","boundary":PRECLINICAL_BOUNDARY}
def compile_computational_execution(req:Mapping[str,Any])->ComputationalExecutionReport9:
 if not all(str(req.get(k,"")).strip() for k in ("request_id","federation_id","workflow_id","requester","purpose","semantic_profile","engine_version")) or not req.get("nodes") or not req.get("peers") or int(req.get("checkpoint",0))<=0 or int(req.get("max_budget_units",0))<=0 or int(req.get("minimum_peer_quorum",0))<=0 or req.get("boundary")!=PRECLINICAL_BOUNDARY or req.get("raw_data_local") is not True or req.get("aggregate_only") is not True or not _digest(req.get("replay_identity")):raise ResearchContractError("computational execution request identity, bounds, nodes, peers, budget, locality, replay, or boundary is invalid")
 nodes=sorted((dict(x) for x in req["nodes"]),key=lambda x:str(x.get("node_id","")));ids=[str(x.get("node_id","")) for x in nodes];peers=sorted((dict(x) for x in req["peers"]),key=lambda x:str(x.get("peer_id","")));pids=[str(x.get("peer_id","")) for x in peers]
 if len(set(ids))!=len(ids) or len(set(pids))!=len(pids) or any(not x.get("node_id") or not x.get("executor_id") or not x.get("input_schema") or not x.get("output_schema") or int(x.get("estimated_units",0))<=0 or not all(_digest(x.get(k)) for k in ("artifact_digest","provenance_digest","replay_identity")) for x in nodes) or any(not x.get("peer_id") or not x.get("origin") or not x.get("workflow_id") or not _digest(x.get("execution_digest")) for x in peers):raise ResearchContractError("computational node or peer identity is invalid")
 by_id={x["node_id"]:x for x in nodes};missing={f"{x['node_id']}:missing:{d}" for x in nodes for d in x.get("dependency_ids",[]) if d not in by_id};remaining={x["node_id"]:len([d for d in x.get("dependency_ids",[]) if d in by_id]) for x in nodes};ready=sorted([k for k,v in remaining.items() if v==0]);plan=[]
 while ready:
  nid=ready.pop(0);plan.append(nid)
  for x in nodes:
   if nid in x.get("dependency_ids",[]) and x["node_id"] in remaining:remaining[x["node_id"]]-=1; ready.append(x["node_id"]) if remaining[x["node_id"]]==0 else None
  ready.sort()
 cycles={k for k,v in remaining.items() if v>0};planned:set[str]=set();unresolved:set[str]=set();blocked:set[str]=set();retry:set[str]=set();omissions:set[str]=set();unc:set[str]=set();negative:set[str]=set();total=0
 for x in nodes:
  nid=x["node_id"];total+=int(x["estimated_units"]);negative.add(f"{nid}:negative-result") if x.get("negative_result") else None; hard=x.get("replay_identity")!=req["replay_identity"] or x.get("local_only") is not True or x.get("permitted") is not True or x.get("signed") is not True or x.get("deterministic") is not True or x.get("evidence_state")=="contradicted" or nid in cycles
  if hard:
   blocked.add(nid) if x.get("evidence_state")=="contradicted" or nid in cycles or x.get("local_only") is not True else unresolved.add(nid);retry.add(f"{nid}:replay-or-authorization") if nid in unresolved else None;negative.add(f"{nid}:contradicted") if x.get("evidence_state")=="contradicted" else None
  elif x.get("evidence_state") not in {"proven","supported"}:unresolved.add(nid);unc.add(f"{nid}:evidence-state")
  elif any(d not in by_id or d in cycles for d in x.get("dependency_ids",[])):blocked.add(nid)
  else:planned.add(nid)
 qp={p["peer_id"] for p in peers if p.get("workflow_id")==req["workflow_id"] and p.get("semantic_profile")==req["semantic_profile"] and int(p.get("checkpoint",0))==int(req["checkpoint"]) and p.get("signed") is True and p.get("aggregate_only") is True and p.get("raw_data_local") is True and p.get("evidence_state") in {"proven","supported"}};mp=set(pids)-qp;unc.update(f"peer:{p}:not-qualified" for p in mp);negative.add("request:cycle-detected") if cycles else None;omissions.add("request:missing-dependency-closure") if missing else None;omissions.add(f"request:budget-exceeded:{total}") if total>int(req["max_budget_units"]) else None;unc.add("peer:minimum-quorum-unmet") if len(qp)<int(req["minimum_peer_quorum"]) else None
 global_block=not all(req.get(k) is True for k in ("policy_allow","protected_closure","signed_approval","federation_approved","raw_data_local","aggregate_only"));negative.add("request:policy-denied") if req.get("policy_allow") is not True else None;unc.add("request:protected-closure-incomplete") if req.get("protected_closure") is not True else None;unc.add("request:signed-approval-missing") if req.get("signed_approval") is not True else None;unc.add("request:federation-approval-missing") if req.get("federation_approved") is not True else None
 disposition="blocked" if global_block or blocked else "unresolved" if cycles or missing or unresolved or total>int(req["max_budget_units"]) or len(qp)<int(req["minimum_peer_quorum"]) or not planned else "qualified";omissions.add("request:execution-not-release-ready") if disposition!="qualified" else None
 if global_block:blocked.update(ids);planned.clear();unresolved.clear()
 payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"feature_id":FEATURE_ID,"request_id":req["request_id"],"federation_id":req["federation_id"],"workflow_id":req["workflow_id"],"requester":req["requester"],"purpose":req["purpose"],"semantic_profile":req["semantic_profile"],"checkpoint":int(req["checkpoint"]),"disposition":disposition,"node_order":ids,"planned_node_order":sorted(planned),"unresolved_node_order":sorted(unresolved),"blocked_node_order":sorted(blocked),"cycle_order":sorted(cycles),"missing_dependency_order":sorted(missing),"peer_order":pids,"qualified_peer_order":sorted(qp),"missing_peer_order":sorted(mp),"retry_order":sorted(retry),"omission_order":sorted(omissions),"uncertainty_order":sorted(unc),"negative_evidence_order":sorted(negative),"total_units":total,"replay_identity":req["replay_identity"],"boundary":PRECLINICAL_BOUNDARY};digest=_hash(payload);result={**payload,"execution_digest":digest,"artifact":{"artifact_id":f"computational-execution-report-9:{req['request_id']}","content_type":CONTENT_TYPE,"content_hash":digest,"semantic_loss":[],"provenance_digests":sorted({x["provenance_digest"] for x in nodes}),"boundary":PRECLINICAL_BOUNDARY},"effect_receipts":[f"exchange:permitted-summaries:{req['request_id']}",f"manage:local-capability:{req['request_id']}"] if disposition=="qualified" else ["block:unsafe-release"],"raw_data_local":True,"aggregate_only":True};receipt=ComputationalExecutionReport9(result);receipt.validate();return receipt
def idsComputationalExecutionDigest(receipt:ComputationalExecutionReport9)->str:receipt.validate();return _hash(receipt.to_dict())
__all__=["FEATURE_ID","CONTRACT_VERSION","INPUT_SCHEMA","OUTPUT_SCHEMA","CONTENT_TYPE","ComputationalExecutionReport9","computational_execution_manifest","compile_computational_execution","idsComputationalExecutionDigest"]
