"""Python parity for Infra P32 reliability-integrity cards."""
from __future__ import annotations
import hashlib,json,re
from typing import Any,Mapping
from .research_contracts import RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions";CONTENT_TYPE="application/vnd.aurora.infra.reliability-integrity-card-1+json"
InfraAsset4=dict[str,Any];ReliabilityIntegrityRequest4=dict[str,Any];ReliabilityIntegrityCard7=dict[str,Any];ReliabilityIntegrityArtifact4=dict[str,Any];ReliabilityIntegrityError=ResearchContractError
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return isinstance(v,list) and v==sorted(set(v))
def manifest(*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"infra","consumers":["cache controller","quota scheduler","storage tier manager","operations service"],"behavior":f"qualify research asset reliability at {scale} ({mode})","value":"prevents low-quality, expired, corrupt, or non-local assets from entering durable research workflows","input_schema":"ReliabilityIntegrityRequest4@1","output_schema":"ReliabilityIntegrityCard7@1","effects":["emit:reliability-card","retain:quality-witness","block:unsafe-asset"],"permissions":["read:local-asset-metadata"],"determinism":"byte_stable","autonomy_tier":"A1","boundary":BOUNDARY}
def validate(o:Mapping[str,Any],*,feature_id:str|None=None)->None:
 a=o.get("artifact",{});bad=o.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or(feature_id is not None and o.get("feature_id")!=feature_id)or not o.get("request_id")or not o.get("purpose")or o.get("boundary")!=BOUNDARY or a.get("boundary")!=BOUNDARY or o.get("raw_data_local") is not True or o.get("aggregate_only") is not True or not _digest(o.get("replay_identity")) or not _digest(o.get("closure_digest")) or a.get("content_type")!=CONTENT_TYPE or a.get("content_hash")!=o.get("closure_digest")
 if bad:raise ResearchContractError("reliability identity, locality, artifact, digest, or boundary is incomplete")
 for k in("asset_order","accepted_order","rejected_order","unknown_order","omitted_order","tier_order","lifecycle_order","quality_order","checksum_order","effect_receipts"):
  if not _ordered(o.get(k,[])):raise ResearchContractError("reliability vectors are not canonical")
 ids=set(o["asset_order"]);states=set(o["accepted_order"])|set(o["rejected_order"])|set(o["unknown_order"])|set(o["omitted_order"])
 if len(o["asset_order"])!=len(ids)or states!=ids:raise ResearchContractError("asset states do not partition")
def qualify(request:Mapping[str,Any],*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:
 if request.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or not request.get("request_id","").strip() or not request.get("purpose","").strip() or not request.get("assets") or not request.get("required_asset_order") or not _ordered(request["required_asset_order"]) or not _ordered(request.get("required_tier_order",[])) or not _digest(request.get("replay_identity")) or request.get("boundary")!=BOUNDARY or request.get("raw_data_local") is not True or request.get("aggregate_only") is not True or not _ordered(request.get("adversarial_events",[])) or request.get("asset_budget",0)<=0:raise ResearchContractError("reliability identity, ordering, digest, locality, boundary, or budget is invalid")
 rows=sorted(request["assets"],key=lambda a:a.get("asset_id",""));seen=set();accepted=set();rejected=set();unknown=set();omitted=set();tiers=set();lifecycles=set();qualities=set();checksums=set();evidence=set()
 for a in rows:
  aid=a.get("asset_id","")
  if not aid.strip()or aid in seen or not a.get("tier","").strip()or not _digest(a.get("checksum"))or not a.get("lifecycle","").strip()or not a.get("evidence_state","").strip()or a.get("quality_milli",0)>1000 or a.get("quality_threshold_milli",0)>1000 or a.get("local") is not True or a.get("aggregate_only") is not True:raise ResearchContractError("asset identity, tier, checksum, lifecycle, quality, evidence, or locality is invalid")
  seen.add(aid);tiers.add(f"{aid}:{a['tier']}");lifecycles.add(f"{aid}:{a['lifecycle']}");qualities.add(f"{aid}:{a.get('quality_milli',0)}:{a.get('quality_threshold_milli',0)}");checksums.add(f"{aid}:{a['checksum']}");evidence.add(a["checksum"])
  if a["evidence_state"]=="unknown"or a["checksum"]==request["replay_identity"]:unknown.add(aid)
  elif a.get("quality_milli",0)<a.get("quality_threshold_milli",0)or a["lifecycle"] in ("expired","corrupt"):rejected.add(aid)
  elif aid not in request["required_asset_order"]:omitted.add(aid)
  else:accepted.add(aid)
 missing=[x for x in request["required_asset_order"] if x not in seen];global_block=not all(request.get(k) is True for k in("policy_allowed","protected_closure","signed_manifest","raw_data_local","aggregate_only"))or bool(request.get("adversarial_events"))or len(rows)>request["asset_budget"]
 if global_block:omitted.update(seen);accepted.clear();rejected.clear();unknown.clear()
 disposition="blocked" if global_block else "unknown" if missing or unknown else "partial" if rejected or omitted else "qualified";payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"request_id":request["request_id"],"purpose":request["purpose"],"disposition":disposition,"asset_order":sorted(seen),"accepted_order":sorted(accepted),"rejected_order":sorted(rejected),"unknown_order":sorted(unknown),"omitted_order":sorted(omitted),"tier_order":sorted(tiers),"lifecycle_order":sorted(lifecycles),"quality_order":sorted(qualities),"checksum_order":sorted(checksums),"replay_identity":request["replay_identity"],"raw_data_local":True,"aggregate_only":True,"boundary":BOUNDARY};d=_hash(payload);payload["closure_digest"]=d;payload["effect_receipts"]=[f"approve:reliability:{request['request_id']}"] if disposition=="qualified" else ["block:unsafe-asset"];payload["artifact"]={"artifact_id":f"infra-reliability:{request['request_id']}","content_type":CONTENT_TYPE,"content_hash":d,"semantic_loss":payload["omitted_order"],"evidence_digests":sorted(evidence),"boundary":BOUNDARY};validate(payload,feature_id=feature_id);return payload
__all__=["BOUNDARY","CONTENT_TYPE","InfraAsset4","ReliabilityIntegrityRequest4","ReliabilityIntegrityCard7","ReliabilityIntegrityArtifact4","ReliabilityIntegrityError","manifest","qualify","validate"]
