"""Python parity for Lab P32 instrument-execution integrity cards."""
from __future__ import annotations
import hashlib,json,re
from typing import Any,Mapping
from .research_contracts import RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions";CONTENT_TYPE="application/vnd.aurora.lab.instrument-execution-integrity-card-1+json"
InstrumentAction4=dict[str,Any];InstrumentExecutionRequest4=dict[str,Any];InstrumentExecutionCard7=dict[str,Any];InstrumentExecutionArtifact4=dict[str,Any];InstrumentExecutionIntegrityError=ResearchContractError
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return isinstance(v,list) and v==sorted(set(v))
def manifest(*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"lab","consumers":["instrument gateway","robotics operator","protocol simulator","research workbench"],"behavior":f"qualify instrument execution preflight at {scale} ({mode})","value":"prevents unauthorized or unsafe physical effects while preserving dry-run, interlock, emergency-stop, and compensation evidence","input_schema":"InstrumentExecutionRequest4@1","output_schema":"InstrumentExecutionCard7@1","effects":["emit:execution-card","retain:preflight-evidence","block:unsafe-physical-effect"],"permissions":["read:local-instrument-fixtures"],"determinism":"byte_stable","autonomy_tier":"A3","boundary":BOUNDARY}
def validate(o:Mapping[str,Any],*,feature_id:str|None=None)->None:
 a=o.get("artifact",{});bad=o.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or(feature_id is not None and o.get("feature_id")!=feature_id)or not o.get("request_id")or not o.get("purpose")or o.get("boundary")!=BOUNDARY or a.get("boundary")!=BOUNDARY or o.get("raw_data_local") is not True or o.get("aggregate_only") is not True or not _digest(o.get("replay_identity")) or not _digest(o.get("closure_digest")) or a.get("content_type")!=CONTENT_TYPE or a.get("content_hash")!=o.get("closure_digest")
 if bad:raise ResearchContractError("execution identity, locality, artifact, digest, or boundary is incomplete")
 for k in("action_order","approved_order","rejected_order","unknown_order","omitted_order","interlock_order","instrument_order","effect_order","effect_receipts"):
  if not _ordered(o.get(k,[])):raise ResearchContractError("execution vectors are not canonical")
 ids=set(o["action_order"]);states=set(o["approved_order"])|set(o["rejected_order"])|set(o["unknown_order"])|set(o["omitted_order"])
 if len(o["action_order"])!=len(ids)or states!=ids:raise ResearchContractError("action states do not partition")
def qualify(request:Mapping[str,Any],*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:
 if request.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or not request.get("request_id","").strip() or not request.get("purpose","").strip() or not request.get("actions") or not request.get("required_action_order") or not _ordered(request["required_action_order"]) or not _digest(request.get("replay_identity")) or request.get("boundary")!=BOUNDARY or request.get("raw_data_local") is not True or request.get("aggregate_only") is not True or not _ordered(request.get("adversarial_events",[])) or request.get("action_budget",0)<=0:raise ResearchContractError("execution identity, ordering, digest, locality, boundary, or budget is invalid")
 rows=sorted(request["actions"],key=lambda a:a.get("action_id",""));seen=set();approved=set();rejected=set();unknown=set();omitted=set();interlocks=set();instruments=set();effects=set();evidence=set()
 for a in rows:
  aid=a.get("action_id","")
  if not aid.strip()or aid in seen or not a.get("instrument_id","").strip()or not a.get("effect","").strip()or not a.get("interlock","").strip()or not _digest(a.get("digest"))or not a.get("evidence_state","").strip()or a.get("local") is not True or a.get("aggregate_only") is not True:raise ResearchContractError("action identity, instrument, effect, interlock, digest, evidence, or locality is invalid")
  seen.add(aid);interlocks.add(f"{aid}:{a['interlock']}");instruments.add(f"{aid}:{a['instrument_id']}");effects.add(f"{aid}:{a['effect']}");evidence.add(a["digest"])
  if a["evidence_state"]=="unknown"or a["digest"]==request["replay_identity"]:unknown.add(aid)
  elif a["effect"]=="physical"and(not request.get("signed_preflight") or not request.get("human_authorized") or request.get("emergency_stop")):rejected.add(aid)
  elif aid not in request["required_action_order"]:omitted.add(aid)
  else:approved.add(aid)
 missing=[x for x in request["required_action_order"] if x not in seen];physical=any(a.get("effect")=="physical" for a in rows);global_block=not all(request.get(k) is True for k in("policy_allowed","protected_closure","raw_data_local","aggregate_only"))or bool(request.get("adversarial_events"))or len(rows)>request["action_budget"]or(physical and(not request.get("signed_preflight")or not request.get("human_authorized")or request.get("emergency_stop")))
 if global_block:omitted.update(seen);approved.clear();rejected.clear();unknown.clear()
 disposition="blocked" if global_block else "unknown" if missing or unknown else "partial" if rejected or omitted else "qualified";payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"request_id":request["request_id"],"purpose":request["purpose"],"disposition":disposition,"action_order":sorted(seen),"approved_order":sorted(approved),"rejected_order":sorted(rejected),"unknown_order":sorted(unknown),"omitted_order":sorted(omitted),"interlock_order":sorted(interlocks),"instrument_order":sorted(instruments),"effect_order":sorted(effects),"replay_identity":request["replay_identity"],"raw_data_local":True,"aggregate_only":True,"boundary":BOUNDARY};d=_hash(payload);payload["closure_digest"]=d;payload["effect_receipts"]=[f"approve:preflight:{request['request_id']}"] if disposition=="qualified" else ["block:unsafe-physical-effect"];payload["artifact"]={"artifact_id":f"lab-execution:{request['request_id']}","content_type":CONTENT_TYPE,"content_hash":d,"semantic_loss":payload["omitted_order"],"evidence_digests":sorted(evidence),"boundary":BOUNDARY};validate(payload,feature_id=feature_id);return payload
__all__=["BOUNDARY","CONTENT_TYPE","InstrumentAction4","InstrumentExecutionRequest4","InstrumentExecutionCard7","InstrumentExecutionArtifact4","InstrumentExecutionIntegrityError","manifest","qualify","validate"]
