"""Python parity for Factory P32 lease/fencing integrity cards."""
from __future__ import annotations
import hashlib, json, re
from typing import Any, Mapping
from .research_contracts import RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError
BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions"; CONTENT_TYPE="application/vnd.aurora.factory.lease-fencing-integrity-card-1+json"
WorkerLease4=dict[str,Any]; LeaseFencingIntegrityRequest4=dict[str,Any]; LeaseFencingIntegrityCard7=dict[str,Any]; LeaseFencingArtifact4=dict[str,Any]; LeaseFencingIntegrityError=ResearchContractError
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return isinstance(v,list) and v==sorted(set(v))
def manifest(*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"factory","consumers":["workflow operator","worker scheduler","recovery auditor","site reliability engineer"],"behavior":f"qualify retry-safe worker leases at {scale} ({mode})","value":"prevents stale, forged, or ambiguously retried leases from duplicating research effects","input_schema":"LeaseFencingIntegrityRequest4@1","output_schema":"LeaseFencingIntegrityCard7@1","effects":["emit:lease-integrity-card","retain:quarantined-leases","block:unsafe-retry"],"permissions":["read:local-worker-attestations","exchange:aggregate-lease-metadata"],"determinism":"byte_stable","autonomy_tier":"A1","boundary":BOUNDARY}
def validate(card:Mapping[str,Any],*,feature_id:str|None=None)->None:
    a=card.get("artifact",{})
    if card.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or (feature_id is not None and card.get("feature_id")!=feature_id) or not card.get("request_id") or not card.get("purpose") or card.get("boundary")!=BOUNDARY or a.get("boundary")!=BOUNDARY or card.get("raw_data_local") is not True or card.get("aggregate_only") is not True or not _digest(card.get("replay_identity")) or not _digest(card.get("closure_digest")) or a.get("content_type")!=CONTENT_TYPE or a.get("content_hash")!=card.get("closure_digest") or card.get("admitted_lease_count",0)>card.get("total_lease_count",0):raise ResearchContractError("lease identity, locality, artifact, digest, boundary, or count is incomplete")
    for key in ("lease_order","admitted_order","rejected_order","unknown_order","omitted_order","fencing_order","worker_order","job_order","effect_order","effect_receipts"):
        if not _ordered(card.get(key,[])):raise ResearchContractError("lease vectors are not canonical")
    ids=set(card["lease_order"]); states=set(card["admitted_order"])|set(card["rejected_order"])|set(card["unknown_order"])|set(card["omitted_order"])
    if len(card["lease_order"])!=len(ids) or states!=ids:raise ResearchContractError("lease states do not partition leases")
    if card["admitted_lease_count"]!=len(card["admitted_order"]):raise ResearchContractError("admitted lease count does not match admitted order")
def qualify(request:Mapping[str,Any],*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:
    if request.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or not request.get("request_id","").strip() or not request.get("purpose","").strip() or not request.get("leases") or request.get("lease_budget",0)<=0 or not _digest(request.get("replay_identity")) or request.get("boundary")!=BOUNDARY or request.get("raw_data_local") is not True or request.get("aggregate_only") is not True or not _ordered(request.get("required_lease_order",[])) or not _ordered(request.get("adversarial_events",[])):raise ResearchContractError("lease identity, ordering, replay, locality, boundary, or budget is invalid")
    rows=sorted(request["leases"],key=lambda item:item.get("lease_id",""));seen:set[str]=set();workers:set[str]=set();jobs:set[str]=set();fencing:set[str]=set();effects:set[str]=set();tokens:set[str]=set();admitted:set[str]=set();rejected:set[str]=set();unknown:set[str]=set();omitted:set[str]=set();semantic_loss:list[str]=[]; generation:dict[str,int]={}
    for lease in rows:
        lid=lease.get("lease_id","")
        if not lid.strip() or not lease.get("worker_id","").strip() or not lease.get("job_id","").strip() or lease.get("generation",0)<=0 or lease.get("expiry_epoch",0)<=0 or not _digest(lease.get("fence_token")) or not lease.get("idempotency","").strip() or not lease.get("evidence_state","").strip() or lease.get("attested") is not True or lease.get("local") is not True or lease.get("aggregate_only") is not True:raise ResearchContractError("lease identity, generation, expiry, fence token, attestation, evidence, or locality is incomplete")
        if lid in seen:raise ResearchContractError(f"duplicate lease {lid}")
        seen.add(lid); prior=generation.get(lease["job_id"]); generation[lease["job_id"]]=lease["generation"]; workers.add(f"{lid}:{lease['worker_id']}");jobs.add(f"{lid}:{lease['job_id']}");fencing.add(f"{lid}:{lease['generation']}");effects.add(f"{lid}:{lease['idempotency']}");tokens.add(lease["fence_token"])
        if prior is not None and prior==lease["generation"]:rejected.add(lid);semantic_loss.append(lid)
        elif lease["evidence_state"] in ("supported","proven") and lease.get("required") is True and lease.get("deterministic") is True and (lease["idempotency"]=="idempotent" or lease.get("compensation_ready") is True):admitted.add(lid)
        elif lease["evidence_state"] in ("contradicted","rejected"):rejected.add(lid);semantic_loss.append(lid)
        elif lease["evidence_state"] in ("unknown","speculative","unmeasured"):unknown.add(lid);semantic_loss.append(lid)
        else:omitted.add(lid);semantic_loss.append(lid)
    if set(request["required_lease_order"])!=seen:raise ResearchContractError("required lease order is not the canonical lease set")
    global_block=request.get("policy_allowed") is not True or request.get("protected_closure") is not True or request.get("signed_manifest") is not True or request.get("raw_data_local") is not True or request.get("aggregate_only") is not True or bool(request.get("adversarial_events")) or len(rows)>request["lease_budget"]
    if global_block:omitted.update(seen);admitted.clear();rejected.clear();unknown.clear()
    disposition="blocked" if global_block else "unknown" if unknown else "partial" if rejected or omitted else "qualified";body={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"request_id":request["request_id"],"purpose":request["purpose"],"disposition":disposition,"lease_order":sorted(seen)};closure_digest=_hash(body);admitted_order=sorted(admitted);rejected_order=sorted(rejected);unknown_order=sorted(unknown);omitted_order=sorted(omitted)
    card={**body,"admitted_order":admitted_order,"rejected_order":rejected_order,"unknown_order":unknown_order,"omitted_order":omitted_order,"fencing_order":sorted(fencing),"worker_order":sorted(workers),"job_order":sorted(jobs),"effect_order":sorted(effects),"replay_identity":request["replay_identity"],"closure_digest":closure_digest,"admitted_lease_count":len(admitted_order),"total_lease_count":len(rows),"raw_data_local":True,"aggregate_only":True,"boundary":BOUNDARY,"effect_receipts":[f"prepare:lease-integrity:{request['request_id']}"] if disposition=="qualified" else ["block:unsafe-retry"],"artifact":{"artifact_id":f"factory-lease-integrity:{request['request_id']}","content_type":CONTENT_TYPE,"content_hash":closure_digest,"semantic_loss":sorted(seen) if global_block else semantic_loss,"fence_tokens":sorted(tokens),"boundary":BOUNDARY}}
    validate(card,feature_id=feature_id);return card
__all__=["BOUNDARY","CONTENT_TYPE","WorkerLease4","LeaseFencingIntegrityRequest4","LeaseFencingIntegrityCard7","LeaseFencingArtifact4","LeaseFencingIntegrityError","manifest","qualify","validate"]
