"""Parity implementation for ``AFA-mutation-P05-F32`` resource control plane."""
from __future__ import annotations
import hashlib, json, re
from typing import Any, Mapping
from .research_contracts import PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError

FEATURE_ID="AFA-mutation-P05-F32"; CONTRACT_VERSION="mutation-federated-continual-resource-discovery-control-plane/1.0"; INPUT_SCHEMA="ResourceNeed4@1"; OUTPUT_SCHEMA="QualifiedResourceSet8@1"; CONTENT_TYPE="application/vnd.aurora.qualified-resource-set-8+json"
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return v==sorted(set(v))
def mutation_federated_resource_discovery_manifest()->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":FEATURE_ID,"version":CONTRACT_VERSION,"owner_crate":"mutation","consumers":["preclinical neuroscientist","resource steward","federation operator"],"behavior":"operate typed local resource registry and aggregate-only federation attestations into a qualified resource set","value":"makes capability fitness, evidence, locality, permissions, omissions, and peer quorum explicit before a researcher selects a resource","input_schema":INPUT_SCHEMA,"output_schema":OUTPUT_SCHEMA,"effects":["manage:local-capability","exchange:permitted-summaries"],"permissions":["operate:institution-node"],"autonomy_tier":"A2","boundary":PRECLINICAL_BOUNDARY}
def _validate_request(r:Mapping[str,Any])->None:
 if not all(isinstance(r.get(k),str) and r[k].strip() for k in ("request_id","federation_id","requester","purpose","semantic_profile","required_protocol_version")) or not r.get("required_capabilities") or not _ordered(r["required_capabilities"]) or not _ordered(r.get("allowed_origins",[])) or not isinstance(r.get("max_results"),int) or not 0<r["max_results"]<=4096 or not _digest(r.get("replay_identity")) or r.get("boundary")!=PRECLINICAL_BOUNDARY:raise ResearchContractError("identity, capabilities, protocol, bounds, replay, or boundary is invalid")
def validate_mutation_federated_resource_discovery(output:Mapping[str,Any])->None:
 if output.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or output.get("contract_version")!=CONTRACT_VERSION or output.get("feature_id")!=FEATURE_ID or output.get("boundary")!=PRECLINICAL_BOUNDARY or output.get("raw_data_local") is not True or output.get("aggregate_only") is not True or not output.get("effect_receipts") or output.get("disposition") not in {"qualified","unresolved","blocked"}:raise ResearchContractError("resource identity, locality, disposition, or effects are incomplete")
 fields=("endpoint_order","qualified_order","unresolved_order","blocked_order","missing_capability_order","peer_order","qualified_peer_order","missing_peer_order","omission_order","uncertainty_order","negative_evidence_order","migration_order","effect_receipts")
 if any(not _ordered(output.get(k,[])) for k in fields):raise ResearchContractError("resource ordering is not canonical")
 endpoints=set(output["endpoint_order"]);parts=output["qualified_order"]+output["unresolved_order"]+output["blocked_order"];peers=set(output["peer_order"]);peer_parts=output["qualified_peer_order"]+output["missing_peer_order"]
 if len(endpoints)!=len(output["endpoint_order"]) or set(parts)!=endpoints or len(parts)!=len(endpoints) or len(peers)!=len(output["peer_order"]) or set(peer_parts)!=peers or len(peer_parts)!=len(peers):raise ResearchContractError("resource or peer states do not partition")
 if not all(_digest(output.get(k)) for k in ("replay_identity","selection_digest")) or output.get("artifact",{}).get("content_hash")!=output.get("selection_digest"):raise ResearchContractError("resource digest or artifact metadata is invalid")
def operate_mutation_federated_resource_discovery(request:Mapping[str,Any],endpoints:list[Mapping[str,Any]],peers:list[Mapping[str,Any]])->dict[str,Any]:
 _validate_request(request); rows=sorted((dict(v) for v in endpoints),key=lambda v:v.get("endpoint_id","")); peer_rows=sorted((dict(v) for v in peers),key=lambda v:v.get("peer_id","")); endpoint_order=[v["endpoint_id"] for v in rows]; required=set(request["required_capabilities"]);qualified=set();unresolved=set();blocked=set();omissions=set();uncertainty=set();negative=set();migration=set();resources=[];provenance=[]
 for row in rows:
  i=row["endpoint_id"];provenance.append(row.get("provenance_digest")); omissions.update(f"{i}:{v}" for v in row.get("omission_reasons",[]));missing=sorted(required-set(row.get("capabilities",[])));protocol=request["required_protocol_version"] in row.get("protocol_versions",[]);origin=not request.get("allowed_origins") or row.get("origin") in request["allowed_origins"];state=row.get("evidence_state")
  hard=not row.get("permitted") or not row.get("signed") or not row.get("raw_data_local") or not row.get("aggregate_only") or row.get("replay_identity")!=request["replay_identity"] or not _digest(row.get("artifact_digest")) or not _digest(row.get("provenance_digest")) or row.get("status") in {"protected","revoked","unavailable"} or row.get("semantic_profile")!=request["semantic_profile"] or not origin
  if hard:blocked.add(i);omissions.add(f"{i}:policy-permission-locality-or-compatibility")
  elif missing or not protocol or row.get("status")=="stale" or state in {"unknown","speculative","unmeasured"}: unresolved.add(i);omissions.update(f"{i}:missing-capability:{v}" for v in missing);migration.add(f"{i}:protocol-version-migration") if not protocol else None;uncertainty.add(f"{i}:evidence-incomplete") if state in {"unknown","speculative","unmeasured"} else None
  elif state=="contradicted":unresolved.add(i);negative.add(f"{i}:contradicted")
  else:qualified.add(i);resources.append({"resource_id":row["resource_id"],"endpoint_id":i,"origin":row["origin"],"protocol_version":request["required_protocol_version"],"fitness_milli":row.get("fitness_milli",0),"capability_order":sorted(row.get("capabilities",[])),"migration_notes":[]})
 peer_order=[v["peer_id"] for v in peer_rows];qualified_peers=set();missing_peers=set()
 for peer in peer_rows:
  if peer.get("signed") and peer.get("aggregate_only") and peer.get("raw_data_local") and peer.get("semantic_profile")==request["semantic_profile"] and peer.get("protocol_version")==request["required_protocol_version"] and _digest(peer.get("summary_digest")) and peer.get("evidence_state")!="contradicted":qualified_peers.add(peer["peer_id"])
  else:missing_peers.add(peer["peer_id"]);uncertainty.add(f"peer:{peer['peer_id']}:summary-incomplete")
 if len(qualified_peers)<request.get("minimum_peer_quorum",0):uncertainty.add("request:peer-quorum-incomplete")
 global_block=not all(request.get(k) is True for k in ("policy_allow","protected_closure","signed_approval","federation_approved","raw_data_local","aggregate_only"))
 if global_block:blocked.update(endpoint_order);qualified.clear();unresolved.clear();resources.clear();omissions.add("request:governance-locality-or-federation-blocked")
 disposition="blocked" if global_block or (blocked and len(blocked)==len(endpoint_order)) else "unresolved" if len(qualified_peers)<request.get("minimum_peer_quorum",0) or unresolved or blocked or migration else "qualified";omissions.add("request:resource-closure-not-ready") if disposition!="qualified" else None
 resources=sorted(resources,key=lambda v:(-v["fitness_milli"],v["endpoint_id"]))[:request["max_results"]];payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"feature_id":FEATURE_ID,"request_id":request["request_id"],"federation_id":request["federation_id"],"requester":request["requester"],"purpose":request["purpose"],"semantic_profile":request["semantic_profile"],"negotiated_protocol_version":request["required_protocol_version"],"disposition":disposition,"endpoint_order":endpoint_order,"qualified_order":sorted(qualified),"unresolved_order":sorted(unresolved),"blocked_order":sorted(blocked),"missing_capability_order":sorted(v for v in omissions if ":missing-capability:" in v),"peer_order":peer_order,"qualified_peer_order":sorted(qualified_peers),"missing_peer_order":sorted(missing_peers),"resources":resources,"omission_order":sorted(omissions),"uncertainty_order":sorted(uncertainty),"negative_evidence_order":sorted(negative),"migration_order":sorted(migration),"replay_identity":request["replay_identity"],"raw_data_local":True,"aggregate_only":True,"boundary":PRECLINICAL_BOUNDARY};d=_hash(payload);payload["selection_digest"]=d;payload["artifact"]={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"artifact_id":f"mutation-qualified-resource-set-8:{request['request_id']}","content_type":CONTENT_TYPE,"content_hash":d,"semantic_loss":[],"provenance":[],"boundary":PRECLINICAL_BOUNDARY};payload["effect_receipts"]=[f"exchange:permitted-summaries:{request['request_id']}",f"manage:local-capability:{request['request_id']}"] if disposition=="qualified" else ["block:unsafe-release"];validate_mutation_federated_resource_discovery(payload);return payload
__all__=["FEATURE_ID","CONTRACT_VERSION","INPUT_SCHEMA","OUTPUT_SCHEMA","CONTENT_TYPE","mutation_federated_resource_discovery_manifest","operate_mutation_federated_resource_discovery","validate_mutation_federated_resource_discovery"]
