"""Python parity surface for ``AFA-obligation-P01-F24``."""
from __future__ import annotations
from dataclasses import dataclass
import hashlib,json,re
from typing import Any,Mapping,Sequence
from .research_contracts import PRECLINICAL_BOUNDARY,RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
FEATURE_ID="AFA-obligation-P01-F24";CONTRACT_VERSION="obligation-federated-evidence-interoperability-gateway/1.0";INPUT_SCHEMA="EvidenceFeed4@1";OUTPUT_SCHEMA="QualifiedEvidenceSet6@1";CONTENT_TYPE="application/vnd.aurora.qualified-evidence-set-6+json"
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _canonical(v:Sequence[str])->bool:return tuple(v)==tuple(sorted(set(v)))
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
@dataclass(frozen=True)
class ObligationQualifiedEvidenceSet:
 request_id:str;federation_id:str;institution_id:str;endpoint:str;purpose:str;semantic_profile:str;disposition:str;evidence_order:tuple[str,...];ranked_order:tuple[str,...];admitted_order:tuple[str,...];unresolved_order:tuple[str,...];blocked_order:tuple[str,...];missing_study_order:tuple[str,...];missing_modality_order:tuple[str,...];omission_order:tuple[str,...];uncertainty_order:tuple[str,...];negative_evidence_order:tuple[str,...];adversarial_event_order:tuple[str,...];study_digest_order:tuple[str,...];artifact_digest_order:tuple[str,...];replay_identity:str;set_digest:str;artifact:dict[str,Any];effect_receipts:tuple[str,...];raw_data_local:bool=True;aggregate_only:bool=True;boundary:str=PRECLINICAL_BOUNDARY;schema_version:str=RESEARCH_CONTRACT_SCHEMA_VERSION;contract_version:str=CONTRACT_VERSION;feature_id:str=FEATURE_ID
 def to_dict(self)->dict[str,Any]:return {"schema_version":self.schema_version,"contract_version":self.contract_version,"feature_id":self.feature_id,"request_id":self.request_id,"federation_id":self.federation_id,"institution_id":self.institution_id,"endpoint":self.endpoint,"purpose":self.purpose,"semantic_profile":self.semantic_profile,"disposition":self.disposition,"evidence_order":list(self.evidence_order),"ranked_order":list(self.ranked_order),"admitted_order":list(self.admitted_order),"unresolved_order":list(self.unresolved_order),"blocked_order":list(self.blocked_order),"missing_study_order":list(self.missing_study_order),"missing_modality_order":list(self.missing_modality_order),"omission_order":list(self.omission_order),"uncertainty_order":list(self.uncertainty_order),"negative_evidence_order":list(self.negative_evidence_order),"adversarial_event_order":list(self.adversarial_event_order),"study_digest_order":list(self.study_digest_order),"artifact_digest_order":list(self.artifact_digest_order),"replay_identity":self.replay_identity,"set_digest":self.set_digest,"artifact":self.artifact,"effect_receipts":list(self.effect_receipts),"raw_data_local":self.raw_data_local,"aggregate_only":self.aggregate_only,"boundary":self.boundary}
 def validate(self)->None:
  if (self.schema_version,self.contract_version,self.feature_id)!=(RESEARCH_CONTRACT_SCHEMA_VERSION,CONTRACT_VERSION,FEATURE_ID) or self.boundary!=PRECLINICAL_BOUNDARY or self.artifact.get("boundary")!=PRECLINICAL_BOUNDARY or not self.raw_data_local or not self.aggregate_only or not all(v.strip() for v in (self.request_id,self.federation_id,self.institution_id,self.endpoint,self.purpose,self.semantic_profile)) or not self.evidence_order or len(self.ranked_order)!=len(self.evidence_order) or not self.effect_receipts:raise ResearchContractError("evidence set identity, locality, ranking, disposition, or effects are incomplete")
  for vals in (self.evidence_order,self.admitted_order,self.unresolved_order,self.blocked_order,self.missing_study_order,self.missing_modality_order,self.omission_order,self.uncertainty_order,self.negative_evidence_order,self.adversarial_event_order,self.effect_receipts):
   if not _canonical(vals):raise ResearchContractError("evidence set ordering is not canonical")
  ids=set(self.evidence_order);parts=self.admitted_order+self.unresolved_order+self.blocked_order
  if len(parts)!=len(ids) or any(v not in ids for v in parts) or len(set(parts))!=len(parts) or set(self.ranked_order)!=ids:raise ResearchContractError("evidence states do not partition observations")
  for v in (self.replay_identity,self.set_digest,self.artifact.get("content_hash")):
   if not _digest(v):raise ResearchContractError("evidence set digest is invalid")
  if self.artifact.get("content_type")!=CONTENT_TYPE:raise ResearchContractError("evidence set artifact type is invalid")
  if self.disposition=="qualified" and self.effect_receipts!=(f"exchange:permitted-artifacts:{self.request_id}",):raise ResearchContractError("qualified evidence effect is invalid")
  if self.disposition!="qualified" and self.effect_receipts!=("block:unsafe-release",):raise ResearchContractError("non-qualified evidence must block release")
def integrate_evidence_feed(*,request_id:str,federation_id:str,institution_id:str,endpoint:str,purpose:str,semantic_profile:str,required_study_order:Sequence[str],required_modality_order:Sequence[str],observations:Sequence[Mapping[str,Any]],replay_identity:str,policy_allow:bool,protected_closure:bool,signed_approval:bool,endpoint_approved:bool,raw_data_local:bool,aggregate_only:bool,budget:int,max_budget:int,adversarial_events:Sequence[str]=(),boundary:str=PRECLINICAL_BOUNDARY)->ObligationQualifiedEvidenceSet:
 if not all(v.strip() for v in (request_id,federation_id,institution_id,endpoint,purpose,semantic_profile)) or not required_study_order or not required_modality_order or not observations or not _canonical(required_study_order) or not _canonical(required_modality_order) or not _canonical(adversarial_events) or not _digest(replay_identity) or budget<=0 or max_budget<=0 or boundary!=PRECLINICAL_BOUNDARY or not raw_data_local or not aggregate_only:raise ResearchContractError("evidence feed identity, closure, digest, budget, locality, or boundary is invalid")
 rows=[dict(x) for x in observations];seen:set[str]=set()
 for row in rows:
  identifier=str(row.get("evidence_id",""))
  if not identifier.strip() or identifier in seen or not str(row.get("source_id","")).strip() or not str(row.get("study_id","")).strip() or not str(row.get("modality","")).strip() or not str(row.get("scope","")).strip() or not 0<=int(row.get("relevance_milli",-1))<=1000 or not 0<=int(row.get("freshness_milli",-1))<=1000 or not _digest(row.get("semantic_digest")) or not _digest(row.get("artifact_digest")) or not _digest(row.get("provenance_digest")) or not _digest(row.get("replay_identity")) or not _canonical(row.get("omissions",())) or not _canonical(row.get("uncertainty",())) or not _canonical(row.get("negative_evidence",())):raise ResearchContractError(f"observation {identifier} is malformed or duplicated")
  seen.add(identifier)
 rows.sort(key=lambda x:(-int(x["relevance_milli"]),-int(x["freshness_milli"]),str(x["evidence_id"])));ranked=tuple(str(x["evidence_id"]) for x in rows);order=tuple(sorted(ranked));studies=set(required_study_order);modalities=set(required_modality_order);admitted:set[str]=set();unresolved:set[str]=set();blocked:set[str]=set();omissions:set[str]=set();uncertainty:set[str]=set();negative:set[str]=set();study_digests:set[str]=set();artifact_digests:set[str]=set()
 for row in rows:
  identifier=str(row["evidence_id"]);omissions.update(f"{identifier}:{x}" for x in row.get("omissions",()));uncertainty.update(f"{identifier}:{x}" for x in row.get("uncertainty",()));negative.update(f"{identifier}:{x}" for x in row.get("negative_evidence",()));
  if row.get("negative_result"):negative.add(f"{identifier}:negative-result")
  state=str(row.get("state",""))
  if state=="contradicted":blocked.add(identifier);negative.add(f"{identifier}:contradicted-evidence");continue
  if state in {"unknown","speculative"}:unresolved.add(identifier);uncertainty.add(f"{identifier}:evidence-unresolved");continue
  complete=str(row["study_id"]) in studies and str(row["modality"]) in modalities and int(row["relevance_milli"])>=600 and int(row["freshness_milli"])>=600 and row["replay_identity"]==replay_identity and not row.get("omissions") and not row.get("uncertainty") and bool(row.get("local_data")) and bool(row.get("permitted"))
  if complete and state in {"proven","supported"}:admitted.add(identifier);study_digests.add(_hash(str(row["study_id"])));artifact_digests.add(str(row["artifact_digest"]))
  else:
   unresolved.add(identifier)
   if str(row["study_id"]) not in studies:omissions.add(f"{identifier}:required-study-missing")
   if str(row["modality"]) not in modalities:omissions.add(f"{identifier}:required-modality-missing")
   if int(row["relevance_milli"])<600:uncertainty.add(f"{identifier}:relevance-threshold-not-met")
   if int(row["freshness_milli"])<600:uncertainty.add(f"{identifier}:freshness-threshold-not-met")
   if not row.get("local_data") or not row.get("permitted"):blocked.add(identifier);unresolved.discard(identifier);omissions.add(f"{identifier}:locality-or-permission-denied")
 missing_study=tuple(sorted(s for s in required_study_order if not any(str(x["study_id"])==s for x in rows)));missing_modality=tuple(sorted(m for m in required_modality_order if not any(str(x["modality"])==m for x in rows)));omissions.update(f"required-study-missing:{s}" for s in missing_study);omissions.update(f"required-modality-missing:{m}" for m in missing_modality);negative.update(f"adversarial:{e}" for e in adversarial_events)
 if not policy_allow:uncertainty.add("request:policy-denied")
 if not protected_closure:uncertainty.add("request:protected-closure-incomplete")
 if not signed_approval or not endpoint_approved:uncertainty.add("request:endpoint-or-signature-approval-incomplete")
 if budget>max_budget:omissions.add("request:budget-ceiling-exceeded")
 global_block=not policy_allow or not protected_closure or not signed_approval or not endpoint_approved or not raw_data_local or not aggregate_only or budget>max_budget or bool(adversarial_events);disposition="blocked" if global_block else ("qualified" if not missing_study and not missing_modality and admitted and not unresolved and not blocked else "unresolved");admitted_order=tuple(sorted(admitted));unresolved_order=tuple(sorted(unresolved));blocked_order=tuple(sorted(blocked));omission_order=tuple(sorted(omissions));uncertainty_order=tuple(sorted(uncertainty));negative_order=tuple(sorted(negative));study_order=tuple(sorted(study_digests));artifact_order=tuple(sorted(artifact_digests));effects=(f"exchange:permitted-artifacts:{request_id}",) if disposition=="qualified" else ("block:unsafe-release",)
 payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"feature_id":FEATURE_ID,"request_id":request_id,"federation_id":federation_id,"institution_id":institution_id,"endpoint":endpoint,"purpose":purpose,"semantic_profile":semantic_profile,"disposition":disposition,"evidence_order":list(order),"ranked_order":list(ranked),"admitted_order":list(admitted_order),"unresolved_order":list(unresolved_order),"blocked_order":list(blocked_order),"missing_study_order":list(missing_study),"missing_modality_order":list(missing_modality),"omission_order":list(omission_order),"uncertainty_order":list(uncertainty_order),"negative_evidence_order":list(negative_order),"adversarial_event_order":list(adversarial_events),"study_digest_order":list(study_order),"artifact_digest_order":list(artifact_order),"replay_identity":replay_identity,"effect_receipts":list(effects),"raw_data_local":raw_data_local,"aggregate_only":aggregate_only,"boundary":PRECLINICAL_BOUNDARY};set_digest=_hash(payload);artifact={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"artifact_id":f"obligation-evidence-set:{request_id}","content_type":CONTENT_TYPE,"content_hash":set_digest,"semantic_loss":[],"provenance":[],"boundary":PRECLINICAL_BOUNDARY};result=ObligationQualifiedEvidenceSet(request_id,federation_id,institution_id,endpoint,purpose,semantic_profile,disposition,order,ranked,admitted_order,unresolved_order,blocked_order,missing_study,missing_modality,omission_order,uncertainty_order,negative_order,tuple(adversarial_events),study_order,artifact_order,replay_identity,set_digest,artifact,effects,raw_data_local,aggregate_only);result.validate();return result
def obligation_evidence_gateway_digest(result:ObligationQualifiedEvidenceSet)->str:result.validate();return _hash(result.to_dict())
__all__=["FEATURE_ID","CONTRACT_VERSION","INPUT_SCHEMA","OUTPUT_SCHEMA","ObligationQualifiedEvidenceSet","integrate_evidence_feed","obligation_evidence_gateway_digest"]
