"""Python parity for ``AFA-oracle-P01-F16`` evidence-surveillance workflow fabric."""
from __future__ import annotations
import hashlib, json, re
from dataclasses import dataclass
from typing import Any, Mapping
from .research_contracts import PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError
FEATURE_ID="AFA-oracle-P01-F16"; CONTRACT_VERSION="oracle-federated-continual-evidence-surveillance-workflow-fabric/1.0"; INPUT_SCHEMA="EvidenceFeed4@1"; OUTPUT_SCHEMA="QualifiedEvidenceSet4@1"; CONTENT_TYPE="application/vnd.aurora.oracle-qualified-evidence-set-4+json"; STAGES=("stage:checkpoint","stage:admit-federation","stage:surveil-evidence","stage:seal-envelope")
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return v==sorted(set(v))
@dataclass(frozen=True)
class QualifiedEvidenceSet4:
    value:dict[str,Any]
    def to_dict(self)->dict[str,Any]:return dict(self.value)
    def validate(self)->None:
        v=self.value
        if v.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or v.get("contract_version")!=CONTRACT_VERSION or v.get("feature_id")!=FEATURE_ID or v.get("boundary")!=PRECLINICAL_BOUNDARY or v.get("artifact",{}).get("boundary")!=PRECLINICAL_BOUNDARY or v.get("raw_data_local") is not True or v.get("aggregate_only") is not True or not all(str(v.get(k,"")).strip() for k in ("request_id","workflow_id","federation_id")) or v.get("stage_order")!=list(STAGES) or not v.get("candidate_order") or not v.get("peer_order") or not v.get("effect_receipts"):raise ResearchContractError("workflow identity, stages, candidates, peers, locality, or effects are incomplete")
        for k in ("candidate_order","qualified_order","unresolved_order","blocked_order","peer_order","qualified_peer_order","missing_peer_order","omission_order","uncertainty_order","negative_evidence_order","effect_receipts"):
            if not _ordered(v.get(k,[])):raise ResearchContractError("workflow ordering is not canonical")
        if set(v["candidate_order"])!=set(v["qualified_order"])|set(v["unresolved_order"])|set(v["blocked_order"]):raise ResearchContractError("candidate states do not partition")
        if set(v["peer_order"])!=set(v["qualified_peer_order"])|set(v["missing_peer_order"]):raise ResearchContractError("peer states do not partition")
        a=v["artifact"]
        if not all(_digest(v.get(k)) for k in ("checkpoint_digest","workflow_digest")) or a.get("content_type")!=CONTENT_TYPE or a.get("content_hash")!=v.get("workflow_digest"):raise ResearchContractError("workflow artifact or digest is invalid")
        if any(e!="block:unsafe-release" and not e.startswith("execute:evidence-surveillance:") for e in v["effect_receipts"]):raise ResearchContractError("workflow effect is outside governed gate")
def evidence_surveillance_workflow_manifest()->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":FEATURE_ID,"version":CONTRACT_VERSION,"owner_crate":"oracle","consumers":["imaging core scientist","evidence workflow operator","federation steward"],"behavior":"schedule checkpointed federated evidence surveillance over signed aggregate attestations without fetching sources","value":"turns continual evidence feeds into replayable workflow receipts while preserving negative and missing evidence","input_schema":INPUT_SCHEMA,"output_schema":OUTPUT_SCHEMA,"effects":["execute:evidence-surveillance"],"permissions":["execute:approved-workflows","exchange:permitted-summaries"],"autonomy_tier":"A2","boundary":PRECLINICAL_BOUNDARY}
def schedule_evidence_surveillance(request:Mapping[str,Any])->QualifiedEvidenceSet4:
    if not all(str(request.get(k,"")).strip() for k in ("request_id","workflow_id","federation_id","purpose","endpoint","semantic_profile","checkpoint_id")) or tuple(request.get("requested_stage_order",[]))!=STAGES or int(request.get("budget_units",0))<=0 or int(request.get("budget_units",0))>int(request.get("max_budget_units",0)) or int(request.get("min_peer_quorum",0))<=0 or request.get("boundary")!=PRECLINICAL_BOUNDARY or request.get("raw_data_local") is not True or request.get("aggregate_only") is not True or not _digest(request.get("replay_identity")) or not request.get("contributions"):raise ResearchContractError("workflow identity, stages, budget, locality, replay, or boundary is invalid")
    rows=sorted((dict(x) for x in request["contributions"]),key=lambda x:(str(x.get("peer_id","")),str(x.get("candidate_id","")))); candidates=sorted({str(x.get("candidate_id","")) for x in rows}); peers=sorted({str(x.get("peer_id","")) for x in rows}); q=set();u=set();b=set();qp=set();om=set();unc=set();neg=set()
    for x in rows:
        cid=x["candidate_id"]; om.update(f"{cid}:{r}" for r in x.get("omission_order",[])); neg.add(f"{cid}:negative-result") if x.get("negative_result") else None; ok=x.get("semantic_profile")==request["semantic_profile"] and x.get("replay_identity")==request["replay_identity"] and x.get("signed") is True and x.get("permitted_artifact") is True and x.get("aggregate_only") is True and x.get("raw_data_local") is True and int(x.get("relevance_milli",0))>=500 and x.get("artifact_kind") in request.get("allowed_artifacts",[])
        if x.get("evidence_state")=="contradicted":b.add(cid);neg.add(f"{cid}:contradicted")
        elif not ok or x.get("evidence_state") not in {"proven","supported"}:u.add(cid);unc.add(f"{cid}:unresolved")
        else:q.add(cid);qp.add(x["peer_id"])
    mp=sorted(set(peers)-qp);om.add(f"peer-quorum:{len(qp)}/{request['min_peer_quorum']}") if len(qp)<int(request["min_peer_quorum"]) else None; global_block=not all(request.get(k) is True for k in ("policy_allow","protected_closure","federation_approved","signed_approval")); [om.add(f"workflow:{k.replace('_','-')}") for k in ("policy_allow","protected_closure","federation_approved","signed_approval") if request.get(k) is not True]; disposition="blocked" if global_block or b else "unresolved" if len(qp)<int(request["min_peer_quorum"]) or u or neg else "qualified";om.add("workflow:closure-incomplete") if disposition!="qualified" else None
    if global_block:b.update(candidates);q.clear();u.clear()
    payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"feature_id":FEATURE_ID,"request_id":request["request_id"],"workflow_id":request["workflow_id"],"federation_id":request["federation_id"],"disposition":disposition,"stage_order":list(STAGES),"candidate_order":candidates,"qualified_order":sorted(q),"unresolved_order":sorted(u),"blocked_order":sorted(b),"peer_order":peers,"qualified_peer_order":sorted(qp),"missing_peer_order":mp,"omission_order":sorted(om),"uncertainty_order":sorted(unc),"negative_evidence_order":sorted(neg),"replay_identity":request["replay_identity"],"boundary":PRECLINICAL_BOUNDARY}; payload["checkpoint_digest"]=_hash({"workflow_id":request["workflow_id"],"checkpoint_id":request["checkpoint_id"],"stage_order":list(STAGES),"replay_identity":request["replay_identity"]});payload["workflow_digest"]=_hash(payload);payload.pop("replay_identity",None);payload["artifact"]={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"artifact_id":f"oracle-evidence-workflow:{request['workflow_id']}","content_type":CONTENT_TYPE,"content_hash":payload["workflow_digest"],"semantic_loss":[],"provenance":[],"boundary":PRECLINICAL_BOUNDARY};payload["effect_receipts"]=[f"execute:evidence-surveillance:{request['workflow_id']}"] if disposition=="qualified" else ["block:unsafe-release"];payload.update(raw_data_local=True,aggregate_only=True);r=QualifiedEvidenceSet4(payload);r.validate();return r
__all__=["FEATURE_ID","CONTRACT_VERSION","INPUT_SCHEMA","OUTPUT_SCHEMA","QualifiedEvidenceSet4","evidence_surveillance_workflow_manifest","schedule_evidence_surveillance"]
