"""Deterministic Python parity for Policy P32 grant-integrity cards."""
from __future__ import annotations
import hashlib,json,re
from typing import Any,Mapping
from .research_contracts import RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions";CONTENT_TYPE="application/vnd.aurora.policy.grant-integrity-card-1+json"
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return isinstance(v,list) and v==sorted(set(v))
def manifest(*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"policy","consumers":["autonomy broker","instrument gateway","federation admission","release auditor"],"behavior":f"qualify expiring autonomy grants at {scale} ({mode})","value":"prevents revoked, expired, over-scoped, or over-tier grants from authorizing research effects","input_schema":"GrantIntegrityRequest4@1","output_schema":"GrantIntegrityCard7@1","effects":["emit:grant-card","retain:revocation","block:unauthorized-effect"],"permissions":["read:local-policy"],"determinism":"byte_stable","autonomy_tier":"A1","boundary":BOUNDARY}
def validate(o:Mapping[str,Any],*,feature_id:str|None=None)->None:
 a=o.get("artifact",{});bad=o.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or feature_id is not None and o.get("feature_id")!=feature_id or o.get("boundary")!=BOUNDARY or o.get("raw_data_local") is not True or o.get("aggregate_only") is not True or not o.get("grant_order") or not _digest(o.get("replay_identity")) or not _digest(o.get("closure_digest")) or a.get("content_type")!=CONTENT_TYPE or a.get("content_hash")!=o.get("closure_digest") or a.get("boundary")!=BOUNDARY
 if bad:raise ResearchContractError("grant identity, locality, digest, artifact, or boundary is incomplete")
 for k in ("grant_order","allowed_order","denied_order","unknown_order","omitted_order","action_order","scope_order","tier_order","expiration_order","revocation_order","effect_receipts"):
  if not _ordered(o.get(k,[])):raise ResearchContractError("grant vectors are not canonical")
 ids=set(o["grant_order"]);states=set(o["allowed_order"])|set(o["denied_order"])|set(o["unknown_order"])|set(o["omitted_order"])
 if len(o["grant_order"])!=len(ids) or states!=ids:raise ResearchContractError("grant states do not partition")
def qualify(request:Mapping[str,Any],*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:
 if not isinstance(request.get("request_id"),str) or not request["request_id"].strip() or not isinstance(request.get("purpose"),str) or not request["purpose"].strip() or not request.get("grants") or not request.get("required_grant_order") or not request.get("required_action_order") or not isinstance(request.get("maximum_tier"),str) or not request["maximum_tier"].strip() or not _digest(request.get("replay_identity")) or request.get("boundary")!=BOUNDARY or request.get("raw_data_local") is not True or request.get("aggregate_only") is not True or not _ordered(request["required_grant_order"]) or not _ordered(request["required_action_order"]) or not _ordered(request.get("adversarial_events",[])):raise ResearchContractError("grant identity, requirements, tier, digest, ordering, locality, or boundary is invalid")
 rows=sorted(request["grants"],key=lambda g:g.get("grant_id",""));order=[];allowed=set();denied=set();unknown=set();omitted=set();actions=set();scopes=set();tiers=set();expirations=set();revocations=set();digests=set();seen=set()
 for g in rows:
  gid=g.get("grant_id","")
  if gid in seen or not isinstance(gid,str) or not gid.strip() or not isinstance(g.get("actor"),str) or not g["actor"].strip() or not isinstance(g.get("action"),str) or not g["action"].strip() or not isinstance(g.get("scope"),str) or not g["scope"].strip() or not isinstance(g.get("autonomy_tier"),str) or not g["autonomy_tier"].strip() or not _digest(g.get("evidence_digest")) or g.get("local") is not True or g.get("aggregate_only") is not True:raise ResearchContractError("grant identity, actor, scope, tier, evidence, or locality is invalid")
  seen.add(gid);order.append(gid);actions.add(g["action"]);scopes.add(g["scope"]);tiers.add(g["autonomy_tier"]);expirations.add(f"{gid}:{g.get('expiration_epoch',0)}");digests.add(g["evidence_digest"])
  if g.get("revoked") is True:revocations.add(f"{gid}:revoked")
  if g.get("policy_epoch",0)==0 or g["evidence_digest"]==request["replay_identity"]:unknown.add(gid)
  elif g.get("revoked") is True or g.get("expiration_epoch",0)<request.get("current_epoch",0) or g["autonomy_tier"]>request["maximum_tier"] or g["action"] not in request["required_action_order"]:denied.add(gid)
  elif gid not in request["required_grant_order"]:omitted.add(gid)
  else:allowed.add(gid)
 global_block=not all(request.get(k) is True for k in ("policy_allowed","protected_closure","signed_approval","raw_data_local","aggregate_only")) or bool(request.get("adversarial_events")) or request.get("action_count",0)>request.get("action_budget",0)
 if global_block:omitted.update(order);allowed.clear();denied.clear();unknown.clear()
 missing=not set(request["required_grant_order"])<=seen or not set(request["required_action_order"])<=actions;disposition="blocked" if global_block else "unknown" if missing else "partial" if denied or unknown or omitted else "qualified"
 payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"mode":mode,"scale":scale,"request_id":request["request_id"],"purpose":request["purpose"],"disposition":disposition,"grant_order":order,"allowed_order":sorted(allowed),"denied_order":sorted(denied),"unknown_order":sorted(unknown),"omitted_order":sorted(omitted),"action_order":sorted(actions),"scope_order":sorted(scopes),"tier_order":sorted(tiers),"expiration_order":sorted(expirations),"revocation_order":sorted(revocations),"replay_identity":request["replay_identity"],"raw_data_local":True,"aggregate_only":True,"boundary":BOUNDARY};d=_hash(payload);payload["closure_digest"]=d;payload["artifact"]={"artifact_id":f"policy-grant:{request['request_id']}","content_type":CONTENT_TYPE,"content_hash":d,"semantic_loss":sorted(payload["omitted_order"]),"evidence_digests":sorted(digests),"boundary":BOUNDARY};payload["effect_receipts"]=[f"emit:grant-card:{request['request_id']}"] if disposition=="qualified" else ["block:unauthorized-effect"];validate(payload,feature_id=feature_id);return payload
AutonomyGrant4=dict[str,Any];GrantIntegrityRequest4=dict[str,Any];GrantIntegrityCard7=dict[str,Any];GrantIntegrityArtifact4=dict[str,Any];GrantIntegrityError=ResearchContractError
__all__=["BOUNDARY","CONTENT_TYPE","AutonomyGrant4","GrantIntegrityRequest4","GrantIntegrityCard7","GrantIntegrityArtifact4","GrantIntegrityError","manifest","qualify","validate"]
