"""Python parity for Bundle P32 signed research-object integrity cards."""
from __future__ import annotations
import hashlib,json,re
from typing import Any,Mapping
from .research_contracts import RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions";CONTENT_TYPE="application/vnd.aurora.bundle.research-object-integrity-card-1+json";BundleEntry4=dict[str,Any];BundleReleaseRequest4=dict[str,Any];BundleCard7=dict[str,Any];BundleArtifact4=dict[str,Any];ResearchBundleIntegrityError=ResearchContractError
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return isinstance(v,list) and v==sorted(set(v))
def manifest(*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"bundle","consumers":["publication release service","reproduction operator","provenance ledger","research workbench"],"behavior":f"assemble signed research-object bundles at {scale} ({mode})","value":"releases content-addressed, omission-aware research objects with provenance and evidence gates while retaining negative results","input_schema":"BundleReleaseRequest4@1","output_schema":"BundleCard7@1","effects":["emit:research-object-bundle","retain:negative-result-evidence","block:unsafe-release"],"permissions":["read:local-research-objects"],"determinism":"byte_stable","autonomy_tier":"A1","boundary":BOUNDARY}
def validate(o:Mapping[str,Any],*,feature_id:str|None=None)->None:
 a=o.get("artifact",{});bad=o.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or(feature_id is not None and o.get("feature_id")!=feature_id)or not o.get("request_id")or not o.get("purpose")or o.get("boundary")!=BOUNDARY or a.get("boundary")!=BOUNDARY or o.get("raw_data_local") is not True or o.get("aggregate_only") is not True or not _digest(o.get("replay_identity"))or not _digest(o.get("closure_digest"))or not _digest(o.get("release_digest"))or a.get("content_type")!=CONTENT_TYPE or a.get("content_hash")!=o.get("closure_digest")or o.get("released_entry_count",0)>o.get("total_entry_count",0)
 if bad:raise ResearchContractError("bundle identity, locality, artifact, digest, boundary, or count is incomplete")
 for k in("entry_order","released_order","rejected_order","unknown_order","omitted_order","role_order","content_order","provenance_order","effect_receipts"):
  if not _ordered(o.get(k,[])):raise ResearchContractError("bundle vectors are not canonical")
 ids=set(o["entry_order"]);states=set(o["released_order"])|set(o["rejected_order"])|set(o["unknown_order"])|set(o["omitted_order"])
 if len(o["entry_order"])!=len(ids)or states!=ids:raise ResearchContractError("bundle states do not partition entries")
def release(request:Mapping[str,Any],*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:
 if request.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or not request.get("request_id","").strip()or not request.get("purpose","").strip()or not request.get("entries")or not request.get("required_entry_order")or not _ordered(request["required_entry_order"])or not _digest(request.get("release_digest"))or not _digest(request.get("replay_identity"))or request.get("boundary")!=BOUNDARY or request.get("raw_data_local") is not True or request.get("aggregate_only") is not True or not _ordered(request.get("adversarial_events",[]))or request.get("bundle_budget",0)<=0:raise ResearchContractError("bundle identity, ordering, release digest, locality, boundary, or budget is invalid")
 rows=sorted(request["entries"],key=lambda a:a.get("entry_id",""));seen=set();released=set();rejected=set();unknown=set();omitted=set();roles=set();contents=set();provenances=set()
 for e in rows:
  eid=e.get("entry_id","")
  if not eid.strip()or eid in seen or not e.get("role","").strip()or not _digest(e.get("content_hash"))or not _digest(e.get("provenance_digest"))or not e.get("evidence_state","").strip()or e.get("local") is not True or e.get("aggregate_only") is not True:raise ResearchContractError("entry identity, role, digest, evidence, or locality is invalid")
  seen.add(eid);roles.add(f"{eid}:{e['role']}");contents.add(f"{eid}:{e['content_hash']}");provenances.add(f"{eid}:{e['provenance_digest']}")
  if e["evidence_state"]=="unknown"or e["content_hash"]==request["replay_identity"]:unknown.add(eid)
  elif e.get("evidence_state")=="contradicted":rejected.add(eid)
  elif e.get("required") is not True or eid not in request["required_entry_order"]:omitted.add(eid)
  else:released.add(eid)
 missing=[x for x in request["required_entry_order"] if x not in seen];global_block=not all(request.get(k) is True for k in("policy_allowed","protected_closure","signed_manifest","raw_data_local","aggregate_only"))or bool(request.get("adversarial_events"))or len(rows)>request["bundle_budget"]
 if global_block:omitted.update(seen);released.clear();rejected.clear();unknown.clear()
 disposition="blocked" if global_block else "unknown" if missing or unknown else "partial" if not released or rejected or omitted else "released";body={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"request_id":request["request_id"],"purpose":request["purpose"],"disposition":disposition,"entry_order":sorted(seen)};d=_hash(body);payload={**body,"released_order":sorted(released),"rejected_order":sorted(rejected),"unknown_order":sorted(unknown),"omitted_order":sorted(omitted),"role_order":sorted(roles),"content_order":sorted(contents),"provenance_order":sorted(provenances),"replay_identity":request["replay_identity"],"closure_digest":d,"release_digest":request["release_digest"],"released_entry_count":len(released),"total_entry_count":len(rows),"raw_data_local":True,"aggregate_only":True,"boundary":BOUNDARY,"effect_receipts":[f"release:bundle:{request['request_id']}"] if disposition=="released" else ["block:unsafe-release"],"artifact":{"artifact_id":f"bundle-research-object:{request['request_id']}","content_type":CONTENT_TYPE,"content_hash":d,"semantic_loss":sorted(omitted),"evidence_digests":sorted(provenances),"boundary":BOUNDARY}};validate(payload,feature_id=feature_id);return payload
__all__=["BOUNDARY","CONTENT_TYPE","BundleEntry4","BundleReleaseRequest4","BundleCard7","BundleArtifact4","ResearchBundleIntegrityError","manifest","release","validate"]
