"""Python parity for ``AFA-scope-P01-F31`` federated evidence control."""
from __future__ import annotations
from dataclasses import dataclass
import hashlib, json, re
from typing import Any, Mapping
from .research_contracts import PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError
FEATURE_ID="AFA-scope-P01-F31"; CONTRACT_VERSION="scope-prospective-high-throughput-evidence-surveillance-federated-control-plane/1.0"; INPUT_SCHEMA="EvidenceFeed3@1"; OUTPUT_SCHEMA="FederatedEvidenceControlReceipt9@1"; CONTENT_TYPE="application/vnd.aurora.scope-federated-evidence-control-receipt-9+json"
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return v==sorted(set(v))
@dataclass(frozen=True)
class FederatedEvidenceControlReceipt9:
    value:dict[str,Any]
    def to_dict(self)->dict[str,Any]:return dict(self.value)
    def validate(self)->None:
        v=self.value;a=v.get("artifact",{})
        if v.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or v.get("contract_version")!=CONTRACT_VERSION or v.get("feature_id")!=FEATURE_ID or v.get("boundary")!=PRECLINICAL_BOUNDARY or a.get("boundary")!=PRECLINICAL_BOUNDARY or v.get("raw_data_local") is not True or v.get("aggregate_only") is not True or not all(str(v.get(k,"")).strip() for k in ("request_id","batch_id","partition","scope","semantic_profile")) or int(v.get("checkpoint_seq",0))<=0 or not v.get("candidate_order") or not v.get("ranked_order") or not v.get("peer_order") or not v.get("effect_receipts") or v.get("disposition") not in {"qualified","unresolved","blocked"}:raise ResearchContractError("scope control identity, bounds, candidates, peers, locality, or effects are incomplete")
        for k in ("candidate_order","ranked_order","qualified_order","unresolved_order","blocked_order","overflow_order","peer_order","qualified_peer_order","missing_peer_order","omission_order","uncertainty_order","negative_evidence_order","effect_receipts"):
            if not _ordered(v.get(k,[])):raise ResearchContractError("scope control ordering is not canonical")
        ids=set(v["candidate_order"]);parts=[*v["qualified_order"],*v["unresolved_order"],*v["blocked_order"],*v["overflow_order"]]; peers=set(v["peer_order"]);pp=[*v["qualified_peer_order"],*v["missing_peer_order"]]
        if len(ids)!=len(v["candidate_order"]) or set(v["ranked_order"])!=ids or len(parts)!=len(ids) or len(set(parts))!=len(parts) or set(parts)!=ids or len(peers)!=len(v["peer_order"]) or len(pp)!=len(peers) or len(set(pp))!=len(pp) or set(pp)!=peers:raise ResearchContractError("scope control candidate or peer states do not partition")
        if not all(_digest(v.get(k)) for k in ("replay_identity","checkpoint_digest","control_digest",a.get("content_hash"))) or a.get("content_type")!=CONTENT_TYPE or a.get("content_hash")!=v.get("control_digest"):raise ResearchContractError("scope control digest or artifact metadata is invalid")
        if any(e!="block:unsafe-release" and not e.startswith("coordinate:evidence-control:") for e in v["effect_receipts"]):raise ResearchContractError("scope control effect is outside governed gate")
        if v["disposition"]=="qualified" and v["effect_receipts"]!=[f"coordinate:evidence-control:{v['batch_id']}"]:raise ResearchContractError("qualified scope control effect is invalid")
        if v["disposition"]!="qualified" and v["effect_receipts"]!=["block:unsafe-release"]:raise ResearchContractError("non-qualified scope control must block")
def federated_evidence_control_manifest()->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":FEATURE_ID,"version":CONTRACT_VERSION,"owner_crate":"scope","consumers":["evidence workflow operator","computational biologist","federation steward"],"behavior":"admit bounded high-throughput EvidenceFeed3 batches and aggregate peer attestations under typed scope, checkpoint, quorum, policy, and locality gates","value":"coordinates federated evidence surveillance without moving raw observations and without hiding overflow or missing peers","input_schema":INPUT_SCHEMA,"output_schema":OUTPUT_SCHEMA,"effects":["coordinate:evidence-control"],"permissions":["execute:approved-workflows","exchange:permitted-summaries"],"autonomy_tier":"A2","boundary":PRECLINICAL_BOUNDARY}
def operate_federated_evidence_control(request:Mapping[str,Any])->FederatedEvidenceControlReceipt9:
    if not all(str(request.get(k,"")).strip() for k in ("request_id","batch_id","partition","scope","semantic_profile")) or int(request.get("checkpoint_seq",0))<=0 or int(request.get("max_items",0))<=0 or int(request.get("max_budget_units",0))<=0 or int(request.get("min_peer_quorum",0))<=0 or not _digest(request.get("replay_identity")) or request.get("aggregate_only") is not True or request.get("raw_data_local") is not True or request.get("boundary")!=PRECLINICAL_BOUNDARY or not request.get("observations") or not request.get("peers"):raise ResearchContractError("scope control identity, bounds, replay, locality, peers, or boundary are invalid")
    rows=sorted((dict(x) for x in request["observations"]),key=lambda x:(int(x.get("sequence",0)),str(x.get("evidence_id","")))); candidates=sorted({str(x.get("evidence_id","")) for x in rows}); admission=min(int(request["max_items"]),int(request["max_budget_units"])); ranked=candidates; overflow=sorted(str(x.get("evidence_id")) for x in rows[admission:]); q=set();u=set();b=set();unc=set();neg=set();om=set()
    for x in rows[:admission]:
        eid=str(x.get("evidence_id"));neg.add(f"{eid}:negative-result") if x.get("negative_result") else None;hard=not request.get("policy_allow",False) or not request.get("protected_closure",False) or not request.get("federation_approved",False) or not request.get("signed_approval",False) or x.get("available") is not True or x.get("permitted") is not True or x.get("aggregate_only") is not True or x.get("raw_data_local") is not True or x.get("semantic_profile")!=request["semantic_profile"] or not _digest(x.get("content_digest")) or not _digest(x.get("provenance_digest"));soft=x.get("replay_identity")!=request["replay_identity"] or int(x.get("relevance_milli",0))<500 or int(x.get("freshness_milli",0))<500 or x.get("evidence_state") not in {"proven","supported"}
        if hard or x.get("evidence_state")=="contradicted":b.add(eid)
        elif soft:u.add(eid);unc.add(f"{eid}:unresolved")
        else:q.add(eid)
    if overflow:om.add(f"batch:overflow:{len(overflow)}")
    qp={str(p.get("peer_id")) for p in request["peers"] if p.get("available") is True and p.get("signed") is True and p.get("aggregate_only") is True and p.get("raw_data_local") is True and p.get("semantic_profile")==request["semantic_profile"] and int(p.get("checkpoint_seq",0))==int(request["checkpoint_seq"]) and _digest(p.get("attestation_digest"))}; peers=sorted({str(p.get("peer_id")) for p in request["peers"]});mp=sorted(set(peers)-qp)
    if len(qp)<int(request["min_peer_quorum"]):om.add(f"peer-quorum:{len(qp)}/{request['min_peer_quorum']}")
    for k,label in (("policy_allow","workflow:policy-denied"),("protected_closure","workflow:protected-closure-incomplete"),("federation_approved","workflow:federation-approval-missing"),("signed_approval","workflow:signed-approval-missing")):
        if request.get(k) is not True:om.add(label)
    global_block=any(request.get(k) is not True for k in ("policy_allow","protected_closure","federation_approved","signed_approval"));disp="blocked" if global_block or b else "unresolved" if overflow or u or neg or len(qp)<int(request["min_peer_quorum"]) else "qualified";om.add("workflow:closure-incomplete") if disp!="qualified" else None
    if global_block:b.update(candidates);q.clear();u.clear()
    checkpoint=_hash({"batch_id":request["batch_id"],"checkpoint_seq":request["checkpoint_seq"],"partition":request["partition"],"replay_identity":request["replay_identity"]});payload={"candidate_order":candidates,"ranked_order":ranked,"qualified_order":sorted(q),"unresolved_order":sorted(u),"blocked_order":sorted(b),"overflow_order":overflow,"peer_order":peers,"qualified_peer_order":sorted(qp),"missing_peer_order":mp,"omission_order":sorted(om),"uncertainty_order":sorted(unc),"negative_evidence_order":sorted(neg),"checkpoint_digest":checkpoint,"replay_identity":request["replay_identity"]};control=_hash(payload);payload.update({"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"feature_id":FEATURE_ID,"request_id":request["request_id"],"batch_id":request["batch_id"],"partition":request["partition"],"scope":request["scope"],"semantic_profile":request["semantic_profile"],"checkpoint_seq":int(request["checkpoint_seq"]),"disposition":disp,"control_digest":control,"artifact":{"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"artifact_id":f"scope-federated-evidence-control:{request['batch_id']}","content_type":CONTENT_TYPE,"content_hash":control,"semantic_loss":[],"provenance_digests":sorted({str(p.get('attestation_digest')) for p in request['peers']}),"boundary":PRECLINICAL_BOUNDARY},"effect_receipts":[f"coordinate:evidence-control:{request['batch_id']}"] if disp=="qualified" else ["block:unsafe-release"],"raw_data_local":True,"aggregate_only":True,"boundary":PRECLINICAL_BOUNDARY});r=FederatedEvidenceControlReceipt9(payload);r.validate();return r
__all__=["FEATURE_ID","CONTRACT_VERSION","INPUT_SCHEMA","OUTPUT_SCHEMA","CONTENT_TYPE","FederatedEvidenceControlReceipt9","federated_evidence_control_manifest","operate_federated_evidence_control"]
