"""Python parity for Standards P32 migration-integrity cards."""
from __future__ import annotations
import hashlib,json,re
from typing import Any,Mapping
from .research_contracts import RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions";CONTENT_TYPE="application/vnd.aurora.standards.migration-integrity-card-1+json"
StandardObject4=dict[str,Any];MigrationIntegrityRequest4=dict[str,Any];MigrationIntegrityCard7=dict[str,Any];MigrationIntegrityArtifact4=dict[str,Any];MigrationIntegrityError=ResearchContractError
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return isinstance(v,list) and v==sorted(set(v))
def manifest(*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"standards","consumers":["harmonization compiler","ontology steward","analysis runtime","research workbench"],"behavior":f"qualify versioned standard migrations at {scale} ({mode})","value":"prevents coordinate, unit, ontology, and semantic-loss incompatibilities from entering reproducible research workflows","input_schema":"MigrationIntegrityRequest4@1","output_schema":"MigrationIntegrityCard7@1","effects":["emit:migration-card","retain:semantic-loss","block:unsafe-migration"],"permissions":["read:local-standard-fixtures"],"determinism":"byte_stable","autonomy_tier":"A1","boundary":BOUNDARY}
def validate(o:Mapping[str,Any],*,feature_id:str|None=None)->None:
 a=o.get("artifact",{});bad=o.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or(feature_id is not None and o.get("feature_id")!=feature_id)or not o.get("request_id")or not o.get("purpose")or o.get("boundary")!=BOUNDARY or a.get("boundary")!=BOUNDARY or o.get("raw_data_local") is not True or o.get("aggregate_only") is not True or not _digest(o.get("replay_identity")) or not _digest(o.get("closure_digest")) or a.get("content_type")!=CONTENT_TYPE or a.get("content_hash")!=o.get("closure_digest")
 if bad:raise ResearchContractError("migration identity, locality, artifact, digest, or boundary is incomplete")
 for k in("object_order","accepted_order","rejected_order","unknown_order","omitted_order","standard_order","version_order","coordinate_order","unit_order","loss_order","effect_receipts"):
  if not _ordered(o.get(k,[])):raise ResearchContractError("migration vectors are not canonical")
 ids=set(o["object_order"]);states=set(o["accepted_order"])|set(o["rejected_order"])|set(o["unknown_order"])|set(o["omitted_order"])
 if len(o["object_order"])!=len(ids)or states!=ids:raise ResearchContractError("object states do not partition")
def qualify(request:Mapping[str,Any],*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:
 if request.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or not request.get("request_id","").strip() or not request.get("purpose","").strip() or not request.get("objects") or not request.get("required_object_order") or not _ordered(request["required_object_order"]) or not _ordered(request.get("required_standard_order",[])) or not _digest(request.get("replay_identity")) or request.get("boundary")!=BOUNDARY or request.get("raw_data_local") is not True or request.get("aggregate_only") is not True or not _ordered(request.get("adversarial_events",[])) or request.get("object_budget",0)<=0:raise ResearchContractError("migration identity, ordering, digest, locality, boundary, or budget is invalid")
 rows=sorted(request["objects"],key=lambda a:a.get("object_id",""));seen=set();accepted=set();rejected=set();unknown=set();omitted=set();standards=set();versions=set();coordinates=set();units=set();losses=set();evidence=set()
 for o in rows:
  oid=o.get("object_id","")
  if not oid.strip()or oid in seen or not o.get("standard","").strip()or not o.get("version","").strip()or not o.get("semantic_loss","").strip()or not o.get("coordinate_frame","").strip()or not o.get("unit","").strip()or not o.get("evidence_state","").strip()or not _digest(o.get("digest"))or o.get("local") is not True or o.get("aggregate_only") is not True:raise ResearchContractError("object identity, standard, version, loss, coordinate, unit, evidence, digest, or locality is invalid")
  seen.add(oid);standards.add(f"{oid}:{o['standard']}");versions.add(f"{oid}:{o['version']}");coordinates.add(f"{oid}:{o['coordinate_frame']}");units.add(f"{oid}:{o['unit']}");losses.add(f"{oid}:{o['semantic_loss']}");evidence.add(o["digest"])
  if o["evidence_state"]=="unknown"or o["digest"]==request["replay_identity"]:unknown.add(oid)
  elif o["semantic_loss"]!="none"or o["standard"]=="unknown":rejected.add(oid)
  elif oid not in request["required_object_order"]:omitted.add(oid)
  else:accepted.add(oid)
 missing=[x for x in request["required_object_order"] if x not in seen];global_block=not all(request.get(k) is True for k in("policy_allowed","protected_closure","signed_manifest","raw_data_local","aggregate_only"))or bool(request.get("adversarial_events"))or len(rows)>request["object_budget"]
 if global_block:omitted.update(seen);accepted.clear();rejected.clear();unknown.clear()
 disposition="blocked" if global_block else "unknown" if missing or unknown else "partial" if rejected or omitted else "qualified";payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"request_id":request["request_id"],"purpose":request["purpose"],"disposition":disposition,"object_order":sorted(seen),"accepted_order":sorted(accepted),"rejected_order":sorted(rejected),"unknown_order":sorted(unknown),"omitted_order":sorted(omitted),"standard_order":sorted(standards),"version_order":sorted(versions),"coordinate_order":sorted(coordinates),"unit_order":sorted(units),"loss_order":sorted(losses),"replay_identity":request["replay_identity"],"raw_data_local":True,"aggregate_only":True,"boundary":BOUNDARY};d=_hash(payload);payload["closure_digest"]=d;payload["effect_receipts"]=[f"approve:migration:{request['request_id']}"] if disposition=="qualified" else ["block:unsafe-migration"];payload["artifact"]={"artifact_id":f"standards-migration:{request['request_id']}","content_type":CONTENT_TYPE,"content_hash":d,"semantic_loss":payload["omitted_order"],"evidence_digests":sorted(evidence),"boundary":BOUNDARY};validate(payload,feature_id=feature_id);return payload
__all__=["BOUNDARY","CONTENT_TYPE","StandardObject4","MigrationIntegrityRequest4","MigrationIntegrityCard7","MigrationIntegrityArtifact4","MigrationIntegrityError","manifest","qualify","validate"]
