"""Python parity for Stewardship P32 immutable snapshot integrity cards."""
from __future__ import annotations
import hashlib,json,re
from typing import Any,Mapping
from .research_contracts import RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
BOUNDARY="preclinical-research-only; no human-subject or clinical-source data; no diagnosis, treatment, triage, enrollment, or clinical decisions";CONTENT_TYPE="application/vnd.aurora.stewardship.snapshot-integrity-card-1+json"
StewardshipItem4=dict[str,Any];SnapshotIntegrityRequest4=dict[str,Any];SnapshotIntegrityCard7=dict[str,Any];SnapshotIntegrityArtifact4=dict[str,Any];SnapshotIntegrityError=ResearchContractError
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return isinstance(v,list) and v==sorted(set(v))
def manifest(*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"stewardship","consumers":["release steward","consortium archivist","review board","research workbench"],"behavior":f"qualify immutable research snapshots at {scale} ({mode})","value":"prevents unsigned, prematurely retired, unreviewed, or negative-result-suppressed snapshots from release","input_schema":"SnapshotIntegrityRequest4@1","output_schema":"SnapshotIntegrityCard7@1","effects":["emit:snapshot-card","retain:negative-finding","block:unsafe-snapshot"],"permissions":["read:local-manifest"],"determinism":"byte_stable","autonomy_tier":"A1","boundary":BOUNDARY}
def validate(o:Mapping[str,Any],*,feature_id:str|None=None)->None:
 a=o.get("artifact",{});bad=o.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or(feature_id is not None and o.get("feature_id")!=feature_id)or not o.get("snapshot_id")or not o.get("quarter")or o.get("boundary")!=BOUNDARY or a.get("boundary")!=BOUNDARY or o.get("raw_data_local") is not True or o.get("aggregate_only") is not True or not _digest(o.get("replay_identity")) or not _digest(o.get("closure_digest")) or a.get("content_type")!=CONTENT_TYPE or a.get("content_hash")!=o.get("closure_digest")
 if bad:raise ResearchContractError("snapshot identity, locality, artifact, digest, or boundary is incomplete")
 for k in("item_order","accepted_order","rejected_order","unknown_order","omitted_order","owner_order","reviewer_order","retention_order","negative_order","checksum_order","effect_receipts"):
  if not _ordered(o.get(k,[])):raise ResearchContractError("snapshot vectors are not canonical")
 ids=set(o["item_order"]);states=set(o["accepted_order"])|set(o["rejected_order"])|set(o["unknown_order"])|set(o["omitted_order"])
 if len(o["item_order"])!=len(ids)or states!=ids:raise ResearchContractError("item states do not partition")
def qualify(request:Mapping[str,Any],*,feature_id:str,contract_version:str,scale:str,mode:str)->dict[str,Any]:
 if request.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or not request.get("request_id","").strip() or not request.get("purpose","").strip() or not request.get("snapshot_id","").strip() or not request.get("quarter","").strip() or not request.get("items") or not request.get("required_item_order") or not _ordered(request["required_item_order"]) or not _digest(request.get("replay_identity")) or request.get("boundary")!=BOUNDARY or request.get("raw_data_local") is not True or request.get("aggregate_only") is not True or not _ordered(request.get("adversarial_events",[])) or request.get("item_budget",0)<=0:raise ResearchContractError("snapshot identity, ordering, digest, locality, boundary, or budget is invalid")
 rows=sorted(request["items"],key=lambda i:i.get("item_id",""));seen=set();accepted=set();rejected=set();unknown=set();omitted=set();owners=set();reviewers=set();retention=set();negative=set();checksums=set();evidence=set()
 for i in rows:
  iid=i.get("item_id","")
  if not iid.strip()or iid in seen or not i.get("owner","").strip()or not i.get("lifecycle","").strip()or not _digest(i.get("checksum"))or not i.get("evidence_state","").strip()or not i.get("reviewer","").strip()or i.get("local") is not True or i.get("aggregate_only") is not True:raise ResearchContractError("item identity, checksum, reviewer, evidence, or locality is invalid")
  seen.add(iid);owners.add(f"{iid}:{i['owner']}");reviewers.add(f"{iid}:{i['reviewer']}");retention.add(f"{iid}:{i.get('retention_epoch',0)}");checksums.add(f"{iid}:{i['checksum']}");evidence.add(i["checksum"]);negative.add(f"{iid}:negative-result") if i.get("negative_result") else None
  if i["evidence_state"]=="unknown" or i["checksum"]==request["replay_identity"]:unknown.add(iid)
  elif i["lifecycle"]=="retired" or i.get("retention_epoch",0)<request.get("minimum_retention_epoch",0) or i["reviewer"]==i["owner"] or i["reviewer"]=="unverified":rejected.add(iid)
  elif iid not in request["required_item_order"]:omitted.add(iid)
  else:accepted.add(iid)
 missing=[x for x in request["required_item_order"] if x not in seen];global_block=not all(request.get(k) is True for k in("policy_allowed","protected_closure","signed_manifest","independent_review","raw_data_local","aggregate_only"))or bool(request.get("adversarial_events"))or len(rows)>request["item_budget"]
 if global_block:omitted.update(seen);accepted.clear();rejected.clear();unknown.clear()
 disposition="blocked" if global_block else "unknown" if missing or unknown else "partial" if rejected or omitted else "qualified";payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"request_id":request["request_id"],"purpose":request["purpose"],"snapshot_id":request["snapshot_id"],"quarter":request["quarter"],"disposition":disposition,"item_order":sorted(seen),"accepted_order":sorted(accepted),"rejected_order":sorted(rejected),"unknown_order":sorted(unknown),"omitted_order":sorted(omitted),"owner_order":sorted(owners),"reviewer_order":sorted(reviewers),"retention_order":sorted(retention),"negative_order":sorted(negative),"checksum_order":sorted(checksums),"replay_identity":request["replay_identity"],"raw_data_local":True,"aggregate_only":True,"boundary":BOUNDARY};d=_hash(payload);payload["closure_digest"]=d;payload["effect_receipts"]=[f"approve:snapshot:{request['snapshot_id']}"] if disposition=="qualified" else ["block:unsafe-snapshot"];payload["artifact"]={"artifact_id":f"stewardship-snapshot:{request['snapshot_id']}","content_type":CONTENT_TYPE,"content_hash":d,"semantic_loss":payload["omitted_order"],"evidence_digests":sorted(evidence),"boundary":BOUNDARY};validate(payload,feature_id=feature_id);return payload
__all__=["BOUNDARY","CONTENT_TYPE","StewardshipItem4","SnapshotIntegrityRequest4","SnapshotIntegrityCard7","SnapshotIntegrityArtifact4","SnapshotIntegrityError","manifest","qualify","validate"]
