"""Backends P32 throughput contract_model capability-negotiation integrity feature."""
from .capability_negotiation_integrity_support import BackendCard7,BackendRequest4,CapabilityNegotiationIntegrityError,manifest,negotiate
FEATURE_ID="AFA-backends-P32-F07";CONTRACT_VERSION="backends-throughput_capability_negotiation_integrity_contract_model/1.0"
def throughput_capability_negotiation_integrity_contract_model_manifest():return manifest(feature_id=FEATURE_ID,contract_version=CONTRACT_VERSION,scale="throughput",mode="contract_model")
def negotiate_throughput_capability_negotiation_integrity_contract_model(request:BackendRequest4)->BackendCard7:return negotiate(request,feature_id=FEATURE_ID,contract_version=CONTRACT_VERSION,scale="throughput",mode="contract_model")
__all__=["FEATURE_ID","CONTRACT_VERSION","throughput_capability_negotiation_integrity_contract_model_manifest","negotiate_throughput_capability_negotiation_integrity_contract_model"]
