"""Choreography P32 throughput contract_model protocol-compilation integrity feature."""
from .protocol_execution_integrity_support import ProtocolExecutionCard7,ProtocolExecutionRequest4,ProtocolExecutionIntegrityError,manifest,execute
FEATURE_ID="AFA-choreography-P32-F07";CONTRACT_VERSION="choreography-throughput_protocol_execution_integrity_contract_model/1.0"
def throughput_protocol_execution_integrity_contract_model_manifest():return manifest(feature_id=FEATURE_ID,contract_version=CONTRACT_VERSION,scale="throughput",mode="contract_model")
def execute_throughput_protocol_execution_integrity_contract_model(request:ProtocolExecutionRequest4)->ProtocolExecutionCard7:return execute(request,feature_id=FEATURE_ID,contract_version=CONTRACT_VERSION,scale="throughput",mode="contract_model")
__all__=["FEATURE_ID","CONTRACT_VERSION","throughput_protocol_execution_integrity_contract_model_manifest","execute_throughput_protocol_execution_integrity_contract_model"]
