"""Deterministic Python parity for Worldgen P18 provenance/visualization qualification."""
from __future__ import annotations
import hashlib,json,re
from dataclasses import dataclass
from typing import Any,Mapping
from .research_contracts import PRECLINICAL_BOUNDARY,RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
FEATURE_ID="AFA-worldgen-P18-F01"; CONTRACT_VERSION="worldgen-local-provenance-signing/1.0"; INPUT_SCHEMA="ArtifactAndDerivation@1"; OUTPUT_SCHEMA="SignedProvenanceEnvelope1@1"; CONTENT_TYPE="application/vnd.aurora.worldgen.provenance-signing-result+json"
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return v==sorted(set(v))
@dataclass(frozen=True)
class SignedProvenanceEnvelope1:
    value:dict[str,Any]
    def to_dict(self)->dict[str,Any]:return dict(self.value)
    def validate(self)->None:
        v=self.value;a=v.get("artifact",{})
        if v.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or v.get("boundary")!=PRECLINICAL_BOUNDARY or a.get("boundary")!=PRECLINICAL_BOUNDARY or a.get("content_type")!=CONTENT_TYPE or a.get("content_hash")!=v.get("provenance_digest") or v.get("raw_data_local") is not True or v.get("federation_export")!="aggregate-digest-only" or not v.get("candidate_order") or len(v.get("decisions",[]))!=len(v["candidate_order"]) or not v.get("effect_receipts") or v.get("disposition") not in {"qualified","unresolved","blocked"} or not all(_digest(v.get(k)) for k in ("replay_identity","provenance_digest","signature_digest")) or not isinstance(v.get("signer_id"),str) or not v["signer_id"].strip() or v.get("signature_algorithm")!="ed25519-content-digest-v1":raise ResearchContractError("provenance identity, signature, locality, digest, or effects are incomplete")
        fields=("candidate_order","selected_order","unresolved_order","blocked_order","omitted_order","derivation_order","signature_scope_order","omissions","uncertainty","contradiction","negative_evidence","effect_receipts")
        if any(not _ordered(v.get(k,[])) for k in fields):raise ResearchContractError("provenance vectors are not canonical")
        ids=set(v["candidate_order"]);parts=v["selected_order"]+v["unresolved_order"]+v["blocked_order"]
        if len(ids)!=len(v["candidate_order"]) or len(parts)!=len(ids) or set(parts)!=ids:raise ResearchContractError("provenance items do not partition candidates")
        if len(v.get("lineage_score_milli",[]))!=len(v["selected_order"]) or len(v.get("uncertainty_milli",[]))!=len(v["selected_order"]):raise ResearchContractError("selected effects and uncertainty do not align")
def manifest(*,feature_id:str,contract_version:str,scale:str)->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"worldgen","consumers":["imaging core scientist","bioinformatician","benchmark curator"],"behavior":f"verify verifiable artifact lineage at {scale} with signature and provenance receipts","value":"prevents leakage, unsupported certainty, unproven effects, and unauthorized data movement from entering research conclusions","input_schema":INPUT_SCHEMA,"output_schema":OUTPUT_SCHEMA,"effects":["emit:qualified-provenance-result","block:unsafe-provenance"],"permissions":["verify:typed-canonicalization"],"determinism":"byte_stable","autonomy_tier":"A1","boundary":PRECLINICAL_BOUNDARY}
def _validate_request(r:Mapping[str,Any])->None:
    if r.get("schema_version")!=INPUT_SCHEMA or not all(isinstance(r.get(k),str) and r[k].strip() for k in ("request_id","study_id","question","scope")) or not r.get("candidates") or len(r["candidates"])>int(r.get("max_candidates",0)) or not _digest(r.get("replay_identity")) or r.get("policy_allow") is not True or r.get("raw_data_local") is not True or r.get("federated_summary_only") is not True or r.get("boundary")!=PRECLINICAL_BOUNDARY or not _ordered(r.get("adversarial_events",[])):raise ResearchContractError("identity, candidate bounds, locality, policy, replay, or boundary is invalid")
    ids=set()
    for c in r["candidates"]:
        if not isinstance(c.get("artifact_id"),str) or not c["artifact_id"].strip() or c["artifact_id"] in ids or not isinstance(c.get("method"),str) or not c["method"].strip() or any(not _ordered(c.get(k,[])) for k in ("input_order","derivation_order","omissions","uncertainty")) or not _digest(c.get("replay_identity")):raise ResearchContractError("candidate identifiers, ordering, evidence, or digests are invalid")
        ids.add(c["artifact_id"])
def qualify(request:Mapping[str,Any],*,feature_id:str=FEATURE_ID,contract_version:str=CONTRACT_VERSION)->SignedProvenanceEnvelope1:
    _validate_request(request);cs=sorted((dict(c) for c in request["candidates"]),key=lambda c:c["artifact_id"]);candidate=[c["artifact_id"] for c in cs];block=not all(request.get(k) is True for k in ("policy_allow","protected_closure","raw_data_local","federated_summary_only")) or bool(request.get("adversarial_events"));selected=[];unresolved=[];blocked=[];omitted=set();uncertainty=set();contradiction=set();negative=set();counterfactual=set();manifest_item=set();estimates=[];widths=[];decisions=[];loss=[]
    for c in cs:
        i=c["artifact_id"];omitted.update(f"{i}:{x}" for x in c.get("omissions",[]));uncertainty.update(f"{i}:{x}" for x in c.get("uncertainty",[]));counterfactual.update(f"{i}:{x}" for x in c.get("derivation_order",[]));manifest_item.update(f"{i}:{x}" for x in c.get("input_order",[]));contradiction.add(f"{i}:contradicted") if c.get("evidence_state")=="contradicted" else None;negative.add(f"{i}:null-or-negative-result") if c.get("evidence_state")=="negative" else None
        fail=block or not c.get("policy_allowed",False) or not c.get("protected_closure",False) or not c.get("baseline_digest") or not c.get("provenance_digest") or c.get("replay_identity")!=request["replay_identity"];pending=not fail and (c.get("evidence_state") not in {"proven","supported"} or bool(c.get("omissions")) or bool(c.get("uncertainty")) or int(c.get("uncertainty_milli",0))==0 or not c.get("derivation_order"));state="blocked" if fail else "unresolved" if pending else "selected";decisions.append({"artifact_id":i,"method":c["method"],"disposition":state,"lineage_milli":int(c.get("lineage_milli",0)),"uncertainty_milli":int(c.get("uncertainty_milli",0))})
        if state=="blocked":blocked.append(i);loss.append({"field":f"candidate:{i}","reason":"provenance gate failed","severity":"decision_relevant"})
        elif state=="unresolved":unresolved.append(i)
        else:selected.append(i);estimates.append(int(c.get("lineage_milli",0)));widths.append(int(c.get("uncertainty_milli",0)))
    if block:selected=[];unresolved=[];blocked=candidate;omitted.add("request:policy-or-locality-blocked")
    selected.sort();unresolved.sort();blocked.sort();disp="blocked" if block or blocked else "unresolved" if unresolved else "qualified";omitted.add("request:provenance-closure-not-ready") if disp!="qualified" else None
    payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"request_id":request["request_id"],"study_id":request["study_id"],"scope":request["scope"],"disposition":disp,"candidate_order":candidate,"selected_order":selected,"unresolved_order":unresolved,"blocked_order":blocked,"omitted_order":sorted(omitted),"lineage_score_milli":estimates,"uncertainty_milli":widths,"derivation_order":sorted(counterfactual),"signature_scope_order":sorted(manifest_item),"decisions":decisions,"replay_identity":request["replay_identity"],"semantic_loss":loss,"omissions":sorted(omitted),"uncertainty":sorted(uncertainty),"contradiction":sorted(contradiction),"negative_evidence":sorted(negative),"raw_data_local":True,"federation_export":"aggregate-digest-only","boundary":PRECLINICAL_BOUNDARY};d=_hash(payload);payload["provenance_digest"]=d;payload["signer_id"]="aurora-local-development-signer";payload["signature_algorithm"]="ed25519-content-digest-v1";payload["signature_digest"]=d;payload["artifact"]={"artifact_id":f"qualified-provenance-result-1:{request['request_id']}","content_type":CONTENT_TYPE,"content_hash":d,"semantic_loss":loss,"provenance":[{"source_id":request["study_id"],"relation":"provenance-signing-qualification","digest":d}],"boundary":PRECLINICAL_BOUNDARY};payload["effect_receipts"]=[f"qualify:provenance:{request['request_id']}"] if disp=="qualified" else ["block:unsafe-provenance"];out=SignedProvenanceEnvelope1(payload);out.validate();return out
__all__=["FEATURE_ID","CONTRACT_VERSION","INPUT_SCHEMA","OUTPUT_SCHEMA","CONTENT_TYPE","SignedProvenanceEnvelope1","manifest","qualify"]
