"""A1 prospective high-throughput evidence-surveillance researcher workbench."""
from __future__ import annotations
from dataclasses import dataclass
import re
from typing import Any, Mapping, Sequence
from .worldgen_throughput_evidence_surveillance_research_copilot import ThroughputCopilotEvidenceObservation, run_throughput_evidence_surveillance_research_copilot
from .research_contracts import PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError, research_artifact_digest

FEATURE_ID="AFA-worldgen-P01-F19"; CONTRACT_VERSION="worldgen-throughput-evidence-surveillance-research-workbench/1.0"; INPUT_SCHEMA="EvidenceFeed3@1"; OUTPUT_SCHEMA="QualifiedEvidenceSet5@1"
CANONICAL_VIEWS=("view:queue","view:capacity","view:checkpoint","view:provenance"); CANONICAL_PANELS=("panel:overflow","panel:negative","panel:qualified","panel:unknown")

@dataclass(frozen=True)
class ThroughputEvidenceSurveillanceResearchWorkbenchReceipt:
    request_id:str; workbench_id:str; scope:str; batch_id:str; checkpoint_seq:int; capacity:int; disposition:str; view_order:tuple[str,...]; panel_order:tuple[str,...]; candidate_order:tuple[str,...]; qualified_order:tuple[str,...]; unknown_order:tuple[str,...]; blocked_order:tuple[str,...]; overflow_order:tuple[str,...]; replay_identity:str; copilot_run_digest:str; workbench_digest:str; queue_digest:str; checkpoint_digest:str; omissions:tuple[str,...]; uncertainty:tuple[str,...]; negative_evidence:tuple[str,...]; effect_receipts:tuple[str,...]; artifact:Mapping[str,Any]; raw_data_local:bool=True; boundary:str=PRECLINICAL_BOUNDARY; feature_id:str=FEATURE_ID; contract_version:str=CONTRACT_VERSION; schema_version:str=RESEARCH_CONTRACT_SCHEMA_VERSION
    def validate(self)->None:
        if (self.schema_version,self.contract_version,self.feature_id)!=(RESEARCH_CONTRACT_SCHEMA_VERSION,CONTRACT_VERSION,FEATURE_ID) or self.boundary!=PRECLINICAL_BOUNDARY or not self.raw_data_local or not self.request_id.strip() or not self.workbench_id.strip() or not self.scope.strip() or not self.batch_id.strip() or self.checkpoint_seq<=0 or self.capacity<=0 or self.view_order!=CANONICAL_VIEWS or self.panel_order!=CANONICAL_PANELS or not self.candidate_order or not self.effect_receipts: raise ResearchContractError("throughput workbench identity, checkpoint, canonical views, capacity, locality, candidates, or effects are incomplete")
        for values in (self.candidate_order,self.qualified_order,self.unknown_order,self.blocked_order,self.overflow_order,self.omissions,self.uncertainty,self.negative_evidence,self.effect_receipts):
            if tuple(sorted(set(values)))!=values: raise ResearchContractError("throughput workbench ordering is not canonical")
        if set(self.qualified_order)|set(self.unknown_order)|set(self.blocked_order)|set(self.overflow_order)!=set(self.candidate_order): raise ResearchContractError("throughput workbench states do not partition candidates")
        for value in (self.replay_identity,self.copilot_run_digest,self.workbench_digest,self.queue_digest,self.checkpoint_digest,self.artifact.get("content_hash")):
            if not isinstance(value,str) or not re.fullmatch(r"[0-9a-f]{64}",value): raise ResearchContractError("throughput workbench digest is invalid")
        if any(not e.startswith("view:throughput-evidence-workbench:") and e!="block:unsafe-release" for e in self.effect_receipts): raise ResearchContractError("throughput workbench effect is outside read-only gate")
    def digest(self)->str: self.validate(); return research_artifact_digest(self.__dict__)

def render_throughput_evidence_surveillance_research_workbench(*, request_id:str, workbench_id:str, scope:str, batch_id:str, checkpoint_seq:int, capacity:int, agent_id:str, declared_tools:Sequence[str], requested_tool:str, max_tool_calls:int, dry_run:bool, approval_reference:str|None, approval_granted:bool, observations:Sequence[ThroughputCopilotEvidenceObservation], replay_identity:str, min_relevance_score:int=0, policy_allow:bool=True, protected_closure:bool=True, raw_data_local:bool=True, view_order:Sequence[str]=CANONICAL_VIEWS, panel_order:Sequence[str]=CANONICAL_PANELS)->ThroughputEvidenceSurveillanceResearchWorkbenchReceipt:
    if not dry_run or not raw_data_local or not re.fullmatch(r"[0-9a-f]{64}",replay_identity) or tuple(view_order)!=CANONICAL_VIEWS or tuple(panel_order)!=CANONICAL_PANELS: raise ResearchContractError("throughput workbench requires local dry-run request with canonical views and panels")
    c=run_throughput_evidence_surveillance_research_copilot(request_id=request_id,agent_id=agent_id,batch_id=batch_id,checkpoint_seq=checkpoint_seq,capacity=capacity,declared_tools=declared_tools,requested_tool=requested_tool,max_tool_calls=max_tool_calls,dry_run=True,approval_reference=approval_reference,approval_granted=approval_granted,observations=observations,min_relevance_score=min_relevance_score,policy_allow=policy_allow,protected_closure=protected_closure,raw_data_local=True,replay_identity=replay_identity)
    candidate=tuple(sorted(c.candidate_order)); qualified=tuple(sorted(c.selected_order)); unknown=tuple(sorted(c.unresolved_order)); blocked=tuple(sorted(c.denied_order)); overflow=tuple(sorted(c.overflow_order)); omissions=tuple(sorted(set(c.omissions)|{"workbench:read-only-throughput-view"})); copilot_digest=research_artifact_digest(c.__dict__); workbench_digest=research_artifact_digest({"workbench_id":workbench_id,"scope":scope,"batch_id":batch_id,"checkpoint_seq":checkpoint_seq,"capacity":capacity,"views":list(view_order),"panels":list(panel_order),"candidate":list(candidate),"qualified":list(qualified),"unknown":list(unknown),"blocked":list(blocked),"overflow":list(overflow),"replay_identity":replay_identity,"copilot_run_digest":copilot_digest}); payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"feature_id":FEATURE_ID,"request_id":request_id,"workbench_id":workbench_id,"scope":scope,"batch_id":batch_id,"checkpoint_seq":checkpoint_seq,"capacity":capacity,"disposition":c.disposition,"view_order":list(view_order),"panel_order":list(panel_order),"candidate_order":list(candidate),"qualified_order":list(qualified),"unknown_order":list(unknown),"blocked_order":list(blocked),"overflow_order":list(overflow),"replay_identity":replay_identity,"copilot_run_digest":copilot_digest,"workbench_digest":workbench_digest,"queue_digest":c.queue_digest,"checkpoint_digest":c.checkpoint_digest,"omissions":list(omissions),"uncertainty":list(c.uncertainty),"negative_evidence":list(c.negative_evidence),"boundary":PRECLINICAL_BOUNDARY,"raw_data_local":True}; r=ThroughputEvidenceSurveillanceResearchWorkbenchReceipt(request_id=request_id,workbench_id=workbench_id,scope=scope,batch_id=batch_id,checkpoint_seq=checkpoint_seq,capacity=capacity,disposition=c.disposition,view_order=tuple(view_order),panel_order=tuple(panel_order),candidate_order=candidate,qualified_order=qualified,unknown_order=unknown,blocked_order=blocked,overflow_order=overflow,replay_identity=replay_identity,copilot_run_digest=copilot_digest,workbench_digest=workbench_digest,queue_digest=c.queue_digest,checkpoint_digest=c.checkpoint_digest,omissions=omissions,uncertainty=tuple(sorted(c.uncertainty)),negative_evidence=tuple(sorted(c.negative_evidence)),effect_receipts=(f"view:throughput-evidence-workbench:{workbench_id}",),artifact={"content_hash":research_artifact_digest(payload),"media_type":"application/vnd.aurora.throughput-evidence-workbench+json"}); r.validate(); return r

__all__=["CANONICAL_VIEWS","CANONICAL_PANELS","FEATURE_ID","CONTRACT_VERSION","ThroughputEvidenceSurveillanceResearchWorkbenchReceipt","render_throughput_evidence_surveillance_research_workbench"]


