"""Read-only retrieval-synthesis researcher workbench for Worldgen P02 F17–F20."""
from __future__ import annotations
from dataclasses import dataclass
import hashlib, json, re
from typing import Any
from .research_contracts import PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError
from .worldgen_retrieval_copilot_support import RetrievalCopilotRequest, run as run_copilot
CONTENT_TYPE="application/vnd.aurora.worldgen.retrieval-workbench-receipt+json"; _HEX=re.compile(r"^[0-9a-f]{64}$")
VIEWS=("view:overview","view:evidence","view:omissions","view:provenance"); PANELS=("panel:negative","panel:provenance","panel:qualified","panel:unknown")
@dataclass(frozen=True)
class RetrievalWorkbenchRequest:
    copilot:RetrievalCopilotRequest; workspace_id:str; scope:str; requested_view_order:tuple[str,...]; requested_panel_order:tuple[str,...]; budget_units:int; replay_identity:str
@dataclass(frozen=True)
class RetrievalWorkbenchReceipt:
    value:dict[str,Any]
    def validate(self, *, feature_id:str, contract_version:str)->None:
        v=self.value; a=v.get("artifact",{}); candidates=tuple(v.get("candidate_order",())); parts=tuple(v.get("selected_order",()))+tuple(v.get("unresolved_order",()))+tuple(v.get("blocked_order",()))
        if v.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or v.get("contract_version")!=contract_version or v.get("feature_id")!=feature_id or v.get("boundary")!=PRECLINICAL_BOUNDARY or a.get("boundary")!=PRECLINICAL_BOUNDARY or a.get("content_type")!=CONTENT_TYPE or v.get("raw_data_local") is not True or v.get("aggregate_only") is not True or not v.get("request_id","").strip() or not v.get("workspace_id","").strip() or not v.get("scope","").strip() or tuple(v.get("view_order",()))!=VIEWS or tuple(v.get("panel_order",()))!=PANELS or not candidates or not v.get("effect_receipts") or not _HEX.fullmatch(v.get("replay_identity","")) or not _HEX.fullmatch(v.get("copilot_digest","")) or not _HEX.fullmatch(v.get("workbench_digest","")) or a.get("content_hash")!=v.get("workbench_digest"): raise ResearchContractError("worldgen retrieval workbench identity, views, locality, digests, or effects are incomplete")
        for key in ("candidate_order","selected_order","unresolved_order","blocked_order","denied_action_order","omissions","uncertainty","negative_evidence","effect_receipts"):
            vals=tuple(v.get(key,()));
            if vals!=tuple(sorted(set(vals))): raise ResearchContractError("worldgen retrieval workbench ordering is not canonical")
        if set(parts)!=set(candidates) or len(parts)!=len(candidates) or len(set(candidates))!=len(candidates): raise ResearchContractError("worldgen retrieval workbench candidate states do not partition")
        if any(e!="block:unsafe-release" and not e.startswith("view:retrieval-workbench:") for e in v["effect_receipts"]): raise ResearchContractError("worldgen retrieval workbench effect is outside read-only gate")
    def digest(self, *,feature_id:str,contract_version:str)->str: self.validate(feature_id=feature_id,contract_version=contract_version); return _digest(self.value)
def _digest(value:Any)->str: return hashlib.sha256(json.dumps(value,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def manifest(*,feature_id:str,contract_version:str,input_schema:str,scale:str,autonomy_tier:str)->dict[str,Any]: return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"worldgen","consumers":["preclinical researcher","research program lead","bioinformatician","imaging core scientist"],"behavior":f"render a deterministic read-only retrieval workbench for {scale}","value":"makes qualified, unknown, omitted, negative, and provenance state directly inspectable without upgrading incomplete evidence","input_schema":input_schema,"output_schema":"EvidenceSynthesis4@1","effects":["view:retrieval-workbench","block:unsafe-release"],"permissions":["read:local-research-artifacts"],"determinism":"byte_stable","autonomy_tier":autonomy_tier,"boundary":PRECLINICAL_BOUNDARY}
def render(request:RetrievalWorkbenchRequest, *,feature_id:str,contract_version:str,require_approval:bool,require_federation:bool)->RetrievalWorkbenchReceipt:
    if not request.workspace_id.strip() or not request.scope.strip() or request.budget_units<=0 or tuple(request.requested_view_order)!=VIEWS or tuple(request.requested_panel_order)!=PANELS or not _HEX.fullmatch(request.replay_identity) or request.copilot.query.replay_identity!=request.replay_identity or not request.copilot.dry_run or not request.copilot.query.raw_data_local or not request.copilot.query.aggregate_only: raise ResearchContractError("worldgen retrieval workbench identity, read-only, budget, locality, views, panels, or replay is invalid")
    copilot=run_copilot(request.copilot,feature_id=feature_id,contract_version=contract_version,require_approval=require_approval,require_federation=require_federation); syn=copilot.value["synthesis"]; candidates=sorted(syn["candidate_order"]); selected=sorted(syn["selected_order"]); unresolved=sorted(syn["unresolved_order"]); blocked=sorted(syn["blocked_order"]); omissions=sorted(set(syn["omission_order"]+[f"action-denied:{x}" for x in copilot.value["denied_action_order"]]+["workbench:read-only-local-view"])); uncertainty=sorted(set(syn["uncertainty_order"])); negative=sorted(set(syn["negative_evidence_order"])); effects=[f"view:retrieval-workbench:{request.workspace_id}"]; payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"request_id":request.copilot.query.request_id,"workspace_id":request.workspace_id,"scope":request.scope,"disposition":copilot.value["disposition"],"view_order":list(VIEWS),"panel_order":list(PANELS),"candidate_order":candidates,"selected_order":selected,"unresolved_order":unresolved,"blocked_order":blocked,"denied_action_order":sorted(copilot.value["denied_action_order"]),"replay_identity":request.replay_identity,"copilot_digest":_digest(copilot.value),"omissions":omissions,"uncertainty":uncertainty,"negative_evidence":negative,"effect_receipts":effects,"raw_data_local":True,"aggregate_only":True,"boundary":PRECLINICAL_BOUNDARY}; digest=_digest(payload); payload["workbench_digest"]=digest; payload["artifact"]={"artifact_id":f"retrieval-workbench:{request.workspace_id}","content_type":CONTENT_TYPE,"content_hash":digest,"boundary":PRECLINICAL_BOUNDARY}; receipt=RetrievalWorkbenchReceipt(payload); receipt.validate(feature_id=feature_id,contract_version=contract_version); return receipt
__all__=["RetrievalWorkbenchRequest","RetrievalWorkbenchReceipt","render","manifest"]
