"""Version-pinned retrieval-synthesis interoperability gates for Worldgen P02 F21–F24."""
from __future__ import annotations
from dataclasses import dataclass
import hashlib, json, re
from typing import Any, Mapping
from .research_contracts import PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError
from .worldgen_retrieval_workbench_support import RetrievalWorkbenchRequest, render as render_workbench
CONTENT_TYPE="application/vnd.aurora.worldgen.retrieval-interoperability-receipt+json"; _HEX=re.compile(r"^[0-9a-f]{64}$")
@dataclass(frozen=True)
class RetrievalInteroperabilityReceipt:
    value:dict[str,Any]
    def validate(self, *,feature_id:str,contract_version:str,input_schema:str,output_schema:str)->None:
        v=self.value; a=v.get("artifact",{}); allowed={"exchange:permitted-artifact-digests-only","block:unsafe-release"}
        if v.get("schema_version")!=RESEARCH_CONTRACT_SCHEMA_VERSION or v.get("contract_version")!=contract_version or v.get("feature_id")!=feature_id or v.get("boundary")!=PRECLINICAL_BOUNDARY or a.get("boundary")!=PRECLINICAL_BOUNDARY or a.get("content_type")!=CONTENT_TYPE or v.get("input_schema")!=input_schema or v.get("output_schema")!=output_schema or not v.get("request_id","").strip() or not v.get("endpoint_id","").strip() or not v.get("negotiated_version","").strip() or not v.get("capability_order") or not v.get("effect_receipts") or not _HEX.fullmatch(v.get("workbench_digest","")) or not _HEX.fullmatch(v.get("protocol_digest","")) or not _HEX.fullmatch(a.get("content_hash","")): raise ResearchContractError("retrieval interoperability identity, schemas, locality, digests, or effects are incomplete")
        for key in ("capability_order","artifact_digest_order","semantic_loss_order","omissions","uncertainty","effect_receipts"):
            vals=tuple(v.get(key,()));
            if vals!=tuple(sorted(set(vals))): raise ResearchContractError("retrieval interoperability ordering is not canonical")
        if any(e not in allowed for e in v["effect_receipts"]): raise ResearchContractError("retrieval interoperability effect is outside digest-only exchange gate")
    def digest(self, *,feature_id:str,contract_version:str,input_schema:str,output_schema:str)->str: self.validate(feature_id=feature_id,contract_version=contract_version,input_schema=input_schema,output_schema=output_schema); return _digest(self.value)
def _digest(value:Any)->str: return hashlib.sha256(json.dumps(value,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def manifest(*,feature_id:str,contract_version:str,input_schema:str,scale:str,autonomy_tier:str)->dict[str,Any]: return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"worldgen","consumers":["bioinformatician","research program lead","imaging core scientist"],"behavior":f"negotiate a version-pinned retrieval protocol and exchange only permitted workbench digests for {scale}","value":"makes compatibility, semantic loss, omissions, and raw-data locality machine-checkable","input_schema":input_schema,"output_schema":"EvidenceSynthesis5@1","effects":["exchange:permitted-artifact-digests-only","block:unsafe-release"],"permissions":["connect:approved-endpoints"],"determinism":"byte_stable","autonomy_tier":autonomy_tier,"boundary":PRECLINICAL_BOUNDARY}
def negotiate(protocol:Mapping[str,Any], workbench_request:RetrievalWorkbenchRequest, *,feature_id:str,contract_version:str,input_schema:str,output_schema:str,require_approval:bool,require_federation:bool,semantic_loss_budget:int)->RetrievalInteroperabilityReceipt:
    if protocol.get("boundary")!=PRECLINICAL_BOUNDARY or not protocol.get("raw_data_local") or workbench_request.boundary!=PRECLINICAL_BOUNDARY or semantic_loss_budget<=0: raise ResearchContractError("protocol boundary, locality, workbench, or semantic-loss budget is invalid")
    request_id=str(protocol.get("request_id","")); endpoint_id=str(protocol.get("endpoint_id","")); source_version=str(protocol.get("source_contract_version","")); target_version=str(protocol.get("target_contract_version","1.0.0")); offered=tuple(sorted(set(map(str,protocol.get("offered_capabilities",()))))); targets=tuple(sorted(set(map(str,protocol.get("target_capabilities",()))))); artifacts=tuple(sorted(set(map(str,protocol.get("artifact_digests",())))))
    if not request_id.strip() or not endpoint_id.strip() or not source_version.strip() or not offered: raise ResearchContractError("protocol identity and offered capabilities are required")
    missing=tuple(x for x in targets if x not in offered); omissions=[]; uncertainty=[]; loss=[]
    if missing: omissions.append("target capabilities unavailable: "+",".join(missing)); uncertainty.append("parity cannot be established for unavailable capabilities")
    if target_version=="1.0.0" and source_version=="1.0.0": disposition="accepted"; negotiated="1.0.0"
    elif target_version=="1.0.0" and source_version=="0.9.0" and "1.0.0" in protocol.get("supported_contract_versions",()): disposition="migrated"; negotiated="1.0.0"; omissions.append("legacy fields outside pinned target remain unknown"); loss.append("legacy_fields")
    else: disposition="incompatible"; negotiated=target_version; uncertainty.append("source and target are outside the pinned compatibility window")
    if not protocol.get("policy_allow",False) or not protocol.get("permitted_export",False): disposition="blocked"; omissions.append("policy or endpoint authorization denied artifact exchange")
    elif not protocol.get("protected_closure",False): disposition="approval_required"; uncertainty.append("protected closure is incomplete")
    elif missing: disposition="unknown"
    if len(loss)>semantic_loss_budget: raise ResearchContractError("semantic-loss budget exceeded")
    wb=render_workbench(workbench_request,feature_id=feature_id,contract_version=contract_version,require_approval=require_approval,require_federation=require_federation); omissions=sorted(set(omissions)|set(wb.value.get("omissions",()))); uncertainty=sorted(set(uncertainty)|set(wb.value.get("uncertainty",()))); capability_order=offered; semantic_loss_order=tuple(sorted(set(loss))); safe=disposition in {"accepted","migrated"} and wb.value.get("disposition")!="blocked"; effect="exchange:permitted-artifact-digests-only" if safe else "block:unsafe-release"; payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"request_id":request_id,"endpoint_id":endpoint_id,"negotiated_version":negotiated,"disposition":disposition,"input_schema":input_schema,"output_schema":output_schema,"migration_policy":str(protocol.get("migration_policy","additive-only")),"semantic_loss_budget":semantic_loss_budget,"capability_order":list(capability_order),"artifact_digest_order":list(artifacts),"semantic_loss_order":list(semantic_loss_order),"omissions":omissions,"uncertainty":uncertainty,"workbench_digest":wb.value["workbench_digest"],"raw_data_local":True,"aggregate_only":True,"boundary":PRECLINICAL_BOUNDARY}; protocol_digest=_digest(payload); payload["protocol_digest"]=protocol_digest; payload["effect_receipts"]=[effect]; payload["artifact"]={"artifact_id":f"retrieval-interoperability:{request_id}","content_type":CONTENT_TYPE,"content_hash":_digest(payload),"boundary":PRECLINICAL_BOUNDARY}; receipt=RetrievalInteroperabilityReceipt(payload); receipt.validate(feature_id=feature_id,contract_version=contract_version,input_schema=input_schema,output_schema=output_schema); return receipt
__all__=["RetrievalInteroperabilityReceipt","negotiate","manifest"]
