"""Python parity surface for AFA-worldgen-P01-F13."""
from __future__ import annotations
from dataclasses import dataclass
import re
from typing import Any, Mapping, Sequence
from .research_contracts import WORLDGEN_LOCAL_EVIDENCE_SURVEILLANCE_WORKFLOW_FABRIC_CONTRACT_VERSION, WORLDGEN_LOCAL_EVIDENCE_SURVEILLANCE_WORKFLOW_FABRIC_FEATURE_ID, PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError, research_artifact_digest

CANONICAL_STAGES = ("stage:checkpoint", "stage:persist-artifact", "stage:surveil-evidence", "stage:validate-input")

@dataclass(frozen=True)
class LocalEvidenceSurveillanceWorkflowReceipt:
    request_id:str; workflow_id:str; study_id:str; scope:str; disposition:str; stage_order:tuple[str,...]; plan_order:tuple[str,...]; completed_order:tuple[str,...]; blocked_order:tuple[str,...]; compensation_order:tuple[str,...]; candidate_order:tuple[str,...]; qualified_order:tuple[str,...]; unknown_order:tuple[str,...]; evidence_receipt_digest:str; checkpoint_digest:str; workflow_digest:str; replay_identity:str; budget_units:int; omissions:tuple[str,...]; uncertainty:tuple[str,...]; negative_evidence:tuple[str,...]; effect_receipts:tuple[str,...]; artifact:dict[str,Any]; schema_version:str=RESEARCH_CONTRACT_SCHEMA_VERSION; contract_version:str=WORLDGEN_LOCAL_EVIDENCE_SURVEILLANCE_WORKFLOW_FABRIC_CONTRACT_VERSION; feature_id:str=WORLDGEN_LOCAL_EVIDENCE_SURVEILLANCE_WORKFLOW_FABRIC_FEATURE_ID; raw_data_local:bool=True; boundary:str=PRECLINICAL_BOUNDARY
    def validate(self)->None:
        if self.schema_version!=RESEARCH_CONTRACT_SCHEMA_VERSION or self.contract_version!=WORLDGEN_LOCAL_EVIDENCE_SURVEILLANCE_WORKFLOW_FABRIC_CONTRACT_VERSION or self.feature_id!=WORLDGEN_LOCAL_EVIDENCE_SURVEILLANCE_WORKFLOW_FABRIC_FEATURE_ID or self.boundary!=PRECLINICAL_BOUNDARY or not self.raw_data_local or not self.request_id.strip() or not self.workflow_id.strip() or not self.study_id.strip() or not self.scope.strip() or not self.stage_order or not self.plan_order or not self.completed_order or not self.effect_receipts or self.budget_units<=0: raise ResearchContractError("workflow identity, stages, plan, locality, budget, or effects are incomplete")
        if any(item not in self.candidate_order for item in self.qualified_order+self.unknown_order): raise ResearchContractError("workflow evidence state is not covered by candidates")
        for values in (self.stage_order,self.plan_order,self.completed_order,self.blocked_order,self.compensation_order,self.candidate_order,self.qualified_order,self.unknown_order,self.omissions,self.uncertainty,self.negative_evidence,self.effect_receipts):
            if tuple(sorted(set(values)))!=values: raise ResearchContractError("workflow ordering is not canonical")
        for value in (self.evidence_receipt_digest,self.checkpoint_digest,self.workflow_digest,self.replay_identity,self.artifact.get("content_hash")):
            if not isinstance(value,str) or not re.fullmatch(r"[0-9a-f]{64}",value): raise ResearchContractError("workflow digest is invalid")
        if self.artifact.get("content_type")!="application/vnd.aurora.worldgen.research-workflow-receipt+json" or self.artifact.get("boundary")!=PRECLINICAL_BOUNDARY: raise ResearchContractError("workflow artifact metadata is invalid")
        if any(not effect.startswith("schedule:research-work:") and not effect.startswith("compensate:research-work:") and effect!="block:unsafe-release" for effect in self.effect_receipts): raise ResearchContractError("workflow effect is outside schedule/compensation gate")

def schedule_local_evidence_surveillance_workflow(*,request_id:str,study_id:str,intent:str,feed:Sequence[Mapping[str,Any]],workflow_id:str,requested_stage_order:Sequence[str],checkpoint_id:str,budget_units:int,replay_identity:str,policy_allow:bool=True,protected_closure:bool=True,raw_data_local:bool=True,boundary:str=PRECLINICAL_BOUNDARY)->LocalEvidenceSurveillanceWorkflowReceipt:
    if not request_id.strip() or not study_id.strip() or not intent.strip() or not workflow_id.strip() or not checkpoint_id.strip() or budget_units<=0 or not feed or boundary!=PRECLINICAL_BOUNDARY or not raw_data_local or not re.fullmatch(r"[0-9a-f]{64}",replay_identity) or tuple(requested_stage_order)!=CANONICAL_STAGES: raise ResearchContractError("workflow identity, feed, stages, checkpoint, budget, locality, or boundary is invalid")
    ordered=tuple(sorted(feed,key=lambda item:(-int(item.get("relevance_score",0)),str(item.get("source_id",""))))); candidate=tuple(sorted(str(item.get("source_id","")) for item in ordered)); available=tuple(sorted(item["source_id"] for item in ordered if item.get("availability")=="available" and item.get("digest"))); unknown=tuple(item for item in candidate if item not in available); negative=tuple(sorted(f"source:{item['source_id']}:negative-result" for item in ordered if item.get("negative_result"))); omissions=set(); uncertainty=set()
    for item in ordered:
        source=str(item.get("source_id",""));
        if item.get("availability")!="available": omissions.add(f"source:{source}:unavailable")
        if not item.get("digest"): uncertainty.add(f"source:{source}:content-digest-missing")
    plan=set(f"plan:{stage}" for stage in CANONICAL_STAGES); plan.add("plan:publish-qualified-local-artifact" if available else "plan:retain-unresolved-evidence"); compensation=set(); blocked=set(unknown)
    required_budget=len(plan)
    if budget_units<required_budget: omissions.add("workflow:budget-exhausted"); compensation.add("compensate:research-work:budget-exhausted")
    if not policy_allow: omissions.add("workflow:policy-denied")
    if not protected_closure: omissions.add("workflow:protected-closure-incomplete")
    if not raw_data_local: omissions.add("workflow:raw-data-locality-failed")
    blocked_gate=not policy_allow or not protected_closure or not raw_data_local or budget_units<required_budget
    disposition="blocked" if blocked_gate else "unknown" if not available else "unknown" if unknown else "passed"
    stage=tuple(CANONICAL_STAGES); plan_order=tuple(sorted(plan)); completed=tuple(sorted(stage)); blocked_order=tuple(sorted(blocked)); compensation_order=tuple(sorted(compensation)); omissions_order=tuple(sorted(omissions)); uncertainty_order=tuple(sorted(uncertainty)); evidence_digest=research_artifact_digest({"candidate_order":list(candidate),"qualified_order":list(available),"unknown_order":list(unknown)}); checkpoint_digest=research_artifact_digest({"workflow_id":workflow_id,"checkpoint_id":checkpoint_id,"stage_order":list(stage),"replay_identity":replay_identity}); workflow_digest=research_artifact_digest({"workflow_id":workflow_id,"plan_order":list(plan_order),"completed_order":list(completed),"compensation_order":list(compensation_order),"checkpoint_digest":checkpoint_digest,"budget_units":budget_units}); payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":WORLDGEN_LOCAL_EVIDENCE_SURVEILLANCE_WORKFLOW_FABRIC_CONTRACT_VERSION,"feature_id":WORLDGEN_LOCAL_EVIDENCE_SURVEILLANCE_WORKFLOW_FABRIC_FEATURE_ID,"request_id":request_id,"workflow_id":workflow_id,"study_id":study_id,"scope":intent,"disposition":disposition,"stage_order":list(stage),"plan_order":list(plan_order),"completed_order":list(completed),"blocked_order":list(blocked_order),"compensation_order":list(compensation_order),"candidate_order":list(candidate),"qualified_order":list(available),"unknown_order":list(unknown),"evidence_receipt_digest":evidence_digest,"checkpoint_digest":checkpoint_digest,"workflow_digest":workflow_digest,"replay_identity":replay_identity,"budget_units":budget_units,"omissions":list(omissions_order),"uncertainty":list(uncertainty_order),"negative_evidence":list(negative),"boundary":PRECLINICAL_BOUNDARY}; artifact={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"artifact_id":f"worldgen-evidence-workflow:{workflow_id}","content_type":"application/vnd.aurora.worldgen.research-workflow-receipt+json","content_hash":research_artifact_digest(payload),"semantic_loss":[],"provenance":[],"boundary":PRECLINICAL_BOUNDARY}; effect=("block:unsafe-release",) if disposition=="blocked" else (f"compensate:research-work:{workflow_id}",) if compensation_order else (f"schedule:research-work:{workflow_id}",); receipt=LocalEvidenceSurveillanceWorkflowReceipt(request_id=request_id,workflow_id=workflow_id,study_id=study_id,scope=intent,disposition=disposition,stage_order=stage,plan_order=plan_order,completed_order=completed,blocked_order=blocked_order,compensation_order=compensation_order,candidate_order=candidate,qualified_order=available,unknown_order=unknown,evidence_receipt_digest=evidence_digest,checkpoint_digest=checkpoint_digest,workflow_digest=workflow_digest,replay_identity=replay_identity,budget_units=budget_units,omissions=omissions_order,uncertainty=uncertainty_order,negative_evidence=negative,effect_receipts=effect,artifact=artifact,raw_data_local=raw_data_local,boundary=boundary); receipt.validate(); return receipt
