from .worldgen_interpretation_visualization_workflow_support import *
FEATURE_ID="AFA-worldgen-P14-F16"; CONTRACT_VERSION="worldgen-federated_continual-interpretation-visualization-workflow/1.0"
def worldgen_federated_continual_interpretation_visualization_workflow_fabric_manifest():return manifest(feature_id=FEATURE_ID,contract_version=CONTRACT_VERSION,scale="federated continual autonomous")
def schedule_worldgen_federated_continual_interpretation_visualization_workflow(request):return schedule(request,feature_id=FEATURE_ID,contract_version=CONTRACT_VERSION,scale="federated continual autonomous",require_approval=True,federation=True)

