"""Workflow-protocol parity for AFA-worldgen-P01-F16."""
from __future__ import annotations

from dataclasses import dataclass
import re
from typing import Any, Mapping, Sequence

from .worldgen_federated_continual_evidence_surveillance_research_copilot import (
    FederatedCopilotEvidenceContribution,
    run_federated_continual_evidence_surveillance_research_copilot,
)
from .research_contracts import (
    WORLDGEN_FEDERATED_CONTINUAL_EVIDENCE_SURVEILLANCE_WORKFLOW_FABRIC_CONTRACT_VERSION,
    WORLDGEN_FEDERATED_CONTINUAL_EVIDENCE_SURVEILLANCE_WORKFLOW_FABRIC_FEATURE_ID,
    PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION, ResearchContractError,
    research_artifact_digest,
)

CANONICAL_STAGES = ("stage:checkpoint", "stage:admit-federation", "stage:surveil-evidence", "stage:seal-envelope")

@dataclass(frozen=True)
class FederatedContinualEvidenceSurveillanceWorkflowReceipt:
    request_id: str; workflow_id: str; agent_id: str; federation_id: str; purpose: str; endpoint: str; disposition: str
    stage_order: tuple[str, ...]; plan_order: tuple[str, ...]; completed_order: tuple[str, ...]; blocked_order: tuple[str, ...]; compensation_order: tuple[str, ...]
    peer_order: tuple[str, ...]; candidate_order: tuple[str, ...]; selected_order: tuple[str, ...]; unresolved_order: tuple[str, ...]; denied_order: tuple[str, ...]; aggregate_order: tuple[str, ...]
    replay_identity: str; copilot_run_digest: str; checkpoint_digest: str; federation_envelope_digest: str; workflow_digest: str
    omissions: tuple[str, ...]; uncertainty: tuple[str, ...]; negative_evidence: tuple[str, ...]; effect_receipts: tuple[str, ...]; artifact: dict[str, Any]
    schema_version: str = RESEARCH_CONTRACT_SCHEMA_VERSION; contract_version: str = WORLDGEN_FEDERATED_CONTINUAL_EVIDENCE_SURVEILLANCE_WORKFLOW_FABRIC_CONTRACT_VERSION; feature_id: str = WORLDGEN_FEDERATED_CONTINUAL_EVIDENCE_SURVEILLANCE_WORKFLOW_FABRIC_FEATURE_ID; raw_data_local: bool = True; boundary: str = PRECLINICAL_BOUNDARY

    def validate(self) -> None:
        if self.schema_version != RESEARCH_CONTRACT_SCHEMA_VERSION or self.contract_version != WORLDGEN_FEDERATED_CONTINUAL_EVIDENCE_SURVEILLANCE_WORKFLOW_FABRIC_CONTRACT_VERSION or self.feature_id != WORLDGEN_FEDERATED_CONTINUAL_EVIDENCE_SURVEILLANCE_WORKFLOW_FABRIC_FEATURE_ID or self.boundary != PRECLINICAL_BOUNDARY or not self.raw_data_local or not self.request_id.strip() or not self.workflow_id.strip() or not self.agent_id.strip() or not self.federation_id.strip() or not self.purpose.strip() or not self.endpoint.strip() or self.stage_order != CANONICAL_STAGES or not self.plan_order or not self.completed_order or not self.effect_receipts:
            raise ResearchContractError("federated workflow identity, stages, locality, or effects are incomplete")
        for values in (self.plan_order, self.completed_order, self.blocked_order, self.compensation_order, self.peer_order, self.candidate_order, self.selected_order, self.unresolved_order, self.denied_order, self.aggregate_order, self.omissions, self.uncertainty, self.negative_evidence, self.effect_receipts):
            if tuple(sorted(set(values))) != values: raise ResearchContractError("federated workflow ordering is not canonical")
        for value in (self.replay_identity, self.copilot_run_digest, self.checkpoint_digest, self.federation_envelope_digest, self.workflow_digest, self.artifact.get("content_hash")):
            if not isinstance(value, str) or not re.fullmatch(r"[0-9a-f]{64}", value): raise ResearchContractError("federated workflow digest is invalid")
        if any(not effect.startswith("schedule:research-work:") and not effect.startswith("compensate:research-work:") and effect != "block:unsafe-release" for effect in self.effect_receipts): raise ResearchContractError("federated workflow effect is outside schedule gate")

def schedule_federated_continual_evidence_surveillance_workflow(*, request_id: str, workflow_id: str, checkpoint_id: str, request: Mapping[str, Any], requested_stage_order: Sequence[str], budget_units: int, replay_identity: str, boundary: str = PRECLINICAL_BOUNDARY) -> FederatedContinualEvidenceSurveillanceWorkflowReceipt:
    if not request_id.strip() or not workflow_id.strip() or not checkpoint_id.strip() or budget_units <= 0 or tuple(requested_stage_order) != CANONICAL_STAGES or boundary != PRECLINICAL_BOUNDARY or not re.fullmatch(r"[0-9a-f]{64}", replay_identity): raise ResearchContractError("federated workflow identity, stages, budget, replay, or boundary is invalid")
    contributions = tuple(item if isinstance(item, FederatedCopilotEvidenceContribution) else FederatedCopilotEvidenceContribution(**item) for item in request.get("contributions", ()))
    copilot = run_federated_continual_evidence_surveillance_research_copilot(request_id=str(request.get("request_id", request_id)), agent_id=str(request["agent_id"]), federation_id=str(request["federation_id"]), purpose=str(request["purpose"]), endpoint=str(request["endpoint"]), semantic_profile=str(request["semantic_profile"]), allowed_artifacts=tuple(request["allowed_artifacts"]), min_peer_quorum=int(request["min_peer_quorum"]), declared_tools=tuple(request["declared_tools"]), requested_tool=str(request["requested_tool"]), max_tool_calls=int(request["max_tool_calls"]), dry_run=bool(request["dry_run"]), approval_reference=request.get("approval_reference"), approval_granted=bool(request["approval_granted"]), contributions=contributions, policy_allow=bool(request.get("policy_allow", True)), protected_closure=bool(request.get("protected_closure", True)), raw_data_local=bool(request.get("raw_data_local", True)), replay_identity=str(request["replay_identity"]))
    plan = set(f"plan:{stage}" for stage in CANONICAL_STAGES); completed = set(CANONICAL_STAGES); compensation: set[str] = set(); plan.add("plan:seal-permitted-aggregate-envelope" if copilot.aggregate_order else "plan:retain-unresolved-federated-evidence")
    if budget_units < len(plan): compensation.add("compensate:research-work:budget-exhausted")
    omissions = set(copilot.omissions); omissions.update({"workflow:policy-denied"} if not request.get("policy_allow", True) else set()); omissions.update({"workflow:protected-closure-incomplete"} if not request.get("protected_closure", True) else set()); omissions.update({"workflow:approval-required"} if not request.get("approval_granted", False) and not request.get("dry_run", False) else set())
    plan_order, completed_order, compensation_order, omissions_order = tuple(sorted(plan)), tuple(sorted(completed)), tuple(sorted(compensation)), tuple(sorted(omissions))
    checkpoint_digest = research_artifact_digest({"workflow_id": workflow_id, "checkpoint_id": checkpoint_id, "stage_order": list(CANONICAL_STAGES), "replay_identity": replay_identity}); copilot_run_digest = research_artifact_digest(copilot.__dict__); federation_envelope_digest = research_artifact_digest({"federation_id": request["federation_id"], "purpose": request["purpose"], "endpoint": request["endpoint"], "peer_order": list(copilot.peer_order), "aggregate_order": list(copilot.aggregate_order), "allowed_artifacts": list(request["allowed_artifacts"]), "raw_data_local": bool(request.get("raw_data_local", True))}); workflow_digest = research_artifact_digest({"workflow_id": workflow_id, "plan_order": list(plan_order), "completed_order": list(completed_order), "compensation_order": list(compensation_order), "checkpoint_digest": checkpoint_digest, "federation_envelope_digest": federation_envelope_digest, "copilot_run_digest": copilot_run_digest, "budget_units": budget_units})
    disposition = copilot.disposition; blocked_order = ("stage:release",) if disposition == "blocked" else (); payload = {"schema_version": RESEARCH_CONTRACT_SCHEMA_VERSION, "contract_version": WORLDGEN_FEDERATED_CONTINUAL_EVIDENCE_SURVEILLANCE_WORKFLOW_FABRIC_CONTRACT_VERSION, "feature_id": WORLDGEN_FEDERATED_CONTINUAL_EVIDENCE_SURVEILLANCE_WORKFLOW_FABRIC_FEATURE_ID, "workflow_id": workflow_id, "federation_id": request["federation_id"], "purpose": request["purpose"], "endpoint": request["endpoint"], "stage_order": list(CANONICAL_STAGES), "plan_order": list(plan_order), "completed_order": list(completed_order), "compensation_order": list(compensation_order), "peer_order": list(copilot.peer_order), "candidate_order": list(copilot.candidate_order), "selected_order": list(copilot.selected_order), "unresolved_order": list(copilot.unresolved_order), "denied_order": list(copilot.denied_order), "aggregate_order": list(copilot.aggregate_order), "replay_identity": replay_identity, "copilot_run_digest": copilot_run_digest, "checkpoint_digest": checkpoint_digest, "federation_envelope_digest": federation_envelope_digest, "workflow_digest": workflow_digest, "omissions": list(omissions_order), "uncertainty": list(copilot.uncertainty), "negative_evidence": list(copilot.negative_evidence), "boundary": PRECLINICAL_BOUNDARY, "raw_data_local": True, "federation_export": "aggregate-only"}; artifact = {"schema_version": RESEARCH_CONTRACT_SCHEMA_VERSION, "artifact_id": f"worldgen-federated-continual-evidence-workflow:{workflow_id}", "content_type": "application/vnd.aurora.worldgen.federated-continual-research-workflow+json", "content_hash": research_artifact_digest(payload), "semantic_loss": [], "provenance": [], "boundary": PRECLINICAL_BOUNDARY}
    effect = ("block:unsafe-release",) if disposition == "blocked" else (f"compensate:research-work:{workflow_id}",) if compensation_order else (f"schedule:research-work:{workflow_id}",)
    receipt = FederatedContinualEvidenceSurveillanceWorkflowReceipt(request_id, workflow_id, str(request["agent_id"]), str(request["federation_id"]), str(request["purpose"]), str(request["endpoint"]), disposition, CANONICAL_STAGES, plan_order, completed_order, blocked_order, compensation_order, tuple(sorted(copilot.peer_order)), tuple(sorted(copilot.candidate_order)), tuple(sorted(copilot.selected_order)), tuple(sorted(copilot.unresolved_order)), tuple(sorted(copilot.denied_order)), tuple(sorted(copilot.aggregate_order)), replay_identity, copilot_run_digest, checkpoint_digest, federation_envelope_digest, workflow_digest, omissions_order, tuple(sorted(copilot.uncertainty)), tuple(sorted(copilot.negative_evidence)), effect, artifact); receipt.validate(); return receipt
