"""Python parity for P16 approval-bounded release copilot."""
from __future__ import annotations
import hashlib,json,re
from typing import Any,Mapping
from .research_contracts import PRECLINICAL_BOUNDARY,RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
from .worldgen_publication_research_object_support import qualify
CONTENT_TYPE="application/vnd.aurora.worldgen.publication-research-object-copilot-receipt+json"
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return v==sorted(set(v))
def manifest(*,feature_id:str,contract_version:str,scale:str)->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"worldgen","consumers":["imaging core scientist","release operator","research program lead"],"behavior":f"run approval-bounded release actions for {scale}","value":"turns qualified statistical evidence into a replayable copilot decision without hidden effects","input_schema":"ReleaseCopilotRequest1@1","output_schema":"ReleaseCopilotReceipt1@1","effects":["invoke:bounded-release-tool","block:unsafe-release"],"permissions":["invoke:declared-release-tool"],"determinism":"byte_stable","autonomy_tier":"A1","boundary":PRECLINICAL_BOUNDARY}
def run(request:Mapping[str,Any],*,feature_id:str,contract_version:str,scale:str,require_approval:bool=False,federation:bool=False)->dict[str,Any]:
    if request.get("boundary")!=PRECLINICAL_BOUNDARY or not request.get("action_order") or not _ordered(request["action_order"]) or int(request.get("action_budget",0))<=0 or request.get("release_request",{}).get("raw_data_local") is not True:return _raise("release copilot request is invalid")
    release=qualify(request["release_request"],feature_id=feature_id,contract_version=contract_version).to_dict();omissions=sorted(set(release.get("omissions",[])+([] if (not require_approval or request.get("signed_approval")) else ["copilot:approval-missing"])+([] if not request.get("dry_run") else ["copilot:dry-run-no-effect"])+([] if len(request["action_order"])<=int(request["action_budget"]) else ["copilot:action-budget-exceeded"])));safe=release["disposition"]=="qualified" and (not require_approval or request.get("signed_approval") is True) and len(request["action_order"])<=int(request["action_budget"]);disp="qualified" if safe else "blocked" if release["disposition"]=="blocked" or (require_approval and not request.get("signed_approval")) else "partial";admitted=request["action_order"][:] if safe else [];denied=[] if safe else request["action_order"][:];effects=[f"invoke:bounded-release-tool:{release['release_digest']}"] if disp!="blocked" else ["block:unsafe-release"];payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"request_id":request["release_request"]["request_id"],"disposition":disp,"action_order":request["action_order"],"admitted_action_order":admitted,"denied_action_order":denied,"release_disposition":release["disposition"],"release_digest":release["release_digest"],"replay_identity":release["replay_identity"],"omissions":omissions,"uncertainty":release["uncertainty"],"negative_evidence":release["negative_evidence"],"effect_receipts":effects,"raw_data_local":True,"aggregate_only":True,"boundary":PRECLINICAL_BOUNDARY};d=_hash(payload);payload["copilot_digest"]=d;payload["artifact"]={"content_type":CONTENT_TYPE,"content_hash":d,"boundary":PRECLINICAL_BOUNDARY};return payload
def _raise(message:str):raise ResearchContractError(message)
