"""Python parity for P19 approval-bounded policy_autonomy copilot."""
from __future__ import annotations
import hashlib,json,re
from typing import Any,Mapping
from .research_contracts import PRECLINICAL_BOUNDARY,RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
from .worldgen_policy_autonomy_support import qualify
CONTENT_TYPE="application/vnd.aurora.worldgen.policy_autonomy-signing-copilot-receipt+json"
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return v==sorted(set(v))
def manifest(*,feature_id:str,contract_version:str,scale:str)->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"worldgen","consumers":["imaging core scientist","policy_autonomy operator","research program lead"],"behavior":f"run approval-bounded policy_autonomy actions for {scale}","value":"turns qualified statistical evidence into a replayable copilot decision without hidden effects","input_schema":"PolicyAutonomyCopilotRequest1@1","output_schema":"PolicyAutonomyCopilotReceipt1@1","effects":["invoke:bounded-policy_autonomy-tool","block:unsafe-policy_autonomy"],"permissions":["invoke:declared-policy_autonomy-tool"],"determinism":"byte_stable","autonomy_tier":"A1","boundary":PRECLINICAL_BOUNDARY}
def run(request:Mapping[str,Any],*,feature_id:str,contract_version:str,scale:str,require_approval:bool=False,federation:bool=False)->dict[str,Any]:
    if request.get("boundary")!=PRECLINICAL_BOUNDARY or not request.get("action_order") or not _ordered(request["action_order"]) or int(request.get("action_budget",0))<=0 or request.get("policy_autonomy_request",{}).get("raw_data_local") is not True:return _raise("policy_autonomy copilot request is invalid")
    policy_autonomy=qualify(request["policy_autonomy_request"],feature_id=feature_id,contract_version=contract_version).to_dict();omissions=sorted(set(policy_autonomy.get("omissions",[])+([] if (not require_approval or request.get("signed_approval")) else ["copilot:approval-missing"])+([] if not request.get("dry_run") else ["copilot:dry-run-no-effect"])+([] if len(request["action_order"])<=int(request["action_budget"]) else ["copilot:action-budget-exceeded"])));safe=policy_autonomy["disposition"]=="qualified" and (not require_approval or request.get("signed_approval") is True) and len(request["action_order"])<=int(request["action_budget"]);disp="qualified" if safe else "blocked" if policy_autonomy["disposition"]=="blocked" or (require_approval and not request.get("signed_approval")) else "partial";admitted=request["action_order"][:] if safe else [];denied=[] if safe else request["action_order"][:];effects=[f"invoke:bounded-policy_autonomy-tool:{policy_autonomy['receipt_digest']}"] if disp!="blocked" else ["block:unsafe-policy_autonomy"];payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"request_id":request["policy_autonomy_request"]["request_id"],"disposition":disp,"action_order":request["action_order"],"admitted_action_order":admitted,"denied_action_order":denied,"policy_disposition":policy_autonomy["disposition"],"policy_digest":policy_autonomy["receipt_digest"],"replay_identity":policy_autonomy["replay_identity"],"omissions":omissions,"uncertainty":policy_autonomy["uncertainty"],"negative_evidence":policy_autonomy["negative_evidence"],"effect_receipts":effects,"raw_data_local":True,"aggregate_only":True,"boundary":PRECLINICAL_BOUNDARY};d=_hash(payload);payload["copilot_digest"]=d;payload["artifact"]={"content_type":CONTENT_TYPE,"content_hash":d,"boundary":PRECLINICAL_BOUNDARY};return payload
def _raise(message:str):raise ResearchContractError(message)
