"""Python parity for P19 typed policy_autonomy-contract negotiation."""
from __future__ import annotations
import hashlib,json,re
from typing import Any,Mapping
from .research_contracts import PRECLINICAL_BOUNDARY,RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
CONTENT_TYPE="application/vnd.aurora.worldgen.policy_autonomy-signing-contract-receipt+json"
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return v==sorted(set(v))
def manifest(*,feature_id:str,contract_version:str,scale:str)->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"worldgen","consumers":["imaging core scientist","research program lead","developer"],"behavior":f"negotiate typed statistical-causal-ML policy_autonomy contract for {scale}","value":"makes policy_autonomy schema compatibility, semantic loss, locality, and permissions explicit","input_schema":"PolicyAutonomyContractRequest1@1","output_schema":"PolicyAutonomyContractReceipt1@1","effects":["none:policy_autonomy-contract-validation","block:unsafe-policy_autonomy"],"permissions":["negotiate:policy_autonomy-contract"],"determinism":"byte_stable","autonomy_tier":"A1","boundary":PRECLINICAL_BOUNDARY}
def negotiate(request:Mapping[str,Any],*,feature_id:str,contract_version:str,scale:str,federation:bool=False)->dict[str,Any]:
    if not request.get("request_id") or not request.get("field_order") or request.get("boundary")!=PRECLINICAL_BOUNDARY or request.get("raw_data_local") is not True or request.get("aggregate_only") is not True or not _digest(request.get("replay_identity")):raise ResearchContractError("policy_autonomy contract request is invalid")
    fields=sorted(set(request["field_order"]));retained=sorted(set(x for x in request.get("retained_field_order",[]) if x in fields));missing=sorted(set(fields)-set(retained));omitted=sorted(set(x for x in request.get("missing_field_order",[]) if x in fields));disp="blocked" if not request.get("policy_allow") or not request.get("protected_closure") else "compatible" if not missing and not omitted else "unknown" if not retained else "partial";payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"request_id":request["request_id"],"consumer":request.get("consumer",""),"producer":request.get("producer",""),"namespace":request.get("namespace",""),"semantic_profile":request.get("semantic_profile",""),"negotiated_version":request.get("negotiated_version",""),"compatibility":"compatible" if disp=="compatible" else "additive_migration","disposition":disp,"field_order":fields,"retained_field_order":retained,"missing_field_order":missing,"omitted_field_order":omitted,"semantic_loss_order":[],"replay_identity":request["replay_identity"],"effect_receipts":["none:policy_autonomy-contract-validation"],"raw_data_local":True,"aggregate_only":True,"boundary":PRECLINICAL_BOUNDARY};d=_hash(payload);payload["contract_digest"]=d;payload["artifact"]={"content_type":CONTENT_TYPE,"content_hash":d,"boundary":PRECLINICAL_BOUNDARY};return payload
