"""Python parity for P16 resumable release workflows."""
from __future__ import annotations
import hashlib,json,re
from typing import Any,Mapping
from .research_contracts import PRECLINICAL_BOUNDARY,RESEARCH_CONTRACT_SCHEMA_VERSION,ResearchContractError
from .worldgen_publication_research_object_copilot_support import run as run_copilot
CONTENT_TYPE="application/vnd.aurora.worldgen.publication-research-object-workflow-receipt+json"
def _hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def _digest(v:Any)->bool:return isinstance(v,str) and re.fullmatch(r"[0-9a-f]{64}",v) is not None
def _ordered(v:list[str])->bool:return v==sorted(set(v))
def manifest(*,feature_id:str,contract_version:str,scale:str)->dict[str,Any]:return {"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"capability_id":feature_id,"version":contract_version,"owner_crate":"worldgen","consumers":["imaging core scientist","release operator","research program lead"],"behavior":f"orchestrate resumable statistical-causal-ML release for {scale}","value":"makes release qualification restartable, budgeted, compensating, and replayable without hidden effects","input_schema":"ReleaseWorkflowRequest1@1","output_schema":"ReleaseWorkflowReceipt1@1","effects":["schedule:worldgen-release-workflow","block:unsafe-release"],"permissions":["schedule:bounded-release-workflow"],"determinism":"byte_stable","autonomy_tier":"A1","boundary":PRECLINICAL_BOUNDARY}
def schedule(request:Mapping[str,Any],*,feature_id:str,contract_version:str,scale:str,require_approval:bool=False,federation:bool=False)->dict[str,Any]:
    if not request.get("workflow_id") or not request.get("stage_order") or not _ordered(request["stage_order"]) or not _digest(request.get("replay_identity")) or int(request.get("checkpoint_seq",0))<=0 or int(request.get("budget_units",0))<=0 or request.get("compensation_enabled") is not True or request.get("copilot",{}).get("release_request",{}).get("replay_identity")!=request.get("replay_identity"):raise ResearchContractError("release workflow request is invalid")
    stages=set(request["stage_order"]);completed=sorted(set(request.get("completed_stage_order",[])));pending=[x for x in request["stage_order"] if x not in completed];copilot=run_copilot(request["copilot"],feature_id=feature_id,contract_version=contract_version,scale=scale,require_approval=require_approval,federation=federation);compensation=[f"workflow:{request['workflow_id']}:retain-partial-release-verdict"] if copilot["disposition"]=="blocked" else [];disp="blocked" if copilot["disposition"]=="blocked" or compensation else "qualified" if not pending else "partial";effects=[f"schedule:worldgen-release-workflow:{request['workflow_id']}"] if disp=="qualified" else ["block:unsafe-release"];payload={"schema_version":RESEARCH_CONTRACT_SCHEMA_VERSION,"contract_version":contract_version,"feature_id":feature_id,"workflow_id":request["workflow_id"],"disposition":disp,"stage_order":request["stage_order"],"completed_stage_order":completed,"pending_stage_order":pending,"compensation_order":compensation,"checkpoint_seq":int(request["checkpoint_seq"]),"budget_units":int(request["budget_units"]),"consumed_units":min(len(request["copilot"].get("action_order",[])),int(request["budget_units"])),"replay_identity":request["replay_identity"],"copilot":copilot,"effect_receipts":effects,"raw_data_local":True,"aggregate_only":True,"boundary":PRECLINICAL_BOUNDARY};d=_hash(payload);payload["workflow_digest"]=d;payload["artifact"]={"content_type":CONTENT_TYPE,"content_hash":d,"boundary":PRECLINICAL_BOUNDARY};return payload
