//! Printing an AST back to WeaveLang source.
//!
//! Blueprint 23.02 expects WeaveLang to be "readable in a repository, generated by an LLM when
//! convenient". Both halves want a canonical form: a repository wants one layout rather than an
//! argument about it, and a generator wants its output normalised before anyone reviews a diff.
//!
//! The property this module exists for is the round trip. `parse(print(parse(s)))` and `parse(s)`
//! must be the same tree modulo source positions, and that is tested rather than asserted. It is
//! also the cheapest continuous check that the parser is not quietly discarding a construct: a
//! clause the parser drops cannot be printed, so the second parse produces a different tree and the
//! test fails.
//!
//! Not preserved: comments and blank lines. 23.03 phase 1 asks the compiler to "preserve comments
//! relevant to documentation" and this printer does not — the AST has nowhere to put them. That is
//! a real gap rather than a style choice, and printing a file therefore loses its commentary.

use crate::ast::*;

/// Renders a program as canonical WeaveLang source.
pub fn print(program: &Program) -> String {
    let mut out = String::new();

    if let Some(package) = &program.package {
        out.push_str(&format!("package {}\n", package.name.text()));
    }
    for import in &program.imports {
        out.push_str(&format!("import {}", import.name.text()));
        if let Some(alias) = &import.alias {
            out.push_str(&format!(" as {alias}"));
        }
        out.push('\n');
    }
    if program.package.is_some() || !program.imports.is_empty() {
        out.push('\n');
    }

    for item in &program.items {
        print_item(item, &mut out);
        out.push('\n');
    }
    out
}

fn print_item(item: &Item, out: &mut String) {
    match item {
        Item::Type(decl) => print_type(decl, out),
        Item::Interface(decl) => print_interface(decl, out),
        Item::Role(decl) => print_role(decl, out),
        Item::Policy(decl) => print_policy(decl, out),
        Item::Choreography(decl) => print_choreography(decl, out),
        Item::Weave(decl) => print_weave(decl, out),
    }
}

fn print_type(decl: &TypeDecl, out: &mut String) {
    match &decl.body {
        TypeBody::Record(fields) => {
            out.push_str(&format!("type {} = record {{\n", decl.name));
            let rendered: Vec<String> = fields
                .iter()
                .map(|field| format!("  {}: {}", field.name, field.ty.text()))
                .collect();
            out.push_str(&rendered.join(",\n"));
            out.push_str("\n}\n");
        }
        TypeBody::Variant(cases) => {
            out.push_str(&format!("type {} = variant {{\n", decl.name));
            let rendered: Vec<String> = cases
                .iter()
                .map(|case| match &case.payload {
                    Some(payload) => format!("  {}({})", case.name, payload.text()),
                    None => format!("  {}", case.name),
                })
                .collect();
            out.push_str(&rendered.join(",\n"));
            out.push_str("\n}\n");
        }
        TypeBody::Alias(target) => {
            out.push_str(&format!("type {} = {}\n", decl.name, target.text()));
        }
    }
}

fn print_interface(decl: &InterfaceDecl, out: &mut String) {
    out.push_str(&format!("interface {} {{\n", decl.name));
    for method in &decl.methods {
        let params: Vec<String> = method
            .params
            .iter()
            .map(|param| format!("{}: {}", param.name, param.ty.text()))
            .collect();
        out.push_str(&format!("  {}({})", method.name, params.join(", ")));
        if let Some(returns) = &method.returns {
            out.push_str(&format!(" -> {}", returns.text()));
        }
        out.push('\n');
        if !method.effects.is_empty() {
            out.push_str(&format!("    effects [{}]\n", join_paths(&method.effects)));
        }
        if !method.throws.is_empty() {
            out.push_str(&format!("    throws [{}]\n", method.throws.join(", ")));
        }
    }
    out.push_str("}\n");
}

fn print_role(decl: &RoleDecl, out: &mut String) {
    out.push_str(&format!("role {} {{\n", decl.name));
    if !decl.provides.is_empty() {
        let provides: Vec<String> = decl.provides.iter().map(VersionedName::text).collect();
        out.push_str(&format!("  provides [{}]\n", provides.join(", ")));
    }
    if !decl.requires.is_empty() {
        out.push_str(&format!("  requires [{}]\n", join_paths(&decl.requires)));
    }
    if let Some(clearance) = &decl.clearance {
        out.push_str(&format!("  clearance {}", clearance.level));
        for compartment in &clearance.compartments {
            out.push_str(&format!("/{compartment}"));
        }
        out.push('\n');
    }
    if let Some(profile) = &decl.minimum_profile {
        out.push_str(&format!(
            "  minimum-profile {} >= {}\n",
            profile.reference,
            bioprism_ids::python_repr_f64(profile.threshold)
        ));
    }
    out.push_str("}\n");
}

fn print_policy(decl: &PolicyDecl, out: &mut String) {
    out.push_str(&format!("policy {} {{\n", decl.name));
    if !decl.allow_effects.is_empty() {
        out.push_str(&format!(
            "  allow effects [{}]\n",
            join_paths(&decl.allow_effects)
        ));
    }
    if !decl.deny_effects.is_empty() {
        out.push_str(&format!(
            "  deny effects [{}]\n",
            join_paths(&decl.deny_effects)
        ));
    }
    if !decl.require_human_for.is_empty() {
        out.push_str(&format!(
            "  require human for [{}]\n",
            join_paths(&decl.require_human_for)
        ));
    }
    for budget in &decl.budgets {
        out.push_str(&format!(
            "  budget {} <= {}\n",
            budget.resource,
            print_literal(&budget.limit)
        ));
    }
    if let Some(max) = decl.max_participants {
        out.push_str(&format!("  max-participants {max}\n"));
    }
    out.push_str("}\n");
}

fn print_choreography(decl: &ChoreographyDecl, out: &mut String) {
    out.push_str(&format!("choreography {} {{\n", decl.name));
    print_choreo_steps(&decl.steps, 1, out);
    out.push_str("}\n");
}

fn print_choreo_steps(steps: &[ChoreoStep], depth: usize, out: &mut String) {
    let pad = "  ".repeat(depth);
    for step in steps {
        match step {
            ChoreoStep::Message {
                from,
                to,
                act,
                payload,
                ..
            } => {
                out.push_str(&format!("{pad}{from} -> {to}: {act}"));
                if let Some(payload) = payload {
                    out.push_str(&format!("<{}>", payload.text()));
                }
                out.push('\n');
            }
            ChoreoStep::Choice { by, branches, .. } => {
                out.push_str(&format!("{pad}choice by {by} {{\n"));
                for branch in branches {
                    out.push_str(&format!("{pad}  {}:\n", branch.label));
                    print_choreo_steps(&branch.steps, depth + 2, out);
                }
                out.push_str(&format!("{pad}}}\n"));
            }
        }
    }
}

fn print_weave(decl: &WeaveDecl, out: &mut String) {
    let params: Vec<String> = decl
        .params
        .iter()
        .map(|param| format!("{}: {}", param.name, param.ty.text()))
        .collect();
    out.push_str(&format!("weave {}({})", decl.name, params.join(", ")));
    if let Some(returns) = &decl.returns {
        out.push_str(&format!(" -> {}", returns.text()));
    }
    if let Some(policy) = &decl.using_policy {
        out.push_str(&format!(" using {policy}"));
    }
    out.push_str(" {\n");
    print_block(&decl.body, 1, out);
    out.push_str("}\n");
}

fn print_block(body: &[Stmt], depth: usize, out: &mut String) {
    for statement in body {
        print_stmt(statement, depth, out);
    }
}

fn print_stmt(statement: &Stmt, depth: usize, out: &mut String) {
    let pad = "  ".repeat(depth);
    match statement {
        Stmt::Bind { name, role, .. } => {
            out.push_str(&format!("{pad}bind {name} to role {role}\n"));
        }
        Stmt::Let {
            attributes,
            name,
            value,
            ..
        } => {
            for attribute in attributes {
                let arguments: Vec<String> = attribute
                    .arguments
                    .iter()
                    .map(|(key, value)| format!("{key}={}", print_literal(value)))
                    .collect();
                if arguments.is_empty() {
                    out.push_str(&format!("{pad}@{}\n", attribute.name));
                } else {
                    out.push_str(&format!(
                        "{pad}@{}({})\n",
                        attribute.name,
                        arguments.join(", ")
                    ));
                }
            }
            out.push_str(&format!("{pad}let {name} = {}\n", print_expr(value)));
        }
        Stmt::Send {
            act,
            arguments,
            from,
            to,
            ..
        } => {
            let rendered: Vec<String> = arguments.iter().map(print_expr).collect();
            out.push_str(&format!(
                "{pad}send {act}({}) from {from} to {to}\n",
                rendered.join(", ")
            ));
        }
        Stmt::Match {
            scrutinee, arms, ..
        } => {
            out.push_str(&format!("{pad}match {} {{\n", print_expr(scrutinee)));
            for arm in arms {
                match &arm.pattern.binding {
                    Some(binding) => {
                        out.push_str(&format!("{pad}  {}({binding}) =>\n", arm.pattern.case))
                    }
                    None => out.push_str(&format!("{pad}  {} =>\n", arm.pattern.case)),
                }
                print_block(&arm.body, depth + 2, out);
            }
            out.push_str(&format!("{pad}}}\n"));
        }
        Stmt::Par { body, .. } => {
            out.push_str(&format!("{pad}par {{\n"));
            print_block(body, depth + 1, out);
            out.push_str(&format!("{pad}}}\n"));
        }
        Stmt::Race {
            policy, branches, ..
        } => {
            if policy.is_empty() {
                out.push_str(&format!("{pad}race {{\n"));
            } else {
                out.push_str(&format!("{pad}race {policy} {{\n"));
            }
            print_branches(branches, depth + 1, out);
            out.push_str(&format!("{pad}}}\n"));
        }
        Stmt::Checkpoint { name, source, .. } => {
            out.push_str(&format!("{pad}checkpoint {name} = {source}\n"));
        }
        Stmt::Fork { from, branches, .. } => {
            out.push_str(&format!("{pad}fork from {from} {{\n"));
            print_branches(branches, depth + 1, out);
            out.push_str(&format!("{pad}}}\n"));
        }
        Stmt::Join { using, .. } => out.push_str(&format!("{pad}join using {using}\n")),
        Stmt::Commit(commit) => {
            out.push_str(&format!(
                "{pad}commit {} to {} when {} {{\n",
                commit.debtor,
                commit.creditor,
                commit.trigger.text()
            ));
            out.push_str(&format!("{pad}  deliver {}\n", commit.deliver.text()));
            if let Some(before) = &commit.before {
                out.push_str(&format!("{pad}  before {}\n", print_literal(before)));
            }
            for predicate in &commit.satisfy {
                out.push_str(&format!("{pad}  satisfy with {}\n", predicate.text()));
            }
            if let Some(compensation) = &commit.compensate {
                out.push_str(&format!(
                    "{pad}  compensate {} on {}\n",
                    compensation.action, compensation.on
                ));
            }
            out.push_str(&format!("{pad}}}\n"));
        }
        Stmt::Watch {
            subject,
            condition,
            actions,
            ..
        } => {
            out.push_str(&format!(
                "{pad}watch {subject} where {} {{\n",
                condition.text()
            ));
            for action in actions {
                match action {
                    WatchAction::PauseEffects { effects, .. } => {
                        out.push_str(&format!("{pad}  pause effects [{}]\n", join_paths(effects)))
                    }
                    WatchAction::SpawnRole { role, .. } => {
                        out.push_str(&format!("{pad}  spawn role {role}\n"))
                    }
                }
            }
            out.push_str(&format!("{pad}}}\n"));
        }
        Stmt::Context(context) => {
            out.push_str(&format!("{pad}context for {} {{\n", context.recipient));
            for include in &context.includes {
                out.push_str(&format!("{pad}  include {}", include.subject));
                for selector in &include.selectors {
                    out.push_str(&format!(" {selector}"));
                }
                if let Some(limit) = include.limit {
                    out.push_str(&format!(" top {limit}"));
                }
                out.push('\n');
            }
            if let Some(resolution) = &context.resolution {
                out.push_str(&format!("{pad}  resolution {resolution}\n"));
            }
            if let Some(max) = context.max_tokens {
                out.push_str(&format!("{pad}  max-tokens {max}\n"));
            }
            out.push_str(&format!("{pad}}}\n"));
        }
        Stmt::Stop {
            outcome, condition, ..
        } => out.push_str(&format!(
            "{pad}stop {outcome} when {}\n",
            print_expr(condition)
        )),
        Stmt::Return { value, .. } => out.push_str(&format!("{pad}return {}\n", print_expr(value))),
        Stmt::Execute { value, .. } => {
            out.push_str(&format!("{pad}execute {}\n", print_expr(value)))
        }
        Stmt::Resolve { value, .. } => {
            out.push_str(&format!("{pad}resolve {}\n", print_expr(value)))
        }
        Stmt::Delegate { value, .. } => {
            out.push_str(&format!("{pad}delegate {}\n", print_expr(value)))
        }
        Stmt::Publish { value, into, .. } => {
            out.push_str(&format!("{pad}publish {} into {into}\n", print_expr(value)))
        }
        Stmt::Repeat { until, body, .. } => {
            out.push_str(&format!("{pad}repeat until {} {{\n", print_expr(until)));
            print_block(body, depth + 1, out);
            out.push_str(&format!("{pad}}}\n"));
        }
        Stmt::Spawn { role, .. } => out.push_str(&format!("{pad}spawn role {role}\n")),
    }
}

fn print_branches(branches: &[Branch], depth: usize, out: &mut String) {
    let pad = "  ".repeat(depth);
    for branch in branches {
        out.push_str(&format!("{pad}branch {}", branch.name));
        if !branch.budget.is_empty() {
            let grants: Vec<String> = branch
                .budget
                .iter()
                .map(|grant| format!("{}({})", grant.resource, grant.amount))
                .collect();
            out.push_str(&format!(" with budget {}", grants.join(", ")));
        }
        out.push_str(" {\n");
        print_block(&branch.body, depth + 1, out);
        out.push_str(&format!("{pad}}}\n"));
    }
}

fn print_expr(expr: &Expr) -> String {
    match expr {
        Expr::Path(path) => path.text(),
        Expr::Call {
            callee, arguments, ..
        } => {
            let rendered: Vec<String> = arguments
                .iter()
                .map(|argument| match &argument.name {
                    Some(name) => format!("{name}: {}", print_expr(&argument.value)),
                    None => print_expr(&argument.value),
                })
                .collect();
            format!("{}({})", callee.text(), rendered.join(", "))
        }
        Expr::Ask { call, .. } => format!("ask {}", print_expr(call)),
        Expr::Await { target, .. } => format!("await {}", target.text()),
        Expr::Choose { subject, by, .. } => format!("choose {subject} by {}", by.text()),
        Expr::Literal { value, .. } => print_literal(value),
        Expr::Current { .. } => "current".to_string(),
        Expr::Binary {
            op, left, right, ..
        } => format!("{} {} {}", print_expr(left), op.as_str(), print_expr(right)),
    }
}

fn print_literal(literal: &Literal) -> String {
    match literal {
        Literal::Integer(value) => value.to_string(),
        Literal::Float(value) => bioprism_ids::python_repr_f64(*value),
        Literal::Duration { text, .. } => text.clone(),
        Literal::Text(text) => format!("{text:?}"),
        Literal::Money {
            currency,
            minor_units,
        } => format!(
            "{currency}({}.{:02})",
            minor_units / 100,
            (minor_units % 100).abs()
        ),
    }
}

fn join_paths(paths: &[Path]) -> String {
    paths
        .iter()
        .map(Path::text)
        .collect::<Vec<String>>()
        .join(", ")
}
