//! Autonomous research protocol runners: a validated request in, a digested dossier or a
//! domain-specific execution plan out — with every finding derived by a fixed rule from a cited
//! measurement.
//!
//! The original runner remains autonomous **measurement science over synthetic decision worlds** —
//! committed fixtures and seeded generators. [`glioma_engine`] adds a second production surface:
//! a preclinical glioma program planner and execution loop that delegates real work to
//! caller-owned local providers. The blueprint does not specify either runner; their request,
//! workflow, artifact and report schemas are this crate's design, stated as such. What the
//! synthetic steps *measure* is specified, and each step calls the crate that owns it: 43.26
//! context certificates via `bioprism-fiber`, the 43.38
//! equal-engineering comparison and the 43.39 structural families and sweep via
//! `bioprism-baseline`/`bioprism-worldgen`, the 03.08/32 metamorphic suite via
//! `bioprism-mutation`, and the 1-minimal reduction (in 43.40/43.41's refusal vocabulary) via
//! `bioprism-prism`. This crate adds orchestration and receipts, never measurement logic.
//!
//! # The honesty rules this crate is built around
//!
//! - **The question is never interpreted.** A [`ResearchRequest`] records its free-text question
//!   verbatim; the protocol is planned from the *other* fields alone, and no code path anywhere
//!   in this crate branches on the question's content. The runner executes the protocol; it does
//!   not understand the question.
//! - **Findings are derived, never free-generated.** Every [`Finding`] comes from one of the
//!   fixed rules in [`findings`], is levelled [`ObservationLevel::Observation`] — a
//!   single-variant enum, so no other level is representable — and cites the content digests of
//!   the artifacts it was derived from.
//! - **Negative findings are first-class.** A tie between the compiler and a baseline is a
//!   *required* finding, flagged `negative: true` and rendered in the same register as any
//!   positive result. The repository's own headline finding is a tie.
//! - **Every dossier anchors to the pinned parity digest.** Step 0 compiles the committed
//!   `fixtures/fiber-v0.1` pair (embedded at build time) and aborts unless the certificate digest
//!   is [`PINNED_REFERENCE_CERTIFICATE_SHA256`], the value CPython, the eager Rust path, and the
//!   indexed store agree on.
//! - **Partial protocols are unrepresentable.** A step that cannot complete is a typed
//!   [`ResearchError`]; [`dossier::StepOutcome`] has exactly one variant, so an emitted dossier
//!   cannot claim a step it did not finish.
//! - **The dossier is tamper-evident.** `dossier_sha256` is computed over the canonical document
//!   with the digest field removed; [`verify_dossier`] recomputes it, checks the 64-hex shape
//!   separately from mismatch, and checks that every finding's supporting digests actually name
//!   artifacts the dossier carries.
//!
//! # Boundary
//!
//! Research and developer infrastructure: it does not diagnose an individual, recommend
//! treatment, triage care, enroll participants, or claim medical-device functionality. It can
//! never claim biology or medicine, literature or prior-work coverage, external-world
//! observation, or release-level claims from fixture evidence. Oracle review is a human gate.
//! These sentences also ship inside every dossier as [`REQUIRED_LIMITATIONS`].
//!
//! # Not implemented
//!
//! - **No question understanding.** The question is recorded and rendered verbatim, digested,
//!   and never parsed, matched, or routed on. There is no NLP anywhere in this crate.
//! - **No literature fetching in the synthetic runner.** Nothing in that runner searches, cites,
//!   or claims coverage of prior work. The glioma engine accepts literature and other evidence as
//!   caller-supplied local artifact references and delegates retrieval to a provider.
//! - **No recurrence in the synthetic runner.** One request runs one protocol to one dossier in
//!   one call. The glioma engine provides bounded stage retries and checkpoints, but recurrence
//!   scheduling is still owned by the host.
//! - **No wall-clock.** No timestamps, durations, or dates appear in any artifact; determinism
//!   is byte-for-byte and the only order is protocol order.
//! - **No oracle acceptance.** The runner emits observations for human review and accepts,
//!   approves, and releases nothing.
//! - **Figures are static SVG only**, rendered by `bioprism-figures`: no raster, no scripts, no
//!   interactivity.
//! - **No I/O.** Fixtures are compiled in; the caller writes the dossier, report, and figures
//!   wherever they belong.
//! - **No generator knobs beyond the presets.** A request chooses one committed 43.39 family,
//!   one seed, and up to six distractor counts; skeleton, events, protected set, decision time,
//!   and policy stay at each preset's committed values, and the sweep runs the committed default
//!   grid at the grid's own seed.

pub mod dossier;
pub mod error;
pub mod findings;
pub mod glioma;
pub mod glioma_engine;
pub mod protocol;
pub mod report;
pub mod request;
pub mod runner;

pub use dossier::{
    artifact_record, build_dossier, verify_dossier, RecordedArtifact, StepOutcome, DOSSIER_SCHEMA,
    INLINE_ARTIFACT_CAP_BYTES, REQUIRED_LIMITATIONS,
};
pub use error::ResearchError;
pub use findings::{
    comparison_findings, minimization_findings, mutation_findings, reference_anchor_finding,
    sweep_findings, Finding, ObservationLevel,
};
pub use glioma::{
    adjudicate_glioma_assay_evidence, adjudicate_glioma_multimodal_contradictions,
    admit_glioma_decision_actions, allocate_glioma_assays, analyze_causal_sensitivity,
    analyze_federated_benchmark, analyze_federated_benchmark_power,
    analyze_federated_continual_knowledge, analyze_federated_evidence_shifts,
    analyze_federated_knowledge, analyze_federated_mechanism_transport,
    analyze_glioma_causal_contrast, analyze_glioma_clonal_evolution,
    analyze_glioma_clone_panel_outcomes, analyze_glioma_combination_synergy,
    analyze_glioma_computation_reproducibility, analyze_glioma_dose_response,
    analyze_glioma_federated_instrument_consensus, analyze_glioma_instrument_batch_stability,
    analyze_glioma_instrument_multichannel_concordance, analyze_glioma_latent_factors,
    analyze_glioma_mechanism_identifiability, analyze_glioma_mechanism_intervention_value,
    analyze_glioma_mechanism_invariance, analyze_glioma_mediation,
    analyze_glioma_multimodal_decision_gate, analyze_glioma_multimodal_dropout_stress,
    analyze_glioma_multimodal_evidence_fusion, analyze_glioma_multimodal_graph_fusion,
    analyze_glioma_multimodal_missingness, analyze_glioma_multimodal_sensitivity,
    analyze_glioma_pathway_activity, analyze_glioma_spatial_communication,
    analyze_glioma_spatial_niches, analyze_glioma_spatial_state_propagation,
    analyze_glioma_state_transitions, analyze_glioma_temporal_multimodal_fusion,
    analyze_glioma_temporal_spatial_alignment, analyze_glioma_trajectories,
    analyze_glioma_transportability, analyze_instrument_calibration,
    analyze_multimodal_concordance, analyze_multimodal_consensus, analyze_preclinical_outcomes,
    analyze_replication_meta_analysis, analyze_stratified_causal_adjustment,
    assess_glioma_robustness, assess_glioma_validation_batch, assess_replication,
    attribute_glioma_multimodal_quality_root_cause, bridge_glioma_knowledge_actions,
    build_research_object_manifest, calibrate_glioma_decision_value, calibrate_glioma_evidence,
    calibrate_glioma_mechanisms, calibrate_glioma_multimodal_quality_transport,
    calibrate_glioma_multimodal_reliability, certify_decision_omissions,
    compile_decision_action_graph, compile_decision_context,
    compile_glioma_computation_interpretation_frontier, compile_glioma_computation_workflow,
    compile_glioma_instrument_research_frontier, compile_glioma_intent_mission_candidates,
    compile_glioma_knowledge_actions, compile_glioma_knowledge_closure,
    compile_glioma_knowledge_consistency, compile_glioma_knowledge_gaps,
    compile_glioma_mechanism_consensus, compile_glioma_mechanism_validation_protocol,
    compile_glioma_multimodal_mission_candidates, compile_glioma_protocol_evidence_surface,
    compile_glioma_replication_protocol, compile_local_research_workflow,
    compile_mechanism_action_plan, compile_multi_study_knowledge, compile_typed_knowledge,
    compose_knowledge_graph, design_glioma_contrast_panel, design_glioma_robust_experiment,
    design_preclinical_experiment, detect_glioma_evidence_temporal_shifts,
    detect_glioma_knowledge_drift, discriminate_mechanisms, dry_run_adaptive_instrument_executor,
    dry_run_glioma_adaptive_frontier_executor, dry_run_instrument_executor_from_request,
    dry_run_robustness_guided_computation_executor, evaluate_glioma_dynamic_policies,
    evaluate_glioma_release_gate, execute_federated_benchmark_adaptive_campaign,
    execute_federated_benchmark_adaptive_campaign_dry_run, execute_federated_benchmark_campaign,
    execute_federated_benchmark_operating_cycle,
    execute_federated_benchmark_operating_cycle_dry_run,
    execute_federated_mechanism_transport_campaign,
    execute_federated_mechanism_transport_campaign_dry_run, execute_glioma_action_portfolio,
    execute_glioma_active_learning_campaign, execute_glioma_adaptive_allocation_campaign,
    execute_glioma_adaptive_clone_campaign, execute_glioma_adaptive_clone_campaign_dry_run,
    execute_glioma_adaptive_decision_branch_campaign,
    execute_glioma_adaptive_decision_branch_campaign_dry_run,
    execute_glioma_adaptive_decision_controller, execute_glioma_adaptive_frontier,
    execute_glioma_adaptive_information_campaign, execute_glioma_adaptive_instrument_campaign,
    execute_glioma_adaptive_interpretation_campaign,
    execute_glioma_adaptive_interpretation_campaign_dry_run,
    execute_glioma_adaptive_mechanism_campaign, execute_glioma_autonomous_campaign,
    execute_glioma_autonomous_gap_cycle, execute_glioma_autonomous_program_cycle,
    execute_glioma_autonomous_protocol, execute_glioma_autonomous_research_engine,
    execute_glioma_autonomous_research_mission, execute_glioma_calibrated_mechanism_campaign,
    execute_glioma_calibrated_mechanism_campaign_dry_run, execute_glioma_causal_claim_adjudication,
    execute_glioma_computation, execute_glioma_computation_campaign,
    execute_glioma_computation_interpretation_evidence_gate,
    execute_glioma_computation_interpretation_frontier, execute_glioma_computation_operating_cycle,
    execute_glioma_computation_operating_cycle_dry_run, execute_glioma_computation_portfolio,
    execute_glioma_computation_recovery, execute_glioma_decision_branch_campaign,
    execute_glioma_decision_context_campaign, execute_glioma_decision_mission,
    execute_glioma_decision_operating_cycle, execute_glioma_evidence_acquisition_campaign,
    execute_glioma_evidence_campaign, execute_glioma_evidence_gated_research,
    execute_glioma_evidence_operating_cycle, execute_glioma_evidence_operating_cycle_dry_run,
    execute_glioma_evidence_refresh_campaign, execute_glioma_experiment_frontier_controller,
    execute_glioma_experiment_operating_cycle, execute_glioma_instrument_campaign,
    execute_glioma_instrument_fleet, execute_glioma_instrument_operating_cycle,
    execute_glioma_instrument_plan, execute_glioma_instrument_research_frontier,
    execute_glioma_instrument_science_loop, execute_glioma_intent_mission,
    execute_glioma_interpretation_operating_cycle, execute_glioma_knowledge_action_dispatch,
    execute_glioma_knowledge_resolution_campaign, execute_glioma_knowledge_selection_cycle,
    execute_glioma_knowledge_synthesis_operating_cycle, execute_glioma_mechanism_autopilot,
    execute_glioma_mechanism_discovery_engine, execute_glioma_mechanism_discrimination_campaign,
    execute_glioma_mechanism_operating_cycle, execute_glioma_mechanism_validation_protocol,
    execute_glioma_mission_recovery, execute_glioma_multi_fidelity_campaign,
    execute_glioma_multimodal_ingestion_campaign, execute_glioma_multimodal_mechanism_campaign,
    execute_glioma_multimodal_mechanism_campaign_with_executor, execute_glioma_multimodal_mission,
    execute_glioma_multimodal_operating_cycle, execute_glioma_multimodal_operating_cycle_dry_run,
    execute_glioma_multimodal_quality_adaptive_campaign,
    execute_glioma_multimodal_quality_schedule, execute_glioma_multimodal_readiness_gate,
    execute_glioma_program_scheduler, execute_glioma_program_scheduler_dry_run,
    execute_glioma_protocol, execute_glioma_release_operating_cycle,
    execute_glioma_release_operating_cycle_dry_run, execute_glioma_replay_campaign,
    execute_glioma_replication_campaign, execute_glioma_replication_closure,
    execute_glioma_replication_closure_campaign, execute_glioma_research_autopilot,
    execute_glioma_research_director, execute_glioma_robust_active_learning_campaign,
    execute_glioma_robustness_guided_computation, execute_glioma_scientific_frontier,
    execute_glioma_sequential_campaign, execute_glioma_validation_campaign,
    execute_glioma_validation_replication_campaign, execute_glioma_workflow,
    execute_validation_replication_transport, explore_mechanisms, extract_glioma_instrument_signal,
    filter_glioma_mechanism_states, forecast_glioma_multimodal_quality,
    fuse_glioma_protocol_evidence, gate_glioma_protocol_transport, generate_feature_catalog,
    glioma_program_catalog, govern_glioma_decision_loop, harmonize_glioma_multimodal_batches,
    harmonize_multimodal_inputs, implemented_feature_ids, interpret_glioma_federated_closure,
    interpret_glioma_replication_closure, materialize_glioma_protocol_branch,
    monitor_prospective_knowledge, optimize_glioma_decision_value,
    optimize_glioma_protocol_branches, plan_adaptive_glioma_dose_surface, plan_decision_actions,
    plan_federated_benchmark_sites, plan_federated_continual_agent, plan_glioma_active_learning,
    plan_glioma_adaptive_information_campaign, plan_glioma_adaptive_mechanism_policy,
    plan_glioma_adaptive_panel, plan_glioma_adaptive_research_frontier,
    plan_glioma_adaptive_workflow, plan_glioma_blocked_randomization,
    plan_glioma_carryover_sequence, plan_glioma_clone_continuation,
    plan_glioma_clone_perturbation_panel, plan_glioma_closed_loop_campaign,
    plan_glioma_computation_portfolio, plan_glioma_decision_branches,
    plan_glioma_evidence_acquisition, plan_glioma_evidence_contradiction_cut,
    plan_glioma_information_design, plan_glioma_mechanism_validation,
    plan_glioma_multi_fidelity_optimization, plan_glioma_multimodal_portfolio,
    plan_glioma_multimodal_quality_remediation, plan_glioma_multimodal_quality_schedule,
    plan_glioma_power_reestimation, plan_glioma_power_stress_surface,
    plan_glioma_protocol_compensation, plan_glioma_replication,
    plan_glioma_replication_closure_frontier, plan_glioma_replication_continuation,
    plan_glioma_research_director, plan_glioma_robust_active_learning,
    plan_glioma_robust_intervention_portfolio, plan_glioma_scientific_frontier,
    plan_glioma_sequential_design, plan_glioma_validation_replication_gate, plan_glioma_workflow,
    preflight_glioma_instrument, prioritize_glioma_evidence, prioritize_knowledge_frontier,
    propagate_glioma_mechanism_graph, protocol_request_from_experiment_design, qualify_evidence,
    rank_glioma_evidence_novelty, register_glioma_spatial_samples, revise_glioma_beliefs,
    schedule_glioma_computation_placement, schedule_glioma_instrument_fleet,
    simulate_glioma_counterfactual, simulate_glioma_counterfactual_ensemble,
    simulate_glioma_mechanism_dynamics, simulate_glioma_protocol,
    simulate_glioma_protocol_scenario_ensemble, smooth_glioma_mechanism_states,
    surveil_glioma_evidence, surveil_glioma_multimodal_drift, synthesize_glioma_interpretation,
    triangulate_glioma_evidence, update_glioma_mechanism_posterior, validate_feature_catalog,
    verify_glioma_multimodal_quality_recovery, ActionExecutionDisposition, ActionExecutionFailure,
    ActionExecutionResult, ActionPortfolioExecution, ActionPortfolioExecutionDisposition,
    ActionPortfolioExecutionError, ActionPortfolioExecutionRequest, ActionPortfolioStopReason,
    ActiveLearningCampaign, ActiveLearningCampaignDisposition, ActiveLearningCampaignError,
    ActiveLearningCampaignExecutor, ActiveLearningCampaignRequest, ActiveLearningCampaignRound,
    ActiveLearningCampaignStopReason, ActiveLearningCandidate, ActiveLearningCandidateDisposition,
    ActiveLearningDirection, ActiveLearningDisposition, ActiveLearningError,
    ActiveLearningExecutionFailure, ActiveLearningObservation, ActiveLearningPlan,
    ActiveLearningRequest, ActiveLearningScore, AdaptiveAllocation, AdaptiveAllocationActionKind,
    AdaptiveAllocationBatchObservation, AdaptiveAllocationCampaign,
    AdaptiveAllocationCampaignDisposition, AdaptiveAllocationCampaignError,
    AdaptiveAllocationCampaignExecutionFailure, AdaptiveAllocationCampaignExecutor,
    AdaptiveAllocationCampaignRequest, AdaptiveAllocationCampaignRound,
    AdaptiveAllocationCampaignStopReason, AdaptiveAllocationDisposition, AdaptiveAllocationError,
    AdaptiveAllocationRequest, AdaptiveArmObservation, AdaptiveArmPosterior, AdaptiveCloneCampaign,
    AdaptiveCloneCampaignDisposition, AdaptiveCloneCampaignError, AdaptiveCloneCampaignExecutor,
    AdaptiveCloneCampaignRequest, AdaptiveCloneCampaignRound, AdaptiveCloneCampaignStopReason,
    AdaptiveCloneExecutionFailure, AdaptiveDecisionBranchCampaign,
    AdaptiveDecisionBranchCampaignDisposition, AdaptiveDecisionBranchCampaignError,
    AdaptiveDecisionBranchCampaignRequest, AdaptiveDecisionBranchCampaignRound,
    AdaptiveDecisionBranchCampaignStopReason, AdaptiveDecisionCampaignDisposition,
    AdaptiveDecisionCandidateScore, AdaptiveDecisionControllerError,
    AdaptiveDecisionControllerRequest, AdaptiveDecisionControllerResult,
    AdaptiveDoseSurfaceDisposition, AdaptiveDoseSurfaceError, AdaptiveDoseSurfacePlan,
    AdaptiveDoseSurfaceRequest, AdaptiveFrontierCandidate, AdaptiveFrontierDisposition,
    AdaptiveFrontierError, AdaptiveFrontierExecution, AdaptiveFrontierExecutionDisposition,
    AdaptiveFrontierExecutionError, AdaptiveFrontierExecutionRequest, AdaptiveFrontierRequest,
    AdaptiveInformationCampaignDisposition, AdaptiveInformationCampaignError,
    AdaptiveInformationCampaignExecution, AdaptiveInformationCampaignPlan,
    AdaptiveInformationCampaignRequest, AdaptiveInformationCampaignRound,
    AdaptiveInformationCampaignTermination, AdaptiveInformationExecutionFailure,
    AdaptiveInformationObservation, AdaptiveInstrumentCampaign,
    AdaptiveInstrumentCampaignDisposition, AdaptiveInstrumentCampaignError,
    AdaptiveInstrumentCampaignRequest, AdaptiveInstrumentCandidate, AdaptiveInstrumentDecision,
    AdaptiveInterpretationCampaign, AdaptiveInterpretationCampaignDisposition,
    AdaptiveInterpretationCampaignError, AdaptiveInterpretationCampaignRequest,
    AdaptiveInterpretationCampaignRound, AdaptiveInterpretationCampaignStopReason,
    AdaptiveInterpretationPlanner, AdaptiveInterpretationPlanningFailure, AdaptiveMechanismAction,
    AdaptiveMechanismActionScore, AdaptiveMechanismCampaign, AdaptiveMechanismCampaignRequest,
    AdaptiveMechanismCampaignRound, AdaptiveMechanismCampaignStopReason,
    AdaptiveMechanismExecutionFailure, AdaptiveMechanismModel, AdaptiveMechanismObservation,
    AdaptiveMechanismPolicy, AdaptiveMechanismPolicyDisposition, AdaptiveMechanismPolicyError,
    AdaptiveMechanismPolicyExecutor, AdaptiveMechanismPolicyPosterior,
    AdaptiveMechanismPolicyRequest, AdaptiveMechanismPolicyStep, AdaptiveMechanismPosterior,
    AdaptiveMechanismPrediction, AdaptivePanelActionKind, AdaptivePanelDesign,
    AdaptivePanelDisposition, AdaptivePanelError, AdaptivePanelRequest, AdaptivePanelSelection,
    AdaptiveResearchFrontier, AdaptiveTarget, AnalysisDataset, AnalysisRequest, AnalysisResult,
    AssayEvidenceDisposition, AssayEvidenceError, AssayEvidenceObservation, AssayEvidenceRecord,
    AssayEvidenceRequest, AutonomousGapCycle, AutonomousGapCycleDisposition,
    AutonomousGapCycleError, AutonomousGapCycleRequest, AutonomousProgramCycle,
    AutonomousProgramCycleDisposition, AutonomousProgramCycleError, AutonomousProgramCycleRequest,
    AutonomousProtocolControllerDisposition, AutonomousProtocolControllerError,
    AutonomousProtocolControllerRequest, AutonomousProtocolControllerRun,
    AutonomousProtocolControllerStopReason, AutonomousProtocolRound, BatchHarmonizationDiagnostic,
    BatchStabilityDisposition, BatchStabilityError, BayesianMechanismHypothesis,
    BayesianMechanismUpdateError, BayesianMechanismUpdateRequest, BayesianUpdateDisposition,
    BeliefConflict, BeliefRevision, BeliefRevisionDecision, BeliefRevisionDecisionKind,
    BeliefRevisionDisposition, BeliefRevisionError, BeliefRevisionRequest, BlockArmAllocation,
    BlockedRandomizationDesign, BlockedRandomizationDisposition, BlockedRandomizationError,
    BlockedRandomizationRequest, BranchExecutionDisposition, BridgedKnowledgeCandidate,
    CalibratedMechanismActionScore, CalibratedMechanismCampaign,
    CalibratedMechanismCampaignDisposition, CalibratedMechanismCampaignError,
    CalibratedMechanismCampaignRequest, CalibratedMechanismCampaignRound,
    CalibratedMechanismCampaignStopReason, CalibratedMechanismTrust, CalibrationBin,
    CalibrationBinDisposition, CalibrationDisposition, CalibrationError, CalibrationPoint,
    CalibrationRequest, CalibrationRun, CampaignAction, CampaignActionScore,
    CampaignExecutionFailure, CampaignExecutionRound, CampaignMechanism,
    CampaignMechanismPosterior, CampaignObservation, CampaignRound, CampaignStopReason,
    CarryoverAction, CarryoverSequenceDesign, CarryoverSequenceDisposition, CarryoverSequenceError,
    CarryoverSequenceRequest, CarryoverSequenceStep, CatalogError, CausalClaimDisposition,
    CausalContrastAnalysis, CausalContrastDisposition, CausalContrastError, CausalContrastRequest,
    CausalSensitivityAnalysis, CausalStratumSummary, ChannelConcordance,
    ChannelConcordanceDisposition, ChannelStability, ChannelStabilityDisposition, ClaimActionKind,
    ClaimGate, ClaimGateDisposition, ClaimNextAction, ClonalEdge, ClonalEvolutionDisposition,
    ClonalEvolutionError, ClonalEvolutionGraph, ClonalEvolutionRequest, ClonalNode, ClonalRelation,
    CloneBranchCoverage, CloneContinuationActionKind, CloneContinuationActionStatus,
    CloneContinuationCandidate, CloneContinuationDecision, CloneContinuationDisposition,
    CloneContinuationError, CloneContinuationPlan, CloneContinuationRequest, CloneMarker,
    CloneMarkerState, ClonePanelBranchAnalysis, ClonePanelCandidateAnalysis,
    ClonePanelCellAnalysis, ClonePanelCellDisposition, ClonePanelMeasurementState,
    ClonePanelObservation, ClonePanelOutcomeAnalysis, ClonePanelOutcomeDisposition,
    ClonePanelOutcomeError, ClonePanelOutcomeRequest, ClonePerturbationCandidate,
    ClonePerturbationDecision, ClonePerturbationKind, ClonePerturbationPanel,
    ClonePerturbationPanelDisposition, ClonePerturbationPanelError, ClonePerturbationPanelRequest,
    CloneProfile, ClosedLoopCampaign, ClosedLoopCampaignDisposition, ClosedLoopCampaignError,
    ClosedLoopCampaignExecution, ClosedLoopCampaignRequest, ClosureInterpretationDisposition,
    ClosureInterpretationError, ClosureInterpretationRequest, ClosureInterpretationRun,
    CombinationCell, CombinationCellDisposition, CombinationObservation,
    CombinationSynergyAnalysis, CombinationSynergyDisposition, CombinationSynergyError,
    CombinationSynergyRequest, CompiledActionDisposition, CompiledResearchAction,
    ComputationCacheEntry, ComputationCandidate, ComputationCandidateDisposition,
    ComputationCandidateScore, ComputationExecution, ComputationExecutionDisposition,
    ComputationExecutionError, ComputationExecutionFailure, ComputationExecutionMode,
    ComputationExecutionRequest, ComputationExecutionStopReason,
    ComputationInterpretationEvidenceGate, ComputationInterpretationEvidenceGateDisposition,
    ComputationInterpretationEvidenceGateError, ComputationInterpretationEvidenceGateRequest,
    ComputationInterpretationFrontier, ComputationInterpretationFrontierDisposition,
    ComputationInterpretationFrontierError, ComputationInterpretationFrontierRequest,
    ComputationInterpretationFrontierRun, ComputationInterpretationObservation,
    ComputationInterpretationSynthesisPolicy, ComputationOperation, ComputationPlacementAssignment,
    ComputationPlacementBlockedTask, ComputationPlacementDisposition, ComputationPlacementError,
    ComputationPlacementRequest, ComputationPlacementSchedule, ComputationPortfolioDisposition,
    ComputationPortfolioError, ComputationPortfolioExecution,
    ComputationPortfolioExecutionDisposition, ComputationPortfolioExecutionError,
    ComputationPortfolioExecutionRequest, ComputationPortfolioPlan, ComputationPortfolioRequest,
    ComputationRecoveryCampaign, ComputationRecoveryDisposition, ComputationRecoveryError,
    ComputationRecoveryRequest, ComputationRecoveryStopReason, ComputationReproducibility,
    ComputationReproducibilityDisposition, ComputationReproducibilityError,
    ComputationReproducibilityRequest, ComputationReproducibilityRun,
    ComputationReproducibilityTaskObservation, ComputationRunOutcome, ComputationTask,
    ComputationTaskDisposition, ComputationTaskReproducibilityDisposition,
    ComputationTaskReproducibilitySummary, ComputationTaskResult, ComputationWorkerProfile,
    ComputationWorkerUtilization, ConcordanceDisposition, ConcordanceError, ConcordanceRequest,
    ConsensusAssignment, ConsensusCluster, ConsensusDisposition, ConsensusError, ConsensusRequest,
    ContradictionAdjudication, ContradictionAdjudicationDisposition,
    ContradictionAdjudicationError, ContradictionAdjudicationRequest, ContradictionAuditSelection,
    ContradictionConflict, ContradictionCut, ContradictionCutDisposition, ContradictionCutError,
    ContradictionCutRequest, ContradictionEvidence, ContradictionKind, ContrastCondition,
    ContrastDesign, ContrastDesignDisposition, ContrastDesignError, ContrastDesignRequest,
    ContrastFactor, CounterfactualContrast, CounterfactualDirection, CounterfactualDisposition,
    CounterfactualEnsembleRequest, CounterfactualError, CounterfactualIntervention,
    CounterfactualModel, CounterfactualRequest, DecisionAction, DecisionActionGraph,
    DecisionActionGraphDisposition, DecisionActionGraphError, DecisionActionGraphRequest,
    DecisionActionKind, DecisionActionPlan, DecisionActionPlanDisposition, DecisionActionPlanError,
    DecisionActionPlanRequest, DecisionAdmissionAction, DecisionAdmissionCampaignDisposition,
    DecisionAdmissionDisposition, DecisionAdmissionError, DecisionAdmissionRecord,
    DecisionAdmissionRequest, DecisionAdmissionResult, DecisionBranchCampaign,
    DecisionBranchCampaignDisposition, DecisionBranchCampaignError, DecisionBranchCampaignRequest,
    DecisionBranchCampaignStopReason, DecisionBranchExecution, DecisionBranchPlan,
    DecisionBranchPlanDisposition, DecisionBranchPlannerError, DecisionBranchPlannerRequest,
    DecisionBranchPortfolio, DecisionContext, DecisionContextCampaign,
    DecisionContextCampaignDisposition, DecisionContextCampaignError,
    DecisionContextCampaignExecutionFailure, DecisionContextCampaignExecutor,
    DecisionContextCampaignRequest, DecisionContextCampaignRound,
    DecisionContextCampaignStopReason, DecisionContextDisposition, DecisionContextError,
    DecisionContextRequest, DecisionCoverageState, DecisionDirection,
    DecisionGateModalityObservation, DecisionGraphNode, DecisionLoopGovernorDisposition,
    DecisionLoopGovernorError, DecisionLoopGovernorRequest, DecisionLoopGovernorResult,
    DecisionLoopRound, DecisionLoopRoundAssessment, DecisionLoopRoundDisposition,
    DecisionLoopStopReason, DecisionMissionBridgeDisposition, DecisionMissionBridgeError,
    DecisionMissionBridgeRequest, DecisionMissionBridgeRun, DecisionOmissionCertificate,
    DecisionOmissionCertificateError, DecisionOmissionCertificateRequest,
    DecisionOmissionDisposition, DecisionOmissionEntry, DecisionOperatingCycle,
    DecisionOperatingCycleDisposition, DecisionOperatingCycleError, DecisionOperatingCycleRequest,
    DecisionScenario, DecisionScenarioOutcome, DecisionScenarioScore,
    DecisionValueCalibrationCampaignDisposition, DecisionValueCalibrationDisposition,
    DecisionValueCalibrationError, DecisionValueCalibrationRecord, DecisionValueCalibrationRequest,
    DecisionValueCalibrationResult, DecisionValueCampaignDisposition, DecisionValueCandidate,
    DecisionValueCandidateScore, DecisionValueDisposition, DecisionValueError,
    DecisionValueObservation, DecisionValuePortfolio, DecisionValueRequest, DecisionValueResult,
    DecisionValueWeights, DesignAction, DesignMechanism, DesignOutcome, DoseDirection, DosePair,
    DoseResponseAnalysis, DoseResponseDisposition, DoseResponseError, DoseResponseObservation,
    DoseResponsePoint, DoseResponseRequest, DoseSurfaceCellState, DoseSurfaceEstimate,
    DoseSurfaceObservation, DriftDisposition, DriftMetricSummary, DriftObservation,
    DriftSurveillance, DriftSurveillanceError, DriftSurveillanceRequest, DropoutModalitySignal,
    DropoutScenario, DropoutScenarioDisposition, DropoutScenarioResult, DropoutStressAnalysis,
    DropoutStressDisposition, DropoutStressError, DropoutStressRequest,
    DryRunActiveLearningCampaignExecutor, DryRunAdaptiveAllocationCampaignExecutor,
    DryRunAdaptiveCloneCampaignExecutor, DryRunAdaptiveInterpretationPlanner,
    DryRunAdaptiveMechanismPolicyExecutor, DryRunDecisionContextCampaignExecutor,
    DryRunEvidenceAcquisitionExecutor, DryRunEvidenceRefreshCampaignExecutor,
    DryRunExperimentOperatingCycleExecutor, DryRunFederatedBenchmarkCampaignExecutor,
    DryRunFederatedMechanismTransportExecutor, DryRunGliomaActionExecutor,
    DryRunGliomaComputationExecutor, DryRunGliomaExperimentFrontierExecutor,
    DryRunGliomaProtocolExecutor, DryRunGliomaReplicationCampaignExecutor,
    DryRunInstrumentExecutor, DryRunKnowledgeActionExecutor,
    DryRunKnowledgeResolutionCampaignExecutor, DryRunMechanismDiscriminationCampaignExecutor,
    DryRunMultiFidelityCampaignExecutor, DryRunMultimodalIngestionCampaignExecutor,
    DryRunQualityScheduleExecutor, DryRunReplayCampaignExecutor,
    DryRunRobustActiveLearningCampaignExecutor, DryRunSequentialCampaignExecutor,
    DynamicPolicyCandidate, DynamicPolicyContribution, DynamicPolicyDisposition,
    DynamicPolicyError, DynamicPolicyEvaluation, DynamicPolicyObservation, DynamicPolicyRequest,
    DynamicPolicyRule, DynamicPolicyScore, DynamicPolicyScoreDisposition, DynamicPolicyTrajectory,
    EndpointEvidence, EnsembleCounterfactualError, EnsembleDirection, EnsembleDisposition,
    EnsembleModelResult, EnsembleTargetSummary, EstimandContrast, EstimateSource,
    EvidenceAcquisitionCampaign, EvidenceAcquisitionCampaignDisposition,
    EvidenceAcquisitionCampaignError, EvidenceAcquisitionCampaignRequest,
    EvidenceAcquisitionCampaignStopReason, EvidenceAcquisitionCandidate,
    EvidenceAcquisitionDisposition, EvidenceAcquisitionError, EvidenceAcquisitionExecutionFailure,
    EvidenceAcquisitionExecutor, EvidenceAcquisitionPlan, EvidenceAcquisitionRequest,
    EvidenceAcquisitionResult, EvidenceAcquisitionResultDisposition, EvidenceAcquisitionSelection,
    EvidenceAcquisitionSourceKind, EvidenceAcquisitionWeights, EvidenceCalibrationAnalysis,
    EvidenceCalibrationDisposition, EvidenceCalibrationError, EvidenceCalibrationObservation,
    EvidenceCalibrationRequest, EvidenceChange, EvidenceChangeKind, EvidenceContribution,
    EvidenceExecutionMode, EvidenceFusionAnalysis, EvidenceFusionDisposition, EvidenceFusionError,
    EvidenceFusionRequest, EvidenceGatedResearchDisposition, EvidenceNoveltyAction,
    EvidenceNoveltyActionDisposition, EvidenceNoveltyRadar, EvidenceNoveltyRadarDisposition,
    EvidenceNoveltyRadarError, EvidenceNoveltyRadarRequest, EvidenceNoveltyRecord,
    EvidencePolarity, EvidencePriorityAction, EvidencePriorityActionKind,
    EvidencePriorityDisposition, EvidencePriorityError, EvidencePriorityPlan,
    EvidencePriorityRequest, EvidencePriorityWeights, EvidenceQualification, EvidenceRecord,
    EvidenceRefreshCampaign, EvidenceRefreshCampaignDisposition, EvidenceRefreshCampaignError,
    EvidenceRefreshCampaignExecutor, EvidenceRefreshCampaignRequest, EvidenceRefreshCampaignRound,
    EvidenceRefreshCampaignStopReason, EvidenceRefreshExecutionFailure, EvidenceRequest,
    EvidenceSurveillance, EvidenceSurveillanceAction, EvidenceSurveillanceActionKind,
    EvidenceSurveillanceDisposition, EvidenceSurveillanceError, EvidenceSurveillanceRequest,
    EvidenceTemporalObservation, EvidenceTemporalShift, EvidenceTemporalShiftAction,
    EvidenceTemporalShiftDisposition, EvidenceTemporalShiftError, EvidenceTemporalShiftKind,
    EvidenceTemporalShiftRequest, EvidenceTriangulation, EvidenceTriangulationDisposition,
    EvidenceTriangulationError, EvidenceTriangulationRequest, ExperimentArm, ExperimentDesign,
    ExperimentOperatingCycle, ExperimentOperatingCycleDisposition, ExperimentOperatingCycleError,
    ExperimentOperatingCycleRequest, ExperimentRequest, FeatureValue, FederatedAgentActionKind,
    FederatedAgentCandidate, FederatedAgentDecision, FederatedAgentDisposition,
    FederatedAgentPlanItem, FederatedBenchmarkAction, FederatedBenchmarkActionKind,
    FederatedBenchmarkAdaptiveCampaign, FederatedBenchmarkAdaptiveCampaignError,
    FederatedBenchmarkAdaptiveCampaignRequest, FederatedBenchmarkAdaptiveDisposition,
    FederatedBenchmarkAdaptiveStopReason, FederatedBenchmarkCampaign,
    FederatedBenchmarkCampaignDisposition, FederatedBenchmarkCampaignError,
    FederatedBenchmarkCampaignExecutor, FederatedBenchmarkCampaignRequest,
    FederatedBenchmarkCampaignRound, FederatedBenchmarkCampaignStopReason,
    FederatedBenchmarkCandidate, FederatedBenchmarkCandidateScore, FederatedBenchmarkConsensus,
    FederatedBenchmarkContribution, FederatedBenchmarkDisposition, FederatedBenchmarkError,
    FederatedBenchmarkExecutionFailure, FederatedBenchmarkExecutionMode,
    FederatedBenchmarkOperatingCycle, FederatedBenchmarkOperatingCycleDisposition,
    FederatedBenchmarkOperatingCycleError, FederatedBenchmarkOperatingCycleRequest,
    FederatedBenchmarkPlanDisposition, FederatedBenchmarkPower,
    FederatedBenchmarkPowerContribution, FederatedBenchmarkPowerDisposition,
    FederatedBenchmarkPowerError, FederatedBenchmarkPowerRequest,
    FederatedBenchmarkPowerSiteDisposition, FederatedBenchmarkRequest, FederatedBenchmarkSite,
    FederatedBenchmarkSiteDisposition, FederatedBenchmarkSitePlan,
    FederatedBenchmarkSitePlannerError, FederatedBenchmarkSitePlannerRequest,
    FederatedConsensusDisposition, FederatedConsensusError, FederatedContinualAgentError,
    FederatedContinualAgentPlan, FederatedContinualAgentRequest, FederatedContinualClaim,
    FederatedContinualClaimDisposition, FederatedContinualDisposition, FederatedContinualKnowledge,
    FederatedContinualKnowledgeError, FederatedContinualKnowledgeRequest,
    FederatedContinualObservation, FederatedContinualTrend, FederatedEndpointConsensus,
    FederatedEndpointDisposition, FederatedEndpointValue, FederatedEpochConsensus,
    FederatedEpochDisposition, FederatedEvidenceShift, FederatedEvidenceShiftAction,
    FederatedEvidenceShiftDisposition, FederatedEvidenceShiftError, FederatedEvidenceShiftKind,
    FederatedEvidenceShiftRequest, FederatedEvidenceShiftSite, FederatedInstrumentConsensus,
    FederatedInstrumentConsensusRequest, FederatedInstrumentSite,
    FederatedInterpretationDisposition, FederatedInterpretationError,
    FederatedInterpretationRequest, FederatedInterpretationRun, FederatedKnowledge,
    FederatedKnowledgeAction, FederatedKnowledgeDisposition, FederatedKnowledgeError,
    FederatedKnowledgeKind, FederatedKnowledgeRequest, FederatedKnowledgeSiteClaim,
    FederatedMechanismContribution, FederatedMechanismSite, FederatedMechanismTransportAction,
    FederatedMechanismTransportAnalysis, FederatedMechanismTransportCampaign,
    FederatedMechanismTransportCampaignDisposition, FederatedMechanismTransportCampaignError,
    FederatedMechanismTransportCampaignRequest, FederatedMechanismTransportCampaignRound,
    FederatedMechanismTransportCampaignStopReason, FederatedMechanismTransportDisposition,
    FederatedMechanismTransportError, FederatedMechanismTransportExecutionFailure,
    FederatedMechanismTransportExecutor, FederatedMechanismTransportRequest,
    FederatedModelCoverage, FidelityCalibration, FidelityCandidate, FidelityEstimate,
    FidelityLevel, FidelityObservation, FrontierActionKind, FrontierCandidateGate,
    FrontierCandidateStatus, GliomaActionExecutor, GliomaActionPlanner,
    GliomaAdaptiveWorkflowSchedulerDisposition, GliomaAdaptiveWorkflowSchedulerError,
    GliomaAdaptiveWorkflowSchedulerPlan, GliomaAdaptiveWorkflowSchedulerRequest,
    GliomaAutonomousCampaign, GliomaAutonomousCampaignDisposition, GliomaAutonomousCampaignError,
    GliomaAutonomousCampaignRequest, GliomaAutonomousCampaignRound,
    GliomaAutonomousCampaignStopReason, GliomaAutonomousPlannerContext,
    GliomaAutonomousResearchEngineCycle, GliomaAutonomousResearchEngineDisposition,
    GliomaAutonomousResearchEngineError, GliomaAutonomousResearchEngineRequest,
    GliomaAutonomousResearchEngineRun, GliomaAutonomousResearchEngineStopReason,
    GliomaAutonomousResearchMission, GliomaCampaignExecutor, GliomaCausalClaimAdjudication,
    GliomaCausalClaimAdjudicationError, GliomaCausalClaimAdjudicationRequest,
    GliomaComputationCampaign, GliomaComputationCampaignDisposition,
    GliomaComputationCampaignError, GliomaComputationCampaignRequest,
    GliomaComputationCampaignRound, GliomaComputationCampaignStopReason, GliomaComputationExecutor,
    GliomaComputationOperatingCycle, GliomaComputationOperatingCycleDisposition,
    GliomaComputationOperatingCycleError, GliomaComputationOperatingCycleRequest,
    GliomaComputationPlanner, GliomaComputationPlannerContext, GliomaComputationPlannerFailure,
    GliomaComputationWorkflow, GliomaComputationWorkflowError, GliomaComputationWorkflowRequest,
    GliomaDirectorAction, GliomaDirectorCheckpoint, GliomaDirectorDisposition, GliomaDirectorFocus,
    GliomaEvidenceCampaignDisposition, GliomaEvidenceCampaignError,
    GliomaEvidenceCampaignExecution, GliomaEvidenceCampaignRequest,
    GliomaEvidenceGatedResearchError, GliomaEvidenceGatedResearchRequest,
    GliomaEvidenceGatedResearchRun, GliomaEvidenceOperatingCycle,
    GliomaEvidenceOperatingCycleDisposition, GliomaEvidenceOperatingCycleError,
    GliomaEvidenceOperatingCycleRequest, GliomaExperimentFrontierError,
    GliomaExperimentFrontierExecutor, GliomaExperimentFrontierRequest, GliomaExperimentFrontierRun,
    GliomaFeatureSpec, GliomaFrontierCandidate, GliomaFrontierDisposition,
    GliomaFrontierExecutionFailure, GliomaFrontierMechanism, GliomaFrontierObservation,
    GliomaFrontierOutcome, GliomaFrontierRound, GliomaFrontierScore, GliomaFrontierStopReason,
    GliomaInformationDesignExecutor, GliomaIntentMissionDisposition, GliomaIntentMissionError,
    GliomaIntentMissionRequest, GliomaIntentResearchMission, GliomaInterpretationOperatingCycle,
    GliomaInterpretationOperatingCycleError, GliomaInterpretationOperatingCycleRequest,
    GliomaMechanismActionPlanner, GliomaMechanismAutopilotDisposition,
    GliomaMechanismAutopilotError, GliomaMechanismAutopilotRequest, GliomaMechanismAutopilotRound,
    GliomaMechanismAutopilotRun, GliomaMechanismAutopilotStopReason,
    GliomaMechanismDiscoveryDisposition, GliomaMechanismDiscoveryError,
    GliomaMechanismDiscoveryRequest, GliomaMechanismDiscoveryRound, GliomaMechanismDiscoveryRun,
    GliomaMechanismDiscoveryStopReason, GliomaMissionDisposition, GliomaMissionError,
    GliomaMissionGates, GliomaMissionRecovery, GliomaMissionRecoveryDisposition,
    GliomaMissionRecoveryError, GliomaMissionRecoveryRequest, GliomaMissionRecoveryStopReason,
    GliomaMissionRequest, GliomaMissionRound, GliomaMissionStopReason, GliomaModalitySensitivity,
    GliomaMultimodalMissionDisposition, GliomaMultimodalMissionError,
    GliomaMultimodalMissionRequest, GliomaMultimodalOperatingCycle,
    GliomaMultimodalOperatingCycleDisposition, GliomaMultimodalOperatingCycleError,
    GliomaMultimodalOperatingCycleRequest, GliomaMultimodalResearchMission,
    GliomaMultimodalSensitivityAnalysis, GliomaMultimodalSensitivityDisposition,
    GliomaMultimodalSensitivityError, GliomaMultimodalSensitivityRequest, GliomaOperatingScale,
    GliomaPlannerFailure, GliomaProgramDescriptor, GliomaProgramId, GliomaProgramResourceCapacity,
    GliomaProgramResourceUsage, GliomaProgramScheduleExecution, GliomaProgramScheduleHold,
    GliomaProgramScheduleJob, GliomaProgramScheduleJobDisposition, GliomaProgramScheduleJobState,
    GliomaProgramSchedulerDisposition, GliomaProgramSchedulerError, GliomaProgramSchedulerRequest,
    GliomaProgramSchedulerRound, GliomaProgramSchedulerRun, GliomaProgramSchedulerStopReason,
    GliomaProtocolExecutor, GliomaReleaseOperatingCycle, GliomaReleaseOperatingCycleDisposition,
    GliomaReleaseOperatingCycleError, GliomaReleaseOperatingCycleRequest, GliomaReplicationAction,
    GliomaReplicationActionKind, GliomaReplicationCampaign, GliomaReplicationCampaignDisposition,
    GliomaReplicationCampaignError, GliomaReplicationCampaignExecutor,
    GliomaReplicationCampaignObservation, GliomaReplicationCampaignRequest,
    GliomaReplicationCampaignRound, GliomaReplicationCampaignStopReason,
    GliomaReplicationExecutionFailure, GliomaResearchAutopilotDisposition,
    GliomaResearchAutopilotError, GliomaResearchAutopilotRequest, GliomaResearchAutopilotRun,
    GliomaResearchDirectorError, GliomaResearchDirectorRequest, GliomaResearchDirectorRun,
    GliomaWorkflowBranch, GliomaWorkflowError, GliomaWorkflowExecution, GliomaWorkflowMode,
    GliomaWorkflowNode, GliomaWorkflowPlan, GliomaWorkflowRequest, GraphFusionAnalysis,
    GraphFusionDisposition, GraphFusionError, GraphFusionNeighbour, GraphFusionRequest,
    GraphFusionState, GraphFusionVector, HarmonizationDisposition, HarmonizationError,
    HarmonizationRequest, HarmonizationVector, HarmonizedFeature, HarmonizedVector,
    IdentifiabilityFeature, IdentifiabilityFeatureUtility, IdentifiabilityMechanism,
    InformationDesignActionScore, InformationDesignDisposition, InformationDesignError,
    InformationDesignPlan, InformationDesignRequest, IngestionQcAction, IngestionQcActionKind,
    InstrumentAction, InstrumentActionDecision, InstrumentActionDisposition,
    InstrumentAssayEvidenceAssessment, InstrumentAuthorization, InstrumentBatchStability,
    InstrumentCalibration, InstrumentCampaign, InstrumentCampaignDisposition,
    InstrumentCampaignError, InstrumentCampaignFailure, InstrumentCampaignRequest,
    InstrumentCampaignRunRequest, InstrumentCampaignRunResult, InstrumentCampaignStopReason,
    InstrumentExecutionDisposition, InstrumentExecutionError, InstrumentExecutionFailure,
    InstrumentExecutionMode, InstrumentExecutionRequest, InstrumentExecutionResult,
    InstrumentExecutionRun, InstrumentExecutionStopReason, InstrumentExecutor,
    InstrumentFleetAssignment, InstrumentFleetBlockedTask, InstrumentFleetDisposition,
    InstrumentFleetExecution, InstrumentFleetExecutionDisposition, InstrumentFleetExecutionError,
    InstrumentFleetExecutionFailure, InstrumentFleetExecutionRequest,
    InstrumentFleetExecutionResult, InstrumentFleetExecutionRunRequest,
    InstrumentFleetExecutionStopReason, InstrumentFleetResource, InstrumentFleetSchedule,
    InstrumentFleetScheduleRequest, InstrumentFleetSchedulerError, InstrumentFleetTask,
    InstrumentFleetUtilization, InstrumentInterlockSnapshot, InstrumentMultichannelConcordance,
    InstrumentOperatingCycle, InstrumentOperatingCycleDisposition, InstrumentOperatingCycleError,
    InstrumentOperatingCycleRequest, InstrumentOperation, InstrumentParameter,
    InstrumentPreflightDisposition, InstrumentPreflightError, InstrumentPreflightPlan,
    InstrumentPreflightRequest, InstrumentPreflightSummary, InstrumentResearchFrontier,
    InstrumentResearchFrontierDisposition, InstrumentResearchFrontierError,
    InstrumentResearchFrontierRequest, InstrumentResearchFrontierRun, InstrumentScienceLoop,
    InstrumentScienceLoopDisposition, InstrumentScienceLoopError, InstrumentScienceLoopRequest,
    InstrumentSignalChannel, InstrumentSignalExtraction, InstrumentSignalPeak,
    InstrumentSignalPoint, InstrumentSignalRun, InterpretationEvidence,
    InterpretationEvidenceDirection, InterpretationEvidenceFamily, InterpretationFamilySummary,
    InterpretationOperatingCycleDisposition, InterpretationSynthesis,
    InterpretationSynthesisDisposition, InterpretationSynthesisError,
    InterpretationSynthesisRequest, InvarianceMechanism, KnowledgeActionBridge,
    KnowledgeActionBridgeError, KnowledgeActionBridgeRequest, KnowledgeActionCompilerError,
    KnowledgeActionCompilerRequest, KnowledgeActionDispatchDisposition,
    KnowledgeActionDispatchError, KnowledgeActionDispatchRequest, KnowledgeActionDispatchResult,
    KnowledgeActionDispatchRun, KnowledgeActionExecutionFailure, KnowledgeActionExecutor,
    KnowledgeActionPlan, KnowledgeActionPlanDisposition, KnowledgeActionResultDisposition,
    KnowledgeActionSelectionCycle, KnowledgeActionSelectionCycleError,
    KnowledgeActionSelectionCycleRequest, KnowledgeActionTemplate, KnowledgeClaim,
    KnowledgeClaimClosure, KnowledgeClaimDisposition, KnowledgeClosure,
    KnowledgeClosureClaimDisposition, KnowledgeClosureDisposition, KnowledgeClosureError,
    KnowledgeClosureRequest, KnowledgeComponentDisposition, KnowledgeComposition,
    KnowledgeCompositionComponent, KnowledgeCompositionDisposition, KnowledgeCompositionError,
    KnowledgeCompositionPath, KnowledgeCompositionRequest, KnowledgeConsistencyClaimDisposition,
    KnowledgeConsistencyClaimScore, KnowledgeConsistencyClosure, KnowledgeConsistencyDisposition,
    KnowledgeConsistencyError, KnowledgeConsistencyRequest, KnowledgeDisposition, KnowledgeDrift,
    KnowledgeDriftAction, KnowledgeDriftDisposition, KnowledgeDriftError, KnowledgeDriftKind,
    KnowledgeDriftRequest, KnowledgeError, KnowledgeFrontier, KnowledgeFrontierDisposition,
    KnowledgeFrontierError, KnowledgeFrontierRequest, KnowledgeFrontierScore,
    KnowledgeFrontierWeights, KnowledgeGapClaimMapping, KnowledgeGapCompilerError,
    KnowledgeGapCompilerRequest, KnowledgeGapPortfolio, KnowledgeGapPortfolioDisposition,
    KnowledgeGapSourceTemplate, KnowledgePathDisposition, KnowledgeRelation, KnowledgeRelationKind,
    KnowledgeRequest, KnowledgeResolutionCampaign, KnowledgeResolutionCampaignDisposition,
    KnowledgeResolutionCampaignError, KnowledgeResolutionCampaignExecutor,
    KnowledgeResolutionCampaignRequest, KnowledgeResolutionCampaignRound,
    KnowledgeResolutionCampaignStopReason, KnowledgeResolutionExecutionFailure,
    KnowledgeSynthesisOperatingCycle, KnowledgeSynthesisOperatingCycleDisposition,
    KnowledgeSynthesisOperatingCycleError, KnowledgeSynthesisOperatingCycleRequest,
    LatentFactorAnalysis, LatentFactorComponent, LatentFactorDisposition, LatentFactorError,
    LatentFactorRequest, LatentFactorVector, LatentLoading, LatentScore, LigandReceptorPair,
    LocalResearchWorkflow, LocalWorkflowDisposition, LocalWorkflowError, LocalWorkflowRequest,
    LocalWorkflowStep, MechanismActionPlan, MechanismActionPlannerConfig,
    MechanismActionPlannerError, MechanismBayesianUpdate, MechanismCalibration,
    MechanismCalibrationBin, MechanismCalibrationError, MechanismCalibrationObservation,
    MechanismCalibrationRequest, MechanismCalibrationScore, MechanismCalibrationScoreDisposition,
    MechanismCampaignDisposition, MechanismCampaignError, MechanismCampaignExecutionDisposition,
    MechanismCandidate, MechanismConsensus, MechanismConsensusDisposition, MechanismConsensusError,
    MechanismConsensusRecord, MechanismConsensusRequest, MechanismCounterfactual,
    MechanismCounterfactualEnsemble, MechanismDiscrimination, MechanismDiscriminationCampaign,
    MechanismDiscriminationCampaignDisposition, MechanismDiscriminationCampaignError,
    MechanismDiscriminationCampaignExecutionFailure, MechanismDiscriminationCampaignExecutor,
    MechanismDiscriminationCampaignRequest, MechanismDiscriminationCampaignRound,
    MechanismDiscriminationCampaignStopReason, MechanismDiscriminationDisposition,
    MechanismDiscriminationError, MechanismDiscriminationRanking, MechanismDiscriminationRequest,
    MechanismDiscriminatorAction, MechanismDynamicsDisposition, MechanismDynamicsEdge,
    MechanismDynamicsError, MechanismDynamicsIntervention, MechanismDynamicsNode,
    MechanismDynamicsPlan, MechanismDynamicsRequest, MechanismDynamicsSensitivity,
    MechanismDynamicsState, MechanismDynamicsStep, MechanismEvidencePacket,
    MechanismFeatureObservation, MechanismGraphDisposition, MechanismGraphEdge,
    MechanismGraphError, MechanismGraphNode, MechanismGraphPropagation, MechanismGraphRelation,
    MechanismGraphRequest, MechanismHypothesis, MechanismIdentifiability,
    MechanismIdentifiabilityDisposition, MechanismIdentifiabilityError,
    MechanismIdentifiabilityRequest, MechanismInformationGain, MechanismInterventionCandidate,
    MechanismInterventionPrediction, MechanismInterventionValue,
    MechanismInterventionValueDisposition, MechanismInterventionValueError,
    MechanismInterventionValueRequest, MechanismInterventionValueScore, MechanismInvariance,
    MechanismInvarianceContext, MechanismInvarianceDisposition, MechanismInvarianceError,
    MechanismInvariancePair, MechanismInvarianceRequest, MechanismInvarianceSignatureScore,
    MechanismInvarianceUtility, MechanismNodeScore, MechanismOperatingCycle,
    MechanismOperatingCycleDisposition, MechanismOperatingCycleError,
    MechanismOperatingCycleRequest, MechanismPairIdentifiability, MechanismPortfolio,
    MechanismPrediction, MechanismRequest, MechanismSignature, MechanismSourceAgreement,
    MechanismStateFilterDisposition, MechanismStateFilterError, MechanismStateFilterRequest,
    MechanismStateFilterResult, MechanismStateModel, MechanismStateObservation,
    MechanismStatePosterior, MechanismStateSmoothPosterior, MechanismStateSmootherDisposition,
    MechanismStateSmootherError, MechanismStateSmootherRequest, MechanismStateSmootherResult,
    MechanismStateTransitionSupport, MechanismValidationArm, MechanismValidationDisposition,
    MechanismValidationError, MechanismValidationExecution,
    MechanismValidationExecutionDisposition, MechanismValidationExecutionError,
    MechanismValidationExecutionRequest, MechanismValidationPlan, MechanismValidationPlanRequest,
    MechanismValidationProtocolCompilation, MechanismValidationProtocolCompileRequest,
    MechanismValidationProtocolDisposition, MechanismValidationProtocolError, MediationAnalysis,
    MediationDisposition, MediationError, MediationObservation, MediationRequest,
    MetaAnalysisDisposition, MetaAnalysisError, MetaAnalysisRequest, MetaStudyContribution,
    MissingnessAudit, MissingnessAuditDisposition, MissingnessAuditError, MissingnessAuditRequest,
    MissingnessModalitySummary, MissingnessObservation, MissingnessPairSummary, MissingnessPattern,
    MissingnessPatternDisposition, MissingnessState, ModalityCapability, ModalityConcordance,
    ModalityPairAdjudication, ModalityPortfolioAlternative, ModalityPortfolioDisposition,
    ModalityPortfolioError, ModalityPortfolioPlan, ModalityPortfolioRequest,
    ModalityQualityForecast, ModalityVector, MultiFidelityCampaign,
    MultiFidelityCampaignDisposition, MultiFidelityCampaignError, MultiFidelityCampaignExecutor,
    MultiFidelityCampaignRequest, MultiFidelityCampaignRound, MultiFidelityCampaignStopReason,
    MultiFidelityDisposition, MultiFidelityExecutionFailure, MultiFidelityOptimizationError,
    MultiFidelityOptimizationPlan, MultiFidelityOptimizationRequest, MultiStudyClaimDisposition,
    MultiStudyKnowledge, MultiStudyKnowledgeDisposition, MultiStudyKnowledgeError,
    MultiStudyKnowledgeRequest, MultiStudyKnowledgeRow, MultichannelConcordanceDisposition,
    MultichannelConcordanceError, MultichannelConcordanceRequest, MultichannelInput,
    MultichannelPoint, MultimodalConcordance, MultimodalConsensus, MultimodalDecisionGateAnalysis,
    MultimodalDecisionGateDisposition, MultimodalDecisionGateError, MultimodalDecisionGateRequest,
    MultimodalExecutionMode, MultimodalHarmonization, MultimodalIngestionCampaign,
    MultimodalIngestionCampaignDisposition, MultimodalIngestionCampaignError,
    MultimodalIngestionCampaignExecutor, MultimodalIngestionCampaignRequest,
    MultimodalIngestionCampaignRound, MultimodalIngestionCampaignStopReason,
    MultimodalIngestionExecutionFailure, MultimodalMechanismCampaign,
    MultimodalMechanismCampaignExecution, MultimodalMechanismCampaignRequest,
    MultimodalObservation, MultimodalQcReport, MultimodalReadinessError,
    MultimodalReadinessRequest, MultimodalRequest, MultimodalResearchReadiness,
    MultimodalResearchReadinessDisposition, MultimodalResearchSurface, MultimodalSurfaceDecision,
    MultimodalSurfaceReadiness, OptimizationDirection, PairConcordanceDisposition, PanelAction,
    PanelMechanism, PanelOutcome, PathwayActivityAnalysis, PathwayActivityDefinition,
    PathwayActivityDirection, PathwayActivityDisposition, PathwayActivityEdge,
    PathwayActivityError, PathwayActivityNode, PathwayActivityObservation, PathwayActivityRecord,
    PathwayActivityRequest, PortfolioDirection, PowerArmDecision, PowerArmObservation,
    PowerDecisionKind, PowerReestimationDisposition, PowerReestimationError, PowerReestimationPlan,
    PowerReestimationRequest, PowerStressArm, PowerStressArmResult, PowerStressDisposition,
    PowerStressError, PowerStressScenario, PowerStressScenarioResult, PowerStressSurface,
    PowerStressSurfaceRequest, ProgramExecutionMode, ProgramGate, ProgramGateStatus,
    ProspectiveKnowledgeAlert, ProspectiveKnowledgeDisposition, ProspectiveKnowledgeError,
    ProspectiveKnowledgeEvent, ProspectiveKnowledgeMonitor, ProspectiveKnowledgeRequest,
    ProspectiveKnowledgeRow, ProspectiveKnowledgeTrend, ProspectiveQualityError,
    ProspectiveQualityForecast, ProspectiveQualityRequest, ProtocolBranchCandidate,
    ProtocolBranchEvaluation, ProtocolBranchOptimizationDisposition,
    ProtocolBranchOptimizationError, ProtocolBranchOptimizationPlan,
    ProtocolBranchOptimizationRequest, ProtocolBranchWeights, ProtocolCompensationCandidate,
    ProtocolCompensationDisposition, ProtocolCompensationError, ProtocolCompensationPlan,
    ProtocolCompensationRequest, ProtocolCompensationSelection, ProtocolDisposition,
    ProtocolEvidenceCell, ProtocolEvidenceDisposition, ProtocolEvidenceFusion,
    ProtocolEvidenceFusionDisposition, ProtocolEvidenceFusionError, ProtocolEvidenceFusionRequest,
    ProtocolEvidenceStudySurface, ProtocolEvidenceSurface, ProtocolEvidenceSurfaceDisposition,
    ProtocolEvidenceSurfaceError, ProtocolEvidenceSurfaceRequest, ProtocolExecution,
    ProtocolExecutionDisposition, ProtocolExecutionError, ProtocolExecutionFailure,
    ProtocolExecutionRequest, ProtocolExecutionStopReason, ProtocolFusionCell,
    ProtocolFusionDisposition, ProtocolMeasurement, ProtocolResource, ProtocolResourceKind,
    ProtocolScenario, ProtocolScenarioEnsemble, ProtocolScenarioEnsembleDisposition,
    ProtocolScenarioEnsembleError, ProtocolScenarioEnsembleRequest, ProtocolScenarioResult,
    ProtocolSimulation, ProtocolSimulationError, ProtocolSimulationRequest, ProtocolTask,
    ProtocolTaskDisposition, ProtocolTaskResult, ProtocolTransportEndpoint,
    ProtocolTransportEndpointDisposition, ProtocolTransportGate, ProtocolTransportGateDisposition,
    ProtocolTransportGateError, ProtocolTransportGateRequest, QualityAcquisitionCandidate,
    QualityAdaptiveCampaign, QualityAdaptiveCampaignDisposition, QualityAdaptiveCampaignError,
    QualityAdaptiveCampaignRequest, QualityAdaptiveCampaignRound,
    QualityAdaptiveCampaignStopReason, QualityExecutionApproval, QualityExecutionDisposition,
    QualityExecutionError, QualityExecutionFailure, QualityExecutionMode,
    QualityExecutionObservation, QualityExecutionRequest, QualityExecutionResult,
    QualityExecutionRun, QualityExecutionStopReason, QualityForecastDisposition,
    QualityForecastObservation, QualityIncidentSignal, QualityRecoveryCampaignDisposition,
    QualityRecoveryError, QualityRecoveryModalityDisposition, QualityRecoveryModalityResult,
    QualityRecoveryObservation, QualityRecoveryPhase, QualityRecoveryRequest,
    QualityRecoveryResult, QualityRemediationActionKind, QualityRemediationCandidate,
    QualityRemediationDisposition, QualityRemediationError, QualityRemediationPlan,
    QualityRemediationRequest, QualityRemediationStep, QualityRootCause,
    QualityRootCauseAttribution, QualityRootCauseAttributionResult,
    QualityRootCauseCampaignDisposition, QualityRootCauseDisposition, QualityRootCauseError,
    QualityRootCauseRequest, QualityRunDisposition, QualityScheduleAlternative,
    QualityScheduleDisposition, QualityScheduleError, QualityScheduleExecutor, QualityScheduleItem,
    QualitySchedulePlan, QualityScheduleRequest, QualitySignalScope, QualityTransportCalibration,
    QualityTransportCell, QualityTransportDisposition, QualityTransportError,
    QualityTransportModalityDisposition, QualityTransportModalitySummary, QualityTransportRequest,
    RandomizationArm, RandomizationBlock, RegisteredSpatialCell, RegistrationLandmark,
    ReleaseExecutionMode, ReleaseGateError, ReleaseGateEvaluation, ReleaseGateRequest,
    ReleaseGateStatus, ReleaseReviewAttestation, ReleaseReviewDecision, ReliabilityCalibration,
    ReliabilityCalibrationError, ReliabilityCalibrationRequest, ReliabilityDisposition,
    ReliabilityModalitySummary, ReliabilityObservation, ReplayCampaign, ReplayCampaignDisposition,
    ReplayCampaignError, ReplayCampaignExecutor, ReplayCampaignRequest, ReplayCampaignRound,
    ReplayCampaignStopReason, ReplayExecutionFailure, ReplayObservation, ReplayObservationStatus,
    ReplayTask, ReplicationAggregateQuality, ReplicationAssessment,
    ReplicationClosureCampaignDisposition, ReplicationClosureCampaignError,
    ReplicationClosureCampaignRequest, ReplicationClosureCampaignRound,
    ReplicationClosureCampaignRun, ReplicationClosureCampaignStopReason,
    ReplicationClosureCandidate, ReplicationClosureDisposition,
    ReplicationClosureExecutionDisposition, ReplicationClosureExecutionError,
    ReplicationClosureExecutionRequest, ReplicationClosureExecutionRun, ReplicationClosureFrontier,
    ReplicationClosureFrontierError, ReplicationClosureFrontierRequest, ReplicationClosureScore,
    ReplicationClosureTarget, ReplicationContinuationAction, ReplicationContinuationDisposition,
    ReplicationContinuationError, ReplicationContinuationObservation, ReplicationContinuationPlan,
    ReplicationContinuationRequest, ReplicationContinuationSiteAction, ReplicationMetaAnalysis,
    ReplicationObservation, ReplicationPlan, ReplicationPlanDisposition, ReplicationPlanError,
    ReplicationPlanRequest, ReplicationProtocolCompilation,
    ReplicationProtocolCompilationDisposition, ReplicationProtocolCompilationError,
    ReplicationProtocolCompileRequest, ReplicationRequest, ReplicationSiteAction,
    ReplicationSitePlan, ReplicationStudy, ResearchObjectManifest, ResearchObjectRequest,
    ResourceUtilization, RobustActiveLearningCampaign, RobustActiveLearningCampaignDisposition,
    RobustActiveLearningCampaignError, RobustActiveLearningCampaignExecutor,
    RobustActiveLearningCampaignRequest, RobustActiveLearningCampaignRound,
    RobustActiveLearningCampaignStopReason, RobustActiveLearningCandidate,
    RobustActiveLearningCandidateDisposition, RobustActiveLearningDisposition,
    RobustActiveLearningError, RobustActiveLearningExecutionFailure, RobustActiveLearningModel,
    RobustActiveLearningObservation, RobustActiveLearningPlan, RobustActiveLearningRequest,
    RobustActiveLearningScore, RobustCandidateAllocation, RobustDesignActionKind,
    RobustDesignCandidate, RobustDesignScenario, RobustExperimentDesign,
    RobustExperimentDesignDisposition, RobustExperimentDesignError, RobustExperimentDesignRequest,
    RobustInterventionCandidate, RobustInterventionPortfolio, RobustInterventionRequest,
    RobustInterventionScore, RobustPortfolioDisposition, RobustPortfolioError, RobustnessCase,
    RobustnessCaseKind, RobustnessDisposition, RobustnessError, RobustnessGuidedCandidate,
    RobustnessGuidedCandidateScore, RobustnessGuidedComputation,
    RobustnessGuidedComputationDisposition, RobustnessGuidedComputationError,
    RobustnessGuidedComputationRequest, RobustnessRequest, RobustnessSuite, SampleRegistration,
    SampleRegistrationDisposition, SampleTimepoint, ScenarioFailureClass, ScheduleEntry,
    SchedulerDecision, SchedulerObservation, SchedulerOutcome, ScientificFrontierDisposition,
    ScientificFrontierError, ScientificFrontierExecution, ScientificFrontierExecutionDisposition,
    ScientificFrontierExecutionError, ScientificFrontierExecutionRequest, ScientificFrontierPlan,
    ScientificFrontierRequest, SensitivityDirection, SensitivityDisposition, SensitivityError,
    SensitivityObservation, SensitivityPoint, SensitivityRequest, SequentialArmDecision,
    SequentialArmObservation, SequentialBatchObservation, SequentialCampaign,
    SequentialCampaignDisposition, SequentialCampaignError, SequentialCampaignExecutionFailure,
    SequentialCampaignExecutor, SequentialCampaignRequest, SequentialCampaignRound,
    SequentialCampaignStopReason, SequentialDecisionKind, SequentialDesignDisposition,
    SequentialDesignError, SequentialDesignPlan, SequentialDesignRequest, SequentialDesignRound,
    SignalBatchStabilityRequest, SignalChannelDisposition, SignalExtractionDisposition,
    SignalExtractionError, SignalExtractionRequest, SourceCalibration,
    SourceCalibrationDisposition, SpatialCell, SpatialCommunicationAnalysis,
    SpatialCommunicationCell, SpatialCommunicationDisposition, SpatialCommunicationError,
    SpatialCommunicationPair, SpatialCommunicationPairDisposition, SpatialCommunicationRequest,
    SpatialNiche, SpatialNicheAnalysis, SpatialNicheDisposition, SpatialNicheError,
    SpatialNicheInteraction, SpatialNicheRequest, SpatialPropagationAnalysis,
    SpatialPropagationDisposition, SpatialPropagationEdge, SpatialPropagationError,
    SpatialPropagationRequest, SpatialPropagationTrajectory, SpatialRegistrationAnalysis,
    SpatialRegistrationCell, SpatialRegistrationDisposition, SpatialRegistrationError,
    SpatialRegistrationRequest, StateTransitionAnalysis, StateTransitionCell,
    StateTransitionContrast, StateTransitionDisposition, StateTransitionError,
    StateTransitionObservation, StateTransitionRequest, StaticGliomaActionPlanner,
    StaticGliomaComputationPlanner, StratifiedCausalActionKind, StratifiedCausalAdjustment,
    StratifiedCausalDisposition, StratifiedCausalError, StratifiedCausalRequest,
    StratifiedObservation, StudyClaimBinding, StudyClaimObservation, StudyKnowledgeSnapshot,
    TemporalFusionAnalysis, TemporalFusionDisposition, TemporalFusionError, TemporalFusionRequest,
    TemporalObservation, TemporalSpatialAlignmentRequest, TemporalState, TemporalStateFeature,
    TemporalTransition, TemporalTransitionDirection, TrajectoryAnalysis, TrajectoryArmSummary,
    TrajectoryDisposition, TrajectoryError, TrajectoryObservation, TrajectoryRequest,
    TransitionCellDisposition, TransitionContrastDisposition, TransitionDirection, TransportStudy,
    TransportStudyContribution, TransportabilityAnalysis, TransportabilityDisposition,
    TransportabilityError, TransportabilityRequest, TriangulatedClaim, TriangulatedClaimVerdict,
    TypedKnowledge, UnitContrast, UnitTrajectory, UnitTrajectoryDisposition, ValidationAction,
    ValidationActionKind, ValidationArmRole, ValidationBatchAssessment,
    ValidationBatchAssessmentDisposition, ValidationBatchAssessmentError,
    ValidationBatchAssessmentRequest, ValidationCampaignDisposition, ValidationCampaignError,
    ValidationCampaignRequest, ValidationCampaignRound, ValidationCampaignRun,
    ValidationCampaignStopReason, ValidationReplicationCampaignDisposition,
    ValidationReplicationCampaignError, ValidationReplicationCampaignRequest,
    ValidationReplicationCampaignRun, ValidationReplicationGate,
    ValidationReplicationGateDisposition, ValidationReplicationGateError,
    ValidationReplicationGateRequest, ValidationReplicationTransportDisposition,
    ValidationReplicationTransportError, ValidationReplicationTransportRequest,
    ValidationReplicationTransportRun, WorkflowNodeDecision, EXECUTION_OUTPUT_SCHEMA,
    PROTOCOL_EXECUTION_OUTPUT_SCHEMA,
};
pub use glioma_engine::{
    compile_glioma_research, dry_run_glioma_research, execute_glioma_research,
    glioma_research_engine_manifest, select_glioma_actions, DryRunGliomaExecutor,
    GliomaActionCandidate, GliomaActionDecision, GliomaActionSelection, GliomaEngineError,
    GliomaExecutionReceipt, GliomaModality, GliomaModelSystem, GliomaPlanDisposition,
    GliomaResearchIntent, GliomaResearchPlan, GliomaSelectionConfig, GliomaSelectionWeights,
    GliomaStage, GliomaStageDisposition, GliomaStageExecution, GliomaStageExecutor,
    GliomaStageFailure, GliomaStageInput, GliomaStageKind, LocalArtifactRef, StageReadiness,
    ACTION_SELECTION_OUTPUT_SCHEMA as GLIOMA_ACTION_SELECTION_OUTPUT_SCHEMA,
    CONTRACT_VERSION as GLIOMA_ENGINE_CONTRACT_VERSION, FEATURE_ID as GLIOMA_ENGINE_FEATURE_ID,
};
pub use protocol::{plan_protocol, ProtocolStep, ResearchProtocol};
pub use report::{render_report, RenderedReport};
pub use request::{
    ResearchRequest, ResearchRequestDocument, WorldFamily, MAX_DISTRACTORS_PER_POINT,
    MAX_DISTRACTOR_POINTS, MAX_QUESTION_BYTES, MAX_RESEARCH_ID_CHARS,
};
pub use runner::{run_research, PINNED_REFERENCE_CERTIFICATE_SHA256, UNSWEPT_KNOBS_CAVEAT};
