//! Autonomous research protocol runners: a validated request in, a digested dossier or a
//! domain-specific execution plan out — with every finding derived by a fixed rule from a cited
//! measurement.
//!
//! The original runner remains autonomous **measurement science over synthetic decision worlds** —
//! committed fixtures and seeded generators. [`glioma_engine`] adds a second production surface:
//! a preclinical glioma program planner and execution loop that delegates real work to
//! caller-owned local providers. The blueprint does not specify either runner; their request,
//! workflow, artifact and report schemas are this crate's design, stated as such. What the
//! synthetic steps *measure* is specified, and each step calls the crate that owns it: 43.26
//! context certificates via `bioprism-fiber`, the 43.38
//! equal-engineering comparison and the 43.39 structural families and sweep via
//! `bioprism-baseline`/`bioprism-worldgen`, the 03.08/32 metamorphic suite via
//! `bioprism-mutation`, and the 1-minimal reduction (in 43.40/43.41's refusal vocabulary) via
//! `bioprism-prism`. This crate adds orchestration and receipts, never measurement logic.
//!
//! # The honesty rules this crate is built around
//!
//! - **The question is never interpreted.** A [`ResearchRequest`] records its free-text question
//!   verbatim; the protocol is planned from the *other* fields alone, and no code path anywhere
//!   in this crate branches on the question's content. The runner executes the protocol; it does
//!   not understand the question.
//! - **Findings are derived, never free-generated.** Every [`Finding`] comes from one of the
//!   fixed rules in [`findings`], is levelled [`ObservationLevel::Observation`] — a
//!   single-variant enum, so no other level is representable — and cites the content digests of
//!   the artifacts it was derived from.
//! - **Negative findings are first-class.** A tie between the compiler and a baseline is a
//!   *required* finding, flagged `negative: true` and rendered in the same register as any
//!   positive result. The repository's own headline finding is a tie.
//! - **Every dossier anchors to the pinned parity digest.** Step 0 compiles the committed
//!   `fixtures/fiber-v0.1` pair (embedded at build time) and aborts unless the certificate digest
//!   is [`PINNED_REFERENCE_CERTIFICATE_SHA256`], the value CPython, the eager Rust path, and the
//!   indexed store agree on.
//! - **Partial protocols are unrepresentable.** A step that cannot complete is a typed
//!   [`ResearchError`]; [`dossier::StepOutcome`] has exactly one variant, so an emitted dossier
//!   cannot claim a step it did not finish.
//! - **The dossier is tamper-evident.** `dossier_sha256` is computed over the canonical document
//!   with the digest field removed; [`verify_dossier`] recomputes it, checks the 64-hex shape
//!   separately from mismatch, and checks that every finding's supporting digests actually name
//!   artifacts the dossier carries.
//!
//! # Boundary
//!
//! Research and developer infrastructure: it does not diagnose an individual, recommend
//! treatment, triage care, enroll participants, or claim medical-device functionality. It can
//! never claim biology or medicine, literature or prior-work coverage, external-world
//! observation, or release-level claims from fixture evidence. Oracle review is a human gate.
//! These sentences also ship inside every dossier as [`REQUIRED_LIMITATIONS`].
//!
//! # Not implemented
//!
//! - **No question understanding.** The question is recorded and rendered verbatim, digested,
//!   and never parsed, matched, or routed on. There is no NLP anywhere in this crate.
//! - **No literature fetching in the synthetic runner.** Nothing in that runner searches, cites,
//!   or claims coverage of prior work. The glioma engine accepts literature and other evidence as
//!   caller-supplied local artifact references and delegates retrieval to a provider.
//! - **No recurrence in the synthetic runner.** One request runs one protocol to one dossier in
//!   one call. The glioma engine provides bounded stage retries and checkpoints, but recurrence
//!   scheduling is still owned by the host.
//! - **No wall-clock.** No timestamps, durations, or dates appear in any artifact; determinism
//!   is byte-for-byte and the only order is protocol order.
//! - **No oracle acceptance.** The runner emits observations for human review and accepts,
//!   approves, and releases nothing.
//! - **Figures are static SVG only**, rendered by `bioprism-figures`: no raster, no scripts, no
//!   interactivity.
//! - **No I/O.** Fixtures are compiled in; the caller writes the dossier, report, and figures
//!   wherever they belong.
//! - **No generator knobs beyond the presets.** A request chooses one committed 43.39 family,
//!   one seed, and up to six distractor counts; skeleton, events, protected set, decision time,
//!   and policy stay at each preset's committed values, and the sweep runs the committed default
//!   grid at the grid's own seed.

pub mod dossier;
pub mod error;
pub mod findings;
pub mod glioma;
pub mod glioma_engine;
pub mod protocol;
pub mod report;
pub mod request;
pub mod runner;

pub use dossier::{
    artifact_record, build_dossier, verify_dossier, RecordedArtifact, StepOutcome, DOSSIER_SCHEMA,
    INLINE_ARTIFACT_CAP_BYTES, REQUIRED_LIMITATIONS,
};
pub use error::ResearchError;
pub use findings::{
    comparison_findings, minimization_findings, mutation_findings, reference_anchor_finding,
    sweep_findings, Finding, ObservationLevel,
};
pub use glioma::{
    adjudicate_glioma_assay_evidence, allocate_glioma_assays, analyze_causal_sensitivity,
    analyze_federated_benchmark, analyze_federated_mechanism_transport,
    analyze_glioma_causal_contrast, analyze_glioma_clonal_evolution,
    analyze_glioma_clone_panel_outcomes, analyze_glioma_combination_synergy,
    analyze_glioma_dose_response, analyze_glioma_latent_factors, analyze_glioma_mediation,
    analyze_glioma_multimodal_decision_gate, analyze_glioma_multimodal_dropout_stress,
    analyze_glioma_multimodal_evidence_fusion, analyze_glioma_multimodal_graph_fusion,
    analyze_glioma_multimodal_missingness, analyze_glioma_multimodal_sensitivity,
    analyze_glioma_pathway_activity, analyze_glioma_spatial_communication,
    analyze_glioma_spatial_niches, analyze_glioma_spatial_state_propagation,
    analyze_glioma_state_transitions, analyze_glioma_temporal_multimodal_fusion,
    analyze_glioma_temporal_spatial_alignment, analyze_glioma_trajectories,
    analyze_glioma_transportability, analyze_instrument_calibration,
    analyze_multimodal_concordance, analyze_multimodal_consensus, analyze_preclinical_outcomes,
    analyze_replication_meta_analysis, analyze_stratified_causal_adjustment,
    assess_glioma_robustness, assess_replication, bridge_glioma_knowledge_actions,
    build_research_object_manifest, calibrate_glioma_evidence, calibrate_glioma_mechanisms,
    calibrate_glioma_multimodal_reliability, certify_decision_omissions,
    compile_decision_action_graph, compile_decision_context, compile_glioma_computation_workflow,
    compile_glioma_intent_mission_candidates, compile_glioma_knowledge_actions,
    compile_glioma_knowledge_gaps, compile_glioma_multimodal_mission_candidates,
    compile_glioma_protocol_evidence_surface, compile_mechanism_action_plan,
    compile_typed_knowledge, compose_knowledge_graph, design_glioma_contrast_panel,
    design_glioma_robust_experiment, design_preclinical_experiment, discriminate_mechanisms,
    dry_run_adaptive_instrument_executor, dry_run_glioma_adaptive_frontier_executor,
    dry_run_instrument_executor_from_request, dry_run_robustness_guided_computation_executor,
    evaluate_glioma_dynamic_policies, evaluate_glioma_release_gate,
    execute_federated_benchmark_adaptive_campaign,
    execute_federated_benchmark_adaptive_campaign_dry_run, execute_federated_benchmark_campaign,
    execute_federated_benchmark_operating_cycle,
    execute_federated_benchmark_operating_cycle_dry_run,
    execute_federated_mechanism_transport_campaign,
    execute_federated_mechanism_transport_campaign_dry_run, execute_glioma_action_portfolio,
    execute_glioma_active_learning_campaign, execute_glioma_adaptive_allocation_campaign,
    execute_glioma_adaptive_clone_campaign, execute_glioma_adaptive_clone_campaign_dry_run,
    execute_glioma_adaptive_decision_branch_campaign,
    execute_glioma_adaptive_decision_branch_campaign_dry_run, execute_glioma_adaptive_frontier,
    execute_glioma_adaptive_information_campaign, execute_glioma_adaptive_instrument_campaign,
    execute_glioma_adaptive_interpretation_campaign,
    execute_glioma_adaptive_interpretation_campaign_dry_run,
    execute_glioma_adaptive_mechanism_campaign, execute_glioma_autonomous_campaign,
    execute_glioma_autonomous_gap_cycle, execute_glioma_autonomous_program_cycle,
    execute_glioma_autonomous_protocol, execute_glioma_autonomous_research_engine,
    execute_glioma_autonomous_research_mission, execute_glioma_calibrated_mechanism_campaign,
    execute_glioma_calibrated_mechanism_campaign_dry_run, execute_glioma_causal_claim_adjudication,
    execute_glioma_computation, execute_glioma_computation_campaign,
    execute_glioma_computation_operating_cycle, execute_glioma_computation_operating_cycle_dry_run,
    execute_glioma_computation_portfolio, execute_glioma_computation_recovery,
    execute_glioma_decision_branch_campaign, execute_glioma_decision_context_campaign,
    execute_glioma_decision_operating_cycle, execute_glioma_evidence_acquisition_campaign,
    execute_glioma_evidence_campaign, execute_glioma_evidence_gated_research,
    execute_glioma_evidence_operating_cycle, execute_glioma_evidence_operating_cycle_dry_run,
    execute_glioma_evidence_refresh_campaign, execute_glioma_experiment_frontier_controller,
    execute_glioma_experiment_operating_cycle, execute_glioma_instrument_campaign,
    execute_glioma_instrument_fleet, execute_glioma_instrument_operating_cycle,
    execute_glioma_instrument_plan, execute_glioma_instrument_science_loop,
    execute_glioma_intent_mission, execute_glioma_interpretation_operating_cycle,
    execute_glioma_knowledge_action_dispatch, execute_glioma_knowledge_resolution_campaign,
    execute_glioma_knowledge_selection_cycle, execute_glioma_knowledge_synthesis_operating_cycle,
    execute_glioma_mechanism_autopilot, execute_glioma_mechanism_discovery_engine,
    execute_glioma_mechanism_discrimination_campaign, execute_glioma_mechanism_operating_cycle,
    execute_glioma_mission_recovery, execute_glioma_multi_fidelity_campaign,
    execute_glioma_multimodal_ingestion_campaign, execute_glioma_multimodal_mechanism_campaign,
    execute_glioma_multimodal_mechanism_campaign_with_executor, execute_glioma_multimodal_mission,
    execute_glioma_multimodal_operating_cycle, execute_glioma_multimodal_operating_cycle_dry_run,
    execute_glioma_multimodal_readiness_gate, execute_glioma_program_scheduler,
    execute_glioma_program_scheduler_dry_run, execute_glioma_protocol,
    execute_glioma_release_operating_cycle, execute_glioma_release_operating_cycle_dry_run,
    execute_glioma_replay_campaign, execute_glioma_replication_campaign,
    execute_glioma_research_autopilot, execute_glioma_research_director,
    execute_glioma_robust_active_learning_campaign, execute_glioma_robustness_guided_computation,
    execute_glioma_scientific_frontier, execute_glioma_sequential_campaign,
    execute_glioma_workflow, explore_mechanisms, fuse_glioma_protocol_evidence,
    gate_glioma_protocol_transport, generate_feature_catalog, glioma_program_catalog,
    harmonize_glioma_multimodal_batches, harmonize_multimodal_inputs, implemented_feature_ids,
    materialize_glioma_protocol_branch, optimize_glioma_protocol_branches,
    plan_adaptive_glioma_dose_surface, plan_decision_actions, plan_federated_benchmark_sites,
    plan_glioma_active_learning, plan_glioma_adaptive_information_campaign,
    plan_glioma_adaptive_mechanism_policy, plan_glioma_adaptive_research_frontier,
    plan_glioma_adaptive_workflow, plan_glioma_clone_continuation,
    plan_glioma_clone_perturbation_panel, plan_glioma_closed_loop_campaign,
    plan_glioma_computation_portfolio, plan_glioma_decision_branches,
    plan_glioma_evidence_acquisition, plan_glioma_evidence_contradiction_cut,
    plan_glioma_information_design, plan_glioma_multi_fidelity_optimization,
    plan_glioma_multimodal_portfolio, plan_glioma_power_reestimation,
    plan_glioma_protocol_compensation, plan_glioma_research_director,
    plan_glioma_robust_active_learning, plan_glioma_robust_intervention_portfolio,
    plan_glioma_scientific_frontier, plan_glioma_sequential_design, plan_glioma_workflow,
    preflight_glioma_instrument, prioritize_glioma_evidence, prioritize_knowledge_frontier,
    propagate_glioma_mechanism_graph, protocol_request_from_experiment_design, qualify_evidence,
    register_glioma_spatial_samples, revise_glioma_beliefs, schedule_glioma_computation_placement,
    schedule_glioma_instrument_fleet, simulate_glioma_counterfactual,
    simulate_glioma_counterfactual_ensemble, simulate_glioma_mechanism_dynamics,
    simulate_glioma_protocol, surveil_glioma_evidence, surveil_glioma_multimodal_drift,
    synthesize_glioma_interpretation, triangulate_glioma_evidence,
    update_glioma_mechanism_posterior, validate_feature_catalog, ActionExecutionDisposition,
    ActionExecutionFailure, ActionExecutionResult, ActionPortfolioExecution,
    ActionPortfolioExecutionDisposition, ActionPortfolioExecutionError,
    ActionPortfolioExecutionRequest, ActionPortfolioStopReason, ActiveLearningCampaign,
    ActiveLearningCampaignDisposition, ActiveLearningCampaignError, ActiveLearningCampaignExecutor,
    ActiveLearningCampaignRequest, ActiveLearningCampaignRound, ActiveLearningCampaignStopReason,
    ActiveLearningCandidate, ActiveLearningCandidateDisposition, ActiveLearningDirection,
    ActiveLearningDisposition, ActiveLearningError, ActiveLearningExecutionFailure,
    ActiveLearningObservation, ActiveLearningPlan, ActiveLearningRequest, ActiveLearningScore,
    AdaptiveAllocation, AdaptiveAllocationActionKind, AdaptiveAllocationBatchObservation,
    AdaptiveAllocationCampaign, AdaptiveAllocationCampaignDisposition,
    AdaptiveAllocationCampaignError, AdaptiveAllocationCampaignExecutionFailure,
    AdaptiveAllocationCampaignExecutor, AdaptiveAllocationCampaignRequest,
    AdaptiveAllocationCampaignRound, AdaptiveAllocationCampaignStopReason,
    AdaptiveAllocationDisposition, AdaptiveAllocationError, AdaptiveAllocationRequest,
    AdaptiveArmObservation, AdaptiveArmPosterior, AdaptiveCloneCampaign,
    AdaptiveCloneCampaignDisposition, AdaptiveCloneCampaignError, AdaptiveCloneCampaignExecutor,
    AdaptiveCloneCampaignRequest, AdaptiveCloneCampaignRound, AdaptiveCloneCampaignStopReason,
    AdaptiveCloneExecutionFailure, AdaptiveDecisionBranchCampaign,
    AdaptiveDecisionBranchCampaignDisposition, AdaptiveDecisionBranchCampaignError,
    AdaptiveDecisionBranchCampaignRequest, AdaptiveDecisionBranchCampaignRound,
    AdaptiveDecisionBranchCampaignStopReason, AdaptiveDoseSurfaceDisposition,
    AdaptiveDoseSurfaceError, AdaptiveDoseSurfacePlan, AdaptiveDoseSurfaceRequest,
    AdaptiveFrontierCandidate, AdaptiveFrontierDisposition, AdaptiveFrontierError,
    AdaptiveFrontierExecution, AdaptiveFrontierExecutionDisposition,
    AdaptiveFrontierExecutionError, AdaptiveFrontierExecutionRequest, AdaptiveFrontierRequest,
    AdaptiveInformationCampaignDisposition, AdaptiveInformationCampaignError,
    AdaptiveInformationCampaignExecution, AdaptiveInformationCampaignPlan,
    AdaptiveInformationCampaignRequest, AdaptiveInformationCampaignRound,
    AdaptiveInformationCampaignTermination, AdaptiveInformationExecutionFailure,
    AdaptiveInformationObservation, AdaptiveInstrumentCampaign,
    AdaptiveInstrumentCampaignDisposition, AdaptiveInstrumentCampaignError,
    AdaptiveInstrumentCampaignRequest, AdaptiveInstrumentCandidate, AdaptiveInstrumentDecision,
    AdaptiveInterpretationCampaign, AdaptiveInterpretationCampaignDisposition,
    AdaptiveInterpretationCampaignError, AdaptiveInterpretationCampaignRequest,
    AdaptiveInterpretationCampaignRound, AdaptiveInterpretationCampaignStopReason,
    AdaptiveInterpretationPlanner, AdaptiveInterpretationPlanningFailure, AdaptiveMechanismAction,
    AdaptiveMechanismActionScore, AdaptiveMechanismCampaign, AdaptiveMechanismCampaignRequest,
    AdaptiveMechanismCampaignRound, AdaptiveMechanismCampaignStopReason,
    AdaptiveMechanismExecutionFailure, AdaptiveMechanismModel, AdaptiveMechanismObservation,
    AdaptiveMechanismPolicy, AdaptiveMechanismPolicyDisposition, AdaptiveMechanismPolicyError,
    AdaptiveMechanismPolicyExecutor, AdaptiveMechanismPolicyPosterior,
    AdaptiveMechanismPolicyRequest, AdaptiveMechanismPolicyStep, AdaptiveMechanismPosterior,
    AdaptiveMechanismPrediction, AdaptiveResearchFrontier, AdaptiveTarget, AnalysisDataset,
    AnalysisRequest, AnalysisResult, AssayEvidenceDisposition, AssayEvidenceError,
    AssayEvidenceObservation, AssayEvidenceRecord, AssayEvidenceRequest, AutonomousGapCycle,
    AutonomousGapCycleDisposition, AutonomousGapCycleError, AutonomousGapCycleRequest,
    AutonomousProgramCycle, AutonomousProgramCycleDisposition, AutonomousProgramCycleError,
    AutonomousProgramCycleRequest, AutonomousProtocolControllerDisposition,
    AutonomousProtocolControllerError, AutonomousProtocolControllerRequest,
    AutonomousProtocolControllerRun, AutonomousProtocolControllerStopReason,
    AutonomousProtocolRound, BatchHarmonizationDiagnostic, BayesianMechanismHypothesis,
    BayesianMechanismUpdateError, BayesianMechanismUpdateRequest, BayesianUpdateDisposition,
    BeliefConflict, BeliefRevision, BeliefRevisionDecision, BeliefRevisionDecisionKind,
    BeliefRevisionDisposition, BeliefRevisionError, BeliefRevisionRequest,
    BranchExecutionDisposition, BridgedKnowledgeCandidate, CalibratedMechanismActionScore,
    CalibratedMechanismCampaign, CalibratedMechanismCampaignDisposition,
    CalibratedMechanismCampaignError, CalibratedMechanismCampaignRequest,
    CalibratedMechanismCampaignRound, CalibratedMechanismCampaignStopReason,
    CalibratedMechanismTrust, CalibrationBin, CalibrationBinDisposition, CalibrationDisposition,
    CalibrationError, CalibrationPoint, CalibrationRequest, CalibrationRun, CampaignAction,
    CampaignActionScore, CampaignExecutionFailure, CampaignExecutionRound, CampaignMechanism,
    CampaignMechanismPosterior, CampaignObservation, CampaignRound, CampaignStopReason,
    CatalogError, CausalClaimDisposition, CausalContrastAnalysis, CausalContrastDisposition,
    CausalContrastError, CausalContrastRequest, CausalSensitivityAnalysis, CausalStratumSummary,
    ClaimActionKind, ClaimGate, ClaimGateDisposition, ClaimNextAction, ClonalEdge,
    ClonalEvolutionDisposition, ClonalEvolutionError, ClonalEvolutionGraph, ClonalEvolutionRequest,
    ClonalNode, ClonalRelation, CloneBranchCoverage, CloneContinuationActionKind,
    CloneContinuationActionStatus, CloneContinuationCandidate, CloneContinuationDecision,
    CloneContinuationDisposition, CloneContinuationError, CloneContinuationPlan,
    CloneContinuationRequest, CloneMarker, CloneMarkerState, ClonePanelBranchAnalysis,
    ClonePanelCandidateAnalysis, ClonePanelCellAnalysis, ClonePanelCellDisposition,
    ClonePanelMeasurementState, ClonePanelObservation, ClonePanelOutcomeAnalysis,
    ClonePanelOutcomeDisposition, ClonePanelOutcomeError, ClonePanelOutcomeRequest,
    ClonePerturbationCandidate, ClonePerturbationDecision, ClonePerturbationKind,
    ClonePerturbationPanel, ClonePerturbationPanelDisposition, ClonePerturbationPanelError,
    ClonePerturbationPanelRequest, CloneProfile, ClosedLoopCampaign, ClosedLoopCampaignDisposition,
    ClosedLoopCampaignError, ClosedLoopCampaignExecution, ClosedLoopCampaignRequest,
    CombinationCell, CombinationCellDisposition, CombinationObservation,
    CombinationSynergyAnalysis, CombinationSynergyDisposition, CombinationSynergyError,
    CombinationSynergyRequest, CompiledActionDisposition, CompiledResearchAction,
    ComputationCacheEntry, ComputationCandidate, ComputationCandidateDisposition,
    ComputationCandidateScore, ComputationExecution, ComputationExecutionDisposition,
    ComputationExecutionError, ComputationExecutionFailure, ComputationExecutionMode,
    ComputationExecutionRequest, ComputationExecutionStopReason, ComputationOperation,
    ComputationPlacementAssignment, ComputationPlacementBlockedTask,
    ComputationPlacementDisposition, ComputationPlacementError, ComputationPlacementRequest,
    ComputationPlacementSchedule, ComputationPortfolioDisposition, ComputationPortfolioError,
    ComputationPortfolioExecution, ComputationPortfolioExecutionDisposition,
    ComputationPortfolioExecutionError, ComputationPortfolioExecutionRequest,
    ComputationPortfolioPlan, ComputationPortfolioRequest, ComputationRecoveryCampaign,
    ComputationRecoveryDisposition, ComputationRecoveryError, ComputationRecoveryRequest,
    ComputationRecoveryStopReason, ComputationTask, ComputationTaskDisposition,
    ComputationTaskResult, ComputationWorkerProfile, ComputationWorkerUtilization,
    ConcordanceDisposition, ConcordanceError, ConcordanceRequest, ConsensusAssignment,
    ConsensusCluster, ConsensusDisposition, ConsensusError, ConsensusRequest,
    ContradictionAuditSelection, ContradictionConflict, ContradictionCut,
    ContradictionCutDisposition, ContradictionCutError, ContradictionCutRequest,
    ContradictionEvidence, ContrastCondition, ContrastDesign, ContrastDesignDisposition,
    ContrastDesignError, ContrastDesignRequest, ContrastFactor, CounterfactualContrast,
    CounterfactualDirection, CounterfactualDisposition, CounterfactualEnsembleRequest,
    CounterfactualError, CounterfactualIntervention, CounterfactualModel, CounterfactualRequest,
    DecisionAction, DecisionActionGraph, DecisionActionGraphDisposition, DecisionActionGraphError,
    DecisionActionGraphRequest, DecisionActionKind, DecisionActionPlan,
    DecisionActionPlanDisposition, DecisionActionPlanError, DecisionActionPlanRequest,
    DecisionBranchCampaign, DecisionBranchCampaignDisposition, DecisionBranchCampaignError,
    DecisionBranchCampaignRequest, DecisionBranchCampaignStopReason, DecisionBranchExecution,
    DecisionBranchPlan, DecisionBranchPlanDisposition, DecisionBranchPlannerError,
    DecisionBranchPlannerRequest, DecisionBranchPortfolio, DecisionContext,
    DecisionContextCampaign, DecisionContextCampaignDisposition, DecisionContextCampaignError,
    DecisionContextCampaignExecutionFailure, DecisionContextCampaignExecutor,
    DecisionContextCampaignRequest, DecisionContextCampaignRound,
    DecisionContextCampaignStopReason, DecisionContextDisposition, DecisionContextError,
    DecisionContextRequest, DecisionCoverageState, DecisionDirection,
    DecisionGateModalityObservation, DecisionGraphNode, DecisionOmissionCertificate,
    DecisionOmissionCertificateError, DecisionOmissionCertificateRequest,
    DecisionOmissionDisposition, DecisionOmissionEntry, DecisionOperatingCycle,
    DecisionOperatingCycleDisposition, DecisionOperatingCycleError, DecisionOperatingCycleRequest,
    DecisionScenario, DecisionScenarioOutcome, DecisionScenarioScore, DesignAction,
    DesignMechanism, DesignOutcome, DoseDirection, DosePair, DoseResponseAnalysis,
    DoseResponseDisposition, DoseResponseError, DoseResponseObservation, DoseResponsePoint,
    DoseResponseRequest, DoseSurfaceCellState, DoseSurfaceEstimate, DoseSurfaceObservation,
    DriftDisposition, DriftMetricSummary, DriftObservation, DriftSurveillance,
    DriftSurveillanceError, DriftSurveillanceRequest, DropoutModalitySignal, DropoutScenario,
    DropoutScenarioDisposition, DropoutScenarioResult, DropoutStressAnalysis,
    DropoutStressDisposition, DropoutStressError, DropoutStressRequest,
    DryRunActiveLearningCampaignExecutor, DryRunAdaptiveAllocationCampaignExecutor,
    DryRunAdaptiveCloneCampaignExecutor, DryRunAdaptiveInterpretationPlanner,
    DryRunAdaptiveMechanismPolicyExecutor, DryRunDecisionContextCampaignExecutor,
    DryRunEvidenceAcquisitionExecutor, DryRunEvidenceRefreshCampaignExecutor,
    DryRunExperimentOperatingCycleExecutor, DryRunFederatedBenchmarkCampaignExecutor,
    DryRunFederatedMechanismTransportExecutor, DryRunGliomaActionExecutor,
    DryRunGliomaComputationExecutor, DryRunGliomaExperimentFrontierExecutor,
    DryRunGliomaProtocolExecutor, DryRunGliomaReplicationCampaignExecutor,
    DryRunInstrumentExecutor, DryRunKnowledgeActionExecutor,
    DryRunKnowledgeResolutionCampaignExecutor, DryRunMechanismDiscriminationCampaignExecutor,
    DryRunMultiFidelityCampaignExecutor, DryRunMultimodalIngestionCampaignExecutor,
    DryRunReplayCampaignExecutor, DryRunRobustActiveLearningCampaignExecutor,
    DryRunSequentialCampaignExecutor, DynamicPolicyCandidate, DynamicPolicyContribution,
    DynamicPolicyDisposition, DynamicPolicyError, DynamicPolicyEvaluation,
    DynamicPolicyObservation, DynamicPolicyRequest, DynamicPolicyRule, DynamicPolicyScore,
    DynamicPolicyScoreDisposition, DynamicPolicyTrajectory, EndpointEvidence,
    EnsembleCounterfactualError, EnsembleDirection, EnsembleDisposition, EnsembleModelResult,
    EnsembleTargetSummary, EstimandContrast, EstimateSource, EvidenceAcquisitionCampaign,
    EvidenceAcquisitionCampaignDisposition, EvidenceAcquisitionCampaignError,
    EvidenceAcquisitionCampaignRequest, EvidenceAcquisitionCampaignStopReason,
    EvidenceAcquisitionCandidate, EvidenceAcquisitionDisposition, EvidenceAcquisitionError,
    EvidenceAcquisitionExecutionFailure, EvidenceAcquisitionExecutor, EvidenceAcquisitionPlan,
    EvidenceAcquisitionRequest, EvidenceAcquisitionResult, EvidenceAcquisitionResultDisposition,
    EvidenceAcquisitionSelection, EvidenceAcquisitionSourceKind, EvidenceAcquisitionWeights,
    EvidenceCalibrationAnalysis, EvidenceCalibrationDisposition, EvidenceCalibrationError,
    EvidenceCalibrationObservation, EvidenceCalibrationRequest, EvidenceChange, EvidenceChangeKind,
    EvidenceContribution, EvidenceExecutionMode, EvidenceFusionAnalysis, EvidenceFusionDisposition,
    EvidenceFusionError, EvidenceFusionRequest, EvidenceGatedResearchDisposition, EvidencePolarity,
    EvidencePriorityAction, EvidencePriorityActionKind, EvidencePriorityDisposition,
    EvidencePriorityError, EvidencePriorityPlan, EvidencePriorityRequest, EvidencePriorityWeights,
    EvidenceQualification, EvidenceRecord, EvidenceRefreshCampaign,
    EvidenceRefreshCampaignDisposition, EvidenceRefreshCampaignError,
    EvidenceRefreshCampaignExecutor, EvidenceRefreshCampaignRequest, EvidenceRefreshCampaignRound,
    EvidenceRefreshCampaignStopReason, EvidenceRefreshExecutionFailure, EvidenceRequest,
    EvidenceSurveillance, EvidenceSurveillanceAction, EvidenceSurveillanceActionKind,
    EvidenceSurveillanceDisposition, EvidenceSurveillanceError, EvidenceSurveillanceRequest,
    EvidenceTriangulation, EvidenceTriangulationDisposition, EvidenceTriangulationError,
    EvidenceTriangulationRequest, ExperimentArm, ExperimentDesign, ExperimentOperatingCycle,
    ExperimentOperatingCycleDisposition, ExperimentOperatingCycleError,
    ExperimentOperatingCycleRequest, ExperimentRequest, FeatureValue, FederatedBenchmarkAction,
    FederatedBenchmarkActionKind, FederatedBenchmarkAdaptiveCampaign,
    FederatedBenchmarkAdaptiveCampaignError, FederatedBenchmarkAdaptiveCampaignRequest,
    FederatedBenchmarkAdaptiveDisposition, FederatedBenchmarkAdaptiveStopReason,
    FederatedBenchmarkCampaign, FederatedBenchmarkCampaignDisposition,
    FederatedBenchmarkCampaignError, FederatedBenchmarkCampaignExecutor,
    FederatedBenchmarkCampaignRequest, FederatedBenchmarkCampaignRound,
    FederatedBenchmarkCampaignStopReason, FederatedBenchmarkCandidate,
    FederatedBenchmarkCandidateScore, FederatedBenchmarkConsensus, FederatedBenchmarkContribution,
    FederatedBenchmarkDisposition, FederatedBenchmarkError, FederatedBenchmarkExecutionFailure,
    FederatedBenchmarkExecutionMode, FederatedBenchmarkOperatingCycle,
    FederatedBenchmarkOperatingCycleDisposition, FederatedBenchmarkOperatingCycleError,
    FederatedBenchmarkOperatingCycleRequest, FederatedBenchmarkPlanDisposition,
    FederatedBenchmarkRequest, FederatedBenchmarkSite, FederatedBenchmarkSiteDisposition,
    FederatedBenchmarkSitePlan, FederatedBenchmarkSitePlannerError,
    FederatedBenchmarkSitePlannerRequest, FederatedMechanismContribution, FederatedMechanismSite,
    FederatedMechanismTransportAction, FederatedMechanismTransportAnalysis,
    FederatedMechanismTransportCampaign, FederatedMechanismTransportCampaignDisposition,
    FederatedMechanismTransportCampaignError, FederatedMechanismTransportCampaignRequest,
    FederatedMechanismTransportCampaignRound, FederatedMechanismTransportCampaignStopReason,
    FederatedMechanismTransportDisposition, FederatedMechanismTransportError,
    FederatedMechanismTransportExecutionFailure, FederatedMechanismTransportExecutor,
    FederatedMechanismTransportRequest, FederatedModelCoverage, FidelityCalibration,
    FidelityCandidate, FidelityEstimate, FidelityLevel, FidelityObservation, FrontierActionKind,
    FrontierCandidateGate, FrontierCandidateStatus, GliomaActionExecutor, GliomaActionPlanner,
    GliomaAdaptiveWorkflowSchedulerDisposition, GliomaAdaptiveWorkflowSchedulerError,
    GliomaAdaptiveWorkflowSchedulerPlan, GliomaAdaptiveWorkflowSchedulerRequest,
    GliomaAutonomousCampaign, GliomaAutonomousCampaignDisposition, GliomaAutonomousCampaignError,
    GliomaAutonomousCampaignRequest, GliomaAutonomousCampaignRound,
    GliomaAutonomousCampaignStopReason, GliomaAutonomousPlannerContext,
    GliomaAutonomousResearchEngineCycle, GliomaAutonomousResearchEngineDisposition,
    GliomaAutonomousResearchEngineError, GliomaAutonomousResearchEngineRequest,
    GliomaAutonomousResearchEngineRun, GliomaAutonomousResearchEngineStopReason,
    GliomaAutonomousResearchMission, GliomaCampaignExecutor, GliomaCausalClaimAdjudication,
    GliomaCausalClaimAdjudicationError, GliomaCausalClaimAdjudicationRequest,
    GliomaComputationCampaign, GliomaComputationCampaignDisposition,
    GliomaComputationCampaignError, GliomaComputationCampaignRequest,
    GliomaComputationCampaignRound, GliomaComputationCampaignStopReason, GliomaComputationExecutor,
    GliomaComputationOperatingCycle, GliomaComputationOperatingCycleDisposition,
    GliomaComputationOperatingCycleError, GliomaComputationOperatingCycleRequest,
    GliomaComputationPlanner, GliomaComputationPlannerContext, GliomaComputationPlannerFailure,
    GliomaComputationWorkflow, GliomaComputationWorkflowError, GliomaComputationWorkflowRequest,
    GliomaDirectorAction, GliomaDirectorCheckpoint, GliomaDirectorDisposition, GliomaDirectorFocus,
    GliomaEvidenceCampaignDisposition, GliomaEvidenceCampaignError,
    GliomaEvidenceCampaignExecution, GliomaEvidenceCampaignRequest,
    GliomaEvidenceGatedResearchError, GliomaEvidenceGatedResearchRequest,
    GliomaEvidenceGatedResearchRun, GliomaEvidenceOperatingCycle,
    GliomaEvidenceOperatingCycleDisposition, GliomaEvidenceOperatingCycleError,
    GliomaEvidenceOperatingCycleRequest, GliomaExperimentFrontierError,
    GliomaExperimentFrontierExecutor, GliomaExperimentFrontierRequest, GliomaExperimentFrontierRun,
    GliomaFeatureSpec, GliomaFrontierCandidate, GliomaFrontierDisposition,
    GliomaFrontierExecutionFailure, GliomaFrontierMechanism, GliomaFrontierObservation,
    GliomaFrontierOutcome, GliomaFrontierRound, GliomaFrontierScore, GliomaFrontierStopReason,
    GliomaInformationDesignExecutor, GliomaIntentMissionDisposition, GliomaIntentMissionError,
    GliomaIntentMissionRequest, GliomaIntentResearchMission, GliomaInterpretationOperatingCycle,
    GliomaInterpretationOperatingCycleError, GliomaInterpretationOperatingCycleRequest,
    GliomaMechanismActionPlanner, GliomaMechanismAutopilotDisposition,
    GliomaMechanismAutopilotError, GliomaMechanismAutopilotRequest, GliomaMechanismAutopilotRound,
    GliomaMechanismAutopilotRun, GliomaMechanismAutopilotStopReason,
    GliomaMechanismDiscoveryDisposition, GliomaMechanismDiscoveryError,
    GliomaMechanismDiscoveryRequest, GliomaMechanismDiscoveryRound, GliomaMechanismDiscoveryRun,
    GliomaMechanismDiscoveryStopReason, GliomaMissionDisposition, GliomaMissionError,
    GliomaMissionGates, GliomaMissionRecovery, GliomaMissionRecoveryDisposition,
    GliomaMissionRecoveryError, GliomaMissionRecoveryRequest, GliomaMissionRecoveryStopReason,
    GliomaMissionRequest, GliomaMissionRound, GliomaMissionStopReason, GliomaModalitySensitivity,
    GliomaMultimodalMissionDisposition, GliomaMultimodalMissionError,
    GliomaMultimodalMissionRequest, GliomaMultimodalOperatingCycle,
    GliomaMultimodalOperatingCycleDisposition, GliomaMultimodalOperatingCycleError,
    GliomaMultimodalOperatingCycleRequest, GliomaMultimodalResearchMission,
    GliomaMultimodalSensitivityAnalysis, GliomaMultimodalSensitivityDisposition,
    GliomaMultimodalSensitivityError, GliomaMultimodalSensitivityRequest, GliomaOperatingScale,
    GliomaPlannerFailure, GliomaProgramDescriptor, GliomaProgramId, GliomaProgramResourceCapacity,
    GliomaProgramResourceUsage, GliomaProgramScheduleExecution, GliomaProgramScheduleHold,
    GliomaProgramScheduleJob, GliomaProgramScheduleJobDisposition, GliomaProgramScheduleJobState,
    GliomaProgramSchedulerDisposition, GliomaProgramSchedulerError, GliomaProgramSchedulerRequest,
    GliomaProgramSchedulerRound, GliomaProgramSchedulerRun, GliomaProgramSchedulerStopReason,
    GliomaProtocolExecutor, GliomaReleaseOperatingCycle, GliomaReleaseOperatingCycleDisposition,
    GliomaReleaseOperatingCycleError, GliomaReleaseOperatingCycleRequest, GliomaReplicationAction,
    GliomaReplicationActionKind, GliomaReplicationCampaign, GliomaReplicationCampaignDisposition,
    GliomaReplicationCampaignError, GliomaReplicationCampaignExecutor,
    GliomaReplicationCampaignObservation, GliomaReplicationCampaignRequest,
    GliomaReplicationCampaignRound, GliomaReplicationCampaignStopReason,
    GliomaReplicationExecutionFailure, GliomaResearchAutopilotDisposition,
    GliomaResearchAutopilotError, GliomaResearchAutopilotRequest, GliomaResearchAutopilotRun,
    GliomaResearchDirectorError, GliomaResearchDirectorRequest, GliomaResearchDirectorRun,
    GliomaWorkflowBranch, GliomaWorkflowError, GliomaWorkflowExecution, GliomaWorkflowMode,
    GliomaWorkflowNode, GliomaWorkflowPlan, GliomaWorkflowRequest, GraphFusionAnalysis,
    GraphFusionDisposition, GraphFusionError, GraphFusionNeighbour, GraphFusionRequest,
    GraphFusionState, GraphFusionVector, HarmonizationDisposition, HarmonizationError,
    HarmonizationRequest, HarmonizationVector, HarmonizedFeature, HarmonizedVector,
    InformationDesignActionScore, InformationDesignDisposition, InformationDesignError,
    InformationDesignPlan, InformationDesignRequest, IngestionQcAction, IngestionQcActionKind,
    InstrumentAction, InstrumentActionDecision, InstrumentActionDisposition,
    InstrumentAssayEvidenceAssessment, InstrumentAuthorization, InstrumentCalibration,
    InstrumentCampaign, InstrumentCampaignDisposition, InstrumentCampaignError,
    InstrumentCampaignFailure, InstrumentCampaignRequest, InstrumentCampaignRunRequest,
    InstrumentCampaignRunResult, InstrumentCampaignStopReason, InstrumentExecutionDisposition,
    InstrumentExecutionError, InstrumentExecutionFailure, InstrumentExecutionMode,
    InstrumentExecutionRequest, InstrumentExecutionResult, InstrumentExecutionRun,
    InstrumentExecutionStopReason, InstrumentExecutor, InstrumentFleetAssignment,
    InstrumentFleetBlockedTask, InstrumentFleetDisposition, InstrumentFleetExecution,
    InstrumentFleetExecutionDisposition, InstrumentFleetExecutionError,
    InstrumentFleetExecutionFailure, InstrumentFleetExecutionRequest,
    InstrumentFleetExecutionResult, InstrumentFleetExecutionRunRequest,
    InstrumentFleetExecutionStopReason, InstrumentFleetResource, InstrumentFleetSchedule,
    InstrumentFleetScheduleRequest, InstrumentFleetSchedulerError, InstrumentFleetTask,
    InstrumentFleetUtilization, InstrumentInterlockSnapshot, InstrumentOperatingCycle,
    InstrumentOperatingCycleDisposition, InstrumentOperatingCycleError,
    InstrumentOperatingCycleRequest, InstrumentOperation, InstrumentParameter,
    InstrumentPreflightDisposition, InstrumentPreflightError, InstrumentPreflightPlan,
    InstrumentPreflightRequest, InstrumentPreflightSummary, InstrumentScienceLoop,
    InstrumentScienceLoopDisposition, InstrumentScienceLoopError, InstrumentScienceLoopRequest,
    InterpretationEvidence, InterpretationEvidenceDirection, InterpretationEvidenceFamily,
    InterpretationFamilySummary, InterpretationOperatingCycleDisposition, InterpretationSynthesis,
    InterpretationSynthesisDisposition, InterpretationSynthesisError,
    InterpretationSynthesisRequest, KnowledgeActionBridge, KnowledgeActionBridgeError,
    KnowledgeActionBridgeRequest, KnowledgeActionCompilerError, KnowledgeActionCompilerRequest,
    KnowledgeActionDispatchDisposition, KnowledgeActionDispatchError,
    KnowledgeActionDispatchRequest, KnowledgeActionDispatchResult, KnowledgeActionDispatchRun,
    KnowledgeActionExecutionFailure, KnowledgeActionExecutor, KnowledgeActionPlan,
    KnowledgeActionPlanDisposition, KnowledgeActionResultDisposition,
    KnowledgeActionSelectionCycle, KnowledgeActionSelectionCycleError,
    KnowledgeActionSelectionCycleRequest, KnowledgeActionTemplate, KnowledgeClaim,
    KnowledgeClaimDisposition, KnowledgeComponentDisposition, KnowledgeComposition,
    KnowledgeCompositionComponent, KnowledgeCompositionDisposition, KnowledgeCompositionError,
    KnowledgeCompositionPath, KnowledgeCompositionRequest, KnowledgeDisposition, KnowledgeError,
    KnowledgeFrontier, KnowledgeFrontierDisposition, KnowledgeFrontierError,
    KnowledgeFrontierRequest, KnowledgeFrontierScore, KnowledgeFrontierWeights,
    KnowledgeGapClaimMapping, KnowledgeGapCompilerError, KnowledgeGapCompilerRequest,
    KnowledgeGapPortfolio, KnowledgeGapPortfolioDisposition, KnowledgeGapSourceTemplate,
    KnowledgePathDisposition, KnowledgeRelation, KnowledgeRelationKind, KnowledgeRequest,
    KnowledgeResolutionCampaign, KnowledgeResolutionCampaignDisposition,
    KnowledgeResolutionCampaignError, KnowledgeResolutionCampaignExecutor,
    KnowledgeResolutionCampaignRequest, KnowledgeResolutionCampaignRound,
    KnowledgeResolutionCampaignStopReason, KnowledgeResolutionExecutionFailure,
    KnowledgeSynthesisOperatingCycle, KnowledgeSynthesisOperatingCycleDisposition,
    KnowledgeSynthesisOperatingCycleError, KnowledgeSynthesisOperatingCycleRequest,
    LatentFactorAnalysis, LatentFactorComponent, LatentFactorDisposition, LatentFactorError,
    LatentFactorRequest, LatentFactorVector, LatentLoading, LatentScore, LigandReceptorPair,
    MechanismActionPlan, MechanismActionPlannerConfig, MechanismActionPlannerError,
    MechanismBayesianUpdate, MechanismCalibration, MechanismCalibrationBin,
    MechanismCalibrationError, MechanismCalibrationObservation, MechanismCalibrationRequest,
    MechanismCalibrationScore, MechanismCalibrationScoreDisposition, MechanismCampaignDisposition,
    MechanismCampaignError, MechanismCampaignExecutionDisposition, MechanismCandidate,
    MechanismCounterfactual, MechanismCounterfactualEnsemble, MechanismDiscrimination,
    MechanismDiscriminationCampaign, MechanismDiscriminationCampaignDisposition,
    MechanismDiscriminationCampaignError, MechanismDiscriminationCampaignExecutionFailure,
    MechanismDiscriminationCampaignExecutor, MechanismDiscriminationCampaignRequest,
    MechanismDiscriminationCampaignRound, MechanismDiscriminationCampaignStopReason,
    MechanismDiscriminationDisposition, MechanismDiscriminationError,
    MechanismDiscriminationRanking, MechanismDiscriminationRequest, MechanismDiscriminatorAction,
    MechanismDynamicsDisposition, MechanismDynamicsEdge, MechanismDynamicsError,
    MechanismDynamicsIntervention, MechanismDynamicsNode, MechanismDynamicsPlan,
    MechanismDynamicsRequest, MechanismDynamicsSensitivity, MechanismDynamicsState,
    MechanismDynamicsStep, MechanismFeatureObservation, MechanismGraphDisposition,
    MechanismGraphEdge, MechanismGraphError, MechanismGraphNode, MechanismGraphPropagation,
    MechanismGraphRelation, MechanismGraphRequest, MechanismHypothesis, MechanismInformationGain,
    MechanismNodeScore, MechanismOperatingCycle, MechanismOperatingCycleDisposition,
    MechanismOperatingCycleError, MechanismOperatingCycleRequest, MechanismPortfolio,
    MechanismPrediction, MechanismRequest, MediationAnalysis, MediationDisposition, MediationError,
    MediationObservation, MediationRequest, MetaAnalysisDisposition, MetaAnalysisError,
    MetaAnalysisRequest, MetaStudyContribution, MissingnessAudit, MissingnessAuditDisposition,
    MissingnessAuditError, MissingnessAuditRequest, MissingnessModalitySummary,
    MissingnessObservation, MissingnessPairSummary, MissingnessPattern,
    MissingnessPatternDisposition, MissingnessState, ModalityCapability, ModalityConcordance,
    ModalityPortfolioAlternative, ModalityPortfolioDisposition, ModalityPortfolioError,
    ModalityPortfolioPlan, ModalityPortfolioRequest, ModalityVector, MultiFidelityCampaign,
    MultiFidelityCampaignDisposition, MultiFidelityCampaignError, MultiFidelityCampaignExecutor,
    MultiFidelityCampaignRequest, MultiFidelityCampaignRound, MultiFidelityCampaignStopReason,
    MultiFidelityDisposition, MultiFidelityExecutionFailure, MultiFidelityOptimizationError,
    MultiFidelityOptimizationPlan, MultiFidelityOptimizationRequest, MultimodalConcordance,
    MultimodalConsensus, MultimodalDecisionGateAnalysis, MultimodalDecisionGateDisposition,
    MultimodalDecisionGateError, MultimodalDecisionGateRequest, MultimodalExecutionMode,
    MultimodalHarmonization, MultimodalIngestionCampaign, MultimodalIngestionCampaignDisposition,
    MultimodalIngestionCampaignError, MultimodalIngestionCampaignExecutor,
    MultimodalIngestionCampaignRequest, MultimodalIngestionCampaignRound,
    MultimodalIngestionCampaignStopReason, MultimodalIngestionExecutionFailure,
    MultimodalMechanismCampaign, MultimodalMechanismCampaignExecution,
    MultimodalMechanismCampaignRequest, MultimodalObservation, MultimodalQcReport,
    MultimodalReadinessError, MultimodalReadinessRequest, MultimodalRequest,
    MultimodalResearchReadiness, MultimodalResearchReadinessDisposition, MultimodalResearchSurface,
    MultimodalSurfaceDecision, MultimodalSurfaceReadiness, OptimizationDirection,
    PairConcordanceDisposition, PathwayActivityAnalysis, PathwayActivityDefinition,
    PathwayActivityDirection, PathwayActivityDisposition, PathwayActivityEdge,
    PathwayActivityError, PathwayActivityNode, PathwayActivityObservation, PathwayActivityRecord,
    PathwayActivityRequest, PortfolioDirection, PowerArmDecision, PowerArmObservation,
    PowerDecisionKind, PowerReestimationDisposition, PowerReestimationError, PowerReestimationPlan,
    PowerReestimationRequest, ProgramExecutionMode, ProgramGate, ProgramGateStatus,
    ProtocolBranchCandidate, ProtocolBranchEvaluation, ProtocolBranchOptimizationDisposition,
    ProtocolBranchOptimizationError, ProtocolBranchOptimizationPlan,
    ProtocolBranchOptimizationRequest, ProtocolBranchWeights, ProtocolCompensationCandidate,
    ProtocolCompensationDisposition, ProtocolCompensationError, ProtocolCompensationPlan,
    ProtocolCompensationRequest, ProtocolCompensationSelection, ProtocolDisposition,
    ProtocolEvidenceCell, ProtocolEvidenceDisposition, ProtocolEvidenceFusion,
    ProtocolEvidenceFusionDisposition, ProtocolEvidenceFusionError, ProtocolEvidenceFusionRequest,
    ProtocolEvidenceStudySurface, ProtocolEvidenceSurface, ProtocolEvidenceSurfaceDisposition,
    ProtocolEvidenceSurfaceError, ProtocolEvidenceSurfaceRequest, ProtocolExecution,
    ProtocolExecutionDisposition, ProtocolExecutionError, ProtocolExecutionFailure,
    ProtocolExecutionRequest, ProtocolExecutionStopReason, ProtocolFusionCell,
    ProtocolFusionDisposition, ProtocolMeasurement, ProtocolResource, ProtocolResourceKind,
    ProtocolSimulation, ProtocolSimulationError, ProtocolSimulationRequest, ProtocolTask,
    ProtocolTaskDisposition, ProtocolTaskResult, ProtocolTransportEndpoint,
    ProtocolTransportEndpointDisposition, ProtocolTransportGate, ProtocolTransportGateDisposition,
    ProtocolTransportGateError, ProtocolTransportGateRequest, RegisteredSpatialCell,
    RegistrationLandmark, ReleaseExecutionMode, ReleaseGateError, ReleaseGateEvaluation,
    ReleaseGateRequest, ReleaseGateStatus, ReleaseReviewAttestation, ReleaseReviewDecision,
    ReliabilityCalibration, ReliabilityCalibrationError, ReliabilityCalibrationRequest,
    ReliabilityDisposition, ReliabilityModalitySummary, ReliabilityObservation, ReplayCampaign,
    ReplayCampaignDisposition, ReplayCampaignError, ReplayCampaignExecutor, ReplayCampaignRequest,
    ReplayCampaignRound, ReplayCampaignStopReason, ReplayExecutionFailure, ReplayObservation,
    ReplayObservationStatus, ReplayTask, ReplicationAssessment, ReplicationMetaAnalysis,
    ReplicationRequest, ReplicationStudy, ResearchObjectManifest, ResearchObjectRequest,
    ResourceUtilization, RobustActiveLearningCampaign, RobustActiveLearningCampaignDisposition,
    RobustActiveLearningCampaignError, RobustActiveLearningCampaignExecutor,
    RobustActiveLearningCampaignRequest, RobustActiveLearningCampaignRound,
    RobustActiveLearningCampaignStopReason, RobustActiveLearningCandidate,
    RobustActiveLearningCandidateDisposition, RobustActiveLearningDisposition,
    RobustActiveLearningError, RobustActiveLearningExecutionFailure, RobustActiveLearningModel,
    RobustActiveLearningObservation, RobustActiveLearningPlan, RobustActiveLearningRequest,
    RobustActiveLearningScore, RobustCandidateAllocation, RobustDesignActionKind,
    RobustDesignCandidate, RobustDesignScenario, RobustExperimentDesign,
    RobustExperimentDesignDisposition, RobustExperimentDesignError, RobustExperimentDesignRequest,
    RobustInterventionCandidate, RobustInterventionPortfolio, RobustInterventionRequest,
    RobustInterventionScore, RobustPortfolioDisposition, RobustPortfolioError, RobustnessCase,
    RobustnessCaseKind, RobustnessDisposition, RobustnessError, RobustnessGuidedCandidate,
    RobustnessGuidedCandidateScore, RobustnessGuidedComputation,
    RobustnessGuidedComputationDisposition, RobustnessGuidedComputationError,
    RobustnessGuidedComputationRequest, RobustnessRequest, RobustnessSuite, SampleRegistration,
    SampleRegistrationDisposition, SampleTimepoint, ScheduleEntry, SchedulerDecision,
    SchedulerObservation, SchedulerOutcome, ScientificFrontierDisposition, ScientificFrontierError,
    ScientificFrontierExecution, ScientificFrontierExecutionDisposition,
    ScientificFrontierExecutionError, ScientificFrontierExecutionRequest, ScientificFrontierPlan,
    ScientificFrontierRequest, SensitivityDirection, SensitivityDisposition, SensitivityError,
    SensitivityObservation, SensitivityPoint, SensitivityRequest, SequentialArmDecision,
    SequentialArmObservation, SequentialBatchObservation, SequentialCampaign,
    SequentialCampaignDisposition, SequentialCampaignError, SequentialCampaignExecutionFailure,
    SequentialCampaignExecutor, SequentialCampaignRequest, SequentialCampaignRound,
    SequentialCampaignStopReason, SequentialDecisionKind, SequentialDesignDisposition,
    SequentialDesignError, SequentialDesignPlan, SequentialDesignRequest, SequentialDesignRound,
    SourceCalibration, SourceCalibrationDisposition, SpatialCell, SpatialCommunicationAnalysis,
    SpatialCommunicationCell, SpatialCommunicationDisposition, SpatialCommunicationError,
    SpatialCommunicationPair, SpatialCommunicationPairDisposition, SpatialCommunicationRequest,
    SpatialNiche, SpatialNicheAnalysis, SpatialNicheDisposition, SpatialNicheError,
    SpatialNicheInteraction, SpatialNicheRequest, SpatialPropagationAnalysis,
    SpatialPropagationDisposition, SpatialPropagationEdge, SpatialPropagationError,
    SpatialPropagationRequest, SpatialPropagationTrajectory, SpatialRegistrationAnalysis,
    SpatialRegistrationCell, SpatialRegistrationDisposition, SpatialRegistrationError,
    SpatialRegistrationRequest, StateTransitionAnalysis, StateTransitionCell,
    StateTransitionContrast, StateTransitionDisposition, StateTransitionError,
    StateTransitionObservation, StateTransitionRequest, StaticGliomaActionPlanner,
    StaticGliomaComputationPlanner, StratifiedCausalActionKind, StratifiedCausalAdjustment,
    StratifiedCausalDisposition, StratifiedCausalError, StratifiedCausalRequest,
    StratifiedObservation, TemporalFusionAnalysis, TemporalFusionDisposition, TemporalFusionError,
    TemporalFusionRequest, TemporalObservation, TemporalSpatialAlignmentRequest, TemporalState,
    TemporalStateFeature, TemporalTransition, TemporalTransitionDirection, TrajectoryAnalysis,
    TrajectoryArmSummary, TrajectoryDisposition, TrajectoryError, TrajectoryObservation,
    TrajectoryRequest, TransitionCellDisposition, TransitionContrastDisposition,
    TransitionDirection, TransportStudy, TransportStudyContribution, TransportabilityAnalysis,
    TransportabilityDisposition, TransportabilityError, TransportabilityRequest, TriangulatedClaim,
    TriangulatedClaimVerdict, TypedKnowledge, UnitContrast, UnitTrajectory,
    UnitTrajectoryDisposition, WorkflowNodeDecision, EXECUTION_OUTPUT_SCHEMA,
    PROTOCOL_EXECUTION_OUTPUT_SCHEMA,
};
pub use glioma_engine::{
    compile_glioma_research, dry_run_glioma_research, execute_glioma_research,
    glioma_research_engine_manifest, select_glioma_actions, DryRunGliomaExecutor,
    GliomaActionCandidate, GliomaActionDecision, GliomaActionSelection, GliomaEngineError,
    GliomaExecutionReceipt, GliomaModality, GliomaModelSystem, GliomaPlanDisposition,
    GliomaResearchIntent, GliomaResearchPlan, GliomaSelectionConfig, GliomaSelectionWeights,
    GliomaStage, GliomaStageDisposition, GliomaStageExecution, GliomaStageExecutor,
    GliomaStageFailure, GliomaStageInput, GliomaStageKind, LocalArtifactRef, StageReadiness,
    ACTION_SELECTION_OUTPUT_SCHEMA as GLIOMA_ACTION_SELECTION_OUTPUT_SCHEMA,
    CONTRACT_VERSION as GLIOMA_ENGINE_CONTRACT_VERSION, FEATURE_ID as GLIOMA_ENGINE_FEATURE_ID,
};
pub use protocol::{plan_protocol, ProtocolStep, ResearchProtocol};
pub use report::{render_report, RenderedReport};
pub use request::{
    ResearchRequest, ResearchRequestDocument, WorldFamily, MAX_DISTRACTORS_PER_POINT,
    MAX_DISTRACTOR_POINTS, MAX_QUESTION_BYTES, MAX_RESEARCH_ID_CHARS,
};
pub use runner::{run_research, PINNED_REFERENCE_CERTIFICATE_SHA256, UNSWEPT_KNOBS_CAVEAT};
