//! Federated continual performance and reliability control plane.
//!
//! Atlas feature: `AFA-bioir-P21-F32`.  The plane evaluates a declared
//! capability workload and produces a signed-ready reliability result.  It
//! never invokes tools, moves raw observations, or turns degraded operation
//! into a scientific conclusion.

use bioprism_foundation::{AuthorityRequirement, AutonomyTier, CapabilityManifest, Determinism, Effect, EvidenceReference, EvidenceState, ResearchSurface, TypedPort, TypedResearchArtifact, PRECLINICAL_BOUNDARY, RESEARCH_CONTRACT_SCHEMA_VERSION};
use bioprism_ids::ContentHash;
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::collections::{BTreeMap, BTreeSet};
use thiserror::Error;

pub const FEATURE_ID: &str = "AFA-bioir-P21-F32";
pub const CONTRACT_VERSION: &str = "bioir-federated-continual-performance-reliability-control-plane/1.0";
pub const INPUT_SCHEMA: &str = "CapabilityWorkload4@1";
pub const OUTPUT_SCHEMA: &str = "ReliableCapabilityResult8@1";
const CONTENT_TYPE: &str = "application/vnd.aurora.reliable-capability-result-8+json";

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CapabilityManifestEntry { pub capability_id: String, pub version: String, pub effect: String, pub deterministic: bool, pub approved: bool, pub revoked: bool, pub capability_digest: ContentHash, pub provenance_digest: ContentHash }
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CapabilityInvocation { pub invocation_id: String, pub capability_id: String, pub input_digest: ContentHash, pub estimated_cost_units: u64, pub timeout_ms: u64, pub max_attempts: u32, pub simulated_failure: Option<String> }
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CapabilityWorkload { pub schema_version: String, pub workload_id: String, pub federation_id: String, pub institution_id: String, pub capability_id: String, pub manifests: Vec<CapabilityManifestEntry>, pub invocations: Vec<CapabilityInvocation>, pub budget_units: u64, pub policy_allow: bool, pub protected_closure: bool, pub signed_approval: bool, pub federation_approved: bool, pub raw_data_local: bool, pub aggregate_only: bool, pub replay_identity: ContentHash, pub adversarial_events: Vec<String>, pub boundary: String }

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ReliabilityDisposition { Qualified, Degraded, Unresolved, Blocked }
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ReliableCapabilityResult { pub schema_version: String, pub contract_version: String, pub feature_id: String, pub workload_id: String, pub federation_id: String, pub institution_id: String, pub capability_id: String, pub disposition: ReliabilityDisposition, pub invocation_order: Vec<String>, pub completed_order: Vec<String>, pub unresolved_order: Vec<String>, pub blocked_order: Vec<String>, pub retry_order: Vec<String>, pub timeout_order: Vec<String>, pub tool_order: Vec<String>, pub budget_used_units: u64, pub omissions: Vec<String>, pub uncertainty: Vec<String>, pub negative_evidence: Vec<String>, pub replay_identity: ContentHash, pub result_digest: ContentHash, pub effect_receipts: Vec<String>, pub artifact: TypedResearchArtifact, pub raw_data_local: bool, pub aggregate_only: bool, pub boundary: String }

#[derive(Debug, Error, Clone, PartialEq, Eq)]
pub enum PerformanceReliabilityError { #[error("invalid capability workload: {0}")] Invalid(String), #[error("reliability result artifact failed: {0}")] Artifact(String) }
fn invalid(value: impl Into<String>) -> PerformanceReliabilityError { PerformanceReliabilityError::Invalid(value.into()) }
fn canonical(values: &[String]) -> bool { values.windows(2).all(|pair| pair[0] < pair[1]) }
fn digest(value: &ContentHash) -> bool { value.as_str().len() == 64 }

impl ReliableCapabilityResult {
    pub fn validate(&self) -> Result<(), PerformanceReliabilityError> {
        if self.schema_version != RESEARCH_CONTRACT_SCHEMA_VERSION || self.contract_version != CONTRACT_VERSION || self.feature_id != FEATURE_ID || self.boundary != PRECLINICAL_BOUNDARY || self.artifact.boundary != PRECLINICAL_BOUNDARY || !self.raw_data_local || !self.aggregate_only || self.workload_id.trim().is_empty() || self.federation_id.trim().is_empty() || self.institution_id.trim().is_empty() || self.capability_id.trim().is_empty() || self.invocation_order.is_empty() || self.tool_order.is_empty() || self.effect_receipts.is_empty() { return Err(invalid("reliability result identity, locality, invocation, tool, or effects are incomplete")); }
        for values in [&self.invocation_order, &self.completed_order, &self.unresolved_order, &self.blocked_order, &self.retry_order, &self.timeout_order, &self.tool_order, &self.omissions, &self.uncertainty, &self.negative_evidence, &self.effect_receipts] { if !canonical(values) { return Err(invalid("reliability result ordering is not canonical")); } }
        let parts = self.completed_order.iter().chain(self.unresolved_order.iter()).chain(self.blocked_order.iter()).cloned().collect::<Vec<_>>(); let ids = self.invocation_order.iter().cloned().collect::<BTreeSet<String>>(); if parts.len() != ids.len() || parts.iter().cloned().collect::<BTreeSet<String>>() != ids { return Err(invalid("reliability result states do not partition invocations")); }
        for value in [&self.replay_identity, &self.result_digest, &self.artifact.content_hash] { if !digest(value) { return Err(invalid("reliability result digest is invalid")); } }
        self.artifact.validate_metadata().map_err(|e| PerformanceReliabilityError::Artifact(e.to_string()))?; if self.artifact.content_type != CONTENT_TYPE { return Err(invalid("reliability result artifact type is invalid")); }
        if self.disposition == ReliabilityDisposition::Qualified { if self.effect_receipts != [format!("exchange:permitted-summaries:{}", self.workload_id), format!("manage:local-capability:{}", self.workload_id)] { return Err(invalid("qualified reliability effects are invalid")); } } else if self.effect_receipts != ["block:unsafe-release"] { return Err(invalid("non-qualified reliability result must block release")); }
        Ok(())
    }
}

pub fn performance_reliability_control_plane_manifest() -> CapabilityManifest { CapabilityManifest { schema_version: RESEARCH_CONTRACT_SCHEMA_VERSION.into(), capability_id: FEATURE_ID.into(), version: CONTRACT_VERSION.into(), owner_crate: "bioir".into(), consumers: ["bioinformatician".into(), "institution operations steward".into(), "federation operator".into()].into(), behavior: "evaluates declared capability workloads for deterministic, replayable, policy-separated reliability without invoking tools".into(), value: "makes performance degradation, failures, locality, and federated authorization visible before a research workflow depends on a capability".into(), inputs: vec![TypedPort { name: "capability_workload".into(), schema: INPUT_SCHEMA.into(), required: true }], outputs: vec![TypedPort { name: "reliable_capability_result".into(), schema: OUTPUT_SCHEMA.into(), required: true }], effects: [Effect::ExecuteLocalComputation, Effect::WriteLocalArtifact, Effect::FederationExport].into(), permissions: ["operate:institution-node".into()].into(), determinism: Determinism::ByteStable, evidence: vec![EvidenceReference { source_id: "w3c-prov-o".into(), state: EvidenceState::Supported, locator: Some("https://www.w3.org/TR/prov-o/".into()) }, EvidenceReference { source_id: "ro-crate-1.3".into(), state: EvidenceState::Supported, locator: Some("https://www.researchobject.org/ro-crate/specification.html".into()) }], authority_requirements: vec![AuthorityRequirement { role: "institution operations steward".into(), reason: "federated capability summaries require institution-local approval".into() }], autonomy_tier: AutonomyTier::A2, surfaces: [ResearchSurface::Ui, ResearchSurface::Api, ResearchSurface::Sdk, ResearchSurface::Operator, ResearchSurface::Policy].into(), boundary: PRECLINICAL_BOUNDARY.into() } }

pub fn evaluate_performance_reliability(workload: &CapabilityWorkload) -> Result<ReliableCapabilityResult, PerformanceReliabilityError> {
    validate_workload(workload)?;
    let manifests = workload.manifests.iter().map(|manifest| (manifest.capability_id.clone(), manifest)).collect::<BTreeMap<_, _>>(); let mut invocations = workload.invocations.clone(); invocations.sort_by(|a, b| a.invocation_id.cmp(&b.invocation_id)); let invocation_order = invocations.iter().map(|x| x.invocation_id.clone()).collect::<Vec<_>>(); let tool_order = invocations.iter().map(|x| x.capability_id.clone()).collect::<BTreeSet<_>>().into_iter().collect::<Vec<_>>(); let retry_order = invocations.iter().filter(|x| x.max_attempts > 1).map(|x| x.invocation_id.clone()).collect::<Vec<_>>(); let timeout_order = invocations.iter().filter(|x| x.timeout_ms > 0).map(|x| x.invocation_id.clone()).collect::<Vec<_>>(); let budget_used_units = invocations.iter().map(|x| x.estimated_cost_units).sum::<u64>(); let mut completed = BTreeSet::new(); let mut unresolved = BTreeSet::new(); let mut blocked = BTreeSet::new(); let mut omissions = BTreeSet::new(); let mut uncertainty = BTreeSet::new(); let mut negative = BTreeSet::new();
    for invocation in &invocations { let manifest = manifests.get(&invocation.capability_id).expect("validated capability"); if let Some(reason) = &invocation.simulated_failure { unresolved.insert(invocation.invocation_id.clone()); negative.insert(format!("{}:{}", invocation.invocation_id, reason)); } else if !manifest.deterministic { unresolved.insert(invocation.invocation_id.clone()); uncertainty.insert(format!("{}:bounded-nondeterminism", invocation.capability_id)); } else { completed.insert(invocation.invocation_id.clone()); } }
    if !workload.policy_allow { negative.insert("request:policy-denied".into()); } if !workload.protected_closure { uncertainty.insert("request:protected-closure-incomplete".into()); } if !workload.signed_approval { uncertainty.insert("request:signed-approval-missing".into()); } if !workload.federation_approved { uncertainty.insert("request:federation-approval-missing".into()); } negative.extend(workload.adversarial_events.iter().map(|event| format!("adversarial:{event}"))); let global = !workload.policy_allow || !workload.protected_closure || !workload.signed_approval || !workload.federation_approved || !workload.raw_data_local || !workload.aggregate_only || !workload.adversarial_events.is_empty(); if global { blocked.extend(invocation_order.iter().cloned()); unresolved.clear(); completed.clear(); omissions.insert("request:reliability-gates-blocked".into()); } else if !unresolved.is_empty() { omissions.insert("failed-or-nondeterministic-invocations-remain-unresolved".into()); }
    let disposition = if global { ReliabilityDisposition::Blocked } else if unresolved.is_empty() { ReliabilityDisposition::Qualified } else if completed.is_empty() { ReliabilityDisposition::Unresolved } else { ReliabilityDisposition::Degraded }; let completed_order = completed.into_iter().collect::<Vec<_>>(); let unresolved_order = unresolved.into_iter().collect::<Vec<_>>(); let blocked_order = blocked.into_iter().collect::<Vec<_>>(); let omissions = omissions.into_iter().collect::<Vec<_>>(); let uncertainty = uncertainty.into_iter().collect::<Vec<_>>(); let negative_evidence = negative.into_iter().collect::<Vec<_>>(); let effect_receipts = if disposition == ReliabilityDisposition::Qualified { vec![format!("exchange:permitted-summaries:{}", workload.workload_id), format!("manage:local-capability:{}", workload.workload_id)] } else { vec!["block:unsafe-release".into()] };
    let payload = json!({"schema_version": RESEARCH_CONTRACT_SCHEMA_VERSION, "contract_version": CONTRACT_VERSION, "feature_id": FEATURE_ID, "workload_id": workload.workload_id, "federation_id": workload.federation_id, "institution_id": workload.institution_id, "capability_id": workload.capability_id, "disposition": disposition, "invocation_order": invocation_order, "completed_order": completed_order, "unresolved_order": unresolved_order, "blocked_order": blocked_order, "retry_order": retry_order, "timeout_order": timeout_order, "tool_order": tool_order, "budget_used_units": budget_used_units, "omissions": omissions, "uncertainty": uncertainty, "negative_evidence": negative_evidence, "replay_identity": workload.replay_identity, "effect_receipts": effect_receipts, "raw_data_local": workload.raw_data_local, "aggregate_only": workload.aggregate_only, "boundary": PRECLINICAL_BOUNDARY}); let result_digest = ContentHash::of_value(&payload).map_err(|e| PerformanceReliabilityError::Artifact(e.to_string()))?; let artifact = TypedResearchArtifact::from_payload(format!("reliable-capability:{}", workload.workload_id), CONTENT_TYPE, &payload, Vec::new(), Vec::new()).map_err(|e| PerformanceReliabilityError::Artifact(e.to_string()))?; let result = ReliableCapabilityResult { schema_version: RESEARCH_CONTRACT_SCHEMA_VERSION.into(), contract_version: CONTRACT_VERSION.into(), feature_id: FEATURE_ID.into(), workload_id: workload.workload_id.clone(), federation_id: workload.federation_id.clone(), institution_id: workload.institution_id.clone(), capability_id: workload.capability_id.clone(), disposition, invocation_order, completed_order, unresolved_order, blocked_order, retry_order, timeout_order, tool_order, budget_used_units, omissions, uncertainty, negative_evidence, replay_identity: workload.replay_identity.clone(), result_digest, effect_receipts, artifact, raw_data_local: workload.raw_data_local, aggregate_only: workload.aggregate_only, boundary: PRECLINICAL_BOUNDARY.into() }; result.validate()?; Ok(result)
}

fn validate_workload(workload: &CapabilityWorkload) -> Result<(), PerformanceReliabilityError> { if workload.schema_version != RESEARCH_CONTRACT_SCHEMA_VERSION || workload.workload_id.trim().is_empty() || workload.federation_id.trim().is_empty() || workload.institution_id.trim().is_empty() || workload.capability_id.trim().is_empty() || workload.manifests.is_empty() || workload.invocations.is_empty() || workload.budget_units == 0 || !digest(&workload.replay_identity) || !workload.raw_data_local || !workload.aggregate_only || workload.boundary != PRECLINICAL_BOUNDARY || !canonical(&workload.adversarial_events) { return Err(invalid("workload identity, manifests, budget, replay, locality, aggregate-only, or boundary is invalid")); } let mut capabilities = BTreeSet::new(); for manifest in &workload.manifests { if manifest.capability_id.trim().is_empty() || manifest.version.trim().is_empty() || manifest.effect.trim().is_empty() || !manifest.approved || manifest.revoked || !digest(&manifest.capability_digest) || !digest(&manifest.provenance_digest) || !capabilities.insert(manifest.capability_id.clone()) { return Err(invalid(format!("capability {} is unapproved, revoked, malformed, or duplicated", manifest.capability_id))); } } let mut ids = BTreeSet::new(); let mut total = 0_u64; for invocation in &workload.invocations { if invocation.invocation_id.trim().is_empty() || invocation.capability_id.trim().is_empty() || !capabilities.contains(&invocation.capability_id) || invocation.estimated_cost_units == 0 || invocation.timeout_ms == 0 || invocation.max_attempts == 0 || !digest(&invocation.input_digest) || !ids.insert(invocation.invocation_id.clone()) { return Err(invalid(format!("invocation {} is incomplete, undeclared, duplicated, or has an invalid digest", invocation.invocation_id))); } total = total.checked_add(invocation.estimated_cost_units).ok_or_else(|| invalid("workload cost overflow"))?; } if total > workload.budget_units { return Err(invalid("workload cost exceeds budget")); } Ok(()) }

#[cfg(test)]
mod tests { use super::*; fn h(value: &str) -> ContentHash { ContentHash::of_bytes(value.as_bytes()) } fn workload() -> CapabilityWorkload { let d = h("reliability"); CapabilityWorkload { schema_version: RESEARCH_CONTRACT_SCHEMA_VERSION.into(), workload_id: "workload:bioir".into(), federation_id: "fed:commons".into(), institution_id: "inst:alpha".into(), capability_id: "capability:qc".into(), manifests: vec![CapabilityManifestEntry { capability_id: "capability:qc".into(), version: "1.0".into(), effect: "read-local".into(), deterministic: true, approved: true, revoked: false, capability_digest: d.clone(), provenance_digest: d.clone() }], invocations: vec![CapabilityInvocation { invocation_id: "invoke:b".into(), capability_id: "capability:qc".into(), input_digest: d.clone(), estimated_cost_units: 2, timeout_ms: 1000, max_attempts: 2, simulated_failure: None }, CapabilityInvocation { invocation_id: "invoke:a".into(), capability_id: "capability:qc".into(), input_digest: d.clone(), estimated_cost_units: 1, timeout_ms: 1000, max_attempts: 1, simulated_failure: None }], budget_units: 10, policy_allow: true, protected_closure: true, signed_approval: true, federation_approved: true, raw_data_local: true, aggregate_only: true, replay_identity: d, adversarial_events: Vec::new(), boundary: PRECLINICAL_BOUNDARY.into() } } #[test] fn manifest_is_a2() { assert_eq!(performance_reliability_control_plane_manifest().autonomy_tier, AutonomyTier::A2); } #[test] fn qualified_result() { assert_eq!(evaluate_performance_reliability(&workload()).unwrap().disposition, ReliabilityDisposition::Qualified); } #[test] fn deterministic_order() { let mut r = workload(); r.invocations.reverse(); let a = evaluate_performance_reliability(&workload()).unwrap(); let b = evaluate_performance_reliability(&r).unwrap(); assert_eq!(a.result_digest, b.result_digest); } #[test] fn failure_degrades() { let mut r = workload(); r.invocations[0].simulated_failure = Some("timeout".into()); assert_eq!(evaluate_performance_reliability(&r).unwrap().disposition, ReliabilityDisposition::Degraded); } #[test] fn nondeterminism_unresolved() { let mut r = workload(); r.manifests[0].deterministic = false; assert_eq!(evaluate_performance_reliability(&r).unwrap().disposition, ReliabilityDisposition::Unresolved); } #[test] fn policy_blocks() { let mut r = workload(); r.policy_allow = false; assert_eq!(evaluate_performance_reliability(&r).unwrap().effect_receipts, vec!["block:unsafe-release"]); } #[test] fn adversarial_blocks() { let mut r = workload(); r.adversarial_events.push("poisoned-artifact".into()); assert_eq!(evaluate_performance_reliability(&r).unwrap().disposition, ReliabilityDisposition::Blocked); } }
