//! Organized glioma product programs.
//!
//! [`crate::glioma_engine`] owns the cross-program execution graph and its provider seam.  This
//! module owns the product programs themselves: each submodule is a typed, deterministic
//! capability that can be called by a local executor, an MCP adapter, a notebook, or a batch
//! worker.  The modules intentionally exchange hashes and de-identified metadata rather than raw
//! specimen bytes.

pub mod analysis;
pub mod catalog;
pub mod evidence;
pub mod experiment;
pub mod mechanism;
pub mod multimodal;
pub mod programs;
pub mod release;
pub mod replication;
pub mod workflow;

pub use analysis::{
    analyze_preclinical_outcomes, AnalysisDataset, AnalysisRequest, AnalysisResult,
};
pub use catalog::{
    generate_feature_catalog, glioma_program_catalog, implemented_feature_ids,
    validate_feature_catalog, CatalogError, GliomaFeatureSpec, GliomaOperatingScale,
    GliomaProgramDescriptor, GliomaProgramId,
};
pub use evidence::{qualify_evidence, EvidenceQualification, EvidenceRecord, EvidenceRequest};
pub use experiment::{
    design_preclinical_experiment, ExperimentArm, ExperimentDesign, ExperimentRequest,
};
pub use mechanism::{explore_mechanisms, MechanismCandidate, MechanismPortfolio, MechanismRequest};
pub use multimodal::{
    harmonize_multimodal_inputs, MultimodalObservation, MultimodalQcReport, MultimodalRequest,
};
pub use programs::p01_evidence_surveillance::{
    calibrate_glioma_evidence, execute_glioma_evidence_refresh_campaign,
    prioritize_glioma_evidence, surveil_glioma_evidence, triangulate_glioma_evidence,
    CalibrationBin, CalibrationBinDisposition, DryRunEvidenceRefreshCampaignExecutor,
    EvidenceCalibrationAnalysis, EvidenceCalibrationDisposition, EvidenceCalibrationError,
    EvidenceCalibrationObservation, EvidenceCalibrationRequest, EvidenceChange, EvidenceChangeKind,
    EvidencePriorityAction, EvidencePriorityActionKind, EvidencePriorityDisposition,
    EvidencePriorityError, EvidencePriorityPlan, EvidencePriorityRequest, EvidencePriorityWeights,
    EvidenceRefreshCampaign, EvidenceRefreshCampaignDisposition, EvidenceRefreshCampaignError,
    EvidenceRefreshCampaignExecutor, EvidenceRefreshCampaignRequest, EvidenceRefreshCampaignRound,
    EvidenceRefreshCampaignStopReason, EvidenceRefreshExecutionFailure, EvidenceSurveillance,
    EvidenceSurveillanceAction, EvidenceSurveillanceActionKind, EvidenceSurveillanceDisposition,
    EvidenceSurveillanceError, EvidenceSurveillanceRequest, EvidenceTriangulation,
    EvidenceTriangulationDisposition, EvidenceTriangulationError, EvidenceTriangulationRequest,
    SourceCalibration, SourceCalibrationDisposition, TriangulatedClaim, TriangulatedClaimVerdict,
};
pub use programs::p02_evidence_knowledge::{
    compile_typed_knowledge, compose_knowledge_graph, execute_glioma_knowledge_resolution_campaign,
    prioritize_knowledge_frontier, revise_glioma_beliefs, BeliefConflict, BeliefRevision,
    BeliefRevisionDecision, BeliefRevisionDecisionKind, BeliefRevisionDisposition,
    BeliefRevisionError, BeliefRevisionRequest, DryRunKnowledgeResolutionCampaignExecutor,
    FrontierActionKind, KnowledgeClaim, KnowledgeClaimDisposition, KnowledgeComponentDisposition,
    KnowledgeComposition, KnowledgeCompositionComponent, KnowledgeCompositionDisposition,
    KnowledgeCompositionError, KnowledgeCompositionPath, KnowledgeCompositionRequest,
    KnowledgeDisposition, KnowledgeError, KnowledgeFrontier, KnowledgeFrontierDisposition,
    KnowledgeFrontierError, KnowledgeFrontierRequest, KnowledgeFrontierScore,
    KnowledgeFrontierWeights, KnowledgePathDisposition, KnowledgeRelation, KnowledgeRelationKind,
    KnowledgeRequest, KnowledgeResolutionCampaign, KnowledgeResolutionCampaignDisposition,
    KnowledgeResolutionCampaignError, KnowledgeResolutionCampaignExecutor,
    KnowledgeResolutionCampaignRequest, KnowledgeResolutionCampaignRound,
    KnowledgeResolutionCampaignStopReason, KnowledgeResolutionExecutionFailure, TypedKnowledge,
};
pub use programs::p03_multimodal_ingestion_qc::{
    analyze_glioma_latent_factors, analyze_glioma_multimodal_graph_fusion,
    analyze_glioma_spatial_communication, analyze_glioma_spatial_niches,
    analyze_glioma_spatial_state_propagation, analyze_glioma_temporal_multimodal_fusion,
    analyze_multimodal_concordance, analyze_multimodal_consensus,
    execute_glioma_multimodal_ingestion_campaign, harmonize_glioma_multimodal_batches,
    register_glioma_spatial_samples, BatchHarmonizationDiagnostic, ConcordanceDisposition,
    ConcordanceError, ConcordanceRequest, ConsensusAssignment, ConsensusCluster,
    ConsensusDisposition, ConsensusError, ConsensusRequest,
    DryRunMultimodalIngestionCampaignExecutor, FeatureValue, GraphFusionAnalysis,
    GraphFusionDisposition, GraphFusionError, GraphFusionNeighbour, GraphFusionRequest,
    GraphFusionState, GraphFusionVector, HarmonizationDisposition, HarmonizationError,
    HarmonizationRequest, HarmonizationVector, HarmonizedFeature, HarmonizedVector,
    IngestionQcAction, IngestionQcActionKind, LatentFactorAnalysis, LatentFactorComponent,
    LatentFactorDisposition, LatentFactorError, LatentFactorRequest, LatentFactorVector,
    LatentLoading, LatentScore, LigandReceptorPair, ModalityConcordance, ModalityVector,
    MultimodalConcordance, MultimodalConsensus, MultimodalHarmonization,
    MultimodalIngestionCampaign, MultimodalIngestionCampaignDisposition,
    MultimodalIngestionCampaignError, MultimodalIngestionCampaignExecutor,
    MultimodalIngestionCampaignRequest, MultimodalIngestionCampaignRound,
    MultimodalIngestionCampaignStopReason, MultimodalIngestionExecutionFailure,
    PairConcordanceDisposition, RegisteredSpatialCell, RegistrationLandmark, SampleRegistration,
    SampleRegistrationDisposition, SpatialCell, SpatialCommunicationAnalysis,
    SpatialCommunicationCell, SpatialCommunicationDisposition, SpatialCommunicationError,
    SpatialCommunicationPair, SpatialCommunicationPairDisposition, SpatialCommunicationRequest,
    SpatialNiche, SpatialNicheAnalysis, SpatialNicheDisposition, SpatialNicheError,
    SpatialNicheInteraction, SpatialNicheRequest, SpatialPropagationAnalysis,
    SpatialPropagationDisposition, SpatialPropagationEdge, SpatialPropagationError,
    SpatialPropagationRequest, SpatialPropagationTrajectory, SpatialRegistrationAnalysis,
    SpatialRegistrationCell, SpatialRegistrationDisposition, SpatialRegistrationError,
    SpatialRegistrationRequest, TemporalFusionAnalysis, TemporalFusionDisposition,
    TemporalFusionError, TemporalFusionRequest, TemporalObservation, TemporalState,
    TemporalStateFeature, TemporalTransition, TemporalTransitionDirection,
};
pub use programs::p04_decision_context::{
    compile_decision_action_graph, compile_decision_context,
    execute_glioma_decision_context_campaign, plan_decision_actions, DecisionAction,
    DecisionActionGraph, DecisionActionGraphDisposition, DecisionActionGraphError,
    DecisionActionGraphRequest, DecisionActionKind, DecisionActionPlan,
    DecisionActionPlanDisposition, DecisionActionPlanError, DecisionActionPlanRequest,
    DecisionContext, DecisionContextCampaign, DecisionContextCampaignDisposition,
    DecisionContextCampaignError, DecisionContextCampaignExecutionFailure,
    DecisionContextCampaignExecutor, DecisionContextCampaignRequest, DecisionContextCampaignRound,
    DecisionContextCampaignStopReason, DecisionContextDisposition, DecisionContextError,
    DecisionContextRequest, DecisionGraphNode, DryRunDecisionContextCampaignExecutor,
};
pub use programs::p05_mechanism_exploration::{
    analyze_glioma_clonal_evolution, analyze_glioma_pathway_activity, calibrate_glioma_mechanisms,
    compile_mechanism_action_plan, discriminate_mechanisms,
    execute_glioma_adaptive_mechanism_campaign, execute_glioma_mechanism_discrimination_campaign,
    plan_glioma_adaptive_mechanism_policy, plan_glioma_robust_intervention_portfolio,
    propagate_glioma_mechanism_graph, simulate_glioma_counterfactual,
    simulate_glioma_counterfactual_ensemble, simulate_glioma_mechanism_dynamics,
    AdaptiveMechanismAction, AdaptiveMechanismActionScore, AdaptiveMechanismCampaign,
    AdaptiveMechanismCampaignRequest, AdaptiveMechanismCampaignRound,
    AdaptiveMechanismCampaignStopReason, AdaptiveMechanismExecutionFailure, AdaptiveMechanismModel,
    AdaptiveMechanismObservation, AdaptiveMechanismPolicy, AdaptiveMechanismPolicyDisposition,
    AdaptiveMechanismPolicyError, AdaptiveMechanismPolicyExecutor,
    AdaptiveMechanismPolicyPosterior, AdaptiveMechanismPolicyRequest, AdaptiveMechanismPolicyStep,
    AdaptiveMechanismPrediction, ClonalEdge, ClonalEvolutionDisposition, ClonalEvolutionError,
    ClonalEvolutionGraph, ClonalEvolutionRequest, ClonalNode, ClonalRelation, CloneMarker,
    CloneMarkerState, CloneProfile, CounterfactualContrast, CounterfactualDirection,
    CounterfactualDisposition, CounterfactualEnsembleRequest, CounterfactualError,
    CounterfactualIntervention, CounterfactualModel, CounterfactualRequest,
    DryRunAdaptiveMechanismPolicyExecutor, DryRunMechanismDiscriminationCampaignExecutor,
    EnsembleCounterfactualError, EnsembleDirection, EnsembleDisposition, EnsembleModelResult,
    EnsembleTargetSummary, GliomaMechanismActionPlanner, MechanismActionPlan,
    MechanismActionPlannerConfig, MechanismActionPlannerError, MechanismCalibration,
    MechanismCalibrationBin, MechanismCalibrationError, MechanismCalibrationObservation,
    MechanismCalibrationRequest, MechanismCalibrationScore, MechanismCalibrationScoreDisposition,
    MechanismCounterfactual, MechanismCounterfactualEnsemble, MechanismDiscrimination,
    MechanismDiscriminationCampaign, MechanismDiscriminationCampaignDisposition,
    MechanismDiscriminationCampaignError, MechanismDiscriminationCampaignExecutionFailure,
    MechanismDiscriminationCampaignExecutor, MechanismDiscriminationCampaignRequest,
    MechanismDiscriminationCampaignRound, MechanismDiscriminationCampaignStopReason,
    MechanismDiscriminationDisposition, MechanismDiscriminationError,
    MechanismDiscriminationRanking, MechanismDiscriminationRequest, MechanismDiscriminatorAction,
    MechanismDynamicsDisposition, MechanismDynamicsEdge, MechanismDynamicsError,
    MechanismDynamicsIntervention, MechanismDynamicsNode, MechanismDynamicsPlan,
    MechanismDynamicsRequest, MechanismDynamicsSensitivity, MechanismDynamicsState,
    MechanismDynamicsStep, MechanismFeatureObservation, MechanismGraphDisposition,
    MechanismGraphEdge, MechanismGraphError, MechanismGraphNode, MechanismGraphPropagation,
    MechanismGraphRelation, MechanismGraphRequest, MechanismHypothesis, MechanismInformationGain,
    MechanismNodeScore, MechanismPrediction, PathwayActivityAnalysis, PathwayActivityDefinition,
    PathwayActivityDirection, PathwayActivityDisposition, PathwayActivityEdge,
    PathwayActivityError, PathwayActivityNode, PathwayActivityObservation, PathwayActivityRecord,
    PathwayActivityRequest, PortfolioDirection, RobustInterventionCandidate,
    RobustInterventionPortfolio, RobustInterventionRequest, RobustInterventionScore,
    RobustPortfolioDisposition, RobustPortfolioError,
};
pub use programs::p06_experiment_design::{
    allocate_glioma_assays, analyze_glioma_combination_synergy, analyze_glioma_dose_response,
    design_glioma_contrast_panel, execute_glioma_adaptive_allocation_campaign,
    execute_glioma_adaptive_information_campaign, execute_glioma_closed_loop_campaign,
    execute_glioma_multi_fidelity_campaign, execute_glioma_sequential_campaign,
    plan_adaptive_glioma_dose_surface, plan_glioma_active_learning,
    plan_glioma_adaptive_information_campaign, plan_glioma_clone_perturbation_panel,
    plan_glioma_closed_loop_campaign, plan_glioma_information_design,
    plan_glioma_multi_fidelity_optimization, plan_glioma_robust_active_learning,
    plan_glioma_sequential_design, ActiveLearningCandidate, ActiveLearningCandidateDisposition,
    ActiveLearningDirection, ActiveLearningDisposition, ActiveLearningError,
    ActiveLearningObservation, ActiveLearningPlan, ActiveLearningRequest, ActiveLearningScore,
    AdaptiveAllocation, AdaptiveAllocationActionKind, AdaptiveAllocationBatchObservation,
    AdaptiveAllocationCampaign, AdaptiveAllocationCampaignDisposition,
    AdaptiveAllocationCampaignError, AdaptiveAllocationCampaignExecutionFailure,
    AdaptiveAllocationCampaignExecutor, AdaptiveAllocationCampaignRequest,
    AdaptiveAllocationCampaignRound, AdaptiveAllocationCampaignStopReason,
    AdaptiveAllocationDisposition, AdaptiveAllocationError, AdaptiveAllocationRequest,
    AdaptiveArmObservation, AdaptiveArmPosterior, AdaptiveDoseSurfaceDisposition,
    AdaptiveDoseSurfaceError, AdaptiveDoseSurfacePlan, AdaptiveDoseSurfaceRequest,
    AdaptiveInformationCampaignDisposition, AdaptiveInformationCampaignError,
    AdaptiveInformationCampaignExecution, AdaptiveInformationCampaignPlan,
    AdaptiveInformationCampaignRequest, AdaptiveInformationCampaignRound,
    AdaptiveInformationCampaignTermination, AdaptiveInformationExecutionFailure,
    AdaptiveInformationObservation, AdaptiveMechanismPosterior, CampaignAction,
    CampaignActionScore, CampaignExecutionFailure, CampaignExecutionRound, CampaignMechanism,
    CampaignMechanismPosterior, CampaignObservation, CampaignRound, CampaignStopReason,
    CloneBranchCoverage, ClonePerturbationCandidate, ClonePerturbationDecision,
    ClonePerturbationKind, ClonePerturbationPanel, ClonePerturbationPanelDisposition,
    ClonePerturbationPanelError, ClonePerturbationPanelRequest, ClosedLoopCampaign,
    ClosedLoopCampaignDisposition, ClosedLoopCampaignError, ClosedLoopCampaignExecution,
    ClosedLoopCampaignRequest, CombinationCell, CombinationCellDisposition, CombinationObservation,
    CombinationSynergyAnalysis, CombinationSynergyDisposition, CombinationSynergyError,
    CombinationSynergyRequest, ContrastCondition, ContrastDesign, ContrastDesignDisposition,
    ContrastDesignError, ContrastDesignRequest, ContrastFactor, DesignAction, DesignMechanism,
    DesignOutcome, DoseDirection, DosePair, DoseResponseAnalysis, DoseResponseDisposition,
    DoseResponseError, DoseResponseObservation, DoseResponsePoint, DoseResponseRequest,
    DoseSurfaceCellState, DoseSurfaceEstimate, DoseSurfaceObservation,
    DryRunAdaptiveAllocationCampaignExecutor, DryRunMultiFidelityCampaignExecutor,
    DryRunSequentialCampaignExecutor, EstimandContrast, EstimateSource, FidelityCalibration,
    FidelityCandidate, FidelityEstimate, FidelityLevel, FidelityObservation,
    GliomaCampaignExecutor, GliomaInformationDesignExecutor, InformationDesignActionScore,
    InformationDesignDisposition, InformationDesignError, InformationDesignPlan,
    InformationDesignRequest, MultiFidelityCampaign, MultiFidelityCampaignDisposition,
    MultiFidelityCampaignError, MultiFidelityCampaignExecutor, MultiFidelityCampaignRequest,
    MultiFidelityCampaignRound, MultiFidelityCampaignStopReason, MultiFidelityDisposition,
    MultiFidelityExecutionFailure, MultiFidelityOptimizationError, MultiFidelityOptimizationPlan,
    MultiFidelityOptimizationRequest, OptimizationDirection, RobustActiveLearningCandidate,
    RobustActiveLearningCandidateDisposition, RobustActiveLearningDisposition,
    RobustActiveLearningError, RobustActiveLearningModel, RobustActiveLearningObservation,
    RobustActiveLearningPlan, RobustActiveLearningRequest, RobustActiveLearningScore,
    SequentialArmDecision, SequentialArmObservation, SequentialBatchObservation,
    SequentialCampaign, SequentialCampaignDisposition, SequentialCampaignError,
    SequentialCampaignExecutionFailure, SequentialCampaignExecutor, SequentialCampaignRequest,
    SequentialCampaignRound, SequentialCampaignStopReason, SequentialDecisionKind,
    SequentialDesignDisposition, SequentialDesignError, SequentialDesignPlan,
    SequentialDesignRequest, SequentialDesignRound, EXECUTION_OUTPUT_SCHEMA,
};
pub use programs::p07_protocol_simulation::{
    execute_glioma_action_portfolio, execute_glioma_active_learning_campaign,
    execute_glioma_autonomous_campaign, execute_glioma_autonomous_research_engine,
    execute_glioma_autonomous_research_mission, execute_glioma_evidence_campaign,
    execute_glioma_evidence_gated_research, execute_glioma_multimodal_mechanism_campaign,
    execute_glioma_multimodal_mechanism_campaign_with_executor, execute_glioma_protocol,
    execute_glioma_research_autopilot, execute_glioma_research_director,
    execute_glioma_robust_active_learning_campaign, plan_glioma_adaptive_workflow,
    plan_glioma_clone_continuation, plan_glioma_research_director,
    protocol_request_from_experiment_design, simulate_glioma_protocol, ActionExecutionDisposition,
    ActionExecutionFailure, ActionExecutionResult, ActionPortfolioExecution,
    ActionPortfolioExecutionDisposition, ActionPortfolioExecutionError,
    ActionPortfolioExecutionRequest, ActionPortfolioStopReason, ActiveLearningCampaign,
    ActiveLearningCampaignDisposition, ActiveLearningCampaignError, ActiveLearningCampaignExecutor,
    ActiveLearningCampaignRequest, ActiveLearningCampaignRound, ActiveLearningCampaignStopReason,
    ActiveLearningExecutionFailure, CloneContinuationActionKind, CloneContinuationActionStatus,
    CloneContinuationCandidate, CloneContinuationDecision, CloneContinuationDisposition,
    CloneContinuationError, CloneContinuationPlan, CloneContinuationRequest,
    DryRunActiveLearningCampaignExecutor, DryRunGliomaActionExecutor, DryRunGliomaProtocolExecutor,
    DryRunRobustActiveLearningCampaignExecutor, EvidenceGatedResearchDisposition,
    GliomaActionExecutor, GliomaActionPlanner, GliomaAdaptiveWorkflowSchedulerDisposition,
    GliomaAdaptiveWorkflowSchedulerError, GliomaAdaptiveWorkflowSchedulerPlan,
    GliomaAdaptiveWorkflowSchedulerRequest, GliomaAutonomousCampaign,
    GliomaAutonomousCampaignDisposition, GliomaAutonomousCampaignError,
    GliomaAutonomousCampaignRequest, GliomaAutonomousCampaignRound,
    GliomaAutonomousCampaignStopReason, GliomaAutonomousPlannerContext,
    GliomaAutonomousResearchEngineCycle, GliomaAutonomousResearchEngineDisposition,
    GliomaAutonomousResearchEngineError, GliomaAutonomousResearchEngineRequest,
    GliomaAutonomousResearchEngineRun, GliomaAutonomousResearchEngineStopReason,
    GliomaAutonomousResearchMission, GliomaDirectorAction, GliomaDirectorCheckpoint,
    GliomaDirectorDisposition, GliomaDirectorFocus, GliomaEvidenceCampaignDisposition,
    GliomaEvidenceCampaignError, GliomaEvidenceCampaignExecution, GliomaEvidenceCampaignRequest,
    GliomaEvidenceGatedResearchError, GliomaEvidenceGatedResearchRequest,
    GliomaEvidenceGatedResearchRun, GliomaMissionDisposition, GliomaMissionError,
    GliomaMissionGates, GliomaMissionRequest, GliomaMissionRound, GliomaMissionStopReason,
    GliomaPlannerFailure, GliomaProtocolExecutor, GliomaResearchAutopilotDisposition,
    GliomaResearchAutopilotError, GliomaResearchAutopilotRequest, GliomaResearchAutopilotRun,
    GliomaResearchDirectorError, GliomaResearchDirectorRequest, GliomaResearchDirectorRun,
    MechanismCampaignDisposition, MechanismCampaignError, MechanismCampaignExecutionDisposition,
    MultimodalMechanismCampaign, MultimodalMechanismCampaignExecution,
    MultimodalMechanismCampaignRequest, ProtocolDisposition, ProtocolExecution,
    ProtocolExecutionDisposition, ProtocolExecutionError, ProtocolExecutionFailure,
    ProtocolExecutionRequest, ProtocolExecutionStopReason, ProtocolResource, ProtocolResourceKind,
    ProtocolSimulation, ProtocolSimulationError, ProtocolSimulationRequest, ProtocolTask,
    ProtocolTaskDisposition, ProtocolTaskResult, ResourceUtilization, RobustActiveLearningCampaign,
    RobustActiveLearningCampaignDisposition, RobustActiveLearningCampaignError,
    RobustActiveLearningCampaignExecutor, RobustActiveLearningCampaignRequest,
    RobustActiveLearningCampaignRound, RobustActiveLearningCampaignStopReason,
    RobustActiveLearningExecutionFailure, ScheduleEntry, SchedulerDecision, SchedulerObservation,
    SchedulerOutcome, StaticGliomaActionPlanner, PROTOCOL_EXECUTION_OUTPUT_SCHEMA,
};
pub use programs::p08_instrument_robotics::{
    adjudicate_glioma_assay_evidence, analyze_instrument_calibration,
    execute_glioma_instrument_campaign, execute_glioma_instrument_plan,
    preflight_glioma_instrument, AssayEvidenceDisposition, AssayEvidenceError,
    AssayEvidenceObservation, AssayEvidenceRecord, AssayEvidenceRequest, CalibrationDisposition,
    CalibrationError, CalibrationPoint, CalibrationRequest, CalibrationRun,
    DryRunInstrumentExecutor, InstrumentAction, InstrumentActionDecision,
    InstrumentActionDisposition, InstrumentAssayEvidenceAssessment, InstrumentAuthorization,
    InstrumentCalibration, InstrumentCampaign, InstrumentCampaignDisposition,
    InstrumentCampaignError, InstrumentCampaignFailure, InstrumentCampaignRequest,
    InstrumentCampaignRunRequest, InstrumentCampaignRunResult, InstrumentCampaignStopReason,
    InstrumentExecutionDisposition, InstrumentExecutionError, InstrumentExecutionFailure,
    InstrumentExecutionRequest, InstrumentExecutionResult, InstrumentExecutionRun,
    InstrumentExecutionStopReason, InstrumentExecutor, InstrumentInterlockSnapshot,
    InstrumentOperation, InstrumentParameter, InstrumentPreflightDisposition,
    InstrumentPreflightError, InstrumentPreflightPlan, InstrumentPreflightRequest,
};
pub use programs::p09_reproducible_computation::{
    assess_glioma_robustness, compile_glioma_computation_workflow, execute_glioma_computation,
    execute_glioma_computation_campaign, execute_glioma_computation_portfolio,
    plan_glioma_computation_portfolio, ComputationCacheEntry, ComputationCandidate,
    ComputationCandidateDisposition, ComputationCandidateScore, ComputationExecution,
    ComputationExecutionDisposition, ComputationExecutionError, ComputationExecutionFailure,
    ComputationExecutionRequest, ComputationExecutionStopReason, ComputationOperation,
    ComputationPortfolioDisposition, ComputationPortfolioError, ComputationPortfolioExecution,
    ComputationPortfolioExecutionDisposition, ComputationPortfolioExecutionError,
    ComputationPortfolioExecutionRequest, ComputationPortfolioPlan, ComputationPortfolioRequest,
    ComputationTask, ComputationTaskDisposition, ComputationTaskResult,
    DryRunGliomaComputationExecutor, GliomaComputationCampaign,
    GliomaComputationCampaignDisposition, GliomaComputationCampaignError,
    GliomaComputationCampaignRequest, GliomaComputationCampaignRound,
    GliomaComputationCampaignStopReason, GliomaComputationExecutor, GliomaComputationPlanner,
    GliomaComputationPlannerContext, GliomaComputationPlannerFailure, GliomaComputationWorkflow,
    GliomaComputationWorkflowError, GliomaComputationWorkflowRequest, RobustnessCase,
    RobustnessCaseKind, RobustnessDisposition, RobustnessError, RobustnessRequest, RobustnessSuite,
    StaticGliomaComputationPlanner,
};
pub use programs::p10_interpretation_replication::{
    analyze_causal_sensitivity, analyze_glioma_causal_contrast,
    analyze_glioma_clone_panel_outcomes, analyze_glioma_mediation,
    analyze_glioma_state_transitions, analyze_glioma_trajectories, analyze_glioma_transportability,
    analyze_replication_meta_analysis, analyze_stratified_causal_adjustment,
    execute_glioma_replication_campaign, plan_glioma_adaptive_research_frontier,
    synthesize_glioma_interpretation, AdaptiveFrontierCandidate, AdaptiveFrontierDisposition,
    AdaptiveFrontierError, AdaptiveFrontierRequest, AdaptiveResearchFrontier, AdaptiveTarget,
    CausalContrastAnalysis, CausalContrastDisposition, CausalContrastError, CausalContrastRequest,
    CausalSensitivityAnalysis, CausalStratumSummary, ClonePanelBranchAnalysis,
    ClonePanelCandidateAnalysis, ClonePanelCellAnalysis, ClonePanelCellDisposition,
    ClonePanelMeasurementState, ClonePanelObservation, ClonePanelOutcomeAnalysis,
    ClonePanelOutcomeDisposition, ClonePanelOutcomeError, ClonePanelOutcomeRequest,
    DryRunGliomaReplicationCampaignExecutor, GliomaReplicationAction, GliomaReplicationActionKind,
    GliomaReplicationCampaign, GliomaReplicationCampaignDisposition,
    GliomaReplicationCampaignError, GliomaReplicationCampaignExecutor,
    GliomaReplicationCampaignObservation, GliomaReplicationCampaignRequest,
    GliomaReplicationCampaignRound, GliomaReplicationCampaignStopReason,
    GliomaReplicationExecutionFailure, InterpretationEvidence, InterpretationEvidenceDirection,
    InterpretationEvidenceFamily, InterpretationFamilySummary, InterpretationSynthesis,
    InterpretationSynthesisDisposition, InterpretationSynthesisError,
    InterpretationSynthesisRequest, MediationAnalysis, MediationDisposition, MediationError,
    MediationObservation, MediationRequest, MetaAnalysisDisposition, MetaAnalysisError,
    MetaAnalysisRequest, MetaStudyContribution, ReplicationMetaAnalysis, SensitivityDirection,
    SensitivityDisposition, SensitivityError, SensitivityObservation, SensitivityPoint,
    SensitivityRequest, StateTransitionAnalysis, StateTransitionCell, StateTransitionContrast,
    StateTransitionDisposition, StateTransitionError, StateTransitionObservation,
    StateTransitionRequest, StratifiedCausalActionKind, StratifiedCausalAdjustment,
    StratifiedCausalDisposition, StratifiedCausalError, StratifiedCausalRequest,
    StratifiedObservation, TrajectoryAnalysis, TrajectoryArmSummary, TrajectoryDisposition,
    TrajectoryError, TrajectoryObservation, TrajectoryRequest, TransitionCellDisposition,
    TransitionContrastDisposition, TransitionDirection, TransportStudy, TransportStudyContribution,
    TransportabilityAnalysis, TransportabilityDisposition, TransportabilityError,
    TransportabilityRequest, UnitContrast, UnitTrajectory, UnitTrajectoryDisposition,
};
pub use programs::p11_research_object_release::{
    evaluate_glioma_release_gate, execute_glioma_replay_campaign, DryRunReplayCampaignExecutor,
    ReleaseGateError, ReleaseGateEvaluation, ReleaseGateRequest, ReleaseGateStatus,
    ReleaseReviewAttestation, ReleaseReviewDecision, ReplayCampaign, ReplayCampaignDisposition,
    ReplayCampaignError, ReplayCampaignExecutor, ReplayCampaignRequest, ReplayCampaignRound,
    ReplayCampaignStopReason, ReplayExecutionFailure, ReplayObservation, ReplayObservationStatus,
    ReplayTask,
};
pub use programs::p12_federated_benchmarking::{
    analyze_federated_benchmark, analyze_federated_mechanism_transport,
    execute_federated_benchmark_campaign, plan_federated_benchmark_sites,
    DryRunFederatedBenchmarkCampaignExecutor, FederatedBenchmarkAction,
    FederatedBenchmarkActionKind, FederatedBenchmarkCampaign,
    FederatedBenchmarkCampaignDisposition, FederatedBenchmarkCampaignError,
    FederatedBenchmarkCampaignExecutor, FederatedBenchmarkCampaignRequest,
    FederatedBenchmarkCampaignRound, FederatedBenchmarkCampaignStopReason,
    FederatedBenchmarkCandidate, FederatedBenchmarkCandidateScore, FederatedBenchmarkConsensus,
    FederatedBenchmarkContribution, FederatedBenchmarkDisposition, FederatedBenchmarkError,
    FederatedBenchmarkExecutionFailure, FederatedBenchmarkPlanDisposition,
    FederatedBenchmarkRequest, FederatedBenchmarkSite, FederatedBenchmarkSiteDisposition,
    FederatedBenchmarkSitePlan, FederatedBenchmarkSitePlannerError,
    FederatedBenchmarkSitePlannerRequest, FederatedMechanismContribution, FederatedMechanismSite,
    FederatedMechanismTransportAnalysis, FederatedMechanismTransportDisposition,
    FederatedMechanismTransportError, FederatedMechanismTransportRequest, FederatedModelCoverage,
};
pub use release::{build_research_object_manifest, ResearchObjectManifest, ResearchObjectRequest};
pub use replication::{
    assess_replication, ReplicationAssessment, ReplicationRequest, ReplicationStudy,
};
pub use workflow::{
    execute_glioma_workflow, plan_glioma_workflow, GliomaWorkflowBranch, GliomaWorkflowError,
    GliomaWorkflowExecution, GliomaWorkflowMode, GliomaWorkflowNode, GliomaWorkflowPlan,
    GliomaWorkflowRequest, WorkflowNodeDecision,
};
